### ISSUE TITLE
Instruments with issues in 2.6.1

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#1006]
Better than 2.6, but also 2.6.1 shipped with instruments that don't pass the test:

* (Corrected on master) templateDIFF gives numerical output which is off by ~25%
* (Corrected on master) templateTOF in one of two cases give numerical output which is off by ~25%
* Test_Pol_Guide_mirror doesn't compile
* Test_PolFieldBox has multiple issues and doesn't compile
* (Corrected on master) PSI_Focus_shielding_129 has a non-meaningful combination of default params and %Example line

Shortlist of current failing instruments:
<pre>
[FAILED] Test_pol_tabled_5 (accuracy off by 300 %)
[FAILED] Test_Pol_Set_43 (accuracy off by 300 %)
[FAILED] Test_Magnetic_Rotation_64 (accuracy off by 301 %)
[FAILED] Test_Pol_Guide_mirror_84 (compilation/execution)
[FAILED] ISIS_HET_87 (accuracy off by 55 %)
[FAILED] Test_PolFieldBox_88 (compilation/execution)
[FAILED] Test_Sources_99 (accuracy off by 89 %)
# Execution check:    FAILED. 2 instrument(s) did not compile/execute.
</pre>

Updated, full abstract visible below
<pre>
Test Abstract for selftest_A2fo
[OK]     Test_Collimator_Radial_1 (accuracy, fair 6 %)
[OK]     Test_Collimator_Radial_2 (accuracy, 1 %)
[OK]     Test_Collimator_Radial_3 (accuracy, 5 %)
[OK]     mini_4 (accuracy, 1 %)
[FAILED] Test_pol_tabled_5 (accuracy off by 300 %)
[notest] RTP_NeutronRadiography (no test procedure)
[notest] Union_test_box (no test procedure)
[OK]     ILL_D2B_6 (accuracy, 9 %)
[OK]     Samples_Isotropic_Sqw_7 (accuracy, 3 %)
[OK]     Test_PSD_Detector_8 (accuracy, 1 %)
[notest] ISIS_CRISP (no test procedure)
[notest] ESS_BIFROST_shielding (no test procedure)
[notest] Histogrammer (no test procedure)
[notest] ISIS_TOSCA_preupgrade_Mantid (no test procedure)
[OK]     Samples_vanadium_9 (accuracy, 1 %)
[OK]     ISIS_test_10 (accuracy, 1 %)
[OK]     ILL_H8_IN1_11 (accuracy, 1 %)
[OK]     Test_Magnetic_Userdefined_12 (accuracy, 1 %)
[OK]     ISIS_GEM_13 (accuracy, fair 10 %)
[notest] ILL_H5 (no test procedure)
[notest] Granroth_SNS_decoupled_poisoned (no test procedure)
[notest] Test_shellguides (no test procedure)
[notest] ESS_butterfly_MCPL_test (no test procedure)
[OK]     Samples_Phonon_14 (accuracy, 1 %)
[notest] ESS_butterfly_Guide_curved_test (no test procedure)
[notest] SNS_test (no test procedure)
[notest] Union_incoherent_validation (no test procedure)
[notest] FZJ_BenchmarkSfin2 (no test procedure)
[notest] SAFARI_PITSI (no test procedure)
[notest] LLB_6T2 (no test procedure)
[notest] Test_Scatter_log_mvalues (no test procedure)
[notest] Test_SSR_SSW (no test procedure)
[OK]     Test_Guides_15 (accuracy, 1 %)
[OK]     Test_Guides_16 (accuracy, 0 %)
[OK]     Test_Guides_17 (accuracy, 1 %)
[OK]     Test_Guides_18 (accuracy, 1 %)
[OK]     Test_Guides_19 (accuracy, fair 8 %)
[OK]     Test_Guides_20 (accuracy, 1 %)
[OK]     Test_Guides_21 (accuracy, 1 %)
[OK]     Test_Guides_22 (accuracy, 1 %)
[OK]     Test_Guides_23 (accuracy, 3 %)
[OK]     Test_DiskChoppers_24 (accuracy, 1 %)
[OK]     Test_DiskChoppers_25 (accuracy, 1 %)
[OK]     ILL_H25_26 (accuracy, 1 %)
[OK]     ILL_H16_IN5_27 (accuracy, 3 %)
[OK]     ILL_H16_IN5_28 (accuracy, 5 %)
[notest] template (no test procedure)
[OK]     ILL_IN5_29 (accuracy, 1 %)
[OK]     ILL_H25_IN22_30 (accuracy, 1 %)
[notest] TestSANS (no test procedure)
[OK]     Test_Magnetic_Constant_31 (accuracy, 0 %)
[notest] ISIS_SANS2d (no test procedure)
[notest] ESS_mcpl2hist (no test procedure)
[notest] McStas_PowderN (no test procedure)
[OK]     Test_Selectors_32 (accuracy, 1 %)
[OK]     Test_Selectors_33 (accuracy, 1 %)
[OK]     templateSANS2_34 (accuracy, 1 %)
[OK]     templateSANS2_35 (accuracy, 1 %)
[OK]     ESS_IN5_reprate_36 (accuracy, 1 %)
[notest] RTP_DIF (no test procedure)
[OK]     templateSANS_37 (accuracy, 2 %)
[notest] ESS_2001_bispectral (no test procedure)
[notest] ILL_H5_new (no test procedure)
[notest] MCPL_filter_radius (no test procedure)
[OK]     ILL_D4_38 (accuracy, 1 %)
[notest] ILL_H53_D16 (no test procedure)
[OK]     FZJ_KWS2_Lens_39 (accuracy, 1 %)
[notest] Union_time_of_flight (no test procedure)
[notest] ESS_butterfly_tfocus_NOFOCUS_test (no test procedure)
[OK]     templateTOF_40 (accuracy, 2 %)
[OK]     templateTOF_41 (accuracy, 1 %)
[notest] Tools_ONION (no test procedure)
[OK]     ILL_BRISP_42 (accuracy, 4 %)
[notest] SNS_ARCS_Mantid (no test procedure)
[notest] MCPL_filter_energy (no test procedure)
[notest] ESS_Brilliance_2001 (no test procedure)
[notest] Union_test_mesh (no test procedure)
[FAILED] Test_Pol_Set_43 (accuracy off by 300 %)
[notest] templateNMX_TOF (no test procedure)
[OK]     ILL_H22_44 (accuracy, 1 %)
[notest] templateSasView (no test procedure)
[notest] Union_laue_camera (no test procedure)
[notest] ILL_H16_Mantid (no test procedure)
[OK]     Test_Fermi_45 (accuracy, fair 6 %)
[OK]     Test_Fermi_46 (accuracy, 1 %)
[OK]     Test_Fermi_47 (accuracy, fair 7 %)
[OK]     Test_Fermi_48 (accuracy, 3 %)
[OK]     Test_Fermi_49 (accuracy, 2 %)
[notest] ISIS_OSIRIS (no test procedure)
[notest] RITA-II (no test procedure)
[notest] MCPL2hist (no test procedure)
[notest] Union_demonstration_absorption_image (no test procedure)
[OK]     ILL_H142_50 (accuracy, 1 %)
[OK]     ILL_IN4_51 (accuracy, 2 %)
[notest] SE_example2 (no test procedure)
[notest] Test_StatisticalChopper (no test procedure)
[notest] ISIS_MERLIN (no test procedure)
[notest] ILL_IN5_Spots (no test procedure)
[notest] Test_PreMonitor_nD (no test procedure)
[notest] Union_manual_example (no test procedure)
[OK]     templateLaue_52 (accuracy, 1 %)
[OK]     templateLaue_53 (accuracy, 0 %)
[OK]     templateDIFF_54 (accuracy, 1 %)
[notest] SEMSANS_instrument (no test procedure)
[notest] templateSasView_Mantid (no test procedure)
[notest] Union_IncoherentPhonon_test (no test procedure)
[OK]     Test_Pol_Bender_55 (accuracy, 1 %)
[notest] Test_Sample_nxs_imaging (no test procedure)
[OK]     ILL_IN13_56 (accuracy, 1 %)
[OK]     Test_Monochromators_57 (accuracy, 1 %)
[OK]     Test_Monochromators_58 (accuracy, 1 %)
[OK]     Test_Monochromators_59 (accuracy, 1 %)
[OK]     Test_Monochromators_60 (accuracy, 1 %)
[OK]     Test_Monochromators_61 (accuracy, 1 %)
[notest] ESS_Testbeamline_HZB_V20 (no test procedure)
[notest] SNS_ARCS (no test procedure)
[notest] ILL_IN6 (no test procedure)
[notest] MCPL_filter_wavelength (no test procedure)
[notest] ISIS_TS2_Brilliance (no test procedure)
[OK]     ILL_H24_62 (accuracy, 3 %)
[notest] Test_Magnon_bcc_2D (no test procedure)
[notest] ILL_H143_LADI (no test procedure)
[OK]     ILL_H15_D11_63 (accuracy, 4 %)
[notest] h8_test_legacy (no test procedure)
[notest] ESS_2015_test (no test procedure)
[FAILED] Test_Magnetic_Rotation_64 (accuracy off by 301 %)
[OK]     ILL_H15_65 (accuracy, 1 %)
[notest] Test_Pol_SF_ideal (no test procedure)
[notest] Test_Sample_nxs_diffraction (no test procedure)
[notest] SNS_analytic_test (no test procedure)
[notest] Union_sample_picture_replica (no test procedure)
[notest] Union_external_component_test (no test procedure)
[notest] Union_powder_validation (no test procedure)
[notest] Gallmeier_SNS_decoupled_poisoned (no test procedure)
[notest] ISIS_SANS2d_Mantid (no test procedure)
[OK]     ILL_H13_IN20_66 (accuracy, 3 %)
[OK]     Test_Pol_MSF_67 (accuracy, 1 %)
[OK]     ILL_IN5_Mantid_68 (accuracy, 4 %)
[notest] templateSANS_Mantid (no test procedure)
[notest] McStas_Isotropic_Sqw (no test procedure)
[notest] template_simple (no test procedure)
[OK]     ILL_H16_IN5_Mantid_69 (accuracy, 3 %)
[OK]     ILL_H16_IN5_Mantid_70 (accuracy, fair 8 %)
[notest] ESS_Brilliance_TDR (no test procedure)
[notest] Test_Magnon_bcc_TAS (no test procedure)
[OK]     ILL_H53_IN14_71 (accuracy, fair 16 %)
[OK]     Tomography_72 (accuracy, 1 %)
[OK]     ILL_H22_VIVALDI_73 (accuracy, 3 %)
[OK]     linup-2_74 (accuracy, 1 %)
[OK]     Test_Jump_Iterate_75 (accuracy, 1 %)
[OK]     Test_single_magnetic_crystal_76 (accuracy, 6 %)
[notest] Test_Lens (no test procedure)
[OK]     templateTAS_77 (accuracy, 1 %)
[OK]     templateTAS_78 (accuracy, 1 %)
[OK]     Test_PowderN_Res_79 (accuracy, fair 12 %)
[OK]     linup-6_80 (accuracy, 3 %)
[notest] Reflectometer (no test procedure)
[notest] SAFARI_MPISI (no test procedure)
[OK]     PSI_Focus_81 (accuracy, 1 %)
[notest] Vout_test (no test procedure)
[notest] SNS_BASIS (no test procedure)
[notest] ESS_Brilliance_2014 (no test procedure)
[notest] ISIS_TS1_Brilliance (no test procedure)
[OK]     ILL_H142_IN12_82 (accuracy, 1 %)
[notest] templateNMX (no test procedure)
[notest] Union_test_absorption (no test procedure)
[notest] MCPL2Mantid_flat (no test procedure)
[notest] ILL_H15_IN6 (no test procedure)
[OK]     ILL_H10_IN8_83 (accuracy, 1 %)
[FAILED] Test_Pol_Guide_mirror_84 (compilation/execution)
[OK]     ISIS_Prisma2_85 (accuracy, 1 %)
[notest] templateVanadiumMultipleScat_Mantid (no test procedure)
[OK]     ILL_H22_D1A_86 (accuracy, 2 %)
[FAILED] ISIS_HET_87 (accuracy off by 55 %)
[notest] Test_SSR_SSW_Guide (no test procedure)
[notest] ESS_butterfly_tfocus_test (no test procedure)
[FAILED] Test_PolFieldBox_88 (compilation/execution)
[notest] Union_test_texture (no test procedure)
[OK]     linup-4_89 (accuracy, 4 %)
[notest] SE_example (no test procedure)
[OK]     ILL_H512_D22_90 (accuracy, 3 %)
[notest] MCPL_merge (no test procedure)
[notest] Test_Single_crystal_inelastic (no test procedure)
[OK]     FZJ_SANS_KWS2_AnySample_91 (accuracy, 2 %)
[OK]     FZJ_SANS_KWS2_AnySample_92 (accuracy, 6 %)
[OK]     FZJ_SANS_KWS2_AnySample_93 (accuracy, 2 %)
[OK]     FZJ_SANS_KWS2_AnySample_94 (accuracy, 6 %)
[notest] Union_external_component (no test procedure)
[OK]     PSI_DMC_simple_95 (accuracy, 1 %)
[OK]     PSI_source_96 (accuracy, 0 %)
[notest] TasResoTest (no test procedure)
[OK]     ILL_H113_97 (accuracy, 2 %)
[notest] Union_demonstration (no test procedure)
[??????] templateSANS_MCPL_98 (reference not found)
[notest] Union_tagging_demo (no test procedure)
[FAILED] Test_Sources_99 (accuracy off by 89 %)
[OK]     Test_Sources_100 (accuracy, 1 %)
[OK]     Test_Sources_101 (accuracy, 0 %)
[OK]     Test_Sources_102 (accuracy, 0 %)
[OK]     Test_Sources_103 (accuracy, 1 %)
[OK]     Test_Sources_104 (accuracy, 1 %)
[OK]     Test_Sources_105 (accuracy, 1 %)
[OK]     Test_Sources_106 (accuracy, 1 %)
[OK]     Test_MCPL_output_107 (accuracy, 6 %)
[notest] Union_single_crystal_validation (no test procedure)
[notest] ESS_butterfly_test (no test procedure)
[notest] NCrystal_example_mcstas (no test procedure)
[OK]     Test_Pol_TripleAxis_108 (accuracy, 1 %)
[OK]     Test_Monitor_Sqw_109 (accuracy, fair 8 %)
[OK]     Test_Monitor_Sqw_110 (accuracy, 4 %)
[notest] ILL_H142_D33 (no test procedure)
[OK]     Test_Magnetic_Majorana_111 (accuracy, 0 %)
[notest] RTP_Laue (no test procedure)
[OK]     ILL_H16_112 (accuracy, 1 %)
[OK]     ILL_H53_113 (accuracy, 5 %)
[OK]     HZB_NEAT_114 (accuracy, 2 %)
[OK]     HZB_NEAT_115 (accuracy, fair 14 %)
[OK]     Samples_Incoherent_116 (accuracy, 1 %)
[OK]     Samples_Incoherent_117 (accuracy, fair 19 %)
[OK]     Samples_Incoherent_118 (accuracy, 1 %)
[OK]     Samples_Incoherent_119 (accuracy, 1 %)
[OK]     Samples_Incoherent_120 (accuracy, 1 %)
[OK]     Samples_Incoherent_121 (accuracy, fair 20 %)
[OK]     Samples_Incoherent_122 (accuracy, 1 %)
[OK]     Samples_Incoherent_123 (accuracy, 1 %)
[OK]     Samples_Incoherent_124 (accuracy, 1 %)
[OK]     Samples_Incoherent_125 (accuracy, 1 %)
[OK]     linup-3_126 (accuracy, 8 %)
[notest] ISIS_TOSCA_preupgrade (no test procedure)
[OK]     linup-1_127 (accuracy, 1 %)
[notest] Union_test_powder (no test procedure)
[OK]     Test_Pol_Guide_Vmirror_128 (accuracy, 1 %)
[OK]     PSI_Focus_shielding_129 (accuracy, 1 %)
[notest] Vin_test (no test procedure)
[OK]     Test_MCPL_input_130 (accuracy, 3 %)
[notest] Test_Scatter_log_losses (no test procedure)
[notest] ESS_Brilliance_2013 (no test procedure)
[notest] Union_test_mask (no test procedure)
[OK]     BNL_H8_simple_131 (accuracy, 7 %)
[notest] McStas_Single_crystal (no test procedure)
[OK]     PSI_DMC_132 (accuracy, 1 %)
[OK]     Test_FocalisationMirrors_133 (accuracy, 1 %)
[notest] Test_focus (no test procedure)
[notest] Union_test_absorption_image (no test procedure)
[OK]     Samples_Incoherent_off_134 (accuracy, 2 %)
[OK]     ILL_Lagrange_135 (accuracy, 7 %)
[OK]     linup-5_136 (accuracy, 2 %)
[OK]     BTsimple_137 (accuracy, 1 %)
[notest] ISIS_IMAT (no test procedure)
[notest] ESS_BEER_MCPL (no test procedure)
[notest] HZB_FLEX (no test procedure)
[notest] Test_Scatter_log_ssw_mcnp (no test procedure)
[notest] Mezei_SNS_decoupled_poisoned (no test procedure)
[notest] ESS_Brilliance_2015 (no test procedure)
[OK]     BNL_H8_138 (accuracy, 1 %)
[OK]     Test_Pol_Bender_Vs_Guide_Curved_139 (accuracy, 2 %)
[OK]     linup-7_140 (accuracy, 4 %)
[OK]     Test_Pol_Mirror_141 (accuracy, 1 %)
[OK]     ILL_H22_D1B_142 (accuracy, 5 %)
[notest] RTP_SANS (no test procedure)
[notest] Demo_shape_primitives (no test procedure)
[OK]     Test_Guides_Curved_143 (accuracy, 1 %)
[OK]     Test_Guides_Curved_144 (accuracy, 1 %)
[OK]     Test_Guides_Curved_145 (accuracy, 1 %)
[OK]     Test_Guides_Curved_146 (accuracy, 1 %)

# Execution check:    FAILED. 2 instrument(s) did not compile/execute.
# >> Check instruments and mcstas installation.
# End Date: Mon May 18 17:31:24 2020 <--- Updated
# End Date: Mon May  4 15:23:12 2020
</pre>

**Comment by willend** [comment]
@ebknudsen we ought to get better at exactly this :-D

**Comment by willend** [comment]
PSI_Focus_shielding works now

**Comment by willend** [comment]
templateDIFF and templateTOF now have updated test values

**Comment by willend** [comment]
Shortlist of current failing instruments:
<pre>
[FAILED] Test_pol_tabled_5 (accuracy off by 300 %)
[FAILED] Test_Pol_Set_43 (accuracy off by 300 %)
[FAILED] Test_Magnetic_Rotation_64 (accuracy off by 301 %)
[FAILED] Test_Pol_Guide_mirror_84 (compilation/execution)
[FAILED] ISIS_HET_87 (accuracy off by 55 %)
[FAILED] Test_PolFieldBox_88 (compilation/execution)
[FAILED] Test_Sources_99 (accuracy off by 89 %)
# Execution check:    FAILED. 2 instrument(s) did not compile/execute.
</pre>

**Comment by ebknudsen** [comment]
Alright - I can feel the elbow in my ribs...

**Comment by willend** [comment]
:-D @ebknudsen no rush though :-)

**Comment by willend** [comment]
These are all ironed out, closing
