### ISSUE TITLE
mcgui and mxgui - File -> Open terminal environment is broken on debian (at least) 

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#1008]
Both for McStas 2.6.1. and McXtrace 1.5 the File->Open terminal Env. -button does not work.
It appears that the call on mcgui.py line 808 is simply wrong:
```                scriptfile = 'x-terminal-emulator ' + scriptfile```
which is called using
```        subprocess.Popen(scriptfile, shell=True)```
where x-terminal-emulatir is an etc.alternatives link to e.g. xterm

**Comment by willend** [comment]
Hmm, this was working fine on Ubuntu? Please check that the patched setup also works.

**Comment by willend** [comment]
I just hand-edited -e into mcgui.py on 20.04 and this also works OK.

**Comment by ebknudsen** [comment]
Also did that - my conclusion is it it only sort of kind of worked before. Notice that the script message gets lost with the missing -e. On 20.04 the default terminal emulator is gnome-terminal.wrapper which appears to result in a 2nd shell opening with the desired environs. Mucho confusing - but it seems to work for these cases as well. Maybe should check on Centos as well...

**Comment by willend** [comment]
Agreed, we should test on CentOS/Fedora, I have a couple of fresh VM's handy...

I think the issue must have arisen when gnome-terminal at one time did not accept an -e (which is of course what xterm always used). 

Never mind, it looks fixed and I believe most non-macOS and non-windows users never realised the menu item was there :-)

**Comment by willend** [comment]
I am reopening this one to remind myself that the x-terminal-emulator alternative is not available on the rpm platforms. Will edit mccodelib to have an entry to define an abstraction for this, which would include the -e (because then the code can be identical across macOS and Linux)

**Comment by willend** [comment]
Closing
