### ISSUE TITLE
Issues with two 2.6.1 monitors (was: Some monitor were broken by fix for #884)

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#1010]
DIvLambda_monitor was accidentally broken by a missing comma introduced by fix for #884.

**Comment by ebknudsen** [comment]
This appears to affect DivLambda_monitor and Divergence_monitor

**Comment by ebknudsen** [comment]
those two monitor fixed by 37b396deb788a42375ed62070cf1ce86fa19a52e

**Comment by willend** [comment]
Reopening for bookkeeping and since Kenji Nakajima reported the same issue via email for DivLambda_monitor:

```
if (xwidth  > 0) { xmax = xwidth/2;  xmin = -xmax; }
   if (yheight > 0) { ymax = yheight/2; ymin = -ymax; }
     printf("ERROR: (%s): Null detection area! Aborting.\n"
          NAME_CURRENT_COMP);
     exit(-1);
   }

Above should be

if (xwidth  > 0) { xmax = xwidth/2;  xmin = -xmax; }
   if (yheight > 0) { ymax = yheight/2; ymin = -ymax; }

   if ((xmin >= xmax) || (ymin >= ymax)) {
     printf("ERROR: (%s): Null detection area! Aborting.\n"
          NAME_CURRENT_COMP);
     exit(-1);
   }
```

**Comment by willend** [comment]
As a workaround, please pick e.g. https://raw.githubusercontent.com/McStasMcXtrace/McCode/master/mcstas-comps/monitors/DivLambda_monitor.comp for replacing your system-installed monitor.
