### ISSUE TITLE
Single_crystal.comp: Some parameter description texts broken

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#1012]
It looks like normal () parenthesis may break mcdoc.py parsing of Single_crystal:

![Screenshot 2020-05-06 at 15 03 23](https://user-images.githubusercontent.com/8593355/81180040-c5904480-8faa-11ea-834b-12608730e26a.png)

**Comment by willend** [comment]
In some sense fixed in 3d317e1d136744696ea0242221548b8c8f3abb9b, it turns out that mcdoc.py does not support parameter definitions/assignments of this type: ```a = 1``` whereas ```a=1``` is OK.

We should probably rather fix the mcdoc.py tool in this respect.

**Comment by willend** [comment]
with d09a597bc an adaptation has been done on the mcdoc parser to tolerate ```a = 1``` in component headers, and last change on Single_crystal reverted

**Comment by ebknudsen** [comment]
related to #1038 and #1043. Should likely be closed
