### ISSUE TITLE
read_table-lib 1-off error in Table_Value

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#1014]
There appears to be a 1-off error in the Table_Value interpolation routine.
Consider the attached instrument file. This ought to yield linear output but does not quite.
![table_value_1off](https://user-images.githubusercontent.com/855956/81731626-7d33c380-948f-11ea-84a6-687f7195d2e5.png)
[test_Table_Value.txt](https://github.com/McStasMcXtrace/McCode/files/4617748/test_Table_Value.txt)

**Comment by ebknudsen** [comment]
Just for simplicity  the test instrument is here as well:
The run above was with low=0, high=1

<code>
DEFINE INSTRUMENT test_Table_Value(low=0, high=1)

DECLARE
%{
  
  %include "read_table-lib"
  char filename[]="datafile1234";

  t_Table ttt;
  double hi,lo;
%}

INITIALIZE
%{
  int i,j;
  FILE *fp;

  fp=fopen(filename,"w");
  for(i=0;i<=10;i++){
    fprintf(fp,"%g %g %g\n",i/10.0,i/100.0,2*i/1000.0);
  }
  fclose(fp);

  j=Table_Read(&ttt,filename,0);
  hi=high;
  lo=low;
%}


TRACE

COMPONENT origin = Arm()
AT(0,0,0) ABSOLUTE 
EXTEND
%{
  double xx=rand01()*(hi-lo)+lo;

  printf("%g %g %g\n",xx,Table_Value(ttt,xx,1),Table_Value(ttt,xx,2));

%}
</code>

**Comment by willend** [comment]
@ebknudsen do we have an updated status on this one?

**Comment by willend** [comment]
There we nailed it @ebknudsen

**Comment by ebknudsen** [comment]
It seems the fix introduced an error the other way instead. Reexamining the issue.

**Comment by willend** [comment]
@ebknudsen nota bene https://github.com/McStasMcXtrace/McCode/issues/1149
