### ISSUE TITLE
McStas 2.6 on Windows 10: mcgui unstable.

### ISSUE THREAD

**Issue by tbigault** [McStasMcXtrace/McCode#1017]
mcgui often crashes in my configuration.
For example, if I open mcgui, then File>Open>Cancel, the mcgui window disappears.

When modifying and saving an instrument file in the editor through mcgui, it also sometimes crashes mcgui when trying to open the instrument file again, like if the *.instr file was corrupted. This happens even if the instrument file has no component in it.

**Comment by willend** [comment]
Hello @tbigault,

The first of the problems you report is in fact solved in 2.6.1, see https://github.com/McStasMcXtrace/McCode/issues/977

For the second issue, could it be you may have input non-ascii (i.e. accented characters) in the said file? If possible, please provide us with an example file that causes the behavior you mention.

Best Peter

**Comment by tbigault** [comment]
Hello Peter,
I updated to 2.6.1, and it solved the first point.
For the second, I had indeed such characters in the header (as comments), now it works.
Thanks!
Thierry
