### ISSUE TITLE
mcdoc (Python) gets confused when there's whitespace between parameter and default value

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#1043]
Python mcdoc has a problem when the comp parameter defintion line looks like this:
```SETTING PARAMETERS( prm1 = 1234, prm2 = 4321)```

as opposed to this which works:
```SETTING PARAMETERS( prm1=1234, prm2=4321)```

The problem manifests itself by leaving the unit and description fields blank in the generated html. 

Example: Slit.comp
The library comp has the line 
``` SETTING PARAMETERS (xmin=0, xmax=0, ymin=0, ymax=0, radius=0, xwidth=0, yheight=0)```
which produces:
![mcdoc_works](https://user-images.githubusercontent.com/855956/91842102-b321d100-ec53-11ea-874e-1f12b30ec769.png)

whereas if the line is changed to:
``` SETTING PARAMETERS (xmin = 0, xmax = 0, ymin = 0, ymax = 0, radius = 0, xwidth = 0, yheight = 0)```
mcdoc produces:
![mcdoc_whitespace](https://user-images.githubusercontent.com/855956/91842167-d2b8f980-ec53-11ea-83e1-bd660c7a6e0c.png)

**Comment by ebknudsen** [comment]
Related to #1038

**Comment by willend** [comment]
What version did you experience this issue with? I am almost certain I did a patch to mcdoc in this direction a couple of months ago, so master ought to not have this issue...

**Comment by ebknudsen** [comment]
Ah yes did not check against master - this was 2.6.1
