### ISSUE TITLE
Could not set parameters in array (pol_bender.comp)

### ISSUE THREAD

**Issue by jh-xu** [McStasMcXtrace/McCode#1051]
Dear Sir,

I am using Pol_Bender and Pol_guide_mirror components. I could not set  rTopUpPar et.al. parameters which 
![Mcstas](https://user-images.githubusercontent.com/57921137/95997787-6d504f00-0e34-11eb-8214-e80e0cf512de.PNG)
are arrays containing five elements. 

When compiling, it shows: "Warning: Using DEFINITION parameter of component Pol_guide_mirror() (potential syntax error) at line Test_Pol_Guide_mirror.instr:79
  rPar={ 0 , 0.0219 , 6.07 , 1 , 0.003 }". Even for this template instr file.

Could you help finding the problem?

Thank you very much.

**Comment by jh-xu** [comment]
PS: I am using Mcstas version 2.6.1 for windows

**Comment by ebknudsen** [comment]
Please note that this is a warning, not an error as such. In this case it can safely be ignored.

The meaning of the warning is that the construction *looks* suspicious to the parser. The end result in terms of generated c-code is completely valid and sound however.
In future releases of McStas, this type of warning will disappear, as we have a new language construct to take care of this kind of situation.

**Comment by jh-xu** [comment]
Thank you so much for you help.
I tested it. It takes in the newly set parameters though it warns "using Definition parameters...".
