### ISSUE TITLE
McCode kernel: math constants are defined in two places

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#1086]
We have definitions for M_PI, PI, M_SQRT2 in both mccode-r.h and by cogen. We should decide which is the right place. This does not block compilation (mostly) but is confusing.

argument for cogen: it is plainly visible to anyone who looks into the .c - code (at the top), which constants we support.

argument for mccode-r.h: cogen is complicated enough. This is simply code to be copy-pasted, and so should be in the runtime lib.

my personal preference is mccode-r.h

**Comment by farhi** [comment]
I agree for mccode-r.h. Having it in cogen is probably for historical reasons.

**Comment by willend** [comment]
Hi Guys and merry x-mas.

I seem to remember two reasons the current situation may have come around:

1) I think the reason to put the #defines in cogen had to do with missing definitions when using accelmath.h that needed to be in place before the random-functions, that are/were different on CPU and GPU. Perhaps this is no longer the case, I have the feeling that it came about when using curand, i.e. in Dresden until around Espoo. 

2) The reason to also have them in the runtime was that they were needed for mcformat (which I have now deprecated on the 3.0 branch)

The conclusion is: Agreed, the most natural place to have this stuff is in the runtime, but whoever does something about this issue should PLEASE test both in OpenACC and normal CPU/MPI execution modes.

**Comment by willend** [comment]
Looking at today's nightly test results, it seems that at least `M_SQRT2` is undefined in many cases in McXtrace:
http://new-nightly.mcxtrace.org/2022-11-09/overview.html
plus a few Pol-oriented ones in McStas:
http://new-nightly.mcstas.org/2022-11-09/overview.html

We can likely do with an `#ifndef M_SQRT2` solution in the top of `mccode-r.h`
