### ISSUE TITLE
McStas 3.0: focussing monochromator

### ISSUE THREAD

**Issue by cfranz82** [McStasMcXtrace/McCode#1106]
I tried to port a triple axis instrument from McStas 2.x to 3.0. Everything is fine, except some strange result of the focussing monochromator. On McStas 3.0, the scattered beam from the analyser is pointing downwards.

For the results, see:
![McStas_2p7](https://user-images.githubusercontent.com/78353151/106448925-b54abe80-6483-11eb-9399-23140c694b3f.png)
![McStas_3](https://user-images.githubusercontent.com/78353151/106450204-28086980-6485-11eb-8f90-2c6ca692183b.png)

The Instrument file used to generate the results:
[PANDA.instr.txt](https://github.com/McStasMcXtrace/McCode/files/5903471/PANDA.instr.txt)

Please note that a already with McStas 2.7 precompiled file runs fine in McStas 3.0.

**Comment by willend** [comment]
Hi @cfranz82,

Thanks for the bug-report that we will have a closer look at. Could you perhaps supply us with both the datafile  "../data/Pb.lau" and either

* The choice of input-parameters used to generate your dataset(s)
* The two datasets 

In the process of making 3.0 ready for release, @ebknudsen fought quite a but with Monochromator_curved. 

While we figure out what is going on, you may try Monochromator_2foc in its place? Most input parameters are compatible.

**Comment by willend** [comment]
(Oh and btw you are right that if an instrument is on the disk with instr/c/out from an earlier compile, this will run just fine with the tools of a newer version :-) )

**Comment by ebknudsen** [comment]
Hi @cfranz82 and @willend - Indeed - I spent some time porting Monochromator curved to 3.0, and in the process had to rewrite a bit of the code. I will take yet another look at it. If you as Peter says supply the Pb.lau file and/the parameters you used the risk of comparing apples to oranges becomes significantly smaller, and thus helps a lot.

**Comment by cfranz82** [comment]
Dear @willend and @ebknudsen ,

I have attached the Pb.lau file below:
[Pb.lau.txt](https://github.com/McStasMcXtrace/McCode/files/5944315/Pb.lau.txt)

The input parameters needed to reproduce the issue are the default parameters given in the instrument file. I will also attach these at the end here.

Let me know if you need further information!

Chris

	int prim_shut_pos=1,  /* 1,2,  or 3 primary shutter opening        */
	int sapphire = 1,     /* sapphire filter 1 = in , else out         */
	int ca1 = 80,         /* alfa 1 collimation 20,40,60, 80 = open    */
	int ca2 = 80,         /* alfa 2 collimation 15,40,60, 80 = open    */
	int ca3 = 80,         /* alfa 3 collimation 15,40,60, 80 = open    */
	int ca4 = 80,         /* alfa 4 collimation 15,40,60, 80 = open    */
	double ms1 = 0.04,    /* width of virtual source                   */
	double lms = 2.15,    /* distance mono to sample                   */
	double lsa = 1.05,    /* distance sample to ana                    */
	double lad = 0.95,    /* distance ana to detector                  */
	double ki = 0,        /* incident wavevector, if 0 not used        */
	double kf = 1.55,        /* final wavevector, if 0 not  used       */ 
	double dE = 0,        /* energy transfer  (meV)                    */
	double  Q = 2.5386,   /* momentum transfer in (AA-1)               */
/* mono axis */
	double mth = 0,       /* theta monochromator 						*/
	double mtt = 0,       /* 2theta monochromator 						*/
	double mtx = 0,       /* x translation monochromator                */
	double mty = 0,       /* y translation monochromator                */
	double mgy = 0,       /* gonio  monochromator 						*/
	double mfh = 4.5,     /* horizontal focus monochromator             */
	double mfv = 2,       /* vertical focus monochromator				*/
/* sample table */
	int scatsense = -1,   /* scattering sense at sample					*/
	double sth = 144.95,  /* theta sample       						*/
	double stt = 0,       /* 2theta sample        						*/
	double stx = 0,       /* x trans sample                             */
	double sty = 0,       /* y trans sample                             */
	double stz = 0,       /* z trans sample                             */
	double sgx = 0,       /* x gonio sample                             */
	double sgy = 0,       /* y gonio sample                             */
	double ss1_width = 0.02, /* ss1 width                               */
	double ss1_height = 0.03,/* ss1 height                              */
	double ss2_width = 0.02,  /* ss2 width                              */
	double ss2_height = 0.04, /* ss2 height                             */
/* analyser table */
	double ath = 0,       /* theta analyser     						*/
	double att = 0,       /* 2theta analyser      						*/
	double atx = 0,       /* x trans analyser							*/
	double aty = 0,       /* y trans analyser							*/
	double agy = 0,       /* y gonio analyser							*/
	double afh = 1.7,
	double afv = 0.6  )   /* focus  analyser

**Comment by ebknudsen** [comment]
Thanks a lot @cfranz82. My own investigations indicate a problem in Monochromator_curved when the number of blades is even. I.e. 13x5 (or 7) works as expected, but not 6. I'll try to find a fix.

**Comment by ebknudsen** [comment]
got it - a classic case of integer division. Fix coming in in a minute.

**Comment by ebknudsen** [comment]
fixed by 11d6f76f3cffb45b742f729f74969518f0ba2a18

**Comment by cfranz82** [comment]
Wow, that was quick! Thanks a lot!

**Comment by ebknudsen** [comment]
you're welcome! Always happy to help.
