### ISSUE TITLE
McStas-3.0 (and related branch) OpenACC/MPI/NeXus on Ubuntu 20.04 - simulation hangs

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#1118]
When generating NeXus files on multiple GPU's with MPI, it seems the simulation hangs in FINALLY when merging event-data.

**Comment by willend** [comment]
It seems the issue is related to the Ubuntu/debian-packaged NeXus package, building and installing NeXus from Git seems to remove this behaviour

**Comment by willend** [comment]
It also looks like event data are not written to the NeXus file even in the non-mpi case

**Comment by willend** [comment]
... On the tested machine there are even problems with cpu-MPI-NeXus run

**Comment by willend** [comment]
The problem is also available when using -ta=multicore

**Comment by willend** [comment]
... Changing the filename-entry in Monitor_nD to a simple one (events.dat) makes the multicore run store some data in the file - but segfaults at 1e8 ncount

**Comment by willend** [comment]
When the filename is simple, I also get data both in the single-GPU and MPIxGPU case!

**Comment by willend** [comment]
It seems even 
```
filename="bank01_events"
```
is OK - or any other up-to-13-char string...

**Comment by ebknudsen** [comment]
port to master in f20e3b604

**Comment by willend** [comment]
Indication is that this was fixed on mcstas-3.0
