### ISSUE TITLE
Pol_guide_mirror, missing on mcstas-3.0 branch, docs don't render properly on 2.x

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#1130]
As per discussion on this thread https://mailman2.mcstas.org/pipermail/mcstas-users/2021q2/001425.html

**Comment by ebknudsen** [comment]
Pol_guide_mirror is now present on the 3.0 branch as per 1dad8a10d1709fe79e74821e6a03ad83d5482b67

**Comment by ebknudsen** [comment]
Docs are not rendering correctly on 3.0 either. This appears to be a general bug concerning vector #1131

**Comment by willend** [comment]
Looks like this was fixed in #1131
