### ISSUE TITLE
McStas 3.0: mcgui insert dialog does not render vector parameter entries

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#1131]
This appears to be a general problem that the insert dialog window cannot render vector entries correctly.
The window simply is blank if a vector entry is present.
![image](https://user-images.githubusercontent.com/855956/122063486-9a546780-cdf0-11eb-8cb7-d0c94112615d.png)

**Comment by ebknudsen** [comment]
This is true for Single_crystal as well as Pol_guide_vmirror, and Pol_guide_mirror at least

**Comment by willend** [comment]
Fixed on mcstas-3.0 and master (even though setting parms including curlies are a 3.0-only feature)

**Comment by willend** [comment]
https://github.com/McStasMcXtrace/McCode/commit/ebf7e49f822b41e313fbe041a8cf50c507db483f#diff-ed1e4e1ee402c3c57cedb7dd85d48fef2f3bbd1dadf9efe9f48c730322d24205

**Comment by willend** [comment]
Reopening but marking "ready for release"
