### ISSUE TITLE
Nov 2021 port McXtrace gpu-achievements on Martin Cramer comps to mcstas 

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#1176]

**Comment by willend** [comment]
These are still missing
SANSPDBFast.comp	SANSQMonitor.comp	SANSShells.comp		SANSSpheres.comp

+ plus testing

**Comment by willend** [comment]
SANSSpheres - OK
SANSShells - OK
SANSCylinders - produces 0 on CPU + GPU
SANSEllipticCylinders - OK
SANSLiposomes - Results indicate thread-corruption on GPU
SANSNanodiscs - OK
SANSNanodiscsWithTags - OK
SANSPDB - does not currently compile
SANSCurve - missing "Curve.mcp"
SANSNanodiscsFast  - does not currently compile
SANSNanodiscsWithTagsFast - does not currently compile
SANSPDBFast - does not currently compile

**Comment by ebknudsen** [comment]
SANSPDB appears to compile - but it lacks an input data file

**Comment by willend** [comment]
All should now be functional, marking ready for release
