### ISSUE TITLE
Change downloads.mcstas.org to https

### ISSUE THREAD

**Issue by andyfaff** [McStasMcXtrace/McCode#1178]
I have issues downloading from `http://downloads.mcstas.org/` because Chrome classifies it as an insecure website (no https). Would it be possible to turn on https for that URL?

**Comment by willend** [comment]
Hi @andyfaff 

Thanks for reporting!

The machine is in fact already serving both http and https, but it seems the certificate had run out (which is likely what your browser reacted to.).

Please let me know if renewal is not enough.

Best,
Peter

**Comment by andyfaff** [comment]
I can't remember the exact links that I visited to do the download, it was probably https://github.com/McStasMcXtrace/McCode/blob/master/INSTALL-McStas-2.x/macOS/README.md. There are a few http links that need to be changed to https.

**Comment by willend** [comment]
Hi Andy,

OK - better now?

**Comment by andyfaff** [comment]
Yes, those links are good now. I'll let you know if I find any more.
