### ISSUE TITLE
mcdisplay: add pure Matlab 3d geometry plotter (without Perl layer)

### ISSUE THREAD

**Issue by farhi** [McStasMcXtrace/McCode#1186]
It would be nice to create a pure Matlab '3D display' viewer, without need for the Perl layer. It could even be better if it runs with Octave compatibility.

As a starting point, we may use the iFit/mccode.plot method <https://gitlab.com/soleil-data-treatment/soleil-software-projects/ifit/-/blob/master/Objects/iFunc_subclasses/@iFunc_McCode/plot.m>.

It only displays a static geometry, not ray trajectories, but it has the advantage to be much faster than the current mcdisplay.pl/matlab plotter. A further evolution could be to plot a limited set of rays, as static lines.

**Comment by willend** [comment]
Hi @farhi,

I have another proposal which I can make happen on a very short notice:

On the neutron-side I these days distribute a stripped-down version of mcdisplay.pl which has no graphics-dependencies and only produces the "Mantid" XML output. (mcdisplay-mantid.pl) It is part of mcstas-tools-perl-cmdline.

I propose we do a similar snippet which is only made for calling Matlab.

**Comment by farhi** [comment]
Hi @willend ;-)

Any solution which is faster and more robust than today is good. 

It's even better if:
- it does not depend on Python or Perl, only a bash script (as for other python launchers) that controls matlab/octave.
- it is compatible with Octave (that is, it remains simple).

**Comment by willend** [comment]
Hi again @farhi ,
It turns out I already did the work - more or less. The above-mentioned mcdisplay-mantid.pl "of course" already allows using m
