### ISSUE TITLE
Absorption Sample misbehaves

### ISSUE THREAD

**Issue by antoinepado** [McStasMcXtrace/McCode#1189]
When using the outer material box and inner material box of two different materials, the absorption sample functions properly.

When using only the outer material box the absorption sample seems to not exist.

When using the outer material box and inner material box of the same material, the trace (with webgl) crashes the OS.
 
[absample_prblm.txt](https://github.com/McStasMcXtrace/McCode/files/7617808/absample_prblm.txt)

**Comment by ebknudsen** [comment]
This is confirmed - there is a problem with the logic in INITIALIZE.
If there is no inner volume, the density of the outer volume never gets set.

**Comment by ebknudsen** [comment]
This should now be fixed by c9204d099a8c4d7e9a50c34a5a9f1ed6cb3db (and on 3.0 by 36fe4c95353f0b7e9358b379b3ec4de9ece42c89)
