### ISSUE TITLE
mcrun -d flag does not work for any directory except "."

### ISSUE THREAD

**Issue by bsobhani** [McStasMcXtrace/McCode#1274]
When I run a test simulation from mcgui it outputs the following to the console:

```
Running: mcrun BNL_H8_simple.instr -d /home/q8i/code/scratch/BNL_H8_simple_20220902_092839 -n 1000000 --autoplot --autoplotter=mcplot-pyqtgraph  lambda=2.36

```

The simulation runs correctly when I run it from the gui, but when I enter `mcrun BNL_H8_simple.instr -d /home/q8i/code/scratch/BNL_H8_simple_20220902_092839 -n 1000000 --autoplot --autoplotter=mcplot-pyqtgraph  lambda=2.36` in the command line and hit enter, I get this error:

```
(mcstas2) q8i@UBUNTU130398:~/code/scratch$ mcrun BNL_H8_simple.instr -d /home/q8i/code/scratch/BNL_H8_simple_20220902_092839 -n 1000000 --autoplot --autoplotter=mcplot-pyqtgraph  lambda=2.36
loading system configuration
Usage: mcrun.py [-cpnN] Instr [-sndftgahi] params={val|min,max|min,guess,max}...

mcrun.py: error: option -d/--dir: invalid path (was: "/home/q8i/code/scratch/BNL_H8_simple_20220902_092839")

```

But it exists and it is a directory:

```
>>> from os.path import isdir, abspath
>>> isdir(abspath("/home/q8i/code/scratch/BNL_H8_simple_20220902_120256"))
True
```

In the code I see the following line:

https://github.com/McStasMcXtrace/McCode/blob/master/tools/Python/mcrun/mcrun.py#L156

More context:

```
    def check_file(exist=True):
        ''' Validate the path to a file '''
        if exist:
            is_valid = isfile
        else:
            def is_valid(path):
                ''' Ensure path to file exists and filename is provided '''
                if path == "." or path == "./" or path == ".\\":
                    return True
                if not dir_exists(dirname(path)):
                    return False
                return not isdir(abspath(path))
        return build_checker(is_valid, 'invalid path')

    add('-d', '--dir',
        metavar='DIR', type=str,
        action='callback', callback=check_file(exist=False),
        help='put all data files in directory DIR')
```

I do not know what build_checker does, but if it effectively runs is_valid and returns the result, then I do not understand why it would say "not isdir(abspath(path))" instead of ""isdir(abspath(path))". If -d takes a directory as an input, then I would expect the result of a function called is_valid to be true if the input is a directory.

**Comment by willend** [comment]
Hello @bsobhani,

While perhaps not correctly documented, the -d option of mcrun (or similarly the directory-field on the mcgui run dialogue) do exactly what they are designed to do:

* The "standard" way of running McStas simulations is by having your .instr, generated .c and generated .out / .exe in some folder (aka "work" folder)
* Arguments to -d are assumed to be _relative_ and _non-existent_ paths, placed below your "work folder"
* Finally, the simulation executable does an mkdir to create the folder, except for the special case of '.' (which is the same as not giving a -d argument)
* When run through the Python tools, a -d output folder is in fact generated with instrument-name and timestamp

Hope this clarifies the situation?

**Comment by willend** [comment]
(Thus it could for instance be argued that the 'invalid path' above should rather be an 'error: path already exists')

**Comment by bsobhani** [comment]
Thank you for clarifying. I just tried entering the name of a non-existent directory and it works.
