### ISSUE TITLE
mcplot/mcplot pyqtgraph in "sweep mode" (across scan): missing dataset transformation from old to new colorbar

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#1287]
In the attached, a factor of 3 in intensity is seen in the plot legend between the first and last value of monitor. This is however not reflected visually. 

In other words, color-bar axes are common, but the datasets seemingly still represented on their old/initial color-bar

![Screenshot 2022-10-11 at 15 02 58](https://user-images.githubusercontent.com/8593355/195098714-4ebb9527-daae-48d4-a77f-20542ca14dfa.png)

**Comment by tweber-ill** [comment]
Should be fixed with https://github.com/McStasMcXtrace/McCode/commit/9f197c8f73de10ac2e445909b8613ece1abb7a75.
