### ISSUE TITLE
help for 'AttributeError: module 'pyqtgraph.Qt.QtGui' has no attribute 'QApplication'' !

### ISSUE THREAD

**Issue by huigui2020** [McStasMcXtrace/McCode#1296]
mcplot-pyqtgraph C:\mcstas-2.7.1\crosscheck\#beamline1
loading system configuration
mcplot error: module 'pyqtgraph.Qt.QtGui' has no attribute 'QApplication'
Traceback (most recent call last):
  File "C:\\mcstas-2.7.1\\lib\\tools\\Python\\mcplot\\pyqtgraph\\mcplot.py", line 67, in <module>
    main(args)
  File "C:\\mcstas-2.7.1\\lib\\tools\\Python\\mcplot\\pyqtgraph\\mcplot.py", line 57, in main
    raise e
  File "C:\\mcstas-2.7.1\\lib\\tools\\Python\\mcplot\\pyqtgraph\\mcplot.py", line 49, in main
    plotter = pqtgfrontend.McPyqtgraphPlotter(graph, sourcedir=loader.directory, plot_func=plotfuncs.plot, invcanvas=args.invcanvas)
  File "C:\mcstas-2.7.1\lib\tools\Python\mcplot\pyqtgraph\..\..\mccodelib\pqtgfrontend.py", line 46, in __init__
    self.app = QtGui.QApplication(sys.argv)
AttributeError: module 'pyqtgraph.Qt.QtGui' has no attribute 'QApplication'

the 'plot' function does not work. I don't know how to deal with it and ask for help! Thanks very much!

**Comment by huigui2020** [comment]
I installed the version 2.7.1 on win10

**Comment by willend** [comment]
Hello @huigui2020,

This is actually a well-known problem with the recent Python 3.10 release and the 2.7.1/3.1 releases, communicated to the [mcstas-users](https://mailman2.mcstas.org/pipermail/mcstas-users/2022q3/001478.html) mailinglist and website [mcstas.org](https://www.mcstas.org) on September 23rd.

To correct both this mcplot-related problem and a similar mcgui-related problem, please

replace the following files within your installation folder:

$MCSTAS/tools/Python/mcgui/viewclasses.py - please replace by [this new version](https://raw.githubusercontent.com/McStasMcXtrace/McCode/mccode-3/tools/Python/mcgui/viewclasses.py)
$MCSTAS/tools/Python/mccodelib/pqtgfrontend.py - please replace by [this new version](https://raw.githubusercontent.com/McStasMcXtrace/McCode/mccode-3/tools/Python/mccodelib/pqtgfrontend.py)

**Comment by huigui2020** [comment]
Hi @willend ,
Thanks for your help! I just subscribed to join the users mailinglist today. So I missed the important information.
The two files have been replaced by the new versions. But there is a new problem as following:

'mcplot-pyqtgraph C:\mcstas-2.7.1\crosscheck\#beamline17-202207_20221101_151108
loading system configuration

q              - quit
p              - save png
l              - log toggle
t              - textinfo toggle
c              - cycle colormap
F1/h           - help
F5             - replot
click          - display subplot
right-click/b  - back
alt + click   - sweep monitors
x              - expand subplots
mcplot error: scale(self): too many arguments
Traceback (most recent call last):
  File "C:\\mcstas-2.7.1\\lib\\tools\\Python\\mcplot\\pyqtgraph\\mcplot.py", line 67, in <module>
    main(args)
  File "C:\\mcstas-2.7.1\\lib\\tools\\Python\\mcplot\\pyqtgraph\\mcplot.py", line 57, in main
    raise e
  File "C:\\mcstas-2.7.1\\lib\\tools\\Python\\mcplot\\pyqtgraph\\mcplot.py", line 51, in main
    plotter.runplot()
  File "C:\mcstas-2.7.1\lib\tools\Python\mcplot\pyqtgraph\..\..\mccodelib\pqtgfrontend.py", line 62, in runplot
    plot_node(node, self.plot_func, plt_layout, viewmodel)
  File "C:\mcstas-2.7.1\lib\tools\Python\mcplot\pyqtgraph\..\..\mccodelib\pqtgfrontend.py", line 144, in plot_node
    viewbox_lst.append(add_plot(layout, node, plot_func, i, n, viewmodel))
  File "C:\mcstas-2.7.1\lib\tools\Python\mcplot\pyqtgraph\..\..\mccodelib\pqtgfrontend.py", line 382, in add_plot
    view_box, plt_itm = plot_node_func(node, i, plt, options)
  File "C:\mcstas-2.7.1\lib\tools\Python\mcplot\pyqtgraph\plotfuncs.py", line 33, in plot
    view_box, lyt = plot_Data2D(data, plt, log=opts['log'], legend=opts['legend'], icolormap=opts['icolormap'],
  File "C:\mcstas-2.7.1\lib\tools\Python\mcplot\pyqtgraph\plotfuncs.py", line 203, in plot_Data2D
    img.scale(dx,dy)
TypeError: scale(self): too many arguments'

**Comment by willend** [comment]
@huigui2020 thanks for reporting this one also, came to my attention from another user only yesterday.

For now the easiest workaround is to configure to use the matplotlib plotter instead i.e. in mcgui:

File -> Configuration

![Screenshot 2022-11-01 at 08 53 08](https://user-images.githubusercontent.com/8593355/199185507-96e4572a-2e37-472f-a599-10022883d788.png)

Choose mcplot-matplotlib in the 'mcplot' list and press save

![Screenshot 2022-11-01 at 08 53 19](https://user-images.githubusercontent.com/8593355/199185645-4ecfe227-f909-4e70-ac77-7e03f91c0837.png)

**Comment by willend** [comment]
Actually @huigui2020 you may use the pyqtgraph plotter again by replacing your

$MCSTAS/tools/Python/mcplot/plotfuncs - please replace by [this new version](https://raw.githubusercontent.com/McStasMcXtrace/McCode/master/tools/Python/mcplot/pyqtgraph/plotfuncs.py)

**Comment by huigui2020** [comment]
Hi @willend&nbsp;
Yes, that solved my problem. Now it can work normally. Thanks very much!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "McStasMcXtrace/McCode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月1日(星期二) 下午4:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [McStasMcXtrace/McCode] help for 'AttributeError: module 'pyqtgraph.Qt.QtGui' has no attribute 'QApplication'' ! (Issue #1296)





 
Actually @huigui2020 you may use the pyqtgraph plotter again by replacing your
 
$MCSTAS/tools/Python/mcplot/plotfuncs - please replace by this new version

**Comment by huigui2020** [comment]
Hi @willend 
Yes, that solved my problem. Now it can work normally. Thanks very much!

**Comment by farhi** [comment]
Done with commit c2ae39a5ef56285cd6d10e80fafb1eab7ed82871
