### ISSUE TITLE
Make CMake cfg more standard

### ISSUE THREAD

**Issue by tkittel** [McStasMcXtrace/McCode#1301]
As a precursor to #1300 and also to support more intuitive standalone builds with cmake, it would be useful if build cfg with a simple:
```
cmake -DCMAKE_INSTALL_PREFIX
```
would work. Any changes should ideally not interrupt current build scripts etc., needed by @willend for building packages for various platforms.

**Comment by tkittel** [comment]
Also needs #1299 to be resolved.

**Comment by tkittel** [comment]
Something to look into later: Trying to build MCXTRACE in this manner lead to the creation of a new file in the *source* directory: `tools/Python/mcdisplay/matplotlib/mxdisplay.py`, which I guess is not OK behaviour.

**Comment by willend** [comment]
@tkittel wrt. the last comment, https://github.com/McStasMcXtrace/McCode/issues/1319 was put together and fixed by @g5t during hackathon
