### ISSUE TITLE
Output instrument geometry to standard-format(s), e.g., STEP

### ISSUE THREAD

**Issue by g5t** [McStasMcXtrace/McCode#1309]
The various `mcdisplay*` tools make use of the binary's `--trace` option to learn the generated instrument geometry as a series line segments and geometric primitives. For a simple instrument with a collection of slits, the output looks like:
```
MCDISPLAY: start
MCDISPLAY: component Origin
MCDISPLAY: component radial_slit
MCDISPLAY: circle('xy',0,0,0,3)
MCDISPLAY: component symmetric_slit
MCDISPLAY: multiline(3,-1,1,0,-0.5,1,0,-0.5,2,0)
MCDISPLAY: multiline(3,1,1,0,0.5,1,0,0.5,2,0)
MCDISPLAY: multiline(3,-1,-1,0,-0.5,-1,0,-0.5,-2,0)
MCDISPLAY: multiline(3,1,-1,0,0.5,-1,0,0.5,-2,0)
MCDISPLAY: component offset_slit
MCDISPLAY: multiline(3,0,5,0,1,5,0,1,7.55,0)
MCDISPLAY: multiline(3,4,5,0,3,5,0,3,7.55,0)
MCDISPLAY: multiline(3,0,-0.1,0,1,-0.1,0,1,-2.65,0)
MCDISPLAY: multiline(3,4,-0.1,0,3,-0.1,0,3,-2.65,0)
MCDISPLAY: component closed_width_slit
MCDISPLAY: multiline(3,-0,5,0,-0,5,0,-0,6,0)
MCDISPLAY: multiline(3,0,5,0,0,5,0,0,6,0)
MCDISPLAY: multiline(3,-0,3,0,-0,3,0,-0,2,0)
MCDISPLAY: multiline(3,0,3,0,0,3,0,0,2,0)
MCDISPLAY: component closed_y_slit
MCDISPLAY: multiline(3,-0,5,0,-0,5,0,-0,5,0)
MCDISPLAY: multiline(3,0,5,0,0,5,0,0,5,0)
MCDISPLAY: multiline(3,-0,5,0,-0,5,0,-0,5,0)
MCDISPLAY: multiline(3,0,5,0,0,5,0,0,5,0)
MCDISPLAY: end
```

This description lends itself to conversion to a Boundary Representation of the geometry, as used in OpenCASCADE (see, e.g., [Toplological shapes](https://dev.opencascade.org/sites/default/files/pdf/Topology.pdf)).

The `MCDISPLAY` information only contains `points`, `edges`, and `wires`; but it may be safe to assume, e.g., that each component forms at least one closed face, and may form `shells` and `solids`.
If the information can be converted to the BRep used by OpenCASCADE then the instrument geometry can be saved to a number of standard formats, including STEP and STL.

This conversion could be performed outside of the instrument binary, like the existing `mcdisplay*` tools; or could be done *within* the binary if numerical precision in point positions is paramount.

**Comment by willend** [comment]
@g5t thanks for your contribution via PR
