### ISSUE TITLE
`mcdisplay-matplotlib` CMake configuration overwrites Python script

### ISSUE THREAD

**Issue by g5t** [McStasMcXtrace/McCode#1319]
Running the CMake configuration in the `mccode-3` branch, `./tools/Python/mcdisplay/matplotlib/mcdisplay.py` gets either overwritten (McStas) or copied to `./tools/Python/mcdisplay/matplotlib/mxdisplay.py` (McXtrace).

The configuration should not overwrite the source file.

**Comment by willend** [comment]
@g5t I think we fixed this during the code-camp?
