### ISSUE TITLE
install instructions: update enable_mcstas -> BUILD_MCSTAS?

### ISSUE THREAD

**Issue by birkenfeld** [McStasMcXtrace/McCode#1394]
While building 2.7.2 from source, the install instructions at https://github.com/McStasMcXtrace/McCode/blob/master/INSTALL-McStas-2.x/Linux/src/README.md say to use `cmake -Denable_mcstas=1`.

Many components' cmake complained with that, saying "no flavor specified" and that I need to define either `BUILD_MCSTAS` or `BUILD_MCXTRACE` - do the instructions need updating?

Same for version 3.2.

**Comment by willend** [comment]
Dear @birkenfeld, thanks for reporting!

Indeed, the build docs need updating. Sorry for the inconvenience.

**Comment by birkenfeld** [comment]
Great, thanks!

**Comment by willend** [comment]
@birkenfeld I have now updated the docs, closing the issue.
