### ISSUE TITLE
MPI: use #cores instead of #cpu limitation: mpirun --oversubscribe

### ISSUE THREAD

**Issue by farhi** [McStasMcXtrace/McCode#1397]
It seems it is not possible to launch an MPI calculation beyond the number of physical cores. However, it is usual to have twice as many logical cores.

```bash
mpirun -np 32  a.out
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 32
slots that were requested by the application:

  a.out

Either request fewer slots for your application, or make more slots
available for use.

A "slot" is the Open MPI term for an allocatable unit where we can
launch a process.  The number of slots available are defined by the
environment in which Open MPI processes are run:

  1. Hostfile, via "slots=N" clauses (N defaults to number of
     processor cores if not provided)
  2. The --host command line parameter, via a ":N" suffix on the
     hostname (N defaults to 1 if not provided)
  3. Resource manager (e.g., SLURM, PBS/Torque, LSF, etc.)
  4. If none of a hostfile, the --host command line parameter, or an
     RM is present, Open MPI defaults to the number of processor cores

In all the above cases, if you want Open MPI to default to the number
of hardware threads instead of the number of processor cores, use the
--use-hwthread-cpus option.

Alternatively, you can use the --oversubscribe option to ignore the
number of available slots when deciding the number of processes to
launch.
--------------------------------------------------------------------------
```

One solution is to add the `--oversubscribe` option to e.g. `mpirun`:
```bash
mpirun -np 32 --oversubscribe ...
```

**Comment by willend** [comment]
@farhi yes, this seems to be default openmpi behaviour since 4.x.

Indeed, simply put `mpirun --oversubscribe` in the MCRUN setting in mcode_config.json

**Comment by willend** [comment]
I am labelling with `wontfix` since this is not really a McStas/McXtrace issue but down to configuration of the chosen / selected MPI.

**Comment by willend** [comment]
Yes it can be set from mcgui configuration:

Before adjustment on a 20 core (40 hyperthread) machine:
![Screenshot 2023-01-18 at 16 19 01](https://user-images.githubusercontent.com/8593355/213211016-9d754de0-1fed-4b14-a1a7-7a23ba397545.png)
![Screenshot 2023-01-18 at 16 19 10](https://user-images.githubusercontent.com/8593355/213211080-6a485fd5-5a77-46d0-bd4a-2360edb1d6c2.png)

Then adjusting by means of config dialogue / save:
![Screenshot 2023-01-18 at 16 19 41](https://user-images.githubusercontent.com/8593355/213211268-39bd7ac5-b981-45b4-bf74-c39fb83c0866.png)
![Screenshot 2023-01-18 at 16 20 04](https://user-images.githubusercontent.com/8593355/213211298-dc928d59-aa89-4013-91ae-a2aa40a7cc61.png)

**Comment by farhi** [comment]
OK, one solution that can apply to all users is to modify the default toolchain that sets the JSON default config:
- https://github.com/McStasMcXtrace/McCode/blob/mccode-3/tools/Python/mccodelib/mccode_config.json.in
- https://github.com/McStasMcXtrace/McCode/blob/mccode-3/tools/Python/mccodelib/mccode_config.json

For instance we could just change the definition:
- set(MPIRUN "mpirun")

into

- set(MPIRUN "mpirun --oversubscribe")

in files such as:
- https://github.com/McStasMcXtrace/McCode/blob/master/cmake/toolchains/linux64.cmake
