### ISSUE TITLE
Guide_anyshape and gravity problem with many intersections (Follow up #1248) 

### ISSUE THREAD

**Issue by riwa73** [McStasMcXtrace/McCode#1407]
I am writing on a problem concerning the Guide_anyshape component (will hold for Guide_anyshape_r, too)

I was very happy as I saw that in the new releases (2.72 and 3.2) the issue 1248 [https://github.com/McStasMcXtrace/McCode/issues/1248]
had been addressed and changes and adaptions in the affected modules and  functions have been made.
(interoff-lib.c and r-interoff-lib.c)

I stumbled over the same issue  in my simulations - with gravity turned on the lower half of my neutron optical components (made with Guide_anyshape) seemed to absorb neutrons.

I use rather complicated nested structures:
<img width="614" alt="image" src="https://user-images.githubusercontent.com/45610613/217290448-f6893e8f-84d1-4bba-8fee-337830858dc4.png">

First tests looked promising, but then (with complicated structures) the simulations crashed resp. didn't ever finish.
If I turned off gravity it worked. 

I think I found the problem and a solution (using some low level debugging aka printf()).

In the **interoff-lib.c** in the function int **off_intersect_all()**

We have the snippet:

  ```
  intersection intersect4[4];
    intersect4[0].time=-FLT_MAX;
    intersect4[1].time=FLT_MAX;
    intersect4[2].time=FLT_MAX;
    intersect4[3].time=FLT_MAX;
    int t_size = 0;
    if(mcgravitation) {

   
      
      Coords pos={ x,  y,  z};
      Coords vel={vx, vy, vz};
      Coords acc={ax, ay, az};
      t_size=off_clip_3D_mod_grav(intersect4, pos, vel, acc,
                  data->vtxArray, data->vtxSize, data->faceArray,
                  data->faceSize, data->normalArray, data->DArray);
    }

```
The crash occurs if **t_size** becomes 5 (or bigger)

in **off_clip_3D_mod_grav()**

the line:
   `t[t_size++]=inters`

writes on **intersect4** (that is pointed on by t) although the length/size is fixed to 4 regardless of the value of **t_size**

In **off_clip_3D_mod()** the situation is treated differently:

```
#ifdef OFF_LEGACY
          t[t_size++]=inters;
#else
    /* Check against our 4 existing times, starting from [-FLT_MAX, FLT_MAX, FLT_MAX, FLT_MAX] */
    /* Case 1, negative time? */
    if (t_size < 4) t_size++;   
    if (inters.time < 0) {
      if (inters.time > t[0].time) {
        t[0]=inters;
      }
    } else {
      /* Case 2, positive time */
      intersection xtmp;
      if (inters.time < t[3].time) {
      t[3]=inters;
        if (t[3].time < t[2].time) {
    xtmp = t[2];
    t[2] = t[3];
    t[3] = xtmp;
        }
        if (t[2].time < t[1].time) {
    xtmp = t[1];
    t[1] = t[2];
    t[2] = xtmp;
        }
      }
    }
#endif
```

So it it is never written to **t** with an index larger than 4.

As a test I did the same in **off_clip_3D_mod_grav()** which seems to work.

The McStas developers are informed.

**Comment by willend** [comment]
@riwa73 thanks a bunch for the issue and patch - that was already integrated on commits 6cb95373fdb11e7cc5d747fb07e22de216740b6d (mccode-3) and 265d631013f766a648a7ad6caf278a950b09e4f8 (master).

I have been running a couple of hand-held test that indicate all is good, but tonight's https://new-nightly.mcstas.org will give the full picture.
