### ISSUE TITLE
Guide_anyshape problem with no gravity (Related to  #1407 and #1248)

### ISSUE THREAD

**Issue by riwa73** [McStasMcXtrace/McCode#1416]
(Related Issues  and   #1407 and #1248  )
Some of my with nested optics had the problem that very few neutrons arrived at the detector at the end of the instrument.
Interestingly with **gravity** turned **off** 

This is what the 2D monitor shows
<img src="https://user-images.githubusercontent.com/45610613/224292472-f0ecf8b1-6ed4-440b-9834-b4962f453425.png" width="400">

wo gravity turned on I get:

<img src="https://user-images.githubusercontent.com/45610613/224292464-e3608cdf-dab3-453b-bbba-374d18e7faff.png" width="400">

from the logs it seems the events have negative time:

run wo gravity:
```
INFO: ===
Warning: 526176 events were removed in Component[9] psd_monitor=PSD_monitor()
         (negative time, miss next components, rounding errors, Nan, Inf).
```

run wt gravity:

```
INFO: ===
no error
```

**Comment by willend** [comment]
@riwa73 thanks for reporting, please supply the instrument you used to allow reproducing. :)

**Comment by riwa73** [comment]
I did some debugging and think found the problem and a solution:
**interoff-lib.c**
`int off_intersect_all(..)`
the intersection structure is inititlized with +/-FLT_MAX

```C++
    intersection intersect4[4];
    intersect4[0].time=-FLT_MAX;
    intersect4[1].time=FLT_MAX;
    intersect4[2].time=FLT_MAX;
    intersect4[3].time=FLT_MAX;
```

Later in the function, if all intersection times are negative:
FLT_MAX is copied to t3

```C++
if(t_size>0){
           
      int i=0;
      if (intersect4[0].time == -FLT_MAX) i=1;
      data->numintersect=t_size;
      if (t0) *t0 = intersect4[i].time;
      if (n0) *n0 = intersect4[i].normal;
      if (t3) *t3 = intersect4[i+1].time;
      if (n3) *n3 = intersect4[i+1].normal;
     
      /* should also return t[0].index and t[i].index as polygon ID */
      return t_size;
```
I added the following lines to supply t3 with 0 in this particular case

```C++
if(t_size>0){
      

      int i=0;
      if (intersect4[0].time == -FLT_MAX) i=1;
      data->numintersect=t_size;
      if (t0) *t0 = intersect4[i].time;
      if (n0) *n0 = intersect4[i].normal;
      if (t3) *t3 = intersect4[i+1].time;
      if (n3) *n3 = intersect4[i+1].normal;
       
      if (intersect4[1].time == FLT_MAX)
      {
        //printf("All intersection times negative -> Set t3 to 0\n");
        if (t3) *t3 = 0.0;
      };  

      /* should also return t[0].index and t[i].index as polygon ID */
      return t_size;
    }
```
The module **r-interoff-lib.c** should have the similar issue

**Comment by riwa73** [comment]
Results from simulations with the proposed patch:

with gravity:
<img src="https://user-images.githubusercontent.com/45610613/224328784-0f890bc1-48b8-492e-b7ff-fcf2b4c18963.png" width="400">
without:
<img src="https://user-images.githubusercontent.com/45610613/224328828-f6c86f60-1ff3-472a-87d6-1601e8eafd19.png" width="400">

As expected performance (= Figure of Merit aka FOM ) is better without gravity

If necessary I can provide a test-instrument, too.

Richard

**Comment by willend** [comment]
@riwa73 implemented on master and mccode-3 in preparation for release. Will check back to this issue pending nightly test.

**Comment by willend** [comment]
Marking "ready for release" and will subsequently close
