### ISSUE TITLE
Feature Request: new block keyword `LITERAL`

### ISSUE THREAD

**Issue by g5t** [McStasMcXtrace/McCode#1470]
## Problem
The [`eniius`](https://github.com/mducle/eniius.git) project has been created by @mducle to, broadly speaking, connect `McStas` instruments with analysis software via enhanced `NeXus` data files. For which there is a need to get arbitrary formatted strings from the `McStas` instrument file into the NeXus structure. Thus far this has been achieved by defining a special variable in a component's `EXTEND` block of the form `char eniius_data[] = "...";` where the elided part of course must be a valid C string. 
_The C string validity is a bit hampering, since some language string formats do not lend themselves well to it._

`eniius` uses `McStasScript` to read an instrument file, which preserves non-comments from `EXTEND`, after which it looks for the special variable and does some translations to get it into the expected format, in this case `JSON`.
For other languages, e.g., `Python` _inside_ of the `JSON` string, the level of mangling required make the C string representation difficult to comprehend in the instrument file.

Since the special variable(s) are only included as `char` arrays, they are processed by the compiler and (depending on compiler optimizations) _may_ be present in the produced binary.
If they are present, they increase the binary size with little utility since even if extracted by, e.g., `strings`, they may still need to undergo special parsing to be understood.

__I think there should be a method to get artibrary-format strings out of an instrument file in a machine and human accessible way.__

### Block comments
We can always include an arbitrary formatted text block inside of an instrument file by placing it inside of a block comment.
At the moment, these comments are omitted during instrument file parsing. Changing this behavior is not likely desirable.

### Add a new special block
A new EXTEND-like block could be defined in a component file or the instrument file. It would store literal strings in the compiled instrument, in a table with keys associated with each component. There would be a way to retrieve the string(s) from the binary.

There would be binary size overhead compared to the current `eniius` solution, but that might be inconsequential compared to the encoding/decoding steps required.

## Desired solution
Of the two possibilities presented, adding a new block to the McCode syntax seems the better option.

As a first attempt, that block could take the name `LITERAL`. It could define the _type_ of string literal (for user informational purposes) and a component-specific name for the string literal. 
`LITERAL [type] [name] %{[string]%}`

### Possible use in instrument file
```
Component slit = Slit() AT (0, 0, 0.1) RELATIVE PREVIOUS
LITERAL JSON eniius_data %{
...{JSON string}...
%}
LITERAL Python extra_function %{
def the_function(a, b, c):
    return a + b / c
%}
```

### Possible interface via binary
The compiled instrument would hold a table of literal strings.
The command line interface would be extended to provide access to these strings via `--literal*` keywords.

| keyword | input | output |
|--------------|---------|------------|
| `--literal-defined` | | was there *any* literal string defined in the instrument |
| `--literal-defined` | component | a list of the literals defined for `component` |
| `--literal-defined` | component::name | character count of literal `name` defined for `component`|
| `--literal-type` | component::name | what format does the literal claim |
| `--literal` | component::name | the literal string |

Interacting with the command line interface might look like:
```bash
$ instrument.out --literal-defined
slit other_component
$ instrument.out --literal-defined slit
eniius_data extra_function
$ instrument.out --literal-defined slit::eniius_data
224
$ instrument.out --literal-type slit::eniius_data
JSON
$ instrument.out --literal-defined slit::undefined_name_data 
0
$ instrument.out --literal-type slit::undefined_name_data
$ instrument.out --literal slit::extra_function
def the_function(a, b, c):
    return a + b / c
$
```

**Comment by g5t** [comment]
I have a development branch in which I've successfully added the `LITERAL` grammar and amended the code-generator to output a suitable string-escaped `struct` in the C file.

Implementing the extra command line options for the binary should be relatively straight forward.

Hopefully no one thinks this is all a terrible idea :sweat_smile:

**Comment by willend** [comment]
I look forward to a demo! 😊

Having given the idea a thought, perhaps `METADATA` could also be a reasonable block name? (One useful purpose could be actual code, other would be explanations documentation etc?)

**Comment by g5t** [comment]
In case anyone is interested:
The `LITERAL` keyword was renamed `METADATA` and included in McStas 3.x via #1477 
A few issues made it through and a second new PR #1478 will hopefully address all of them.

This issue is now resolved since my feature request was accepted. :partying_face:
