### ISSUE TITLE
tools: mcplot/mxplot: allow save as png/tif/eps/svg/etc plots from command line

### ISSUE THREAD

**Issue by farhi** [McStasMcXtrace/McCode#1488]
Currently, only the `mcplot-matplotlib` allows to save the plots from the command line (--format).
The `mcplot-svg` does not create an SVG, but displays/creates an HTML plot, and only for a single monitor file

So I'd like to bring-up the possibility to:
- add `--format` to all plotters
- perhaps rename the `mcplot-svg` to `mcplot-html` ? Add a loop to generate HTML's for all monitors when given a directory ?

**Comment by willend** [comment]
@farhi agreed. As far as I remember, the pyqtgraph plotter can only create a "hardcopy" once a plot window exists, so it is really Qt/display oriented... 

And perfectly fine with a rename of mcplot-svg ->  mcplot-html. Perhaps also an extension with an "overview" plot containing iframes with the individual monitor subplots?

( BTW. the `Scipp` (https://scipp.github.io) guys have developed the `plopp`(https://scipp.github.io/plopp/index.html) plotting tool which is supposed to work on the terminal, in Jupyter and potentially in e.g. Qt apps. I was thinking we should have a closer look at some point. )

**Comment by farhi** [comment]
I think I can not do more. PyQTGraph requires indeed a display. The mcplot-svg could be renamed, but for now I think this is fine.
