### ISSUE TITLE
McCode rpm repository

### ISSUE THREAD

**Issue by jeremyspencer39171** [McStasMcXtrace/McCode#1499]
Hi,

Apologies if this isn't the right place for this.
We make use of the repo at https://packages.mccode.org/rpm/x86_64/ to install McStas.
Sometime yesterday the `repodata` directory seems to have gone missing, so yum can't use the repository.

I wonder if something has gone awry when making the latest package available.

Is this something you can help resolve?

Thanks.

This is the error I get:
> https://packages.mccode.org/rpm/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden

**Comment by willend** [comment]
Jeremy, thanks for reaching out, I will have a look at what is going on.

That being said, be aware that particular rpm repo is/was intended for CenOS 8 and below, which we are in principle not providing packages for any longer…

Best
Peter

**Comment by willend** [comment]
Hi again,

Hardened security on the machine set a more restrictive default umask - I have now fixed the permissions.

Are you interested in a Centos8-build being made available? (I might have time for this thursday or friday...)

**Comment by jeremyspencer39171** [comment]
Excellent. That's all working now.
Thank you very much.

We've started putting it in Apptainer (fork from Singularity) containers based on Ubuntu, so hopefully we won't need that.
I'll make a different issue if later it turns out that would be helpful. Thank you for the offer.

Best,
Jeremy

**Comment by jeremyspencer39171** [comment]
We're in the process of switching from CentOS 7 to Rocky 8 (started before the change in RedHat's business plan, so we'll see how well that goes).
conda-forge would be useful too as an alternative in case we get any complications with the container route.

**Comment by willend** [comment]
I might give Rocky 8 a spin, will let you know what the best route forward is.

**Comment by willend** [comment]
I've created a set of experimental RPM's - they require a newer Python than the stock one on Rocky 8...

But I've included a shell-script based mechanism to inject the required dependencies via an embedded conda env..

http://downloads.mcstas.org/mcstas-3.4/Linux/rocky8/

Let me hear how it goes?

**Comment by willend** [comment]
Similarly I have now build a set of rpm's for CentOS7 http://downloads.mcstas.org/mcstas-3.4/Linux/centos7/ - dependencies handled the same way via a shell script... 

I would prefer not to stick these rpm's in the normal /rpm repo as they would not be much use for an end-user until the Python dependencies are "injected" - but what do you think?
