### ISSUE TITLE
cmake_minimum_required 2.x is too old

### ISSUE THREAD

**Issue by tkittel** [McStasMcXtrace/McCode#1507]
https://github.com/McStasMcXtrace/McCode/blob/2f807a909b79f3105a770c986cf1a622b9afc212/mcstas/CMakeLists.txt#L1C1-L2C1

Causes warnings in conda builds (where CMake is brand new) like:

```
CMake Deprecation Warning at mcstas/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.
```

We should probably update all of them to the 3.17 that we use in the top-level CMakeLists.txt.

**Comment by willend** [comment]
Have bumped all "non-legacy" things to 3.17.0 see b2e791c on main and de1e052dd on mcstas-3.4-release

**Comment by tkittel** [comment]
Perfect!

**Comment by farhi** [comment]
All cmake now target a 3.17. Ready...
