### ISSUE TITLE
McStas-Components,Polarisation: Pol_simpleBfield segfault

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#151]
**Reported by erkn on 20 Aug 2013 08:43 UTC**
When using nested fields - segfaults may occur when the neutron escapes the inner field description in an unexpected manner.

**Comment by willend** [comment]
@farhi , @ebknudsen was this maybe fixed already?

**Comment by ebknudsen** [comment]
This has been fixed

**Comment by willend** [comment]
👍 :-)
