### ISSUE TITLE
Missing semicolon

### ISSUE THREAD

**Issue by g5t** [McStasMcXtrace/McCode#1515]
https://github.com/McStasMcXtrace/McCode/blob/b590eb9bf1122f5e76abe69b9ca13bc5bd4a6f68/mcstas-comps/union/Union_init.comp#L57

The print statement should be followed by a semicolon to be valid `C` code.

**Comment by willend** [comment]
Indeed.

**Comment by g5t** [comment]
I think this one was overlooked because, in the expected use case, it's protected by a preprocessor fence and never seen by the compiler. And if something has defined `Union` already, an error would have been expected at runtime.
