### ISSUE TITLE
pol_tabled_field result changes after sorting input file

### ISSUE THREAD

**Issue by sq-meng** [McStasMcXtrace/McCode#1553]
The two images shown are polarized neutron imaging results of the same magnetic field using pol_tabled_field, just with points supplied in the file in different order.

Edit: original contents collapsed to save page space.
<details>

![no_sort](https://github.com/McStasMcXtrace/McCode/assets/24553296/753b9fa1-615e-485f-85be-773dbeff2baa )
![z_sort](https://github.com/McStasMcXtrace/McCode/assets/24553296/66177324-6e21-40b6-adb0-ccc50a2a64f3)

I had expected the results to be identical as the interpolation process employs a kd-tree nearest neighbor search, which shouldn't require the source file to have a certain spatial order. The behavior is reproduced on both ubuntu and windows, both MPI and single-thread.
To make things even more perplexing, below is the same stuff ran on a cluster, which looks more similar and symmetric:
![cluster_nosort](https://github.com/McStasMcXtrace/McCode/assets/24553296/6b1f4fb4-7ff1-4b3f-a1b0-e4f5d2866716)
![cluster_zsort](https://github.com/McStasMcXtrace/McCode/assets/24553296/9eb3a836-d2fe-47ea-8436-8c779ce121bd)
But the cluster doesn't always do this. If I `module load` something into bash ~~during run-time~~ before submitting the job, then I get the top two different results again. So the behavior can be affected by system environment during run-time.

The files used to reproduce this behavior is supplied in the zip file. The two .instr files are identical except the hard-coded b-field data filenames. the python script is used to generate the two field .dat files.
[instr_field_results.zip](https://github.com/McStasMcXtrace/McCode/files/14059188/instr_field_results.zip)
</details>

**Comment by sq-meng** [comment]
I think this is it:
https://github.com/McStasMcXtrace/McCode/blob/8c8cfc0e777f8cbac59cdf9247a76fcd634a1d88/common/lib/share/interpolation-lib.c#L223-L227
Line 224, `int treek` should be `double`. Making this change results in the following image, which I think is expected from the field:
![mcplot](https://github.com/McStasMcXtrace/McCode/assets/24553296/164b3c28-7aac-4b37-bda9-edcf617991d1)

**Comment by willend** [comment]
@sq-meng thank you for reporting and also getting back with a potential solution!

I will try implementing this on a special branch and run the test-suite to ensure there are no unwanted side-effects.

**Comment by sq-meng** [comment]
@willend Yes, point order no longer affects output now. I do expect test outputs to change though, as I think the old code contained a bug that caused some search branches to be aborted incorrectly. We probably should consult original author @farhi2 for a go/no-go?

**Comment by willend** [comment]
@sq-meng I think @farhi2 would have no issue with this patch. :-) 

For now I have implemented on my personal McCode fork and started a test 
https://github.com/willend/McCode/actions/workflows/mcstas-testsuite.yml

**Comment by willend** [comment]
The test output looks reasonable, http://tmp.mcstas.org/test_output.html

I will not merge the patch to main

**Comment by willend** [comment]
I deem this "ready for release" - will close on release of McStas 3.5, hopefully within 1-2 months

**Comment by sq-meng** [comment]
Thanks for testing! I'll go update the libraries on my machines.
