### ISSUE TITLE
interpolation-lib.c : unique values not determined correctly

### ISSUE THREAD

**Issue by sq-meng** [McStasMcXtrace/McCode#1559]
## The problem

Currently the number of unique values found for each axis can be spuriously large due to a sort function not working correctly. This could be reproduced using the example provided in https://github.com/McStasMcXtrace/McCode/issues/1553: The z axis only has 5 unique values, but runtime output reports 605, which equals x * y * z unique numbers.
This is caused by the comparator function here: 
https://github.com/McStasMcXtrace/McCode/blob/abf0947103ebacaba79c855f7fe244590514b51b/common/lib/share/interpolation-lib.c#L258-L261
The return value got coerced into an int, which causes the sort function to only work for differences larger than a whole integer. In the case of lengths, one meter.
This is actually mostly asymptomatic except when trying to use `regular` interpolation, as the code would try to allocate a unrealistically huge array.

## Proposed changes

~~The return value should be scaled by `READ_TABLE_STEPTOL` before returning.~~
~~The current `READ_TABLE_STEPTOL` at 0.04 can be too large in some cases. For example, I'm using a magnetic field definition with 0.001 m step length. Step tolerance could be made an option for components where this could be a problem.~~
~~The return value should be scaled up before returning.~~
Probably should just use if...else as scaling up can cause elusive bugs.
Additionally:
https://github.com/McStasMcXtrace/McCode/blob/abf0947103ebacaba79c855f7fe244590514b51b/common/lib/share/interpolation-lib.c#L397-L402
This causes values to be considered different at very tight tolerances. This probably should be compared against a tolerance margin.
Edit: Doing this could cause results to be silently slightly wrong in certain cases, which is much worse than failing loudly when it could have chugged along. Will leave as is.

**Comment by sq-meng** [comment]
There are some other problems with `regular` interpolation:
https://github.com/McStasMcXtrace/McCode/blob/abf0947103ebacaba79c855f7fe244590514b51b/common/lib/share/interpolation-lib.c#L397-L402
The bin count is off by one as the 1st is not counted. 
https://github.com/McStasMcXtrace/McCode/blob/abf0947103ebacaba79c855f7fe244590514b51b/common/lib/share/interpolation-lib.c#L458-L462
I tried inspecting the floored values by ` printf("value=%lf, floored into %ld\n", (x - interpolator->min[axis])/interpolator->step[axis], indices[axis]);` and got:

> value=5.000000, floored into 4
value=10.000000, floored into 9
value=2.000000, floored into 2
value=5.000000, floored into 4
value=10.000000, floored into 9

Some values got floored into the previous bin probably due to precision. `round()` probably is more appropriate here.

**Comment by willend** [comment]
@sq-meng thanks a lot for digging deep in `interpolation-lib`, much appreciated!

You are very welcome to clone the repo and directly patch the code via a [PR](https://github.com/McStasMcXtrace/McCode/pulls) ? (e.g. via your own fork of https://github.com/McStasMcXtrace/McCode)

**Comment by sq-meng** [comment]
@willend Much obliged. I'll get to it and come back with a PR. Actually this will be my first ever PR so looking forward to it : D.
