### ISSUE TITLE
mxplot/mcplot: issue with Qt6

### ISSUE THREAD

**Issue by farhi** [McStasMcXtrace/McCode#1561]
Hi,
Our mcplot/mxplot default python GUI tools are currently based on Qt.

When launching the mcplot/mxplot on a recent (Debian 12 bookworm, june 2023)  system with both Qt5 and Qt6, we get an error related to **QtWidgets** (from **pyqtgraph**):
```
File "tools/Python/mxplot/pyqtgraph/../../mccodelib/pqtgfrontend.py", line 144, in create_plotwindow
    rect = QtWidgets.QApplication.desktop().screenGeometry()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'QApplication' has no attribute 'desktop'
```
This seems to be related to a change of behaviour/API from Qt5 -> Qt6 as handled by **pyqtgraph**.

For instance, we may solve locally the first issue with:
```
        # window size
        try:	# pyQt5
        	rect = QtWidgets.QApplication.desktop().screenGeometry()
        except:	# pyQt6
        	rect = QtWidgets.QApplication.primaryScreen().size()
```

but we then get a further error:
```
 File "tools/Python/mxplot/pyqtgraph/../../mccodelib/pqtgfrontend.py", line 182, in get_modifiers
    return QtCore.Qt.AltModifier
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Qt' has no attribute 'AltModifier'. Did you mean: 'Modifier'?
```
I have the feeling there will be a series of changes...

So there is a global issue with Qt 5,6,... evolutions wrt our python plot scripts based on **pyqtgraph**.

**Comment by willend** [comment]
Thanks @farhi, I am also convinced there will be a good deal of work to do in this respect… 

A first initial step to think of could be to explicitly require PyQt5 (in .deb recipes etc.)

**Comment by farhi** [comment]
The issue is not on our side, but rather on the `pyqtgraph` which has changed to PyQt6, whereas our code assumes Qt5...

**Comment by willend** [comment]
Yikes, disgusting!

In "condo-land" I guess we can go for pinning the pyqtgraph version to the last one still using PyQt5 - but perhaps not as easy on Debian?

**Comment by willend** [comment]
@farhi I guess a similar effort is needed for mc/xdisplay?

**Comment by farhi** [comment]
The mcdisplay/mxdisplay seems to globally work (zoom, keys, etc).
The particle ray-trace is however not displayed on my side.

**Comment by willend** [comment]
Ok, thanks @farhi, could be that this has to do with default 'ray color'? Does --inv_canvas help in any way?
(I will get myself a Debian 12 vm to experiment a little, but expect slow progress... I am in bed with the flu...)

**Comment by willend** [comment]
Rays look visible here with newly installed Debian 12 Arm
<img width="1760" alt="Screenshot 2024-02-07 at 11 12 57" src="https://github.com/McStasMcXtrace/McCode/assets/8593355/9092ed87-5dd6-4752-86a4-620c6157ba13">
<img width="1760" alt="Screenshot 2024-02-07 at 11 12 37" src="https://github.com/McStasMcXtrace/McCode/assets/8593355/5e69c869-cd5e-4f56-999f-74d5d30d63f2">

**Comment by farhi** [comment]
This is to keep track as "Ready for release"
