### ISSUE TITLE
Interpolation-lib issue on GPU with kdtree + kdtree vs. regular differences 

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#1563]
Something seems off between interp GPU/CPU regular/kdtree - needs further investigation. A first step is introducing both kdtree and regular runs on both CPU and GPU.

CPU:
<img width="1372" alt="Screenshot 2024-02-09 at 08 54 18" src="https://github.com/McStasMcXtrace/McCode/assets/8593355/2904cd03-50a5-440f-9eff-ffcdf10b410f">
<img width="1372" alt="Screenshot 2024-02-09 at 08 54 32" src="https://github.com/McStasMcXtrace/McCode/assets/8593355/f58be160-5f28-4fbe-836c-4d2074f881df">

GPU:
<img width="1372" alt="Screenshot 2024-02-09 at 08 53 54" src="https://github.com/McStasMcXtrace/McCode/assets/8593355/c3910eb6-453a-4880-8dcb-6edeb3d02992">
<img width="1372" alt="Screenshot 2024-02-09 at 08 54 07" src="https://github.com/McStasMcXtrace/McCode/assets/8593355/027900bc-08e6-4e45-803a-a1b927a0cec5">

- so irrespective of simulated case something is off... :-) 

```
* %Example: -n1e4 MF=flipfield.dat Detector: pol_6_I=1.0
* %Example: -n1e4 MF=constfield.dat Detector: polx_6_I=0.05
*
* %Parameters
* MF:              [string] Field definition file
* zdepth:               [m] Z-dimension of field
* interpol_method: [string] Choice of interpolation method "kdtree" (default on CPU) / "regular" (default on GPU)
```

**Comment by sq-meng** [comment]
I looked at the test, the test field has Z steps at `-0.5, -0.25, -0.025, 0.025, 0.25, 0.5` meters, which is not `constant_step`. The code should have rejected `regular` interpolation and used `kdtree` at this point, which it didn't. 
https://github.com/McStasMcXtrace/McCode/blob/be6ee82680373ea8f69bdade8913bc1b99d8be6d/common/lib/share/interpolation-lib.c#L411-L421
I think there are two problems:
1. Every table line gets checked against `interpolator->step[dim]` instead of every unique value. This should have caused the code to fall back to `kdtree` even on regular data, however:
2. Line 420, the fallback only triggers if `interpolator->method` is `NULL` or `0`, which isn't the case if 'regular' is provided.
If the data was forced to run on `regular` mode, the code would have assumed every z step to be 0.25 m wide, which causes the field to be no longer symmetric about z=0 and thus the wavelength dependent precession, instead of both halves cancelling out.

**Comment by sq-meng** [comment]
`constfield.dat` only has 12 data points, for `regular` interpolation there should be 3 x 3 x 3 = 27 points. Unpopulated grid cells remain at their as-allocated state and are invalid, causing invalid results.
The two methods agree after filling out the missing values as such:

```
constantfield.dat
# 12
-0.1 0.0 -0.5   0.0 0.0 -6.8e-05
0.1 0.0 -0.5    0.0 0.0 -6.8e-05
0.0 -0.1 -0.5   0.0 0.0 -6.8e-05
0.0 0.1 -0.5    0.0 0.0 -6.8e-05
-0.1 0.0 0.0   0.0 0.0 -6.8e-05
0.1 0.0 0.0    0.0 0.0 -6.8e-05
0.0 -0.1 0.0   0.0 0.0 -6.8e-05
0.0 0.1 0.0    0.0 0.0 -6.8e-05
-0.1 0.0 0.5   0.0 0.0 -6.8e-05
0.1 0.0 0.5    0.0 0.0 -6.8e-05
0.0 -0.1 0.5   0.0 0.0 -6.8e-05
0.0 0.1 0.5    0.0 0.0 -6.8e-05

0.0 0.0 -0.5 0.0 0.0 -6.8e-05
-0.1 -0.1 -0.5 0.0 0.0 -6.8e-05
-0.1 0.1 -0.5 0.0 0.0 -6.8e-05
0.1 -0.1 -0.5 0.0 0.0 -6.8e-05
0.1 0.1 -0.5 0.0 0.0 -6.8e-05

0.0 0.0 0.5 0.0 0.0 -6.8e-05
-0.1 -0.1 0.5 0.0 0.0 -6.8e-05
-0.1 0.1 0.5 0.0 0.0 -6.8e-05
0.1 -0.1 0.5 0.0 0.0 -6.8e-05
0.1 0.1 0.5 0.0 0.0 -6.8e-05
```

**Comment by willend** [comment]
It all makes sense and I believe you are absolutely right in your analysis, and a supplemental simulation dataset point in the same direction:

In http://tmp.mcstas.org/oneoff_2024-02-09 CPU and GPU seem to nicely agree. Tests run are now these, explicitly setting method to 'kdtree' and 'regular':
```
* %Example: -n1e4 interpol_method=kdtree MF=flipfield.dat Detector: pol_6_I=1.0
* %Example: -n1e4 interpol_method=kdtree MF=constfield.dat Detector: polx_6_I=0.05
* %Example: -n1e4 interpol_method=regular MF=flipfield.dat Detector: pol_6_I=1.0
* %Example: -n1e4 interpol_method=regular MF=constfield.dat Detector: polx_6_I=0.05
```
(Full dataset can be downloaded here http://tmp.mcstas.org/oneoff_2024-02-09.tgz ~ 2Mb for 4 tests on each "system")

As I remember, the "default" interpolator is in fact set to "something" on both CPU (kdtree) and GPU (regular) which goes against the logic of the above code that only switches if "NULL" was set.

**Comment by willend** [comment]
CPU run overview-plots, same order as in the instrument file:
<img width="1372" alt="Screenshot 2024-02-09 at 10 40 59" src="https://github.com/McStasMcXtrace/McCode/assets/8593355/6aa7fc08-7671-4dbd-8fbc-d4eb44804570">
<img width="1372" alt="Screenshot 2024-02-09 at 10 41 07" src="https://github.com/McStasMcXtrace/McCode/assets/8593355/555de6b6-c2bc-44e0-b410-6238f1524cb4">
<img width="1372" alt="Screenshot 2024-02-09 at 10 41 16" src="https://github.com/McStasMcXtrace/McCode/assets/8593355/48263f76-ffbd-4990-93ba-998c1b265b63">
<img width="1372" alt="Screenshot 2024-02-09 at 10 41 23" src="https://github.com/McStasMcXtrace/McCode/assets/8593355/015eff5b-6540-4931-a20b-b7b3fa9ff1aa">

GPU run overview-plots, same order as in the instrument file:
<img width="1372" alt="Screenshot 2024-02-09 at 10 41 37" src="https://github.com/McStasMcXtrace/McCode/assets/8593355/48c5d5d7-0ce9-437f-863a-3d6c86304ad1">
<img width="1372" alt="Screenshot 2024-02-09 at 10 41 47" src="https://github.com/McStasMcXtrace/McCode/assets/8593355/96e44b65-1fd6-480e-b22f-3c2afdea8430">
<img width="1372" alt="Screenshot 2024-02-09 at 10 41 55" src="https://github.com/McStasMcXtrace/McCode/assets/8593355/bf44b425-0086-4059-b099-24f42ff20fef">
<img width="1372" alt="Screenshot 2024-02-09 at 10 42 02" src="https://github.com/McStasMcXtrace/McCode/assets/8593355/7644cd60-fae8-43b6-a7ff-0f573afd62a4">

**Comment by willend** [comment]
I am now collecting old datasets from historical tests to check if the flipping actually ever worked on GPU...

**Comment by sq-meng** [comment]
@willend The new usage of `round()` could change results. In the constant field case, x and y data are given at -0.1, 0.0 and 0.1, and the polarization detector is from -0.05 to 0.05 in both x and y axes. If `round()` is used, all counted neutrons would fall inside the [-0.05, 0.05] bin, which is not populated in the original 12-line field file. But if the numbers are not rounded, half of the neutrons would fall into populated bins.

**Comment by willend** [comment]
@sq-meng something is still iffy somewhere:
Using kdtree does not yield the same results as regular in the case of the constant field - neither on CPU or GPU.

With the new file in place things look similar on GPU and CPU with "regular" interpolation - but with also with a different spin oscillation periodicity than earlier.

Regular interpolation, CPU:
![Screenshot 2024-02-09 at 12 51 04](https://github.com/McStasMcXtrace/McCode/assets/8593355/9a944bd5-8cc9-4643-9a74-d597166a7cbf)



Regular interpolation, GPU:
![Screenshot 2024-02-09 at 12 51 23](https://github.com/McStasMcXtrace/McCode/assets/8593355/8e25022b-620f-4fec-ae5f-371c8300dd77)



kdtree, CPU:
![Screenshot 2024-02-09 at 12 51 43](https://github.com/McStasMcXtrace/McCode/assets/8593355/410df2f3-6287-4686-bc34-36d338db26d7)



kdtree, GPU:
![Screenshot 2024-02-09 at 12 51 57](https://github.com/McStasMcXtrace/McCode/assets/8593355/e30e9f2d-9022-4f0e-b584-8ff3ac3cbdce)

**Comment by willend** [comment]
So in conclusion, at the moment:

* kdtree does not function on GPU - less of a problem 🟡 
* regular provides the same output on CPU and GPU, which is good! 🟢 
* kdtree and regular does not produce the same output on CPU - which is bad. 🔴 

Not judging what the "output should exactly be", given the simple constant-field datafile **it should at least give the same irrespective of interpolation method** - at least if we for now exclude the somewhat "experimental" GPU platform... 🚧 
(BUT: We should probably go back with pen+paper and look at a "hand-held" propagation of neutrons of the relevant wavelengths through the relevant field to decide from a physics point of view...)

I think this indicates that either the comparator-function needs a revert / another overhaul - or at least something further needs doing on the kdtree side, also on CPU... Agreed @sq-meng ?

**Comment by sq-meng** [comment]
@willend I agree - something is still iffy. And to make things worse, I was not able to get the longer period oscillations on my machine with either kdtree or regular😂. This definitely still needs more work.

**Comment by sq-meng** [comment]
@willend Could you check if your constant field file has 27 lines? My original reply containing the field file missed last 5 lines and I edited to add these soon after. But if you got the unedited version, the z=0.0 plane would have remained unpopulated, explaining the longer period.

**Comment by willend** [comment]
Right! I was missing the last block! I will rerun and see where this takes us on my side...

**Comment by willend** [comment]
And you were right this updates the situation to:
* kdtree does not function on GPU - less of a problem 🟡
* regular provides the same output on CPU and GPU, which is good! 🟢
* kdtree and regular does not produce the same output on CPU - which is good! 🟢 

CPU regular:
![Screenshot 2024-02-09 at 14 20 28](https://github.com/McStasMcXtrace/McCode/assets/8593355/663db463-b106-42d8-aa08-e7eb3981673e)

CPU kdtree:
![Screenshot 2024-02-09 at 14 20 40](https://github.com/McStasMcXtrace/McCode/assets/8593355/73f5ea1b-ba07-4c64-bc6a-35a6c63b423b)

GPU regular:
![Screenshot 2024-02-09 at 14 20 26](https://github.com/McStasMcXtrace/McCode/assets/8593355/81d94b5d-c68c-4fd6-ae72-58ee4a426e5c)

Flipping the "CPU default" to "NULL" should make it adaptive - and keeping the GPU side to "regular" unless explicitly chosen otherwise makes sense for now.

**Comment by willend** [comment]
One of the typical things that _could_ give this type of difference is if some variable initially in the `COMPONENT` scope (i.e. the Table object) gets modified during `TRACE` - thus leading to memory/data overlap between the GPU threads... But I didn't spot that up to now...

**Comment by willend** [comment]
Actual a VERY obvious candidate is the "R_SWAP"... macro.

I am afraid every neutron will either need its own copy of the interpolator - or a function with one or more `#pragma acc atomic` claused need writing... (Then the global interpolator gets updated via "locks" - only access by one thread at a time...)

**Comment by sq-meng** [comment]
Can't comment on that as I have zero knowledge on GPU programming... But I reckon the tons of branches in kd-tree won't perform on GPU anyway. Glad we at least have the result mismatch situation closed!

**Comment by willend** [comment]
I think my choice will in fact be to effectively disable "kdtree" on GPU. Exit with a warning if anything other than "default" / "regular" is chosen.

The other stuff will either become 
a) very memory demanding, i.e. an "interpolator" copy pr. GPU thread or 
b) Slow due to use of `#pragma acc atomic`s (i.e. mutex'es that lock memory on acces to allow one single thread at a time...)

**Comment by willend** [comment]
Heh, interestingly the size of flipfield.dat is not what it claims to be...
```
wc -l flipfield.dat 
151 flipfield.dat
(mcstas-3.x-dev/miniconda3) data $ head -2 flipfield.dat 
# 300
-0.1 -0.1 -0.5 0.0 0.0 1.0e-05
```

But I am not sure the # 300 header has any practical meaning in this particular case....

**Comment by willend** [comment]
Ha! The remaining issue with the flipfield.dat file is apparently one of "irregular" array dimensions! Apparently there is an underlying assumption not only that the bins along each of the dimensions are uniform length, but also that Nx == Ny == Nz:

The file is 5x5x6 naturally which (forcing `regular` - this occurs both on CPU and GPU) gives this output in the flip-case:
![Screenshot 2024-02-09 at 18 26 00](https://github.com/McStasMcXtrace/McCode/assets/8593355/5374cfe7-e143-47a1-93d0-3fc4708b06c7)

I have now written up a short Matlab (yes I know, better do it in Python ;-)) script to resample a field file:
[remesh.m.txt](https://github.com/McStasMcXtrace/McCode/files/14224679/remesh.m.txt)

Using this I was able to resample to e.g. 6x6x6:
[remeshed_6x6x6_flipfield.dat.txt](https://github.com/McStasMcXtrace/McCode/files/14224688/remeshed_6x6x6_flipfield.dat.txt)

Which now performs correctly in both the CPU and GPU cases with `regular` interpolation!

CPU:
![Screenshot 2024-02-09 at 18 41 27](https://github.com/McStasMcXtrace/McCode/assets/8593355/81dd8875-721c-4c82-bba0-4e0b9e3d45d6)


GPU:
![Screenshot 2024-02-09 at 18 39 22](https://github.com/McStasMcXtrace/McCode/assets/8593355/8e8e0bc8-243b-4e75-84ec-0e2e152daacc)

- which then both agree with `kdtree` on CPU:
![Screenshot 2024-02-09 at 18 41 11](https://github.com/McStasMcXtrace/McCode/assets/8593355/2cac309d-5cd3-462b-83da-f38e7f26a923)

I will simply replace the file with the remeshed one (and as I assumed, the header is not used for anything...)

I believe all that remains is either documenting these 'fragile' aspects or even exit fatal in the case the file properties are not "actually, fully regular" when requesting this method (meaning when forcing regular on CPU or "always" on GPU...

**Comment by willend** [comment]
@sq-meng thanks for the ping-pong! :) I believe we have arrived at a good solution, so marking "ready for release".
(This is my hack to help when I write a CHANGELOG on releasing.)

Please let me know if you find anything further that is off - and have a nice weekend!

**Comment by willend** [comment]
@farhi this stuff is likely also important in several places in McXtrace, do try it out when you feel like it. In essence:
* @sq-meng provided bug fixes that could lead to erroneous interpolations both in the `kdtree` and `regular` cases.
* We found that the field-datafiles in McStas were actually not functioning for the `regular` case, they have been edited.
* I have finally concluded that we will (very likely) never get `kdtree` to work on GPU and thus disabled it, so:
 1. On GPU the automatic `NULL` mode is mapped to `default` which means `regular` (`NULL` remains the CPU `default`)
 2. One can still explicitly select `kdtree` on GPU, but this will lead to an error.
 3. In `regular` mode (which may be selected explicitly or comes automatically on the GPU) there is a check for equal number of bins in the axis dimensions. Exit in error if this is not the case, with instructions to resample or use `kdtree`

**Comment by willend** [comment]
https://github.com/McStasMcXtrace/McCode/blob/main/mcstas-comps/examples/Tests_polarization/Test_Pol_Tabled/ now has a couple of remeshing-tools and the input files alongside the instrument.

**Comment by sq-meng** [comment]
@willend Looks mostly good to me! I don't believe that `regular` interpolation requires Nx == Ny == Nz though: Nsteps and step sizes can safely vary between axes, and the only requirement is that step size within each axis is consistent. The original `flipfield.dat` has z-axis steps at `-0.5, -0.25, -0.025, 0.025, 0.25, 0.5`, the middle 2 numbers break the 0.25 step size.
Attached is a 5x5x10 flip field which works fine here:
[5-5-10_flipfield.zip](https://github.com/McStasMcXtrace/McCode/files/14227356/5-5-10_flipfield.zip)

**Comment by sq-meng** [comment]
Sure. Silently producing slightly wrong results is the worst behavior for scientific software so a warning against unexpected data is necessary.

**Comment by willend** [comment]
Ended up with an actual exit(-1), which I think is for the better (here run with the original flipfield.dat):

```
(mcstas-3.x-dev/miniconda3) Test_Pol_Tabled-hack $ mcrun Test_Pol_Tabled.instr  MF=flipfield.dat interpol_method=regular -n1e4 
[Test_Pol_Tabled] Initialize
INFO: Set_pol(setpol): Setting polarization to (0.000000, 1.000000, 0.000000)
Opening input file 'flipfield.dat' (Table_Read_Offset)
interpolator_load: Axis 0: step=0.05, unique values=5, from file 'flipfield.dat'.
interpolator_load: Axis 1: step=0.05, unique values=5, from file 'flipfield.dat'.


!! interpolation-lib ERROR: !!
   You are running the 'regular' interpolation scheme with a file of
   non-consistent axis 'binning' along one or more axes.
   This combination is not possible.
   Please either resample the file to a regular grid or run with 'kdtree'
   (NB: kdtree is available on CPU only)

```
Using `default` reverts automatically to `kdtree` and lets the simulation run.

**Comment by willend** [comment]
BTW I also spotted yet another annoyance in the regular -> kdtree switch case logic:
https://github.com/McStasMcXtrace/McCode/blob/195d18aa0bed5b06958c5923a58149aafda44ee7/common/lib/share/interpolation-lib.c#L434-L462

An `if (this_step` was actually missing - so even on actual regular grids, the non-unique axis-positions from the "meshing" would trigger a switch to `kdtree` :-)
