### ISSUE TITLE
Mc/MxDisplay: fails "sometimes"

### ISSUE THREAD

**Issue by farhi** [McStasMcXtrace/McCode#1584]
Some Trace commands fail with e.g. error:

```python
Syntax error in input!
LexToken(POS,'POS',3,57)
Traceback (most recent call last):
  File "/usr/share/mcxtrace/3.4-20240304/tools/Python/mxdisplay/webgl/mxdisplay.py", line 198, in <module>
    main(**args)
  File "/usr/share/mcxtrace/3.4-20240304/tools/Python/mxdisplay/webgl/mxdisplay.py", line 166, in main
    instrument = reader.read_instrument()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/mcxtrace/3.4-20240304/tools/Python/mccodelib/mcdisplayutils.py", line 50, in read_instrument
    instrbuilder = InstrObjectConstructor(instrparser.parsetree)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/mcxtrace/3.4-20240304/tools/Python/mccodelib/instrparser.py", line 272, in __init__
    raise Exception('InstrObjectConstructor: parsetreeroot must be a Node of type "instrdeftree"')
Exception: InstrObjectConstructor: parsetreeroot must be a Node of type "instrdeftree"
```

This is for instance the case with `SOLEIL_MARS`, but not for `Test_Fluorescence`.

**Comment by willend** [comment]
On the McStas side I have seen that there are sometimes issues along these lines if a component instance name starts with a numeric (e.g. `1stmonitor`) is this potentially the case here @farhi ?

**Comment by willend** [comment]
Edited the instr on main, but maybe we should think of a better / more robust way of fixing this...

**Comment by willend** [comment]
Would it be too ugly if the cogen inserted a `printf("\n");` at the end of INTITALIZE? (I am guessing this would fix almost anything we can imagine people doing along thes lines?

**Comment by farhi** [comment]
Yes, this could be a good solution.

**Comment by willend** [comment]
... if documented properly :-D (Otherwise it will be the good old "WTF did anyone put a printf here... ;-) "

**Comment by farhi** [comment]
Perhaps a test could be made to plot every instrument as a PNG, and see if some fail.
