### ISSUE TITLE
We should check validity of included laz/lau files

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#1602]
Via Céline Durniak (ESS) I have learned that simulated output from the `C_diamond.lau` and `C_diamond.laz` differ... 

She cross-checked against a `CIF` file from the internet - it seems in this case our `.laz` can not be trusted.

1) We need a mechanism to check that we we ship is valid

2) We should advertise that people can use the "cif2hkl" mode of e.g. PowderN.

**Comment by tkittel** [comment]
Or, if you wish a somewhat smaller .lau file you can omit some of the smaller dspacing planes:
```
ncrystal_ncmat2hkl 'C_sg227_Diamond.ncmat;dcutoff=0.3Aa' --format lau -o C_sg227_diamond.lau
```

**Comment by tkittel** [comment]
If I fix the header a bit, I can load the existing lazy file with ncrystal and compare:
![image](https://github.com/user-attachments/assets/d1b54c46-3087-4eb3-9a06-1b3aed16814e)

Looks a bit suspicous!

And the .lau file does not even load with NCrystal:sure throw out:
```
NCrystal.exceptions.NCBadInput: HKL list is not consistent with spacegroup. The hkl=(2, 2, 2) value should have 8 equivalent planes (or possibly just one or half of these specified), but only found 2 of these in the list
```
For reference, NCrystal agrees with at least one CIF file :-)
![image](https://github.com/user-attachments/assets/372d07a8-a2a3-47b7-b05b-73e57c0f617a)
