### ISSUE TITLE
Testing: Comprehensive Component Unit testing

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#163]
**Reported by farhi on 16 Jan 2015 13:34 UTC**
Today, our Test instruments can be considered as Integration tests for McCode.
Developing a new McCode code generation from 'instr' files, I have seen that many components do not fully comply with good coding standards and can be very easily improved. Also, a few bugs have been found in this exercise.

It is needed to implement an as-simple-as-possible test instrument for each maintained, existing component, with a single test result for checking. 
1- A 'Test' directory holding these tests should be created, not to be distributed in installation packages, but checked daily. 
2- A tool to assign a test to a component should be written to point out components without test instrument (e.g. for each component, look for instruments that make use of the component, i.e. grep reports at least one use as a single word).

**Comment by farhi** [comment]
The `mctest` already brings a fairly complete test infrastructure. 

Keeping a clean `* %INSTRUMENT_SITE: Tests` with categories:
- Tests
- Tests_sources
- Tests_samples
- Tests_optics
- Tests_grammar
- Tests_polarization

is probably enough.
