### ISSUE TITLE
McXtrace:Mirror_parabolic component bug

### ISSUE THREAD

**Issue by minghuisvn** [McStasMcXtrace/McCode#1633]
A bug occurred when using a Mirror_parabolic component to focus the x-ray generated from Source_pt into parallel x-ray, the code is as follows:
```
DEFINE INSTRUMENT Test_mirror_parabolic()

TRACE

COMPONENT origin = Progress_bar()
AT (0, 0, 0) RELATIVE ABSOLUTE

COMPONENT source = Source_pt(focus_xw=1e-1, focus_yh=1e-1, focus_x0=0, focus_y0=0,
		dist=0.5, E0=8, dE=0, gauss=1)
AT (0, 0, 0) RELATIVE origin

COMPONENT m2 = Mirror_parabolic(
    b=2, a=2, xwidth=1, zdepth=1, yheight=1, R0=1)
AT(0,0, 2) RELATIVE origin
ROTATED (-90,0,0) RELATIVE origin

COMPONENT det_a = Arm()
AT(0,1,0) RELATIVE m2
ROTATED (-90,0,0) RELATIVE m2


COMPONENT det1 = PSD_monitor(xwidth=0.21, yheight=0.21, nx=201, ny=201,filename="det1", restore_xray=1)
AT(0,0,0.2) RELATIVE det_a

COMPONENT det2 = PSD_monitor(xwidth=0.21, yheight=0.21, nx=201, ny=201,filename="det2", restore_xray=1)
AT(0,0,0.2) RELATIVE PREVIOUS

FINALLY
%{
%}

END

```
The result is as:  
![image](https://github.com/McStasMcXtrace/McCode/assets/68952982/972d2b2e-ac4d-4b4d-84bf-8a51b3ed3846)
The result is certainly unreasonable.

**Comment by willend** [comment]
Hello @minghuisvn,

Thanks for reporting! Indeed it seems the component had multiple issues, most importantly:

* Wrong sign on calculations in surface-grid points in the DISPLAY section (visualisation only)
* Wrong inputs for the third dimension in the "parabolid" intersection routine

I attach an instrument modified from your version, mostly taste/flavour changes plus comments. It should be OK to change most back (but I would advise to keep the "yheight" of the mirror low - it is a "substrate thickness" - 1m is a bit much ;-) ).

I further attach the rectified component. (Remove the .txt suffixes once downloaded - only added to allow upload here)

There is now a more reasonable display:
<img width="1912" alt="Screenshot 2024-06-27 at 19 52 34" src="https://github.com/McStasMcXtrace/McCode/assets/8593355/9545f399-9a1e-4598-9af0-09e5c75111d3">

And the default simulation output also looks good:
<img width="1372" alt="Screenshot 2024-06-27 at 19 53 00" src="https://github.com/McStasMcXtrace/McCode/assets/8593355/5d06fcc2-59ee-4f64-b779-a1635d8ed64c">

[Test_mirror_parabolic.instr.txt](https://github.com/user-attachments/files/16019156/Test_mirror_parabolic.instr.txt)
[Mirror_parabolic.comp.txt](https://github.com/user-attachments/files/16019157/Mirror_parabolic.comp.txt)
