### ISSUE TITLE
mcresplot front-end in McStas 3.4

### ISSUE THREAD

**Issue by LukasEijk** [McStasMcXtrace/McCode#1648]
Hey there,

I tried using the mcreplot frontend with a file created from the TOFRes_Monitor in combinaton with TOFRes_Sample (new fixed versions from GitHub) in McStas Version 3.4
I tried it both under Windows and WSL and it didnt work on both platforms:

1. Windows:
"python: can't open file 'C:\\mcstas-3.4\\lib\\tools\\Python\\mcresplot\\pyqtgraph\\mcresplot.py': [Errno 2] No such file or directory"

2. WSL: 
"mcresplot: command not found"

Is this a known Problem or am I maybe using it wrong (i used "mcresplot filename" in the folder where the file is)

Best regards 
Augustin

**Comment by willend** [comment]
Hi @LukasEijk,

On vacation at this instance, but sending some quick initial feedback:

On windows, try installing the “mcresplot package” found here https://download.mcstas.org/mcstas-3.4/Windows/single-packages/

Similarly under Ubuntu/WSL try `sudo apt-get install mcstas-tools-python-mcresplot-3.4`

Hope this helps? Will get back to you again some time next week.

**Comment by LukasEijk** [comment]
Hi @willend, 
thanks for your quick reply, even though you're on holiday. 
Worked without any problems! 
Thanks again
