### ISSUE TITLE
Monitor_nD and user-defined variable

### ISSUE THREAD

**Issue by nicriz** [McStasMcXtrace/McCode#1651]
Hi,

I encountered a weird behavior with Monitor_nD when trying to track the number of reflections in Guide_gravity. I read the issue #1433 and used `USERVAR` to define my variable:
```
USERVARS
%{
	int n_reflections;
%}
```

then, according to the manual, I appended to my Arm:
```
EXTEND
%{
	n_reflections = 0;
%}
```

finally, to each section of the guide :
```
EXTEND
%{
	n_reflections += GVars.N_reflection[0]; //Here I also tried SCATTERED - 2
        printf("%d\n", n_reflections);
%}
```
But my Monitor_nD with `user1=n_reflections`:
```
COMPONENT monitor_nd = Monitor_nD(
    user1="n_reflections", 
    xwidth=0.06,
    yheight=0.12,
    options="user1, bins=10 limits=[-2 8]", 
    username1="N reflections",
    filename="reflections.dat")
AT (0, 0, 1.01) RELATIVE PREVIOUS
```
doesn't seem to store correctly the variable since it returns always n_reflections 0, which is incorrect according to the print. 

Is this is also related to #1433 or am I missing something?

McStas Version: 3.4.55 (clean from conda channel)
Linux version 4.18.0-553.5.1.el8_10.x86_64 
test file: [test_reflections.txt](https://github.com/user-attachments/files/16411059/test_reflections.txt)

**Comment by nicriz** [comment]
Ciao @willend, 

Yes, the behavior was the same. Yesterday evening I tried, with all due adjustments, with McStas 2.7.2 and it works as intended.

**Comment by willend** [comment]
@nicriz as far as I can see the problem is one of "scoping", things like number of bounces ought to be "local" TRACE variables in McStas 3....

While the component in truth deserves a "full" rewrite, I have hacked it slightly here: There is now a "Global" GVarsGlobal which is used to initialise the "local" GVars variable which as far as I can see can now be used in a meaningful way from EXTEND. (I.e., try using your unmodified instrument together with the attached .comp)

Hope this helps? :-) Please report back and I will then include the modified comp in the next release.
 
[Guide_gravity.comp.txt](https://github.com/user-attachments/files/16438423/Guide_gravity.comp.txt)

**Comment by willend** [comment]
Comp uploaded to main, meaning that it should make it to next conda "prerelease" in its current form.

**Comment by nicriz** [comment]
It seems it still doesn't work for me. I renamed the component you sent as Guide_gravity_fixed just to be sure I was loading the correct component. Then I run
`mcrun -c -I /mnt/nfs/home/rizzi_n/NNBAR_old -n 1000 test_reflections.instr `

the printf correctly shows 0,1 and 2 but Monitor_nD puts everything in bin 0.

[test_reflections.txt](https://github.com/user-attachments/files/16439311/test_reflections.txt)
[reflections.txt](https://github.com/user-attachments/files/16439337/reflections.txt)

**Comment by nicriz** [comment]
I didn't mean to close the issue, I wanted to leave it open

**Comment by willend** [comment]
Gotcha! 

The (clearly undocumented!!) issue seems to be that for Monitor_nD to measure a USERVAR, it seemingly has to be of type double in McStas 3...

Try running the attached instrument file - it seems to work even with the unmodified Guide_gravity.

[test_reflections.instr.txt](https://github.com/user-attachments/files/16440051/test_reflections.instr.txt)

**Comment by willend** [comment]
(Some sort of warning or code-gymnastics will be necessary to solve this in a more general way, clearly...)

**Comment by nicriz** [comment]
Ah ah! It works.

Indeed, in the manual n_bounces is defined as a double, but a warning to highlight the importance of that would be helpful. Maybe updating the component Readme.

Thanks Peter!

**Comment by willend** [comment]
You're very welcome, and thanks for pointing out the problem!
