### ISSUE TITLE
Code generator: Uniformize across McStas/McXtrace

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#1662]
As per discussion in https://github.com/McStasMcXtrace/McCode/pull/1661 we should reengineer the code generator code to remain identical between McStas and McXtrace.

More specifically we should try avoiding .in templating and put the differences e.g. dedicated include files.

@farhi @g5t inputs welcome

**Comment by farhi** [comment]
It seems the failing tests are caused by a network failure...
- https://github.com/McStasMcXtrace/McCode/pull/1664

**Comment by willend** [comment]
All test finalised OK via reruns - merged.
