### ISSUE TITLE
MCPL_output.comp: verbose = 1 does not work as described

### ISSUE THREAD

**Issue by jkrueger1** [McStasMcXtrace/McCode#1676]
Setting the verbose parameter to 1 does not work as described. It doesn't reload the written output and therefor gives not statistics. :( It would be nice to have the statistics about the number of the written events/neutrons.

**Comment by willend** [comment]
@jkrueger1 thank you for reporting, I will try to look into this and correct the behaviour before McStas 3.5 release... 
(Which really **should** be here in august...)

**Comment by willend** [comment]
@jkrueger1 the component has been updated with a simple `mcpltool filename` system call in `FINALLY`
