### ISSUE TITLE
McStas-components,Polarisation: Increasing intensity when propagating through Pol_simpleBfield

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#168]
**Reported by erkn on 3 Mar 2015 06:07 UTC**
Andre Kusmin (Delft) reports:
Hi everyone,

I noticed that in a simple polarized neutron instrument
made of source, polarizer, precession field, analyzer
the resulting signal, as expected, oscillates as cos(const*lambda*B*L)
but at B=0, the intensity of the signal is less than 100% (see attached PNG, plotted intensity against two different lengths of magnetic field regions).

It turns out that intensity at B*L=0 is correct.

For 100 % polarized beam and zero precession field  the intensity after the analyzer is 4.2e-14
(with TestLarmor.out)
The same intensity I get with ./TestLarmorOnlysource.out
but when I set non zero field in precession region I get even larger intensity, which is impossible.

Test can be done with two  attached  instr files and commands:

./TestLarmor.out By1=0  -n 1e5  DLambda=0.000001
./TestLarmor.out By1=0.000001  -n 1e5   DLambda=0.000001
./TestLarmorOnlysource.out   -n 1e5   DLambda=0.000001

could anyone please check if this is reproducible?
perhaps I miss something.

I have McStas pre2.2 (compiled from SVN) on linux multilib 64 bit (Slackware)

best regards
Andre

**Comment by willend** [comment]
@ebknudsen would you look? :-)

**Comment by willend** [comment]
@ebknudsen did you have a look?

**Comment by ebknudsen** [comment]
This issue was fixed by this [commit](https://github.com/McStasMcXtrace/McCode/commit/d179e2215eb3229318d1ce80c4bd0bae43246653)
