### ISSUE TITLE
MCPL_input `E_smear` should be `v_smear`

### ISSUE THREAD

**Issue by g5t** [McStasMcXtrace/McCode#1693]
Due to the way particle property randomization is handled in `MCPL_input.comp`, the parameter `E_smear` with documentation 
> When repeating events, make a Gaussian MC choice within E_smear*E around particle energy E
is actually a relative random change to the particle's _velocity_ magnitude.

In the following, the random factor needs to be applied to `nrm` *before* the square root in order to be a factor on the particle energy.
(Also, the variable `tmp` assigned on line 342 is not used)
https://github.com/McStasMcXtrace/McCode/blob/974554e463cabb01d5c5aabaf7149cbdb3c56558/mcstas-comps/misc/MCPL_input.comp#L339-L346

## Possible solutions
Either change the documentation to match behavior, or change the behavior to match the documentation.

## Preferred solution
Update the documentation to avoid changing behavior (and results) relative to older versions of McStas.

**Comment by willend** [comment]
Thanks for noticing that little annoyance, will do something about it today.

**Comment by willend** [comment]
Good point, I will add that in CHANGES_McStas.
