### ISSUE TITLE
Tools: mcplot return code

### ISSUE THREAD

**Issue by markusappel** [McStasMcXtrace/McCode#171]
mcplot from the 2.2a release returns `2` instead of `0` after successfully saved plot:

```
$ mcplot -gif test ; echo "mcplot return code: $?"
Opening test/mccode.sim
Wrote GIF file 'test/mccode.sim.gif' (gif)
mcplot return code: 2
```

**Comment by willend** [comment]
... connected to general discussion on what exit value to use in case of succes / failure in the global case...

**Comment by willend** [comment]
We are about to make our new python set of tools default - taking the liberty to mark this one as wontfix... :-) Otherwise we are always happy to receive a pull request @markusappel
