### ISSUE TITLE
Installing McStas 2.x meta packages

### ISSUE THREAD

**Issue by rtang-sidney** [McStasMcXtrace/McCode#1711]
When attempting to install a meta package (whether it's for Python, Perl, or both), the command sudo apt-get install mcstas-suite-python no longer works for version 2.x. Both the commands with and without the -ng suffix result in the installation of the latest 3.x version instead.

I encountered the same issue when trying to manually download and install the .deb file - it still defaults to version 3.x. Is there a way to resolve this, so that it's possible to install all the necessary 2.x packages in one step without having to install them individually?

Cheers!

**Comment by willend** [comment]
Hi @rtang-sidney 

Thanks for reporting, albeit this is sort-of-intentional. We really want people to move away from the now deprecated McStas 2.x and McXtrace 1.x -> version 3.5.1 of both. :-) And in this respect, both of the -suite and -suite-ng packages point to the new version.

That being said, I did define a set of new meta-packages with naming:

```
mcstas-tools-python-legacy
mcstas-tools-perl-legacy
mcxtrace-tools-python-legacy
mcxtrace-tools-perl-legacy
```
... intended for people that insist. I just didn't document this anywhere to not encourage running the old code. ;-)

**Comment by rtang-sidney** [comment]
Hi Peter,

Thanks for the information! I completely understand your point about encouraging people to move away from older versions. That's our goal in the long term as well. However, we have some legacy code written for the instrument quite some time ago, and we'd like to run some tests with it before updating to the 3.x version. Since we didn't write the original code, the transition might take some time.

I imagine this is why some people prefer to stick with the older version, at least parallel to the new version, especially when the users aren't very familiar with McStas. But hopefully, things will only improve from here! :D

**Comment by willend** [comment]
@rtang-sidney understood completely :-) 

For the transition I hope the wiki may be of help https://github.com/McStasMcXtrace/McCode/wiki#migrating-from-mcstas-2x-to-3x-and-mcxtrace-1x-to-3x

And as always, if you find issues you can not solve yourselves you are VERY welcome to 
* Write an issue here
* Send a question to mcstas-users@mcstas.org
* Start a discussion at https://github.com/McStasMcXtrace/McCode/discussions
