### ISSUE TITLE
McGui stuck in "getting instrument parameters"

### ISSUE THREAD

**Issue by rtang-sidney** [McStasMcXtrace/McCode#1717]
Hello,

I'm encountering an issue when trying to run an instrument in McGui. It gets stuck at the "Getting instrument parameters" stage. However, the GUI doesn't fully freeze - I'm still able to access the menu and close the window normally, and I can also open the editor through the GUI.

I'm using McStas 3.5.1 on Ubuntu 24.04.1 LTS, but I don't believe the version is the problem, as McGui 3.5.1 works fine on another PC running the same Ubuntu version.

Has anyone else experienced this issue or have any insights into what might be causing it?

Many thanks,

Ran

**Comment by willend** [comment]
@rtang-sidney could you help with more specifics:

* Did you install using the "mccode.org" Debian packages or via conda?
* Does this happen with "any instrument"? 
* Is any output given in the console? (Both the mcgui console and anything potentially indicated in a gnome-terminal etc. from which you started mcgui?)

**Comment by rtang-sidney** [comment]
Dear Peter,

Thank you for your reply. Here’s some additional information regarding your questions:

- I installed McStas using Debian packages via the "repo way".
- The issue does not occur when I run instruments from templates. Even with files generated from the previous version (I believe it was 3.4), I can still run them without any problem. However, the instruments I wrote in version 3.4 cannot be run using mcgui, even though they worked in 3.4.
- All instruments can still be run using mcrun in the terminal or with Python.
- I’ve managed to narrow down the issue to the pop-up window for instrument parameters. The window appears when running a template instrument but does not pop up for my self-written instruments. This is confusing, as I wrote the instruments using version 3.x, and they worked fine at that time.

Many thanks!

**Comment by willend** [comment]
Weird, but interesting. Maybe send me an example of one that does not work?

**Comment by rtang-sidney** [comment]
Hi Peter, the recompiling has solved the issue.. Thanks!

**Comment by willend** [comment]
Excellent, good to hear!
