### ISSUE TITLE
Code generation: SPLIT breaks GROUP

### ISSUE THREAD

**Issue by markusappel** [McStasMcXtrace/McCode#172]
A `GROUP` seems not to behave like expected when it is behind a `SPLIT`ted component. Consider this instrument file:
```
DEFINE INSTRUMENT test()

DECLARE
%{
   int scattered_on_1;
%}

TRACE

COMPONENT source = Source_div(xwidth=0.01,yheight=0.01,focus_aw=0.1,focus_ah=0.1,lambda0=6.27,dlambda=1,flux=1e10)
AT (0,0,0) ABSOLUTE

SPLIT 3 COMPONENT MCBooster = Arm()
AT (0,0,1) ABSOLUTE

COMPONENT graphite1 = Monochromator_flat()
AT (0,0,2) ABSOLUTE
ROTATED (0,69,0) ABSOLUTE
EXTEND
%{
   scattered_on_1 = SCATTERED;
%}

COMPONENT graphite2 = Monochromator_flat()
WHEN (!scattered_on_1)
AT (0,0,2.1) ABSOLUTE
ROTATED (0,70,0) ABSOLUTE

COMPONENT monitor = Monitor_nD(options="banana, theta limits=[130,150], bins=120, y bins=30", radius=1, yheight=0.1)
AT (0,0,2) ABSOLUTE

END
```
The components `graphite1` and `graphite2` should behave as if they were in a group, like this:
```
COMPONENT graphite1 = Monochromator_flat()
AT (0,0,2) ABSOLUTE
ROTATED (0,69,0) ABSOLUTE
GROUP deflectors

COMPONENT graphite2 = Monochromator_flat()
AT (0,0,2.1) ABSOLUTE
ROTATED (0,70,0) ABSOLUTE
GROUP deflectors
```
But these variants give different results (seen immediately in monitor intensity). Without the `SPLIT`ting, both variants give the same result.

**Comment by ebknudsen** [comment]
Dear Marcus
I can confirm this behaviour - I can reproduce the bug using e.g. the attached instrument file. We will investigate further.
[test_instr.txt](https://github.com/McStasMcXtrace/McCode/files/79594/test_instr.txt)

**Comment by farhi** [comment]
All this is true. I wrote the current 'advanced' grammar with GROUP, WHEN, JUMP more than 10 years ago, as a kind of hack to the existing grammar. Mixing was not the original intention.

The only way to solve it definitively and provide even more possibilities, is to switch to the new 'functional' OO-like code generation aka cogen-3. 

The current cogen-3 branch compiles and runs most of the instruments accurately, but we can proceed only once McStas 2.3 is out and we decide to jump forward. Then a few more adjustments will be needed. Among them is the Vitess Fermi chopper: a tricky one to adjust as it has plenty of hidden global variables.

**Comment by ebknudsen** [comment]
Hi E,
I have identified the exact cause of this thing - the group scattered flag is initialized at the top of mcraytrace(), which is obviously shortcut by the split. It should be moved
to be prepended to the trace of the first component in the group, or indeed be reset after the last component in the group. Perhaps the 2nd option is better as the last element
has to be treated differently anyway.
I'll investigate further if I can fix this in the current 2.0 tree - I might even call and ask for a bit of help if you don't mind :-) (if I get stuck that is).

But sure - these things (I expect) will become simpler to deal with come cogen 3.

Btw - did you have plans to come up to the cold north soon? Peter mentioned something to that effect.

cheers
e


On 06/01/16 10:37, Emmanuel FARHI wrote:
> All this is true. I wrote the current 'advanced' grammar with GROUP,
> WHEN, JUMP more than 10 years ago, as a kind of hack to the existing
> grammar. Mixing was not the original intention.
>
> The only way to solve it definitively and provide even more
> possibilities, is to switch to the new 'functional' OO-like code
> generation aka cogen-3.
>
> The current cogen-3 branch compiles and runs most of the instruments
> accurately, but we can proceed only once McStas 2.3 is out and we decide
> to jump forward. Then a few more adjustments will be needed. Among them
> is the Vitess Fermi chopper: a tricky one to adjust as it has plenty of
> hidden global variables.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/McStasMcXtrace/McCode/issues/172#issuecomment-169277243>.
>

-- 
Erik Bergbäck Knudsen, Research Engineer | DTU | morituri
NEXMAP, DTU Fysik, DK-2800 Kgs. Lyngby, Denmark |<>-<>| te
phone: (+45) 2132 6655 |<>-<>| salutant

**Comment by ebknudsen** [comment]
Hi again E,
I believe I've fixed it. I'll run a few more tests though before 
commiting. In summary - you don't have to do anything. Nice eh?
/e

On 06/01/16 10:37, Emmanuel FARHI wrote:
> All this is true. I wrote the current 'advanced' grammar with GROUP,
> WHEN, JUMP more than 10 years ago, as a kind of hack to the existing
> grammar. Mixing was not the original intention.
>
> The only way to solve it definitively and provide even more
> possibilities, is to switch to the new 'functional' OO-like code
> generation aka cogen-3.
>
> The current cogen-3 branch compiles and runs most of the instruments
> accurately, but we can proceed only once McStas 2.3 is out and we decide
> to jump forward. Then a few more adjustments will be needed. Among them
> is the Vitess Fermi chopper: a tricky one to adjust as it has plenty of
> hidden global variables.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/McStasMcXtrace/McCode/issues/172#issuecomment-169277243>.
>

-- 
Erik Bergbäck Knudsen, Research Engineer         | DTU | morituri
NEXMAP, DTU Fysik, DK-2800 Kgs. Lyngby, Denmark  |<>-<>|    te
phone: (+45) 2132 6655                           |<>-<>| salutant

**Comment by ebknudsen** [comment]
patch commited, closing
