### ISSUE TITLE
OS X (Mavericks) build fails

### ISSUE THREAD

**Issue by andyfaff** [McStasMcXtrace/McCode#173]
I have OS X Mavericks 10.9.5 installed. I tried to build McStas using:

    ./build_macos_Maverics_mcstas 2.0

However, the build fails. The build log is at https://gist.github.com/andyfaff/22eb2cff2263e83453ee

**Comment by willend** [comment]
Hi Andrew,

Thanks for reporting this! It seems the CMakelists.txt for Python/mcgui was not updated to reflect a code name change.

Hope things work better for you using my latest commit:

https://github.com/McStasMcXtrace/McCode/commit/28bd980c417112b863fd58580c5a8cd0e3a994a1

Best,

Peter

**Comment by willend** [comment]
Hi Andrew,

Thanks for reporting this! It seems the CMakelists.txt for Python/mcgui was not updated to reflect a code name change.

Hope things work better for you using my latest commit:

https://github.com/McStasMcXtrace/McCode/commit/28bd980c417112b863fd58580c5a8cd0e3a994a1

Best,

Peter


On 17 Aug 2015, at 08:45 , Andrew Nelson <notifications@github.com<mailto:notifications@github.com>> wrote:


I have OS X Mavericks 10.9.5 installed. I tried to build McStas using:

./build_macos_Maverics_mcstas 2.0


However, the build fails. The build log is at https://gist.github.com/andyfaff/22eb2cff2263e83453ee

**Comment by willend** [comment]
Did you re-test @andyfaff - and how do things look?

Please also note that if you want to generate a 'full' stand-alone installation package, you need to install PackageMaker (was previously part of Xcode) and run the build script like this:

./build_macos_Maverics_mcstas 2.0 meta

- followed by a number of clicks in the PackageMaker gui (build & and run, answer 'no' to using dialogues from each sub-package)

**Comment by andyfaff** [comment]
Sorry, I've been distracted by a lot of other stuff.

**Comment by willend** [comment]
No worries, let us know when you have time :-)

**Comment by ebknudsen** [comment]
We've successfully built for maverics for some time now - closing
