### ISSUE TITLE
PowderN (McStas) test issues

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#1741]
The latest (d_phi/tth_sign) changes (https://github.com/McStasMcXtrace/McCode/commit/bc505762c2ee0beda817c74f03eb4b521ec28745) breaks expected results in a number of tests, see

https://new-nightly.mcstas.org/2024-10-12_output.html

**Comment by willend** [comment]
(@farhi I will look / fix once I am back from vacation, but I believe what was there prior to f9c844207a140d2e12aed13922c216b4a6a94c36 and bc505762c2ee0beda817c74f03eb4b521ec28745 "worked" numerically - but that `tth_sign` **needed** to be combined with `d_phi` or `d_omega`. Somehow the normalisation got lost in translation since. :-) )

**Comment by farhi** [comment]
OK, got it. My tests using the `tth_sign` have shown no effects, but I think I did not set `d_phi` in conjunction. A factor 2 in flux has indeed appeared compared wrt previous `PowderN` version.
