### ISSUE TITLE
mcdisplay-webgl and mcdisplay-pyqtgraph commands not found

### ISSUE THREAD

**Issue by Momsnoodle** [McStasMcXtrace/McCode#1763]
Recently,  I have started using the app for some X-ray simulations. The plots are working fine, However, when I wanted to see some 2D or 3D simulations, here comes up the error message.

<img width="887" alt="Screenshot 2024-11-19 at 10 49 48" src="https://github.com/user-attachments/assets/5d879d51-eeb3-46dd-bf62-8e61509526af">
And then I tried the Mcstas and it seemed like it was working. How can I fix this problem?
The version I am using is the Mcxtrace 3.5.1 and the computer is a MacBook Pro with M3 and the system version is macOS Sequoia 15.1.

**Comment by willend** [comment]
Hi @Momsnoodle

Looks weird that you seem to get "McStas" oriented display utils from "McXtrace"? Is the screenshot from one or the other?

Just to be sure something is not fundamentally wrong with the provided installer, I am now (re-)installing my local McXtrace 3.5.1 via the bundle available at http://downloads.mcxtrace.org/mcxtrace-3.5.1/macOS/ - did you get your McXtrace this way?

As a rule, the McXtrace tools differ from their McStas counterpart by an `mx` instead of `mc`:

- mcgui in McStas is mxgui in McXtrace
- mcrun in McStas is mxrun in McXtrace
- mcplot in McStas is mxplot in McXtrace
- mcplot in McStas is mxplot in McXtrace
- mcdisplay in McStas is mxdisplay in McXtrace etc.

Is it correctly understood that you took

**Comment by Momsnoodle** [comment]
> Hi @Momsnoodle
> 
> Looks weird that you seem to get "McStas" oriented display utils from "McXtrace"? Is the screenshot from one or the other?
> 
> Just to be sure something is not fundamentally wrong with the provided installer, I am now (re-)installing my local McXtrace 3.5.1 via the bundle available at http://downloads.mcxtrace.org/mcxtrace-3.5.1/macOS/ - did you get your McXtrace this way?
> 
> As a rule, the McXtrace tools differ from their McStas counterpart by an `mx` instead of `mc`:
> 
> * `mcgui` in McStas is `mxgui` in McXtrace
> * `mcrun` in McStas is `mxrun` in McXtrace
> * `mcplot` in McStas is `mxplot` in McXtrace
> * `mcdisplay` in McStas is `mxdisplay` in McXtrace etc.

![Screenshot 2024-11-19 145239](https://github.com/user-attachments/assets/51187e55-7363-418e-9cd3-7761fb382d5b)
And I've also tried with Windows and it shows the same thing I guess

**Comment by Momsnoodle** [comment]
> Hi @Momsnoodle
> 
> Looks weird that you seem to get "McStas" oriented display utils from "McXtrace"? Is the screenshot from one or the other?
> 
> Just to be sure something is not fundamentally wrong with the provided installer, I am now (re-)installing my local McXtrace 3.5.1 via the bundle available at http://downloads.mcxtrace.org/mcxtrace-3.5.1/macOS/ - did you get your McXtrace this way?
> 
> As a rule, the McXtrace tools differ from their McStas counterpart by an `mx` instead of `mc`:
> 
> * `mcgui` in McStas is `mxgui` in McXtrace
> * `mcrun` in McStas is `mxrun` in McXtrace
> * `mcplot` in McStas is `mxplot` in McXtrace
> * `mcdisplay` in McStas is `mxdisplay` in McXtrace etc.

![Screenshot 2024-11-19 145239](https://github.com/user-attachments/assets/56384a42-f173-4abb-9b9c-5f247718380a)
And I've just tried with Windows and it shows the same error

**Comment by willend** [comment]
Ah now I partly understand! The ` --default` in the command gave away that you are using `Simulation->Display-3D`.

It seems that when using the `Simulation->` entires the commands are in fact hard-coded to mcdisplay- ... 
(Yes, a proper bug and would naturally affect the McXtrace installations only...)

Could you instead try pressing `Run` and on the subsequent dialogue switch from `Simulation` to `Trace` to see if this gives you any more mileage?

**Comment by Momsnoodle** [comment]
> Ah now I partly understand! The ` --default` in the command gave away that you are using `Simulation->Display-3D`.
> 
> It seems that when using the `Simulation->` entires the commands are in fact hard-coded to mcdisplay- ... (Yes, a proper bug and would naturally affect the McXtrace installations only...)
> 
> Could you instead try pressing `Run` and on the subsequent dialogue switch from `Simulation` to `Trace` to see if this gives you any more mileage?

<img width="887" alt="Screenshot 2024-11-19 at 15 29 32" src="https://github.com/user-attachments/assets/9c400cd1-ef55-4a5f-a805-01770bf01e1a">
<img width="524" alt="Screenshot 2024-11-19 at 15 30 39" src="https://github.com/user-attachments/assets/b93ecf02-11ea-4a7a-823e-e998664e4ca7">
There is still some problem.

**Comment by willend** [comment]
@Momsnoodle I believe I have a fix:

You may replace the `mxgui.py` (residing in your McXtrace installations) by the one found here: 
https://raw.githubusercontent.com/willend/McCode/refs/heads/fix-issue-1763/tools/Python/mcgui/mcgui.py - remember to rename correctly ;-) 

Let me know if this fixes the issues you experienced.

**Comment by Momsnoodle** [comment]
> @Momsnoodle I believe I have a fix:
> 
> You may replace the `mxgui.py` (residing in your McXtrace installations) by the one found here: https://raw.githubusercontent.com/willend/McCode/refs/heads/fix-issue-1763/tools/Python/mcgui/mcgui.py - "save as" and remember to name correctly ;-)
> 
> Let me know if this fixes the issues you experienced.

It works! Thank you so much!
By the way, it took me a while to find where the file is. In case the others have the same problem, here is the directory: `/Applications/McXtrace-3.5.1.app/Contents/Resources/miniconda3/share/mcxtrace/tools/Python/mxgui`

**Comment by willend** [comment]
Good to hear. :-) And yes it is a bit buried... ;-)

Sorry, I should have given you the path or a hint to use an "environment terminal" hack: `find $CONDA_PREFIX -name mxgui.py` 

On Windows you can find the file in your `c:\mcxtrace-3.5.1\lib\tools\Python\mxgui` folder (McStas/McXtrace wille eventually also become fully "built into" conda also on Windows).
