### ISSUE TITLE
Documentation and code generation: COPY does not copy EXTEND

### ISSUE THREAD

**Issue by markusappel** [McStasMcXtrace/McCode#180]
From the documentation of the COPY statement, it seems that any EXTEND block applies for the copied instances as well:

> Together with JUMPs (see below), there is a way to copy a component instance, duplicating
> parameter set, as well as any EXTEND, GROUP, JUMP and WHEN keyword.

and later:

> In case EXTEND, GROUP, JUMP and WHEN keywords are defined for the copied instance, these
> will override the settings from the copied instance.

However, this seems not to be the case (suspected from the behavior of an instrument file and confirmed in the generated C-code). Using McStas release 2.2a.

**Comment by farhi** [comment]
Yes this is true. It's been discussed, and I think we finally converged to NOT copy these extended grammar keywords EXTEND GROUP JUMP and WHEN.
The question is: does a copied component instance with such keywords will not lead to unexpected behaviours because these will be hidden, or do we explicitely, as today, request to manually write these sections  to avoid errors.

**Comment by markusappel** [comment]
However, I can confirm that the WHEN condition is silently applied to the copies as well.
Personally, I think either option is ok, but it should be the same for all the "extended grammar" keywords and explicitly documented :)

**Comment by willend** [comment]
Check the code generation in both instrument.y from 2.3 and 3.0

**Comment by willend** [comment]
@farhi I have fixed the docs, but still feel a little weary about instrument.y... My feeling would be that the lines around 267 in that file should maybe be taken out, that is those below...

But it would be great if you could maybe have a quick look...? :-)

<pre>
    | "TRACE" "COPY" TOK_ID "EXTEND" codeblock
      {
        struct comp_def *def;
        struct code_block *cb;
        cb = codeblock_new();
        def = read_component($3);
        if (def) {
          cb->filename        = def->trace_code->filename;
          cb->quoted_filename = def->trace_code->quoted_filename;
          cb->linenum         = def->trace_code->linenum;
          list_cat(cb->lines, def->trace_code->lines);
          list_cat(cb->lines, $5->lines);  
        }
        $$ = cb;
      }
</pre>

**Comment by willend** [comment]
I have decided that the current edits to the docs will do for 2.3, it is anyhow a quite only in combining multiple keywords that these types of issues arise...

Taking off 2.3 Label.
