### ISSUE TITLE
Runtime: randvec_target_rect_angular does not give uniform distribution over area

### ISSUE THREAD

**Issue by markusappel** [McStasMcXtrace/McCode#181]
In `randvec_target_rect_angular` a random vector is drawn from a uniform distribution in spherical coordinates theta and phi:
```c
    /* Now choose point uniformly on quadrant within angle theta0/phi0 */
    theta = width*randpm1()/2.0;
    phi   = height*randpm1()/2.0;
```
... which will lead to increased probability at the poles. I *think* the correct way would be 
```c
    theta = width*randpm1()/2.0;
    phi   = asin(randpm1()*sin(height/2.0));
```
similar to `randvec_target_circle` (theta and phi seem to be inverse to their usual definition in `randvec_target_rect_angular`), with an additional check that `0 < height <= pi`.

**Comment by willend** [comment]
@ebknudsen says this is indeed the case and easy... ;)

**Comment by willend** [comment]
@ebknudsen did you look at this one?

**Comment by ebknudsen** [comment]
I have now thought a bit more about this. The conclusion is that indeed randvec_target_rect_angular _does_ in fact work correctly. The reason being that it does not sample in spherical coordinates. For spherical coordinates it is correct that you'd see oversampling at the poles. The angles drawn in randvec_target_rect_angular are not spherical though.

An obvious drawback to this is that it does not work for angles >pi.  To fix this we could go to spherical coordinates and sample correctly.

**Comment by markusappel** [comment]
I am still convinced that it is not working correctly. It should not matter whether it actually uses spherical coordinates or not, the resulting distribution counts.
I reported this bug because I saw that the `Incoherent` component was occasionally peaking scattered intensity in the +/- y-direction. It uses either `randvec_target_rect_angular`, `randvec_target_rect` or `randvec_target_circle` depending on how the target is specified, and the results were not the same. If these functions are used for direction focusing, they should always use an isotropic distribution as written in the manual:
> All directions [...] are chosen with equal probability.

This is not the case if one of them prefers orientations towards the +/- y-direction. As far as I can tell from the code, `Isotropic_Sqw` should show the same problem for `0 < d_phi < PI`.

**Comment by ebknudsen** [comment]
hmm - I just did a few tests using nothing but randvec_target_rect_angular (i.e.EXTENDing a source), and as far as I can tell it generates an even spread of events without clustering at the poles, or prefering any direction. I'll look into the matter a bit further and repost a quantitative study.
 
What I meant by my comment was that if you sample spherical coordinates (generally denoted by theta,phi) uniformly you get the oversampling at the poles. The theta,phi of randvec_..._angular are however not spherical coordinates and should thus be sampled differently.   As you say the resulting distribution counts.

cheers
Erik

**Comment by willend** [comment]
Hi guys, I guess we will "park" this one for after 2.3 release anyway. My feeling is that if this is indeed a bug, it will affect very few cases / people.

@markusappel if you come across the effect again, could you place the relevant pieces here for us to debug this further? (I.e. a full .tgz archive with instr, any extra comps etc. plus an output dataset that shows the issue?)

**Comment by markusappel** [comment]
I don't think it's a good idea to postpone this, all components that use this function will give wrong results which is not immediately obvious. It's a minor effect if you stay very close to the xz-plane, but if you go out by 30 degrees you're already wrong in intensity by `1/cos(30deg) - 1 = 15%` !

Here is an instrument file to test:
```
DEFINE INSTRUMENT randvec_bug()

TRACE

COMPONENT source = Source_div(xwidth=0.04,yheight=0.04,focus_aw=0.2,focus_ah=0.2,
                              E0=2,dE=0.1)
AT (0,0,0) ABSOLUTE

// specify focus_aw and _ah so randec_target_rect_angular is used
COMPONENT sample = Incoherent(radius=0.015,focus_aw=180,focus_ah=180)
AT (0,0,2) ABSOLUTE
EXTEND
%{
   { // only scattered events
   if (!SCATTERED)
      ABSORB;
   }
%}

COMPONENT target = Arm()
AT (1,0,0) RELATIVE sample

COMPONENT mon_x = Monitor_nD(xwidth=1,yheight=1,options="x y",bins=50, restore_neutron=1)
AT (1,0,0) RELATIVE sample
ROTATED (0,90,0) RELATIVE sample

COMPONENT mon_y = Monitor_nD(xwidth=1,yheight=1,options="x y",bins=50, restore_neutron=1)
AT (0,1,0) RELATIVE sample
ROTATED (90,0,0) RELATIVE sample

END
```
or download here: https://cloud.ill.fr/index.php/s/NSgYwLMFCfRtoh9

It scatters from a full sphere and looks at intensity in x- and y- direction. They should be the same due to symmetry of the setup. Here's a 3D view:
![3d](https://cloud.githubusercontent.com/assets/13602252/13812229/3b2b4fa6-eb7b-11e5-8742-c6705343b278.png)
The top detector is only half illuminated due to the direction focusing.
If you look at the intensities on the monitors the problem is clear:
![mccode sim](https://cloud.githubusercontent.com/assets/13602252/13812253/6a502a36-eb7b-11e5-86ab-4e6108aa9ff0.gif)
