### ISSUE TITLE
On gcc/Ubuntu 12.04 with NeXus - requirement for #include <inttypes.h> ?

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#184]
From @trnielsen Torben Nielsen, ESS:

When compiling templateSANS_Mantid.instr with NeXus AND using -std=c99, compilation fails with errors ala

/usr/include/napi.h: 396:92: error: unknown type name 'int64_t'

- Can be remedied by adding #include inttypes.h  in the runtime code. (sharp brackets missing here, sorry)

Investigate if this is an issue on newer Ubuntus, e.g. 14.04 LTS?

**Comment by trnielsen** [comment]
Same issue on Ubuntu 14.04 LTS. 

Need to include inttypes.h in c-code by hand in order to compile c-code

**Comment by willend** [comment]
FIXED on main
