### ISSUE TITLE
McStas-Components: SNS_source does not compile

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#188]
After commit f77ac47cd1896d54581e65a2a4225c33ffb82c9 SNS_source does not compile.

This is because some of the functions that now reside in SHARE use global variables which have not been defined yet, as DECLARE is generated afterwards.

**Comment by climbcat** [comment]
Thanks for pointing this out, will fix.

**Comment by climbcat** [comment]
The component now compiles.

**Comment by willend** [comment]
:+1:
