### ISSUE TITLE
Tools: mcrun and friends - configurable location of CFLAGS in the compile string?

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#192]
I got the below bugreport from Rob Dalgliesh
<pre>
On 19 Jan 2016, at 14:22 , robert.dalgliesh@stfc.ac.uk wrote:

I did an git build of mcstas under mint and installed but I’m still having problems.
If I use the multilayer_sample component and the try to add the –lgsl and –lgslcblas flags 
to the compile it attaches the flags to the wrong part of the gcc command line. They should
be at the end.
</pre>

I suggest we act on it by giving an configuration item for this in mccode_config.perl and mccode_config.py, e.g.

CFLAGS_PLACEMENT = 0 / 1

**Comment by willend** [comment]
@climbcat will you have a look at this one? :-)

**Comment by climbcat** [comment]
What tools should implement this "flag position" stuff? mcrun, mcgui, mcrun-py, mcgui-py?

**Comment by willend** [comment]
Hi,

Yes, these are the ones - those that may call a compiler to generate a .out . For mcgui and mcrun it may be that this is in fact found in a common place - in

McCode/tools/Legacy-Perl/lib/tools/perl/mcrunlib.pl

Best,

Peter


On 15 Feb 2016, at 08:38 , Jakob Garde <notifications@github.com<mailto:notifications@github.com>> wrote:


What tools should implement this "flag position" stuff? mcrun, mcgui, mcrun-py, mcgui-py?

**Comment by climbcat** [comment]
- mcgui/mcrun: a parameter has been added to mccode_config.perl.in and the corresponding logics in mcrunlib.pl and the functionality has been tested with mcgui (not mcrun)

- mcrun-py: No changes were necessary
- mcgui-py: I interchanged mpi and cflags, it now puts cflags at the end of the copile-string just like mcrun-py

**Comment by willend** [comment]
:+1: nice! Will test later
