### ISSUE TITLE
McStas: Update sasview_generator.py to deal with float / double

### ISSUE THREAD

**Issue by trnielsen** [McStasMcXtrace/McCode#194]

**Comment by climbcat** [comment]
Please send me a few "double" c-files as a test sample, and I will fix this. @climbcat

**Comment by willend** [comment]
I think we agreed that the seen issues (intensity of 0 produced in some cases) are not directly related to this, what do you think @trnielsen ? I also think we agreed to look at this again post 2.3

**Comment by willend** [comment]
Believe this one was done
