### ISSUE TITLE
McStas: Sqw: classical: classical -> quantum S(q,w)

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#196]
Apply sqrt(n(w)) Bose rather than exp(hw/2kT)

**Comment by farhi** [comment]
Just to keep you informed, there is also something strange in the MPI sections of the Isotropic_Sqw (from #150). 

So the table-read / MPI bug seen before may be more involved than thought (#376 and similar weird stuff). I will simply remove the MPI sections in the INITIALIZE section of the component. It makes it longer to initialise, but at least it works.

**Comment by farhi** [comment]
Closed with commit https://github.com/McStasMcXtrace/McCode/commit/5b026b3c0dba2a2d8368279c55a8bced7a93102b
