### ISSUE TITLE
McStas: Preparations for 4D-Sqw

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#199]
@farhi: Sqw 4D: compute total x section from Single_crystal assuming Bragg peaks give most of the signal and determine phonon intensity.

**Comment by farhi** [comment]
I think this is done with commit https://github.com/McStasMcXtrace/McCode/commit/6ba16d5cbde7808a7d344983ebd8c8c6a8ea14ed#diff-526b226b594d72cef2820969ce5aa829

The intensity is computed and stored in the 4D list data file.

Close it ?
