### ISSUE TITLE
McStas: Checks / inclusion of Duc Le 4D-Sqw code

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#200]

**Comment by willend** [comment]
I finally had time to have a proper look.... @farhi it seems that Duc's solution is McStas 2.0 specific, in the sense that he uses DETECTOR_OUT_3D (which seems to have been removed between McStas 2.0 and 2.1)

It further uses a home-grown Matlab script for running etc.

What do you think, should we put it on our website "share" and say that it works for 2.0 only?  

(tagging you so that you are informed also @ebknudsen)

**Comment by willend** [comment]
It further seems that he is also using the --format=Matlab output that we supported back then... 

- Both of these things can in principle be fixed of course, but the question is if any of us will do that... (And Duc is a busy guy...)

**Comment by farhi** [comment]
Duc Lee component and example instruments are now part of the master branch.
Can close this issue as, in the current state, it does run properly, and iFit can generate 4D Sqw data files.

**Comment by willend** [comment]
Still, it would be good with an example instrument file that uses this and gives meaningful data... :-)
