### ISSUE TITLE
--trace output consistence

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McCode#284]
- ISIS_SANS2d does not print Initialize and Save sections correctly (Initialize and Save tags are missing)
- PSI_Focus does not start its --trace output with INSTRUMENT:

**Comment by climbcat** [comment]
@willend is it possible to conform the --trace writer to output start flags for the Initialize, Save and Finally sections (e.g. the way they appear from PSI_DMC)? (See https://github.com/McStasMcXtrace/McCode/blob/master/tools/Python/mcdisplay/webgl/traceparser.py#L298, these "comment section" states are initialized by a specific pattern)

**Comment by willend** [comment]
We believe this has been done via a set of workarounds
