### ISSUE TITLE
Python mcdisplay webgl: Wishlist :-)

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#285]
Feature suggestions @climbcat :
- Initial zoom set from cmdline via e.g. --first=COMP_A --last=COMP_B (ala existing for Matlab, but still draws outside this "boundingbox"
- Event filtering via --inspect=COMP_C: Takes out events that do not reach that point in instr
- Use mcrun (or equivalent) for "automation" of compilation, prompting for parms etc. @willend will take a look for existing half-solutions in the Py tools

**Comment by climbcat** [comment]
More features: 

Backend/structure

- neutron ray runtime environment: mcdisplay.html is drawn as a static function library and contains the instrument drawing. Neutron rays are written to secondary files which are loaded by javascript dynamically. These "bundles" are created from processed real-time --trace output of a continous background simulation, by the python layer. It might e.g. contain only the neutrons that reach the sample. This change requires a restructuring of the python and js layers. 
- RGB map for ray coloring by lambda
- auto-position camera for suitable initial zoom
- opacity by neutron intensity
- neutron statistics guess for lambda and intensity displays (Python layer)

UI

- displays for neutron index, intensity and lambda
- controls for neutron ray mode: Display all, continuous, iterative, window count
- ray-cast double-click to reposition camera towards new rotation point in the xz plane
- ray-cast component info and reposition
- color map controls
- opacity controls

**Comment by willend** [comment]
I belive we could close this one
