### ISSUE TITLE
release tags / .tar.gz or .zip on github

### ISSUE THREAD

**Issue by jonasstein** [McStasMcXtrace/McCode#289]
the recent releases are not yet tagged on github.
I try to make an package for gentoo linux. Where can users reliable download the source for a special release as tar.gz?

**Comment by willend** [comment]
Hi @jonasstein, true we might have forgotten that sorry. :-) Hardly any build themselves from our GitHub sources but download a platform-specific binary or source release from http://download.mcstas.org/ .

**Comment by willend** [comment]
It might be that looking at http://www.mcstas.org/download/install_unix/ also helps for config options etc.
