### ISSUE TITLE
mcplot-gnuplot-py: overview plot of scan only plots scan of first monitor

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#291]
Only the first monitor (with errorbars) is plotted when doing an overview plot of a scan.
Have not tried the other plotter backends.

It is unclear if the bug is in the interpretation of the mccode.sim file of the scan or in the sctual file itself.

**Comment by climbcat** [comment]
As we have agreed, this should be fixed by implementing a proper mcplot-python backend
