### ISSUE TITLE
mcdisplay: various changes

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McCode#296]
- include stderr by use of Popen3 or similar (as a new buffer on the low level "databucket")
- print all non- [KEYWORD COLON] lines to console (impl. low-level)
- hardcopy of scene from js in mcdisplay-webgl
- make it work on the Windows OS

**Comment by climbcat** [comment]
http://learningthreejs.com/blog/2011/09/03/screenshot-in-javascript/

**Comment by willend** [comment]
I believe we can actually close this one
