### ISSUE TITLE
McStas Sqw component: use 'standard' Bose factor weighting

### ISSUE THREAD

**Issue by farhi** [McStasMcXtrace/McCode#300]
See http://ifit.mccode.org/Treatment.html#mozTocId906474

Should use 'standard'  or 'Frommhold' Q = 2./(1+exp(-hw/kT))

This should fix issues when normalizing classical Sqw data, which result in a very large norm with the exp(hw/2kT) weighting, and most probably produces wrong results.

**Comment by willend** [comment]
@farhi we are considering a new McStas mid january or so - any chance to look at this one before or should we "park" it until after?

**Comment by willend** [comment]
Related user report from Ketty Beauvois, CNRS

<pre>
Dear Ken,

When we met at ECNS last year in Spain, we discussed together with Björn Fåk in front of my poster "The excitations in superfluid 4He". For the data treatment,  I performed multiple scattering calculations using McStas. I found a problem that I describe in the report "McStas.pdf" (attached). I tested also two other programs for the multiple scattering calculations. One is MScat (written by John Copley) and the other is written by Javier Dawidowski. I sent him a report called "multiple_scattering.pdf" (also attached), which compares the results from the three Monte Carlo programs. I would like to know if you have any idea where the problems could come from in McStas. I would be happy to discuss or respond to any questions.

Best regards,

Ketty Beauvois
</pre>
[McStas.pdf](https://github.com/McStasMcXtrace/McCode/files/1007622/McStas.pdf)
[multiple_scattering.pdf](https://github.com/McStasMcXtrace/McCode/files/1007623/multiple_scattering.pdf)

**Comment by farhi** [comment]
In fact, Isotropic_Sqw uses 'Schofield' / 'Boltzmann' Bose factor. This is not adapted when temperature is lower than the excitation energies. This is mostly the case for liquid 4He and other cryogenic liquids.

I will try a fix in relation with #196

**Comment by farhi** [comment]
This is duplicate of #196.

**Comment by farhi** [comment]
Done with commit https://github.com/McStasMcXtrace/McCode/commit/5b026b3c0dba2a2d8368279c55a8bced7a93102b
see #196.
