### ISSUE TITLE
mcgui-py: Issue with string parameters at component insertion

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#301]
When inserting a comp e.g. PSD_TOF_monitor that has a filename parameter of type string, that parameter ends up having the type also put in the instrument file text., like this:

<pre>
COMPONENT psd_tof_monitor = PSD_TOF_monitor( 
    nx=90, 
    ny=90, 
    nt=10, 
    <b>string</b> filename="PSDtof", 
    restore_neutron=0, 
    xmin=0, 
    xmax=0, 
    ymin=0, 
    ymax=0, 
    xwidth=0.25, 
    yheight=0.25, 
    tmin=0, 
    tmax=1)
AT (1.43, 0, 1.43) RELATIVE sample
ROTATED (0, 45, 0) RELATIVE sample
</pre>

The <b>string</b> label should be dropped, as it causes the code generator to fail.

**Comment by climbcat** [comment]
Can not reproduce. Probably fixed.
