### ISSUE TITLE
mcgui-py: Trace runs should be backgrounded, i.e. non-blocking

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#302]
(At least) when running with the oldschool PGPLOT mcdisplay, mcgui-py remains blocked until the underlying simulation is ended. Situations occur where mcdisplay itself does not terminate the simulation.

Suggestion: Run mcdisplay runs (completely) in the background (On Unix systems this can be done with adding an & at the end of the cmdline).

**Comment by climbcat** [comment]
I could not reproduce the problem, but an & was added to the end of the command string when the Trace option is selected in the start simulation dialogue. Could you test if this changes mcgui behavior on your system?

**Comment by willend** [comment]
Adding & will not work on windows - add exception about that either from "config" or simply as a nasty if !WIN32

**Comment by willend** [comment]
Done
