### ISSUE TITLE
mcplot-gnuplot-py has restrcitions on filename extensions

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#306]
mcplot (or mxplot really) refuses to plot anything that does not have extension .sim or .dat
Monitor_nD will however frequently produce file which have different extensions.

This restriction should (imho) be removed.

**Comment by climbcat** [comment]
Should be easy enough to fix. Some sample data would be helpful, do you have some with the Monitor_nD generated filenames I could test it on?

**Comment by ebknudsen** [comment]
sure - here are two:
[bananapsd.th.zip](https://github.com/McStasMcXtrace/McCode/files/484940/bananapsd.th.zip)
[det_ccd_angle.A.zip](https://github.com/McStasMcXtrace/McCode/files/484941/det_ccd_angle.A.zip)
Basically what Monitor_nD does is to add (an abbreviation of) whatever the monitor measures as an "extension".

**Comment by ebknudsen** [comment]
Oh - it only is a problem when plotting a single file from the command line: e.g.
mxplot-gnuplot-py DIRECTORY/banana.th

When doing:
mxplot-gnuplot-py DIRECTORY
it works fine.

**Comment by climbcat** [comment]
fixed
