### ISSUE TITLE
Pol_simpleBfield tabulated field step size and constant field threshold

### ISSUE THREAD

**Issue by mortensales** [McStasMcXtrace/McCode#311]
@ebknudsen 
When using a tabulated field input for the Pol_simpleBfield component, changes in the field might be ignored when they are smaller than the threshold for what McStas "sees" as constant or when the changes are on a smaller scale than the distance step that the neutron takes when travelling through the field.
I would be nice if the treshold and the step could be set manually.
Kind Regards,
Morten
(I'm running mcstas-2.2a version 2.2a on Mac OS X 10.11.6, but I believe this is an issue for all current versions.)

**Comment by ebknudsen** [comment]
indeed this is an issue for all versions.

**Comment by willend** [comment]
@ebknudsen will you have time for this one before release?

**Comment by ebknudsen** [comment]
Should be fixed by 3aa8525f5419cbf186cae4e7502227ed1c2ea5ee
maximal time step size can be set by the functions mc_pol_set_timestep(double)   mc_pol_set_angular_accuracy(double)

**Comment by willend** [comment]
Sounds good, closing
