### ISSUE TITLE
McGui-py: Scan crashes when number of steps is >30 and mcrun is perl

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#317]
The scan crashes and leaves the run button at halt when the perl mcrun is used.

The console reports:
RuntimeError: maximum recursion depth exceeded
RuntimeError: maximum recursion depth exceeded
RuntimeError: maximum recursion depth exceeded
RuntimeError: maximum recursion depth exceeded
RuntimeError: maximum recursion depth exceeded
RuntimeError: maximum recursion depth exceeded
RuntimeError: maximum recursion depth exceeded
RuntimeError: maximum recursion depth exceeded
RuntimeError: maximum recursion depth exceeded
RuntimeError: maximum recursion depth exceeded
RuntimeError: maximum recursion depth exceeded
Traceback (most recent call last):
  File "/usr/share/mcstas/2.3/tools/Python/mcgui/mcgui.py", line 398, in <lambda>
    self.__runthread.finished.connect(lambda: self.__runFinished(self.__runthread.process_returncode))
  File "/usr/share/mcstas/2.3/tools/Python/mcgui/mcgui.py", line 411, in __runFinished
    self.__fireSimStateUpdate()
  File "/usr/share/mcstas/2.3/tools/Python/mcgui/mcgui.py", line 125, in __fireSimStateUpdate
    self.simStateUpdated.emit([str(self.canRun()), str(self.canPlot()), str(self.isSimRunning())])
  File "/usr/share/mcstas/2.3/tools/Python/mcgui/mcgui.py", line 184, in canRun
    return self.__instrFile != ""
RuntimeError: maximum recursion depth exceeded in cmp

**Comment by willend** [comment]
Seems not to be tied to 30 steps, can be reproduced at even lower number of scan steps when each simulation is sufficiently short (e.g. -n1).

I suggest to mark as wontfix as the python mcrun works
