### ISSUE TITLE
Copyright statements should be thought through.

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#323]
Not everything gets updated in the copyright statements. for instance
mcstas --version report both 2016 and 2015 as years.

**Comment by willend** [comment]
Agreed!

**Comment by willend** [comment]
@ebknudsen lets think then ;-)

**Comment by willend** [comment]
Attempt to fix this in 73d09b52e926c5d4523a51bf6f68e4b56a48652c - have added a define for MCCODE_YEAR via cmake TIMESTAMP feature. 

I think we can close - what do you think @ebknudsen ?

**Comment by ebknudsen** [comment]
agreed!
