### ISSUE TITLE
McXtrace: PowderN: add 2theta limit possibility 

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#327]
Would be good to be able to also limit the scattering to longitude as well as latitude.

1.  add prm twotheta maximum
2. two places this would have to be introduced:
  2.1. first in the computation of my_s_sum
  2.2 in the looping over possible Nq lines - only try the wanted lines.

**Comment by ebknudsen** [comment]
First version made - under the assumption that the hkl-file is ordered by q. Will generalize such that in th e search a second list of lines is built to include the possible ones.

**Comment by willend** [comment]
@ebknudsen close thos one?

**Comment by ebknudsen** [comment]
Well the second bit never got done - it still assumes hkl file is ordered by q.

**Comment by ebknudsen** [comment]
Upon reconsideration will leave as is for 1.4 - and write a note in the docs that the hkl-list has to be ordered in q.
Will open a new issue for second bit - as it is relevant for McStas also.
