### ISSUE TITLE
Redhat/CentOS Linux packages require perl 5.18

### ISSUE THREAD

**Issue by ajj** [McStasMcXtrace/McCode#333]
Current release of RedHat/CentOS/SL seem to ship with perl 5.16 - why does mcstas require perl 5.18?

**Comment by willend** [comment]
Hi Andrew,

I believe at least Centos 7 ships with 5.18? If you are trying to install via yum/our repo, we probably do indeed require 5.18. 

I remember helping someone else needing rpms for a system with perl 5.16 - I generated this supplementary set of packages: http://download.mcstas.org/mcstas-2.3/linux/mcstas-2.3-rpm64-Scientific_Linux_6.1/ - could you check if they can be hand-installed and work better?

**Comment by ajj** [comment]
Hi Peter

Just installed CentOS 7 and it comes with 5.16. Those SL6.1 packages don't work because they are missing perl-PGPLOT which is not a system package (or EPEL).

**Comment by willend** [comment]
I might indeed have built on Fedora, but SL6.1 is from the ESS compile node as I remember...

A workaround could be to
* Install pgplot from source code as in the old days (just use XDISP, XSERV and PS drivers, skip the others) - and remember to do both make and make cpg
* Install perl-PGPLOT from CPAN source code (you'll need ExtUtils:F77, a dependency)
* perhaps also PDL from CPAN

And then install the packages with --nodeps... Not so nice, I know.

If you can find rpms for the dependencies (pgplot, perl-PGPLOT, perl-Tk, PDL etc.) that fit your system you could also simply roll you a McStas 2.3 yourself from the repo? 
I think there is a relevant release tag/branch, look at needed dependencies in the top-level https://github.com/McStasMcXtrace/McCode/blob/master/BUILD_DEPS.TXT and run the top level script build_rpms_mcstas with input parameter 2.3.

**Comment by willend** [comment]
(Sorry, we are just a lot more of a Debian shop... :-) )

**Comment by willend** [comment]
I just remembered I had a fresh Centos 7 handy. The following worked for me:

* Add EPEL
* Install perl-PDL, perl-Tk, libgfortran, libpng, libpng12
* Download and hand-install these packages
** http://packages.mccode.org/rpm/x86_64/pgplot-5.2.2-28.el6.x86_64.rpm
** http://packages.mccode.org/rpm/x86_64/perl-PGPLOT-2.21-2.fc19.x86_64.rpm
** http://packages.mccode.org/rpm/x86_64/libtk-codetext-perl-0.3.4-2.noarch.rpm
** http://download.mcstas.org/mcstas-2.3/linux/mcstas-2.3-rpm64-Scientific_Linux_6.1/mcstas-2.3-rpm64.rpm
** http://download.mcstas.org/mcstas-2.3/linux/mcstas-2.3-rpm64-Scientific_Linux_6.1/mcstas-comps-2.3-rpm64.rpm
** http://download.mcstas.org/mcstas-2.3/linux/mcstas-2.3-rpm64-Scientific_Linux_6.1/mcstas-manuals-2.3-rpm64.rpm
** http://download.mcstas.org/mcstas-2.3/linux/mcstas-2.3-rpm64-Scientific_Linux_6.1/mcstas-suite-perl-2.3-1.x86_64.rpm

- and you should be in business!

BTW we are moving to a default of all-python tool-set with next release, should have been done ages ago... ;-)

**Comment by ajj** [comment]
Also needed mcstas-tools-perl, but all sorted now!

Thanks - the thought of compiling pgplot and installing perl-PGPLOT from cpan was giving me flashbacks to 1997.

**Comment by willend** [comment]
Overlooked that you closed this one the other day @ajj - but great to hear it all worked out OK. :-)

McStas 2.4 should come with a full python tool set around it, maybe even before Christmas... We are btw thinking to ship almost all via pyinstaller ala SASview, which should make end-user life with McStas much easier!
