### ISSUE TITLE
mcplot-pyqtgraph-py: "common" zoom factor in sweep scan series?

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#339]
When meta+clicking to get monitor output as fct. of series scan, a common zoom would optionally be nice.

**Comment by willend** [comment]
Hi there, the solution found here could work http://stackoverflow.com/questions/23292664/link-to-view-changes-axis-range-pyqtgraph

**Comment by climbcat** [comment]
Note to self: We need to identify a "zoom change" event in pqtg. Alternatively, use direct "mouse wheel" events and forward to a (mulitiple) zoom action(s).

**Comment by climbcat** [comment]
This has been implemented by a9acccd9a59279ef136d4e7b8ef0921273a2bfee. There is no common pan position, tough.

**Comment by willend** [comment]
This would in fact be non-standard, i.e. all subplots zooming together. Parking with wontfix
