### ISSUE TITLE
mcplot-pyqtgraph-py subplot titles

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#341]
Please put indication of filename / stats when applicable, see attached
[PSD.dat copy.pdf](https://github.com/McStasMcXtrace/McCode/files/597021/PSD.dat.copy.pdf)

**Comment by climbcat** [comment]
Done.

**Comment by climbcat** [comment]
A few things have been added, BUT a big problem has arisen. pyqtgraph does not support linebreaks in labels to plots. I have tried to hack it in various ways, but have only so far succeeded in hacking it by creating a label in a new row in a GraphicsLayout for every "line" of the title text. However, this creates an unacceptably large space between the lines, which I was in turn unable to remove.

**Comment by climbcat** [comment]
@willend, what do you make of this?

**Comment by willend** [comment]
I there, I see two immediate options:

1) Add another keypress / click combo that brings up a small Qt widget with the information for the current / clicked plot

2) Is it possible to put a "legend" or text onto the actual graph, ala the attached?

![figure](https://cloud.githubusercontent.com/assets/8593355/20718376/cc89af12-b658-11e6-8265-eae525a63c4e.png)

**Comment by willend** [comment]
I will experiment a little with http://www.pyqtgraph.org/documentation/graphicsItems/textitem.html and http://stackoverflow.com/questions/16698074/pyqtgraph-add-legend-for-lines-in-a-plot think

**Comment by climbcat** [comment]
Update:

Since the legend item doesn't support linebreaks either, I have separated the statistics and subplot title text into three separate "name" items in the legend. The text size can now be adjusted in the ModLegend constructor.

**Comment by willend** [comment]
Looks acceptable, maybe the fonts should be adjustable in size?

Seems we are missing an if statement to disable this information for the scan view, on scan sweep folders I get:
<pre>
pkwi-mbp2016:tmp pkwi$ python ../McCode/tools/Python/mcplot/pyqtgraph/mcplot.py A
mcplot error: tuple index out of range
Traceback (most recent call last):
  File "../McCode/tools/Python/mcplot/pyqtgraph/mcplot.py", line 298, in <module>
    main(args)
  File "../McCode/tools/Python/mcplot/pyqtgraph/mcplot.py", line 289, in main
    raise e
  File "../McCode/tools/Python/mcplot/pyqtgraph/mcplot.py", line 280, in main
    plotter.runplot()
  File "../McCode/tools/Python/mcplot/pyqtgraph/mcplot.py", line 39, in runplot
    plot_node(node, plt_layout, flipper)
  File "../McCode/tools/Python/mcplot/pyqtgraph/mcplot.py", line 92, in plot_node
    viewbox_lst.append(add_plot(layout, data_lst[i], i, n, logflipper.state(), logflipper.legendstate(), logflipper.cmapindex()))
  File "../McCode/tools/Python/mcplot/pyqtgraph/mcplot.py", line 243, in add_plot
    item, view_box = plot_Data1D(data, log=log, legend=legend, icolormap=icolormap)
  File "/Users/pkwi/Projects/McCode/tools/Python/mcplot/pyqtgraph/plotfuncs.py", line 73, in plot_Data1D
    lname3 = 'I = %s Err = %s N = %s; %s' % (data.values[0], data.values[1], data.values[2], data.statistics)
IndexError: tuple index out of range

</pre>

**Comment by climbcat** [comment]
Yes, of cause. However, I think it should be fixed at the data imitialization side rather than in the plotting code.

**Comment by climbcat** [comment]
We have implemented a solution and fixed some errors, is this issue to be closed?

**Comment by willend** [comment]
Found two remaining issues:

1) It looks as if toggling the legends "sometimes" makes changes to the y-axis limits? See the attached two figures

2) Do you remember how the style of the legend can be set? The current combination of gray-ish text on semi-transparent black makes it difficult to read at times. A simple fix would be to make it less transparent?
![mcplot_1](https://cloud.githubusercontent.com/assets/8593355/20837785/e7cfddec-b8a5-11e6-8472-9f811978fa36.png)
![mcplot_0](https://cloud.githubusercontent.com/assets/8593355/20837786/e7f504aa-b8a5-11e6-84b8-7b2e9cab8044.png)

**Comment by willend** [comment]
Closing this one and making separate issue for the range issue when toggling legend
