### ISSUE TITLE
mcplot-pyqt... other interactivity via keyboard

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#343]
something like

* 'p' - dump a PDF
* 'l' - toggle log
* 'q' - quit

(Let this also become a template for controlling a similar "scientific" mcdisplay)

**Comment by willend** [comment]
@climbcat could you also add e.g.
s          - save svg
?
(Then I will look at conversion options svg->pdf)

**Comment by climbcat** [comment]
Done.
