### ISSUE TITLE
mcplot-pyqt... Support for more complex colormaps ala Matlab

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#350]
As far as I can see, the current colormap implementation can not implement color maps like the default Matlab colormap which varies several times up and down in the 3 base colors - see attached files.

As also mentioned in https://github.com/McStasMcXtrace/McCode/commit/99885ed76943fe91b1601ac385aefb19f1a1da15, this may be possible to handle with a 'pos' definition for each separate colormap.

![figure1](https://cloud.githubusercontent.com/assets/8593355/20624821/72ae01b0-b30f-11e6-9434-33bf9d89e740.png)

[cmap.txt](https://github.com/McStasMcXtrace/McCode/files/613185/cmap.txt)

**Comment by climbcat** [comment]
Generalized somewhat. The 'pos' variable is now adjusted to fit the chosen colormap. Colormap is gotten by means of a function. New color maps must be entered into this function, using the existing format.

**Comment by willend** [comment]
Done with last commit - except we should add some code to change the colormap, e.g. cycle through them by 'c' or something...
