### ISSUE TITLE
mcgui-py save user config seems broken

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#353]
@climbcat with the last edits to the config stuff I get the below error.  

<pre>
user config does not exist: /Users/pkwi/.mcstas/2.4rc07/mccode_config.json
userconfig could not be saved to /Users/pkwi/.mcstas/2.4rc07/mccode_config.json: [Errno 2] No such file or directory: '/Users/pkwi/.mcstas/2.4rc07/mccode_config.json'
Traceback (most recent call last):
  File "/Applications/McStas-2.4rc07.app/Contents/Resources/mcstas/2.4rc07/tools/Python/mcgui/viewclasses.py", line 988, in save
    mccode_config.save_user_config()
  File "/Applications/McStas-2.4rc07.app/Contents/Resources/mcstas/2.4rc07/tools/Python/mcgui/../mccodelib/mccode_config.py", line 72, in save_user_config
    f.close()
UnboundLocalError: local variable 'f' referenced before assignment
</pre>

![python3screensnapz003](https://cloud.githubusercontent.com/assets/8593355/20792183/c65ba1a4-b7c0-11e6-90dd-6009953f03fb.png)

**Comment by climbcat** [comment]
The main problem is "no such file or directory", so the line where the variable 'usercomfig' is assembled may need to be rethought

**Comment by climbcat** [comment]
Fixed the 'referenced before assignment' thing, which was a side effect.

**Comment by willend** [comment]
Yup - I introduced an mkdir if not exist(config folder)
