### ISSUE TITLE
mcplot-pyqtgraph order of plots?

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#354]
Hi there,

it would be great if we could ensure that the plots occur in the same order as they occur in the instrument file (and mccode.sim)

Peter

**Comment by willend** [comment]
More precisely, I think the order is OK in single sims but think i saw it ordered differently on the mccode.dat-generated scan sweep plot?

**Comment by climbcat** [comment]
Hi! I'll look into the ordering.

**Comment by climbcat** [comment]
Do you have an example data set in which the ordering is mixed up? I don't see anything in the code that loudly screams of disorder. The only time an ordering ambiguity could arise - the listing of the sweep subfolders - there is an alphasort call on that list.

**Comment by willend** [comment]
It is indeed that alphasort when plotting a scan output - can we avoid that by using the order that the monitors appear in the scan folder mccode.sim?

**Comment by willend** [comment]
After checking this is no longer an issue. Closing
