### ISSUE TITLE
mcplot-pyqtgrahph... legend toggle side effect

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#355]
Adding a legend seems to "expand" the y-axis range down toward zero. In other words, the plot looks different with/without legend if the signal does not already reach the zero value. See below plots

![mcplot_1](https://cloud.githubusercontent.com/assets/8593355/20846987/79b9f172-b8cc-11e6-96d6-6c15dea40858.png)
![mcplot](https://cloud.githubusercontent.com/assets/8593355/20846988/79d80d56-b8cc-11e6-9371-cdd5c8d8e08e.png)

**Comment by climbcat** [comment]
This should now have been fixed!

**Comment by willend** [comment]
Confirmed, works now!
