### ISSUE TITLE
mcplot-pyqtgraph segfaults on q-exit (on macOS) (mcplot now works - same issue for mcdisplay)

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#358]
On my mac I currently get

<pre>
Active colormap: jet
q            - quit
p            - save png
s            - save svg
d            - save pdf
l            - log toggle
t            - textinfo toggle
c            - cycle colormap
F1/h         - help
F5           - replot
click        - display subplot
right-click  - back
Meta + click - sweep monitors
x            - expand subplots
python(32900,0x7fffbd3273c0) malloc: *** error for object 0x119bac888: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
</pre>
when pressing 'q' to exit. 

Closing the window terminates the plotter nicely.

**Comment by climbcat** [comment]
We must try to put "QtGui.QApplication.quit()" instead of just "quit()"

**Comment by willend** [comment]
Has now been tested and works as intended!

**Comment by willend** [comment]
mcdisplay-pqtgraph does the same - @climbcat could you implement the same workaround / solution there? :-)

**Comment by willend** [comment]
My bad, mcdisplay-pyqtgraph also uses QtGui.QApplication.quit() and seems to work OK. Closing
