### ISSUE TITLE
mcdisplay-pyqtgraph - missing support for MCDISPLAY: circle directives

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#362]
Seems we are missing circle directives - see below image. I see two solutions

1) Make 100 steps in theta and generate (x,y) = radius * (cos(theta), sin(theta))

2) Look at CircleROI http://pyqtgraph.narkive.com/Kbv2OSt1/smooth-circleroi ( CircleROI((offset_x, offset_y), (radius, radius), movable=False)) )

![pythonscreensnapz003](https://cloud.githubusercontent.com/assets/8593355/21718790/04a56cf4-d41a-11e6-9116-d3aca382397d.png)

**Comment by climbcat** [comment]
this has now been implemented in mcdisplay-2D

**Comment by willend** [comment]
Confirmed, works
