### ISSUE TITLE
mcdisplay-pyqtgraph - issue rendering ILL_IN5

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#363]
For whatever reason ILL_IN5 seems to never render?

**Comment by climbcat** [comment]
Here, it renders like this:

![ill_in5_render](https://cloud.githubusercontent.com/assets/11196009/21890951/99eb4b20-d8d0-11e6-8145-10a6c1ddeec6.png)

**Comment by willend** [comment]
Confirmed, my issue is an unrelated more general issue with ILL_IN5 and read-table_lib...
