### ISSUE TITLE
mcplot-pyqtgraph: Subplots of uneven width in some cases?

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#365]
Hi,
Reproduce the below graphic by running PSI_Focus and plotting 

![mcplot_1](https://cloud.githubusercontent.com/assets/8593355/21925585/62807ce2-d97e-11e6-9b98-d04343a1d04f.png)

Related to subplot title length maybe? Marking as "minor" since the plotter is functional in spite of this visualisation artefact.

**Comment by climbcat** [comment]
Never saw it that extreme, but have observed that the widths were a bit uneven. We could try changing the strategy for populating the plot grid.

**Comment by climbcat** [comment]
I think we should close this as a "known issue that we keep working on".

**Comment by willend** [comment]
Agrred.
