### ISSUE TITLE
mcplot-pyqtgraph and mcdisplay-pyqtgraph: F1/h should spawn QMessageBox

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#366]
I tried myself but failed... :-)

Many users will never look at the terminal, meaning that when help is requested from the event handler, the text should go in a QMessageBox of type "information".

**Comment by climbcat** [comment]
works on linux now

**Comment by willend** [comment]
I belive this is at least partly done @climbcat ? 

In mcdisplay it brings up the component list though?

**Comment by climbcat** [comment]
Yes, because the help text is printed in the legend item in the forth quadrant.. should this be changed?

**Comment by willend** [comment]
You are right, that is probably OK.

Two points though:
* We should add s and p to dump svg and png files
* The help mentions that you will ‘zoom’ if clicking, I think ‘select single plane’ is more descriptive maybe?

P

On 19 Jan 2017, at 16:45 , Jakob Garde <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, because the help text is printed in the legend item in the forth quadrant.. should this be changed?

**Comment by climbcat** [comment]
Ok! Will port from mcplot.

**Comment by willend** [comment]
As far as I can see this functionality is now available, closing
