### ISSUE TITLE
Document use of the new python tools on wiki / README.md

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#368]
Since there are a lot of new features we need to document this somewhere. I was thinking that docs together with the individual python snippets would be a good solution.

**Comment by willend** [comment]
Tree structure for these "docs" initiated here:
https://github.com/McStasMcXtrace/McCode/wiki/User-documentation-for-the-2017--Python-tool-set

**Comment by willend** [comment]
@climbcat I have a feeling I saw something from you in this direction, but couldn't find it back - or is this just my bad memory? :-)

**Comment by climbcat** [comment]
I haven't written anything yet=)

**Comment by willend** [comment]
I belive what is now available at https://github.com/McStasMcXtrace/McCode/wiki/User-documentation-for-the-2017--Python-tool-set is sufficient for a start. Closing
