### ISSUE TITLE
Find a way to _raise() mcplot and mcdisplay pyqtgraph ala mcgui

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#369]
We should find a way to _raise() (i.e. assign focus) to our plot and display windows.

We may have to define a MainWindow ala mcgui caafd993719b75684bd3eae4faaec7f55fd128f2 - at least calling _raise() on the pyqtgraph GraphicsWindow does not work...

**Comment by climbcat** [comment]
Ready for test

**Comment by climbcat** [comment]
I think we can close this if it is tested.

**Comment by willend** [comment]
I have tested it for mcplot, will have a look wrt mcdisplay and then close

**Comment by willend** [comment]
Yup, works 👍 Closing
