### ISSUE TITLE
Python tools: Ensure to decode files and OS-generated strings 

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#374]
On macOS you can occasionally see issues like below when the .py tools are run through the .app bundle and mcgui.

E.g. mcrun (py) gives the below output on my test VM:

<pre>

INFO: No output directory specified (--dir)
INFO: Using directory: "BNL_H8_20170118_151822"
INFO: Recompiling: ./BNL_H8.out
INFO: Regenerating c-file: BNL_H8.c
Warning: 'V_sample' is an obsolete component (not maintained).
Info:    Defining SPLIT from PG1Xtal=Monochromator_flat() to END in instrument BNL_H8
Info:    Defining SPLIT from Sample=V_sample() to END in instrument BNL_H8
Info:    Defining SPLIT from PG2Xtal=Monochromator_flat() to END in instrument BNL_H8
CFLAGS=
Traceback (most recent call last):
  File "/Applications/McStas-2.4rc27.app/Contents/Resources/mcstas/2.4rc27/tools/Python/mcgui/../mccodelib/../../../bin/../tools/Python/mcrun/mcrun.py", line 356, in <module>
    main()
  File "/Applications/McStas-2.4rc27.app/Contents/Resources/mcstas/2.4rc27/tools/Python/mcgui/../mccodelib/../../../bin/../tools/Python/mcrun/mcrun.py", line 280, in main
    mcstas.prepare(options)
  File "/Applications/McStas-2.4rc27.app/Contents/Resources/mcstas/2.4rc27/tools/Python/mcrun/mccode.py", line 154, in prepare
    for line in ccode:
  File "/Users/willend/anaconda3/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 358: ordinal not in range(128)
</pre>

What needs doing is along the lines of this commit: cc82edb1df1c9e3cff4ab881d67b297f288983f8  (that solved a similar issue for mcgui...)

**Comment by climbcat** [comment]
I have done something about it, let's have a look next week!

**Comment by willend** [comment]
I've fixed the mcrun issue above - we should probably check all of the .py tools using the standard open() with a grep

**Comment by willend** [comment]
These are the places we ought to check

<pre>
./mccodelib/fileutils.py:        text = open(self.file).read()
./mccodelib/fileutils.py:        text = open(self.file).read()
./mccodelib/instrgeom.py:        #data = open(filename).readlines()
./mccodelib/instrparser.py:    def p_instr_open(self, p):
./mccodelib/instrparser.py:    def p_draw_open(self, p):
./mccodelib/mccode_config.py:    text = open(userconfig).read()
./mccodelib/mccode_config.py:        f = open(str(userconfig), 'w')
./mccodelib/mcdisplayutils.py:    f = open(filename, 'w')
./mccodelib/mcplotloader.py:    text = open(f).read()
./mccodelib/mcplotloader.py:    text = open(mccodesim).read()
./mccodelib/mcplotloader.py:    text = open(f).read()
./mccodelib/mcplotloader.py:    text = open(f).read()
./mccodelib/mcplotloader.py:    text = open(f_dat).read()
./mccodelib/uiutils.py:    f = open(instr_file, 'rb')
./mccodelib/uiutils.py:    f = open(str(instr), 'w')
./mccodelib/uiutils.py:    f = open(file, 'rb')
./mcdisplay/pyqtgraph/mcdisplay.py:    instrdef = open(filename).read()
./mcdisplay/pyqtgraph/mcdisplay.py:    particles = open(filename).read()
./mcdisplay/pyqtgraph/mcdisplay.py:    f = open(filename, 'w')
./mcdisplay/webgl/mcdisplay.py:            f = open(self.html_filename, 'w')
./mcdisplay/webgl/mcdisplay.py:            f = open(filename, 'w')
./mcdisplay/webgl/mcdisplay.py:    f = open(filename, 'w')
./mcgui/mcgui.py:            ccode = open(self.__cFile)
./mcgui/mcgui.py:            self.emitter.message(open(comprev).read())
./mcgui/mcgui.py:            template_text = open(os.path.join(mccode_config.configuration["MCCODE_LIB_DIR"], "examples", "template_simple.instr")).read()
./mcgui/viewclasses.py:            self.__scintilla.setText(open(instr).read())
./mcplot/matplotlib/mcplot.py:    Header = filter(isHeader, open(this_File).readlines())
./mcplot/matplotlib/mcplot.py:    SimFile = filter(isBegin, open(this_File).readlines())
./mcplot/matplotlib/mcplot.py:    MonFiles = filter(isCompFilename, open(this_File).readlines())
./mcplot/matplotlib/mcplot.py:            Scanfile = filter(isFilename, open(this_File).readlines()); 
./mcrun/mccode.py:        ccode = open(self.cpath,'rb')
./mcrun/optimisation.py:        fid = open(self.outfile, 'w')        
./mcrun/optimisation.py:        mccodesim = open(self.simfile, 'w')
</pre>

**Comment by willend** [comment]
Didn't see anything like this for a while so I think we can close it
