### ISSUE TITLE
Latest read-table_lib changes breaks use of .lau/.laz in Isotropic_sqw

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#376]
@ebknudsen will you have time to fix this one (within ~1 week) or should we restore the earlier revisions of the .c/.h files?

**Comment by ebknudsen** [comment]
Yes - I have a fix which I am testing presently.

**Comment by willend** [comment]
👍

**Comment by ebknudsen** [comment]
should be fixed now...

**Comment by willend** [comment]
Yup, confirmed 👍
