### ISSUE TITLE
McCode: python mcgui has a problem when opening files

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#379]
On my debian testing system - there's a problem when opening a file using the open-button.
This does not enable the run and edit buttons. Choosing an instrument from the templates list works however.
If I choose a template instrument - it not change anything to subsequently "open" an instrument.

**Comment by ebknudsen** [comment]
The same happens ( or doesn't :-) ) for McXtrace (mxgui) as well.

**Comment by climbcat** [comment]
Super cool, let's have a look at this next week.

**Comment by willend** [comment]
Hi there,

I think I may have missed an edit for the Open… call similar to what I did for e.g. the Save As in one of the last commits.

Peter

On 20 Jan 2017, at 16:06 , Jakob Garde <notifications@github.com<mailto:notifications@github.com>> wrote:


Super cool, let's have a look at this next week.

**Comment by willend** [comment]
Fixed in ddbb570..53e6fa1
