### ISSUE TITLE
Tests of builds across all platforms

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#381]

**Comment by willend** [comment]
Apart from py mcdisplay's failing, Windows seems close to functional.

**Comment by willend** [comment]
Troublesome platforms macOS and Windows look good at this point

**Comment by willend** [comment]
@climbcat found a couple of hickups on my Ubuntu 16.04:

* mcdisplay-webgl works, but has an error message about parsetab.py:
 <pre>starting particle parsing
ended particle parsing
  global configuration
WARNING: t_ignore contains a literal backslash '\'
WARNING: Couldn't open 'parser.out'. [Errno 13] Permission denied: '/usr/share/mcstas/2.4rc42/tools/Python/mcgui/../mccodelib/../../../bin/../tools/Python/mcdisplay/webgl/../../mccodelib/parser.out'
Generating LALR tables
WARNING: Couldn't create 'parsetab'. [Errno 13] Permission denied: '/usr/share/mcstas/2.4rc42/tools/Python/mcgui/../mccodelib/../../../bin/../tools/Python/mcdisplay/webgl/../../mccodelib/parsetab.py'
ATTENTION: default value of option force_s3tc_enable overridden by environment.
simulation done
</pre>

* Almost the same for mcdisplay-pyqtgraph:
<pre>
WARNING: Couldn't open 'parser.out'. [Errno 13] Permission denied: '/usr/share/mcstas/2.4rc42/tools/Python/mcgui/../mccodelib/../../../bin/../tools/Python/mcdisplay/pyqtgraph/../../mccodelib/parser.out'
Generating LALR tables
WARNING: Couldn't create 'parsetab'. [Errno 13] Permission denied: '/usr/share/mcstas/2.4rc42/tools/Python/mcgui/../mccodelib/../../../bin/../tools/Python/mcdisplay/pyqtgraph/../../mccodelib/parsetab.py'
</pre>

What to do?

**Comment by willend** [comment]
mcplot-pyqtraph also works, but when exited by 'q', it crashes ala what we saw on windows

<img width="578" alt="vmware fusionscreensnapz009" src="https://cloud.githubusercontent.com/assets/8593355/22266190/47c27694-e27f-11e6-99b2-c3935ba5f7f2.png">

**Comment by climbcat** [comment]
Oh noes...

**Comment by climbcat** [comment]
I'm on it, we can disable the output files from ply. It will run a bit slower, but the slowness doesn't scale with the size of the instrument or number of particles, it is fixed by the grammar complexity.

**Comment by climbcat** [comment]
Disabled output files in the instrument parser and the particle parser. An alternative solution may be possible, which has to do with file permissions, but this is simpler if it works.

**Comment by climbcat** [comment]
Disabled output files in the instrument parser and the particle parser. An alternative solution may be possible, which has to do with file permissions, but this is simpler if it works.

**Comment by willend** [comment]
@climbcat is there a way to control where the ply output goes? Because if we can, that would probably be preferable?

e.g. to some file in the user directory or in /tmp with a randomized filename?

Otherwise I am having a look at how things install and run on windows at the moment, and think we will soon be able to close this "general" issue - then only the specific ones are left...

**Comment by climbcat** [comment]
They just say this in their documentation: 

"To prevent yacc from generating any kind of parser table file, use:

    parser = yacc.yacc(write_tables=False)

Note: If you disable table generation, yacc() will regenerate the parsing tables each time it runs (which may take awhile depending on how large your grammar is). "

Therefore, having the files output somewhere else might require us to hack it a little bit (maybe only from our own source, don't know, but still).

Have you experienced mcdisplay to start noticably slower after the change?

**Comment by willend** [comment]
I think we can close this one - except we should of course run a final test everywhere...
