### ISSUE TITLE
Better handling of output from mcdisplay-pythons from within mcgui

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#385]
I think we have to do something about the Popen calls to mcdisplay...

On MacOS, the instrument Union_demonstration_absorption_image.instr never displays when called from within mcgui - whereas copying the command to the terminal works just fine...

I have a feeling the mcdisplay "does not know where to send stdout". A solution would of course be to call these commands via an independent terminal - but I would prefer we find a line-oriented solution from within mcgui.

@climbcat will you have a look? :-) 

The issue is that on the other hand it seems not to block on Linux... But hangs for a while.... So we might have to sit together to really debug this...

**Comment by climbcat** [comment]
Absolutely, I'm on it!

**Comment by climbcat** [comment]
I have "improved" the calling of subprocess through a hopefully more rigorously implemented proxy method, placed in mccode_utils. But I need access to a macOS system to test it. However, mcdisplay does know where to put stdout, namely, subprocess.PIPE. So if it is chained properly in the popen-call-to-python-to-popen-to..... etc., it should have a nice pipe to put it it. 

Note that cwd is NOT passed from mcdisplay to the underlying pipe running the mcrun --trace call.

In a related observation, it seems that PtQt4 messes with the process that popen creates, making it appear to have terminated while it really hasn't. This causes an issue where the help text of mcdisplay-pqtg is printed when its window is closed.

We may not be using sub processes correctly - maybe we could try python-daemon (on the unix's).

Finally, it would not be that hard to simply call all of the python tools programmatically. We don't need to go through the terminal, but could simply call the needed code lines directly. Most of it is nicely organized in classes, and this could be elaborated as needed. We would then preserve the terminal-based tools for actual terminal usage.

**Comment by willend** [comment]
Hi there - improvements do not help here - at all... :-) Now mcrun also hangs mcgui... :-D

I think I might roll your latest commits back and see what I can figure out myself...

**Comment by willend** [comment]
Ooops, wrong - your latest commits DO work better, my issues here seem to be with a specific couple of instruments...  More info later

**Comment by willend** [comment]
Hi there,

One of the instruments that seem to cause some headache for mcgui is this one (I see the problem on both macOS and Linux):

* The instrument is Union_demonstration_absorption_image
* It outputs all kinds of extra output, see the text file below captured by a mcrun instrument > stdout.txt command (one could argue 'junk', but this is relevant info in this type of simulation - and our tools need to somhow tolerate "anything" of this sort... :-) )
* It does run OK in the terminal using mcrun and mcdisplay
* It becomes stuck when run from within mcgui - list line I see in the interface is <pre>PowderN: Al_Powder: Reading 26 rows from Al.laz</pre>

You can have a look if you want @climbcat but it might be a better task for the next time we are in the same room? :-) 
(BTW I am at DMSC today - don't know if @ebknudsen is at DTU, where will you go yourself @climbcat ? :-) )

[stdout.txt](https://github.com/McStasMcXtrace/McCode/files/731699/stdout.txt)

**Comment by willend** [comment]
Another observation is that the simulation seems stuck also, the data files are never written.

- And this is irrespective of being run through mcrun.pl or mcrun python
- So I have a feeling the simulation somehow through our various "redirects" of stdout can no longer write its output anywhere

**Comment by climbcat** [comment]
I'll try to write some debug code to monitor what comes out of the mcrun pipe from mcdisplay to the simulation process, but other than that I'm out of ideas.

**Comment by willend** [comment]
I think the general issue has been addressed but have 1-3 specific instruments that fail. Will describe as specific issues.
