### ISSUE TITLE
pyqtgraph mcplot: Only read "ctrl-click" data (for scan plot) once needed

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#389]
Hi,

Have a look at the attached scan data set, which is really slow to load... :-) Of course the datafiles beneath in the subfolders are a bit big, but the load should not take as long as this...

I propose we only read data once they are necessary to generate a given plot, i.e. only read the subfolder monitor data once meta-click has been clicked...

[Files are here](http://tmp.mcstas.org/ToAddaptforBFly_1_20170127_140125.zip)

**Comment by willend** [comment]
@climbcat will you have a look? :-)

**Comment by climbcat** [comment]
Yes:) Yeah, it's pretty slow to load! We do currently load all files at startup. On-the-fly data loading for sweep folders it is. I'm going to have to restructure parts of the code, so there is a risk of the introduction of bugs in the process.

**Comment by climbcat** [comment]
Deferred loading has now been implemented in the mcplot data loader, and is automatically applied to all data nodes from now on. (Except the sweep headers, which are set manually, because they can not be loaded individually without complication, and this data is by definition orders of magnitude smaller than the regular data.) The data set of ~480 files should load much faster now, as it does on my system.

**Comment by willend** [comment]
Looks much better now, closing

**Comment by willend** [comment]
I don't know if it is a side-effect of the restructuring or it is the same issue @ebknudsen reported earlier, but it is clear tha meta-clicking loads the wrong underlying data. Will upload example dataset(s) later.

**Comment by willend** [comment]
Have a look at the attached data which is a scan dataset

1) Overview plot:
![mcplot_2](https://cloud.githubusercontent.com/assets/8593355/22423319/53467fe4-e6f1-11e6-8ebe-d07b3c36c003.png)

2) First issue: The plots do not occur in the same order as they are column-wise defined in mccode.dat / appear in mccode.sim

3) Second issue: Ctrl-clicking PSD_sample_I (top row, farthest to the right) brings up data from l_mon_source:
![mcplot_3](https://cloud.githubusercontent.com/assets/8593355/22423380/a631c362-e6f1-11e6-9cee-4dcac3cf7746.png)

Demo dataset available here:
[PSI_DMC_20170130_133448.zip](https://github.com/McStasMcXtrace/McCode/files/738898/PSI_DMC_20170130_133448.zip)

**Comment by climbcat** [comment]
Yes, it could be that a bug messes up the order of objects at some point. Looking into it.

**Comment by climbcat** [comment]
There is a bug in the order of data when it is constructed by the loader. This issue is unrelated to that, however. It is also not loading data files more than once (Eriks issue). It is just messing up the order of references in the data graph.

**Comment by climbcat** [comment]
This should be closed:-)

**Comment by willend** [comment]
Agreed
