### ISSUE TITLE
Speed / responsiveness input on the .py tools from Niko Tsapatsaris, ESS

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#391]
Received the following input from Niko Tsapatsaris, based on a build from ~ Jan 25th, so e.g. 3) is probably slightly better already.

Will post his instr model here later so that we can reproduce and do something... :-) His OS is macOS Sierra

<pre>
Hi Peter,
 
I am experiencing some issues with this version.
 
1)       I cannot edit the mcstas file through the python gui once the simulation started or the plotter is enabled
2)       Once the plotter is on I cannot run another simulation or do anything with mcstas
3)       The plotter is really heavy . My computer basically hangs and I wait for 1-2 minutes between zoomed in zoomed our versions fo the plotter.
4)       I am forced to stop the python 3 task as activity monitor says not responding.
5)       Once I exit the plotter the rest of the gui including the python editor runs fine
 
Do you have any suggestions on this. I think this is solely related to the python gui/plotter as the simulation backend and data look fine.
 
I really need to use it tomorrow as I am working on simulations otherwise I will work on Esko’s computer…
 
Thanks a lot Peter
Niko
</pre>

**Comment by willend** [comment]
For the backgrounding 1), 2) and 5) above I think there is no way around using subprocess.call in place of subprocess.popen... Let's maybe discuss all of this tomorrow @DTU @climbcat ?

**Comment by willend** [comment]
For discussion: maybe simply allow to run subtools with their own terminal...

Windows: via batch
Linux, e.g. xterm -e
Mac OS is unfortunately like this: http://stackoverflow.com/questions/989349/running-a-command-in-a-new-mac-os-x-terminal-window

**Comment by climbcat** [comment]
The mcplot process call through run_subtool is blocking. We can use another call, in which case we might get portability issues again. 

Running in its own terminal creates an intire terminal, and also portability issues.

I suggest running the sub tools properly and doing it right once and for all, by starting them programmatically through python. IMO it's the right way to do it:  The solution is portable, you get all messages (with a replacement of "print" to "print_cb" and a setter for that, in subtools) to go where you want them, you don't get weird thread/blocking issues. You could probably even run Mads' instrument out of the box...;)

**Comment by climbcat** [comment]
I have made the call non-blocking, but also without communication. We could make it responsive and with communication by running it in a thread.

**Comment by willend** [comment]
I belive this one can be closed after todays working together @climbcat :-)

**Comment by climbcat** [comment]
Yes, good work:-)
