### ISSUE TITLE
Mcplot backend: Fix the order of data loaded from files in the plot data graph

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McCode#392]
Data isn't loaded in the correct order, nor is the order matched correctly when loading scan sweep data.

**Comment by climbcat** [comment]
It looks like some sweeps repeat the y-variable in the mccode.sim file. This y-variable would be a component name. So, it looks like more than one data file can be associated with the same component (e.g. PSDrad and PSDrad, where one of the files also has the suffix "_av").

What data file should in general be assigned to the first / second / n'th... instance of the same y-var? @willend We won't get this right every time.

**Comment by willend** [comment]
Ah, you are talking about e.g. 
<pre>yvars: (Ldetector_I,Ldetector_ERR) (PSDrad_I,PSDrad_ERR) (PSDrad_I,PSDrad_ERR) (detector_I,detector_ERR)</pre>
and
<pre>variables: r Ldetector_I Ldetector_ERR PSDrad_I PSDrad_ERR PSDrad_I PSDrad_ERR detector_I detector_ERR</pre>
as it occurs in a mccode.sim corresponding to a scan? (That also correspond to the vyars indicated in the mccode.dat datafile

I would instead use the order the filename: labels occur in the mccode.sim file of e.g. the 0'th folder - these filenames are unique and also correspond to the order of the columns in the mccode.dat scan sweep datafile.

If this is still confusing, lets discuss it tomorrow.

**Comment by climbcat** [comment]
Ok. No, thank you, I hope that we will never talk about this again:-)

**Comment by willend** [comment]
:-D

**Comment by climbcat** [comment]
Hate to keep going, but actually, "the order the filename: labels occur in mccode.sim [of subfolders]", does not correspond to the "order of the columns in the mccode.dat scan sweep datafile". 

mccode.dat sweep root file: 
`# variables: lambda Ldetector_I Ldetector_ERR PSDrad_I PSDrad_ERR PSDrad_I PSDrad_ERR detector_I detector_ERR
`

.../0/mccode.sim:
```  filename: PSD.dat
  filename: Edet.dat
  filename: psd2.dat
  filename: psd2_av.dat 
```

How should these be matched?

**Comment by climbcat** [comment]
Actually, this would be a bug in mcrun, that the order isn't matching. I'll have a look.

**Comment by willend** [comment]
mcrun <b>should</b> (but may not) pick these up by the order they produce this type of Deterctor: output in each sim step... 

<pre>
Detector: Histograms_I=5.90601e+15 Histograms_ERR=6.54923e+13 Histograms_N=999884 "Histograms_1485874246.E"
Detector: Histograms_I=5.90601e+15 Histograms_ERR=6.54923e+13 Histograms_N=999884 "Histograms_1485874246.L"
Detector: Emon_I=5.90601e+15 Emon_ERR=6.54923e+13 Emon_N=999888 "E.dat"
<E> : 20.5602 meV , E-width : 24.4761 meV 
Detector: Lmon_I=5.906e+15 Lmon_ERR=6.54923e+13 Lmon_N=998493 "L.dat"
</pre>

We could in principle pick up the filenames directly from there and put them in the "upper" mccode.sim scan file?

**Comment by climbcat** [comment]
Right. I have debugged it, and the order of the "filename:" labels as they appeared in a scan point sim, was equal to what they were in mcrun, before a sorted() call was performed. I have removed the sorted call, and it looks much better. In the loader, the order of the monitor files are read from the "filename:" labels. So now, the two should match, I hope.

**Comment by willend** [comment]
Excellent, I will have a look later

**Comment by willend** [comment]
Seems to me you nailed it @climbcat, closing - @ebknudsen could you rerun the instr you had issues with as the order of plots was related to a bug in mcrun also?
