### ISSUE TITLE
Issues with FermiChopper from Ryoichi Kajimoto (J-PARC) (half-solved)

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#394]
Bug report from J-PARC:
___________
<pre>
Dear Peter,
I have two questions about FermiChopper.comp in McStas 2.3.
We have been simulating neutron intensity for a time-of-flight Fermi chopper spectrometer 
when the Fermi chopper slits are coated by supermirrors. However, when I recently tried to 
use McStas 2.3, I found that the result does not reproduce the old one by McStas 1.12c. 
The intensity at sample is too low, and it seems to me as if the supermirror does not work.

The supermirror should increase the neutron intensity especially at low energy. Indeed, the 
result by McStas 1.12c shows an expected result, but the result by McStas 2.3 does not.

Then, I transported FermiChopper.comp in McStas 1.12c to McStas 2.3 and compared the 
results from the two FermiChopper.comp. I found that both the versions give almost the same 
results when the supermirror is disabled. However, when the supermirror is enabled, they show 
different results. I also found that the supermirror "does" work even in FermiChopper.comp in
McStas 2.3, but the spatial distribution of the transmitted neutrons is different from that 
produced by the McStas 1.12c component.

I would appreciate if you can tell me which version of the component is reliable. According to 
our "real" experiment, I have an expression that McStas 1.12c component produces more
 realistic result. If you want, I can send you the simulation sources and results.

The other question is less serious: about the rotating direction. According to the explanation 
of "nu" in the source code of FermiChopper.comp, "Positive value corresponds to a clockwise 
rotation from X towards Z from above (y>0)." I understand that in the standard coordinate 
system of McStas, rotation from +Z to +X (anticlockwise) is positive. Is the definition used in
FermiChopper.comp is different? When I give a positive "nu", then the transmitted neutrons 
shows an asymmetric spatial distribution in which the intensity at +X is a little higher than 
that at -X. It seems to me that Fermi chopper rotates anticlockwise...

I'm sorry for bothering you, but I would appreciate your help.
Best wishes,
Ryoichi
</pre>

**Comment by willend** [comment]
@farhi if you have just a little time, it would be great if you had a look - most of the changes to the comp in question since 1.12c are "yours" ;-)

**Comment by willend** [comment]
Communication with Ryoichi:
<pre>
Dear Ryoichi,


Again, sorry for being late in responding - I finally managed to have a good look at the component (and had discussions with Emmanuel and Erik, both cc:) 

Discussing your second point first, you are completely right: 
	The component documentation is wrong on the point of direction of rotation, it is indeed rotating counter-clocwise which is btw what we typically expect in McStas. This was fixed in 2.4 which was just released.


On the first point about the supermirror slit-package, the story is a lot more complex:

1) When NOT using a supermirror slit-package, the component seems to work OK and is in agreement our other possible implementations (see Test_Fermi.instr in your distribution, also attached here.)

2) We also observe a disagreement in the transported intensity between the 1.12c and 2.3/GitHub versions. Some of this can be explained by only the slit-package being coated in the new version, whereas the inner walls of the “drum” were also coated in 1.12c. 

3) Erik tried looking at the reflectivity profiles from a stationary chopper slit-package with only one slit. The curves in the two cases are of identical shape, see attached graphic.

4) I myself tried testing the FermiChopper (in both versions) in use as a Guide - i.e. stationary and with only one (or 3) slits. The transmission looks quite stange and not like the rectangular guides. On the other hand it looks equally bad for the 1.12c and current versions of the component. See attached graphic with 8 color plots. The 6 top ones are for our rectangular guides, the “round” one is four our “honeycomb” shaped guide and the last one is for  the FermiChopper. 

In conclusion I belive neither of the versions can actually be trusted when using the supermirror slit package…!


As we have been waiting very long for the release of 2.4 I have decided not to clear this up before - but we will sort it out during the summer.

In the meantime I propose we take a look at the solution of using the components Rotator and Derotator around an assembly of 3 guide pieces, where the Rotator should be placed centrally wrt. a Guide_chanelled, acting as a supermirror slit-package. This will of course only be a 1st order approximation, since the guides will be stationary for each individual neutron, but for neutrons of not too lang wavelength this approximation should be good.


All the best,

Peter Willendrup
</pre>

![fermi_chop_i_vs_angle](https://cloud.githubusercontent.com/assets/8593355/26246095/9e491cf8-3c97-11e7-8626-3db5b9445813.png)
![18491370_10210433315362404_5516134366799635087_o](https://cloud.githubusercontent.com/assets/8593355/26246098/a0fb3b5c-3c97-11e7-8edd-a2366d25b063.jpeg)
[Test_Fermi.instr.txt](https://github.com/McStasMcXtrace/McCode/files/1014020/Test_Fermi.instr.txt)

**Comment by willend** [comment]
Looking at this again, here is a comp (ported from 1.12c) and an instr:

[FermiChopperOld.comp.txt](https://github.com/McStasMcXtrace/McCode/files/2621991/FermiChopperOld.comp.txt)
[Fermi_still.instr.txt](https://github.com/McStasMcXtrace/McCode/files/2621992/Fermi_still.instr.txt)

Running that instrument to look at transmission through a guide, the new and old fermi sitting still with the same reflectivity parameters yields  - and 10 channels gives

Guide:
<img width="1119" alt="screenshot 2018-11-27 at 23 02 22" src="https://user-images.githubusercontent.com/8593355/49114446-87143780-f298-11e8-8e1d-85e01fc98a4d.png">


New fermi:
<img width="1119" alt="screenshot 2018-11-27 at 23 02 55" src="https://user-images.githubusercontent.com/8593355/49114484-9b583480-f298-11e8-8f0e-bcb09b41132b.png">


Old fermi:
<img width="1119" alt="screenshot 2018-11-27 at 23 03 24" src="https://user-images.githubusercontent.com/8593355/49114529-b034c800-f298-11e8-8ce9-d34bfa696bcf.png">

**Comment by willend** [comment]
It is clear to me that the old parametrisation is closer to that of the Guide_channeled.

Considering to use ported 1.12c component with new parameter names since clearly something got lost in translation...

@farhi what do you think about this long standing story

**Comment by farhi** [comment]
Hi @willend and @ebknudsen ,

Basically, both versions discussed above use the same logic and intersection/propagation functions, so the 1.12c has all what is needed. The commit 573abb9a0d20e4643ae3ca610e90270b593e5df3 indicates that there was a bug fix in intersection, and most of the changes are there.

So I would recommend to test with the version from May 15, 2013, before these changes to see if the odd transmission originates from that point.

**Comment by willend** [comment]
With baa939256216d16a0fcab101c8351e77f71b086e the output now looks like this in the above test:
![screenshot 2018-11-28 at 12 45 42](https://user-images.githubusercontent.com/8593355/49149928-bd3ecf00-f30b-11e8-9a54-37261b9b40a2.png)

Much better I think. I believe this should be enough to close this issue
