### ISSUE TITLE
mccodelib mcdisplay parser - put limit on # visualised neutrons

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#396]
Common limit for pyqtgraph and webgl mcdisplay's at first 1e3 neutrons (Issue warning to terminal and ignore trailing data)

**Comment by climbcat** [comment]
This has been implemented, but how to kill a process in Python... I may have to pass this one on...

**Comment by willend** [comment]
Roger, I shall have a look

**Comment by climbcat** [comment]
They say that when we run a popen with shell=True, the "real" process we must close is a child process of a shell. So we have to deal with both somehow.

**Comment by willend** [comment]
My guess we can use os.killpg() as suggested here:
http://stackoverflow.com/questions/6549669/how-to-kill-process-and-child-processes-from-python

**Comment by climbcat** [comment]
Using os.getpgid(pid) with Popen.pid and os.killpg() did the job, it killed the required process... but my session also crashed... I don't think that solution is satisfactory.

**Comment by willend** [comment]
This was fixed with 0dce67d7c507b760cfa8d92f17e5fa14b4986074
