### ISSUE TITLE
"right click" doesn't work in mcplot

### ISSUE THREAD

**Issue by ajj** [McStasMcXtrace/McCode#404]
Testing 2.4rc58, OS X 10.11.6

In mcplot, clicking on subplots to enlarge works. "right clicking" i.e. Ctrl-click does not seem to work to return to the multiplot view.

**Comment by willend** [comment]
OK. Here right-clicking works, i.e. using a multi-button mouse or after configuring the trackpad to have a "right click" option in the lower right corner... 

Will test to see how control-click works when this is set up as standard. We might also simply add a keyboard shortcut of 'b' for 'back'

**Comment by climbcat** [comment]
Hej Peter 

Hvis det er ok med dig, så ses vi på dtu i morgen torsdag - jeg er sneet delvist inde herude, har hovedpine og meget andet. Kæmper lidt med logistikken i det her vejr:)

Jakob.



________________________________________

**Comment by climbcat** [comment]
So far, I have enabled the keyboard shortcut 'b' for 'back'.

**Comment by willend** [comment]
B for back seems to work here, plus secondary click via mouse or configured trackpad
