### ISSUE TITLE
mcpl component doesn't put output in output directory

### ISSUE THREAD

**Issue by ajj** [McStasMcXtrace/McCode#406]
The mcpl component does not put its output file in the same directory as all the other component output, even if -d is used on mcrun command line

Thus if you run more than one simulation, the mcpl output is overwritten. If you run more than one simulation simultaneously, it fails since two processes are trying to write the same file.

**Comment by willend** [comment]
@ebknudsen would you have a look?

**Comment by ebknudsen** [comment]
done
