### ISSUE TITLE
Scientific notation on mcplot labels Intensity and Error labels

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#409]
Could we get 7.253e10 instead of 72530000000 - would be a lot easier to read :-) Just for the I and E parts, the Ncount is an integer and should be treated as such.

Just a matter of string formatting I guess?

![mcplot](https://cloud.githubusercontent.com/assets/8593355/23207236/e7fa4cea-f8f0-11e6-9ca9-d494ac96a2e5.png)

**Comment by climbcat** [comment]
Yes, should be hope so.

**Comment by climbcat** [comment]
It is possibly better now, could you test the change?

**Comment by willend** [comment]
With yesterdays changes and one last hickup (4ae6d06..5c582ea) fixed, this now looks good. :)
