### ISSUE TITLE
mxdisplay: call McStas to generate c

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#410]
mxdisplay (pyqtgraph version) tries to call McStas to generate c-code. This obviously doesn't work. :-)

**Comment by climbcat** [comment]
Ok cool, how about the webgl version? Is it working properly?

**Comment by ebknudsen** [comment]
It would appear no, but it fails in a different way.

**Comment by climbcat** [comment]
That sounds invonvenient. It has worked before, right?

An unrelated fix for all mcdisplays is being uploaded shortly, by the way.

**Comment by ebknudsen** [comment]
line #30 in mcdisplayutils.py has a hardcoded 'mcrun'. This is likely the cause no?

**Comment by willend** [comment]
@ebknudsen I guess this on has been fixed, no?

**Comment by ebknudsen** [comment]
fixed
