### ISSUE TITLE
Small (~ish) bug at contrib. comp. Source_gen4

### ISSUE THREAD

**Issue by emmarant** [McStasMcXtrace/McCode#412]
Line 211, first line of the initialise section:
> Lambda0=0;
should be removed. It clears away the assigned (by the user) value, and later the component fails to pass the test of positive wavelength range.

Also, the declaration of above parameter on line 190 is redundant. 

Thanks!

**Comment by willend** [comment]
- Fixed @emmarant :-) and thanks 👍
