### ISSUE TITLE
Visible z-ranges for each component in the mcdisplay --tof mode

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#414]
e.g. on the Z axis:

zmax gets ---
AT gets solid line
zmin gets ---

**Comment by willend** [comment]
I think this one makes very little sense for anyone else @climbcat

**Comment by willend** [comment]
Also please make --tof available by --TOF and --ToF also

**Comment by willend** [comment]
... And neutrons all visualised by same colour, with x or o markers

**Comment by climbcat** [comment]
This has been implemented.
