### ISSUE TITLE
mcdisplay-pyqtgraph --TOF bug: h/F1 does not bring up the component list

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#418]
The terminal echoes

<pre>
Traceback (most recent call last):
  File "/Applications/McStas-2.4rc79.app/Contents/Resources/miniconda3/lib/python3.4/site-packages/pyqtgraph/widgets/GraphicsView.py", line 181, in keyPressEvent
    self.scene().keyPressEvent(ev)  ## bypass view, hand event directly to scene
  File "/Applications/McStas-2.4rc79.app/Contents/Resources/mcstas/2.4rc79/bin/../tools/Python/mcdisplay/pyqtgraph/mcdisplay.py", line 367, in _key_handler
    self.iw = create_infowindow(self._get_comp_color_pairs())
  File "/Applications/McStas-2.4rc79.app/Contents/Resources/mcstas/2.4rc79/bin/../tools/Python/mcdisplay/pyqtgraph/mcdisplay.py", line 383, in _get_comp_color_pairs
    for idx in range(len(self.instr.components)):
AttributeError: 'McDisplay2DGui' object has no attribute 'instr'
</pre>

**Comment by climbcat** [comment]
Hej Peter 

I forbindelse med disse TOF bugs, er der andre ændringer du kan få øje på til mcdisplay-tof der ville være rare at indføre?

J.
________________________________________

**Comment by willend** [comment]
Will think about that. :-) First thought brings to mind:

1) Common for both the "TOF" og 2D modes: Put neutron colour til something "non-white" since SVG has empty background => neutrons become invisible. Maybe something like a 50-70% gray, i.e. [0.5 0.5 0.5]-[0.7 0.7 0.7] which likely becomes visible on both black (screen/png) and white (svg)

2) In the TOF case I get a strange warning message when exporting to svg, but the generated file seems OK:
<pre>
QPainter::deviceTransform: Painter not active
QPainter::deviceTransform: Painter not active
QPainter::deviceTransform: Painter not active
QPainter::deviceTransform: Painter not active
QPainter::deviceTransform: Painter not active
QPainter::deviceTransform: Painter not active
QPainter::deviceTransform: Painter not active
QPainter::deviceTransform: Painter not active
QPainter::deviceTransform: Painter not active
QPainter::deviceTransform: Painter not active
QPainter::deviceTransform: Painter not active
QPainter::deviceTransform: Painter not active
....
</pre>

**Comment by climbcat** [comment]
Should have been fixed now.

**Comment by willend** [comment]
Confirmed, closing
