### ISSUE TITLE
mcdisplay-mantid_xml packaging / inclusion in meta-packages 

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#419]

**Comment by climbcat** [comment]
Hej Peter 

Har du testet mantid-xml, og virker den i så fald tilfredsstillende?

VH
Jakob



________________________________________

**Comment by willend** [comment]
Hej,

Det står endnu på min liste, jeg opretter mig lige et matchende issue…

P
On 9 Mar 2017, at 11:21 , Jakob Garde <notifications@github.com<mailto:notifications@github.com>> wrote:

Hej Peter

Har du testet mantid-xml, og virker den i så fald tilfredsstillende?

VH
Jakob



________________________________________

**Comment by willend** [comment]
Hi @climbcat,

0) Found a div/0 which now has protection since 71580841fb2882f7fb3b5daf085a695e953850d3.

1) Also found another little something that needs fixing:
* The xml file should always be written to instrumentfile.instr.xml

2) The generated HDF files all load which is a good step!

3) The rectangular detector seems OK

4) The "pixel"/OFF-file geometry detector seems OK

4) Something is wrong with the detector shape in the cylindrical case, will have a closer look

**Comment by climbcat** [comment]
Hej Peter. 

Ok!

Jeg er ved dmsc lige om lidt. Så kan vi måske kigge på den cylindriske. 

J. 
________________________________________

**Comment by willend** [comment]
Hejsa,

Den tror jeg nok jeg fiksede for lidt siden… :-) Jeg havde desværre glemt at du ville komme herud i dag, så jeg har arrangeret at hente Magnus… :-( Så jeg skal gå lige om snart…

Peter

On 9 Mar 2017, at 14:34 , Jakob Garde <notifications@github.com<mailto:notifications@github.com>> wrote:

Hej Peter.

Ok!

Jeg er ved dmsc lige om lidt. Så kan vi måske kigge på den cylindriske.

J.
________________________________________

**Comment by willend** [comment]
Looks as if these are packaged OK - only the thorough output file testing remains
