### ISSUE TITLE
mcgui (py): Update the list of available mcdisplay tool variants in mccode_config (and related .in)

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#420]
One thing that we should probably think about is that the mantid xml output is not relevant for McXtrace... @ebknudsen do you have a point of view?

**Comment by climbcat** [comment]
How will the mantid_xml tool be named?

**Comment by willend** [comment]
I've named it mcdisplay-mantid

**Comment by willend** [comment]
I have made modifications in the config files that enable the --mantid callbacks, plus defined separate tool lists for McStas and McXtrace in 9843b1d330e3c155c0bc941937d1a7c49c447327. Closing
