### ISSUE TITLE
McStas: Source_div reduces "intensity density" with larger divergence window.

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#424]
Reported by Leland Harringer (NIST) 
There is a bit of strange behavior when I use the McStas source ‘Source_div()’. Namely, I place a monitor a small distance away from the source and then specify the source divergence such that the monitor is fully illuminated. I read out the total intensity.  I then begin increasing the divergence even more such that the monitor becomes increasingly over-illuminated. My expectation is that I will need longer count times to maintain the same statistics on the monitor (which I find to be true), but the total intensity should remain constant. This ends up not being true. I get a 4.2% reduction in intensity when I go from a 15 degree window to a 60 degree window, even though both of these windows overilluminate the acceptance of the monitor. I have attached a figure (Divergence_focusing.png) showing this, along with the instrument file I used (Source_div_Brilliance.inst). Why would I get this reduction? Is this a normalization bug, or am I missing some detail?

 
![divergence_focusing](https://cloud.githubusercontent.com/assets/855956/23769108/8f5a8e7c-050e-11e7-8b58-dcaca7a7d13c.png)

**Comment by ebknudsen** [comment]
Here's the instrument file

[Source_div_Brilliance.txt](https://github.com/McStasMcXtrace/McCode/files/832218/Source_div_Brilliance.txt)

**Comment by ebknudsen** [comment]
Done some testing today - it appears to be sensitive to which divergence direction is emitted.
The intensity drops with increasing overillumination in the vertical direction whereas it remains constant for an increase in the horizontal direction.

**Comment by willend** [comment]
Thanks for that @ebknudsen - I am considering if this could be one of the ones we leave for after 2.5 as it is a (relatively) small effect
