### ISSUE TITLE
Test packages and meta-packages for Windows / Linux from Mac "template"

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#425]
1) build_macos_mcstas -> corresponding for Deb, RPM, ...

2) Update metapackages 
- Deb: meta-pkgs/deb/control-* should be edited to include the above built packages
-- VM with Ubuntu 16.10
- RPM: meta-pkgs/rpm/*.spec
-- VM with CentOS 7? ("EPEL" repository is probably key...)
- Windows: meta-pkgs/windows/*.iss
-- Windows 10 + "native" (32 bit) packages
-- Windows 10 + WSL to run the Debian packages (Look at front page of mcstas.org - "Use Microsofts "Windows subsystem for Linux" for running McStas under Windows 10")

3) Document as you progress... - Check how out of date http://www.mcstas.org/download/install_linux/  and http://www.mcstas.org/download/install_windows/ are

**Comment by climbcat** [comment]
![img_0222](https://cloud.githubusercontent.com/assets/11196009/23907619/0324acb8-08d2-11e7-8769-60b631576afe.JPG)

**Comment by climbcat** [comment]
Windows: 

- conda commands (post-install) do not run themselves during installation
- downgrading anaconda 3.6 to python 3.4 takes quite a long time (this possibly wont take as long on a native system)
- gcc and openmpi can not be added via conda 3.6 or requires an additional channel

**Comment by climbcat** [comment]
windows hangs during downgrade to py3.4 (20 mins)

**Comment by climbcat** [comment]
centos: 

sudo yum install python34 python34-ply python34-numpy

- pyqtgraph does not exist as a package, download source and run
sudo python setup.py install

- unable to get qscintilla and PyQt4 bindings for python3, base packages are 
sudo yum install PyQt4.x86_64 qscintilla-python.x86_64

**Comment by willend** [comment]
For CentOS et al I belive we could package this miniconda3:
http://support.mccode.org/rpm/miniconda3.tgz
as an RPM, depend on it at be done.

**Comment by willend** [comment]
Closed with b95e5e51 and results from the workshop @ ISIS last week
