### ISSUE TITLE
Increase maximum comp list length 

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#433]
To allow til MACS model from Mads Bertelsen to be included

**Comment by willend** [comment]
@mads-bertelsen this one is now closed - would be happy to get a copy of your MACS instrument? ;-)

**Comment by mads-bertelsen** [comment]
Off course, I just have to update it to the current syntax and combine the front / backend to one instrument. Will upload when I find the time to complete these tasks.
