### ISSUE TITLE
sample Sans_spheres default values

### ISSUE THREAD

**Issue by lindaudby** [McStasMcXtrace/McCode#443]
The sigma_abs parameter default value is 0.5 m-1 which is sufficiently high that no scattered signal is visible on detector without a beamstop (or focus only on sample). Since the sample is often used for quick McStas demonstration purposes it may be a good idea to set the default value sigma_abs=0.05.

**Comment by climbcat** [comment]
This instrument needs to be recompiled manually with some special flags and/or mcstas version, and I do not remember exactly how this is done.
