### ISSUE TITLE
Single_crystal component manual docs revision

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#445]
Docs currently lists things like

"The component is currently under further review. The current documentation is outdated, especially with respect to the model of crystal mosaicity."

**Comment by ebknudsen** [comment]
Here's a list of features that sould be documented (TODOc):
1. the split_count feature and what it does
1. the two anisotropic mosaicity modes
1. the powder mode
1. curved crystal mode, and the limitations of this model
