### ISSUE TITLE
mcgui: Typing "q" in the edit window

### ISSUE THREAD

**Issue by mducle** [McStasMcXtrace/McCode#447]
In the edit window in `mcgui` typing the letter "q" brings up the `quit` dialog (the letter is correctly entered but the dialog has to be closed before further editting happens). This makes it difficult to write instrument files as "q" is is used for wavevector, etc.

The `quit` dialog also pops up if "Q" is typed (uppercase).

**Comment by willend** [comment]
Confirmed - on all platforms...

**Comment by climbcat** [comment]
Fixed :) - q should indeed be available in any editor.

**Comment by mducle** [comment]
Confirmed fixed.

**Comment by willend** [comment]
👍 Yup, works
