### ISSUE TITLE
Update (internal) instr names in Union instruments

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#454]
Hi @mads-bertelsen,

Could you please give unique names (i.e. not all "test") in your Union example instrs? Currently, most are simply
<pre>
DEFINE INSTRUMENT test(...)
</pre>

Best,
Peter

**Comment by mads-bertelsen** [comment]
Hi @willend,

I did start updating the test instruments, but realised the openings were a rougher than I remembered. I am updating and verifying all Union related example instruments works properly and have reasonable comments.

Best regards,
  Mads

**Comment by willend** [comment]
Sounds good. FYI we will release end of may.

**Comment by mads-bertelsen** [comment]
Made a pull request with updates that should solve the issue. Thanks for the heads up on release schedule!

**Comment by willend** [comment]
Thanks!
