### ISSUE TITLE
Py mcdoc list of stuff

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#456]
* (some??) Iinks from comp / instr page to "source" includes double "cathegory" source/source...
* Include directories under contrib/ (e.g. Union) in contrib comp search
* Enable mccode_config configuration and use that for
** PDF links
** "deep-link" to McStas installation dir (wherever MCCODE_LIB_DIR points to), next to PDF links

Behaviour:
mcdoc input_parms can give 2 different scenarios:

1) If . is given traverse that path, generating docs with user privs -> mccode.html
 (The above could also be used at install time by root mcdoc $MCCODE_LIB_DIR generates a set of "system" docs > $MCCODE_LIB_DIR/mccode.html)

2) Otherwise generate a mccode.html in a temporary folder, including creation of cathegory dirs. In those dirs, generate html files corresponding to what can be found in $MCCODE_LIB_DIR + local files. If pattern is given as input parm, filter results by that.

In all cases, open resulting mccode.html via start/open/xdg-open....

**Comment by climbcat** [comment]
Most of the remaining stuf for mcdoc has been implemented, and the behavior is described in --help.

"Local components" section in the overview page has not been implemented, although local component are parsed (and have their individual docpages written) if the user actively selects this directory by means of --crawl=<somedir>.

**Comment by willend** [comment]
@ebknudsen you and I need to give @climbcat some feedback here

**Comment by willend** [comment]
Duplicate of 571
