### ISSUE TITLE
mcgui: run dialogue tickmark for "autoplot"

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#458]
Should be easy to do: 

Add a tickmark option to get 

mcrun simulation.instr --autoplot

(a mcrun python only feature, but let's simply add it to "simulation" runs)

**Comment by climbcat** [comment]
The --autoplot flas has been added to the runstring from mcgui, but it does not work. The string produces an autoplot when executed in the terminal.

We could change the way mcrun calls its plotter subprocess (it should wait for its child process to terminate), or reimplement --autoplot in mcgui.

**Comment by willend** [comment]
Will have a look later myself 😊

Get Outlook for iOS<https://aka.ms/o0ukef>
_____________________________

**Comment by willend** [comment]
Did you do anything more to this @climbcat - it works nicely here (in a fresh ./build_macos...)

**Comment by willend** [comment]
Could you maybe "gray out" the tickmark if Trace is used?

**Comment by willend** [comment]
Also works fine on Ubuntu here. One detail that I'll have a look at is "backgrounding" the mcplot call from mcrun - otherwise the mcrun looks "busy" still from the POV of mcgui.

**Comment by willend** [comment]
... and also works on Windows 10

**Comment by willend** [comment]
Closing, works just fine :-)

**Comment by climbcat** [comment]
Ok :) And yes will gray out if trace
