### ISSUE TITLE
mcplot-pyqtgraph on Ubuntu 14.04 (and earlier?): python3-pyqtgraph dependency missing

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#471]
@farhi reports this issue - and workaround:

* mcstas-tools-python-mcplot-pyqtgraph-2.4 requires python3-pyqtgraph which is not available under Ubuntu 14.04. Logically, the mcstas-suite-python is not installable.

* Solution for Ubuntu 14.04:
 * I've installed the python3-pyqtgraph package from the 16.04 xenial repo <http://packages.ubuntu.com/xenial/python/python3-pyqtgraph>. Then, it is possible to install the full mcstas-suite-python package. And the pyqtgraph front-end works OK.

**Comment by AlexDG89** [comment]
Hello,
I'm using Bash on Windows and I found the same problem installing 2.4.
In Windows 10 the bash shell is based on Ubuntu 14.04 so I think can be useful to insert  this instructions in the Windows Install page

**Comment by willend** [comment]
Hi @AlexDG89,

Thanks for pointing this out, the website now lists the hint on the Windows Install page also.

Best,
Peter
