### ISSUE TITLE
configuration dialog missing after clean install 2.4

### ISSUE THREAD

**Issue by pwlink** [McStasMcXtrace/McCode#477]
I just installed on a new Virtualbox / Ubuntu 16.04 with all packages upgraded the 2.4 packages as described. I use the python gui.
Upon mcgui  I get a message that the configuration .json is missing.
Further there is no access from the gui to the config dialog.
I did already the reinstall hint - no change.

![error1](https://cloud.githubusercontent.com/assets/15047537/26307551/7870f89c-3ef5-11e7-9c7e-19790ba65516.png)

**Comment by willend** [comment]
Hi Peter,

The warning is not elegant, but "normal" and can be ignord.

Did you reinstall with
<pre>
sudo apt-get install --reinstall mcstas-pythom-mccodelib-2.4
</pre>
?
(Otherwise you probably get whatever was previously downloaded/cached on your system)

Best,
Peter

**Comment by willend** [comment]
Alternatively you may also dump this file: (changing the suffix to .py only)
[mccode_config.py.txt](https://github.com/McStasMcXtrace/McCode/files/1019130/mccode_config.py.txt)
into your /usr/share/mcstas/2.4/tools/Python/mccodelib/ folder

**Comment by willend** [comment]
Alternatively you may also dump the attached file: (renaming the suffix to .py only)

[mccode_config.py.txt](https://github.com/McStasMcXtrace/McCode/files/1019145/mccode_config.py.txt)

in your /usr/share/mcstas/2.4/tools/Python/mccodelib/ folder

**Comment by willend** [comment]
@pwlink did any of the above hints work for you?

**Comment by pwlink** [comment]
Hi Peter,

! no, on my Virtualbox Ubuntu16.04 it didn’t work. I tried besides that on my private PC at home (W10) the linux subsystem  install and there I got it reasonably working. I also did an install just for fun on a W7 laptop with the windows installers which worked also.

I can’t get the point what’s wrong with the Linux install…

I’m back to office next Monday, and may go back one step and restart the procedure again from a fresh setup of Ubuntu 17.?

Best regards, Peter  

 

Von: Peter Willendrup [mailto:notifications@github.com] 
Gesendet: Mittwoch, 24. Mai 2017 19:53
An: McStasMcXtrace/McCode
Cc: pwlink; Mention
Betreff: Re: [McStasMcXtrace/McCode] configuration dialog missing after clean install 2.4 (#477)

 

@pwlink <https://github.com/pwlink>  did any of the above hints work for you?

**Comment by willend** [comment]
Thanks for the feedback!

No point in installing a 17.04, the software was built on a 16.04. 😊

Try instead to
* sudo apt-get clean 
* sudo apt-get purge mcstas-suite-python 
* sudo apt-get install mcstas-suite-python

Best,
Peter

**Comment by pwlink** [comment]
Hi all,
just to keep you updated, why so ever: using Lubuntu 16.04.2 instead the Unity standard Ubuntu on the Virtualbox machine works! 
No point of missing menus or dialogs :) 
Tested openmpi - works :)
Tested pyqtgraph - works :) 
Still get some funny core dumps / seg faults AFTER successful execution and termination of commands from the mcgui,
can't see any reason for it!

**Comment by willend** [comment]
@pwlink thanks for the update!

I think it works on your Lubuntu because the "fresh install" means a fresh installation of the related mcstas-pythom-mccodelib-2.4 package. My guess is that purging your mcstas install on the other machine, clearing all package caches etc will also work. :-)

I did see a few crashes like what you describe - mainly from mcdisplay runs. Could you grab a screenshot / debugging info next time it occurs and @climbcat will have a look?

**Comment by pwlink** [comment]
@climbcat here we go:
[core dump.txt](https://github.com/McStasMcXtrace/McCode/files/1055320/core.dump.txt)

**Comment by climbcat** [comment]
Hi. Thanks! This may be due to a simple bug, should be fixed by a98d452365f4f467fd29b342c9bc0d9c8ad7b7ca. If you are up for it you may test this - if not, we will keep an eye out for this error in the following weeks.

**Comment by pwlink** [comment]
@climbcat 
Just tested the fix a98d452. It's fine for me!

**Comment by climbcat** [comment]
@pwlink - good to hear it.

**Comment by willend** [comment]
I belive this was resolved in the end? Closing
