### ISSUE TITLE
Exploratory: Have a look at silx (ESRF) for plotting purposes

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#489]
mcdisplay/mcplot could maybe use this "matplotlib on steroids" https://github.com/silx-kit/silx

**Comment by willend** [comment]
Has very powerful, easily accessible fitting etc. for scientific datasets, have a look here - 20 min effort to 'hack' the old matplotlib plotter to use silx instead:

![pythonscreensnapz004](https://cloud.githubusercontent.com/assets/8593355/26586928/12764e4a-4551-11e7-81ab-9e4afdf5dd23.png)

[mcplot.py.txt](https://github.com/McStasMcXtrace/McCode/files/1038561/mcplot.py.txt)

**Comment by willend** [comment]
![terminalscreensnapz002](https://cloud.githubusercontent.com/assets/8593355/26587076/909915dc-4551-11e7-9aeb-1f7fcf7d69ee.png)

**Comment by willend** [comment]
![terminalscreensnapz003](https://cloud.githubusercontent.com/assets/8593355/26587211/f782d242-4551-11e7-8ac9-66430c1b0343.png)

**Comment by climbcat** [comment]
Does indeed look powerful and specific to the needs of experimentalists!

**Comment by farhi** [comment]
Yes and this is work from Jerome Kiefer at ESRF. Good quality, efficient, interoperable with Fabio and pyFAI, with OpenCL acceleration when required.
