### ISSUE TITLE
McXtrace and McStas: PSD_monitor (and friends) nx=1 should trigger 1D

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#495]
The PSD_monitor(s) gets confused by having nx or ny=1. Its puts array_2D in the header but outputs 1D (column style) data. The plotter can't make sense of that.

**Comment by ebknudsen** [comment]
While this can easily be fixed by logic in the PSD component, should this really be fixed in the detector out subsystem?

**Comment by willend** [comment]
I think we should fix this in the detector subsystem. - A quick check on dimensions in DETECTOR_OUT_2D early on?

**Comment by willend** [comment]
(But then again, if it looks invasive to do, I'd rather leave as is until I've done a 2.4.1...)

**Comment by ebknudsen** [comment]
I've written a targeted McXtrace fix for the PSD_monitor only

**Comment by ebknudsen** [comment]
Haven't looked into the "real" fix and how complicated it'd be to fix

**Comment by willend** [comment]
OK, then leave as is and look into that after the McStas update + McXtrace releases

**Comment by willend** [comment]
Superseeded by https://github.com/McStasMcXtrace/McCode/issues/506
