### ISSUE TITLE
Saving the instrument files with simulation results

### ISSUE THREAD

**Issue by gfev** [McStasMcXtrace/McCode#496]
Good afternoon,
 
just a suggestion, not an issue. It often happens to me to change my instrument file and get new simulation results, and to often lose track of the changes I made. Have you ever considered this feature of automatically saving a copy of the instrument file together with the results? Just to be dead sure of how those results were obtained... 

Cheers,
Giovanni

**Comment by willend** [comment]
Hi @gfev, 

This is now implemented in the Python mcrun/mxrun on the main branch (i.e. will make it to McXtrace 
1.4 and McStas 2.4.1) - when a simulation results in a directory output, a copy of the instr is placed within.

Thanks for suggesting this! :-)

Best,
Peter
