### ISSUE TITLE
Pol_monitor.comp

### ISSUE THREAD

**Issue by pwlink** [McStasMcXtrace/McCode#498]
Inconsistent documentation of component:

* INPUT PARAMETERS:
*
* xwidth:   Width of detector (m). 
* yheight:  Height of detector (m). 
* mx:       X-component of monitor vector (can be negative) (1)
* my:       Y-component of monitor vector (can be negative) (1)
* mz:       Z-component of monitor vector (can be negative) (1)
* npol:     Number of channels (1)
* restore_neutron: If set, the monitor does not influence the neutron state (1)
*
* OUTPUT PARAMETERS:
*
* Pol_N:      Array of neutron counts
* Pol_p:      Array of neutron weight counts
* Pol_p2:     Array of second moments
*
* %E
*************************************************************************/

DEFINE COMPONENT Pol_monitor
DEFINITION PARAMETERS (xwidth=0.1, yheight=0.1, restore_neutron=0)
SETTING PARAMETERS (mx=0, my=0, mz=0)
OUTPUT PARAMETERS (Pol_N, Pol_p, Pol_p2, Psum, titlestring)
/* Neutron parameters: (x,y,z,vx,vy,vz,t,sx,sy,sz,p) */ 

npol does not exist: Monitor saves a single numbers not arrays

**Comment by willend** [comment]
Thanks for reporting @pwlink. I believe this component was meant to be a "polarisation equivalent" of the scalar Monitor.comp, @ebknudsen? - We just remove npol from the doc header and maybe refer the other "polarisation as function of..." monitors?

**Comment by ebknudsen** [comment]
indeed. Bug confirmed.

**Comment by ebknudsen** [comment]
fixed
