### ISSUE TITLE
no gravity from mcgui in Windows???

### ISSUE THREAD

**Issue by RichardHeenan** [McStasMcXtrace/McCode#499]
Have tried to run several instruments, none of them will work with --gravity, why??? using  McStas 2.4, Windows 7

the gui window has e.g.
start mcrun Test_Vert_Bender.instr -d C:\McStas_New\loki_2June2017\Test_Vert_Bender_20170614_122220 -n 1000 --gravity   collen=3  reardet=10  l_min=3  l_max=9.95  sourceapx=0.015  sampleapx=0.005  insertangle=0.8  pulseskip=0  sampletype=0  incohb=1e-005  gout=0  mcplout=0  windows=0  virtualout=0

the cmd.exe window has:
loading user configuration from C:\Users\rkh98\AppData\mcstas\2.4\mccode_config.json
Usage: mcrun.py [-cpnN] Instr [-sndftgahi] params={val|min,max|min,guess,max}...

mcrun.py: error: no such option: --gravity

C:\McStas_New\loki_2June2017>

**Comment by RichardHeenan** [comment]
fixed it by editing line 116 of mcrun.py to add --gravity after --gravitation  i.e.

    add('-g', '--gravitation', '--gravity',
        action='store_true', default=False,
        help='enable gravitation for all trajectories')

**Comment by willend** [comment]
Thanks for reporting (and suggesting a fix!) @RichardHeenan - will get that onto our main and development branches later today. 

(There will be a 2.4.1 or similar picking up on this and other minor issues with 2.4)

**Comment by willend** [comment]
Fixed with bc332648
