### ISSUE TITLE
Create a "monitor-lib" for the "simple monitors" (i.e. non-Monitor_nD)

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#506]
Features:
* Monitor data on the heap via malloc()
* Free call in FINALLY 

This will remedy situations where 
1) the stack is too small for the "statically defined" arrays PSD[nx][ny]
2) the user wants to dynamically change a binning

**Comment by willend** [comment]
Somewhat related to https://github.com/McStasMcXtrace/McCode/issues/495 - central DETECTOR_OUT routines should be patched to make 2D->1D fallback when nbins in one direction is 1

**Comment by farhi** [comment]
Are the Darray calls in mccode-3 an answer to this issue ?

**Comment by willend** [comment]
Yes, I think we can decide that. Closing.
