### ISSUE TITLE
Virtual_output maximum file limit 4 GB

### ISSUE THREAD

**Issue by ajulik1997** [McStasMcXtrace/McCode#516]
When running a simulation to collect neutron events via a virtual_output instrument, around 3.2e7 neutron events are saved, reaching a file size of 4.06 GB before giving the error:

> Warning: could not open output file '###' for append (mcnew_file)

Terminating the simulation via a keyboard interrupt generates this output:

![image](https://user-images.githubusercontent.com/9460842/27533766-b58d19a4-5a5c-11e7-9138-4ede7eba5720.png)

This is not due to insufficient storage space or not enough memory.

**Comment by willend** [comment]
Hi @ajulik1997,

I believe there might be a hidden, implicit limit somewhere, sorry about that. 

Virtual_output is more or less now superseeded by MCPL_output, which has been tested with files of even greater length - I would advise you to try using that instead. (As there is a stupid off-by-one problem with the 2.4 component, please pick the newest version of the component file here from GitHub, or use McStas 2.4.1 which will be out shortly.)

Best,

Peter
