### ISSUE TITLE
Slit width/height zero does not absorb neutron

### ISSUE THREAD

**Issue by ajulik1997** [McStasMcXtrace/McCode#522]
Setting a slit width or height to zero does not actually set it to zero, it falls back to {xmin,xmax,...} which are non-zero by default.

When defining a slit by its height and width only, it is a common scenario to perform a scan for slit widths including closed (0). It is obvious from the source code but not from the documentation that a slit width of zero is not possible unless defined by xmin and xmax only.

A simple fix would be to set xmin, xmax, ymin, ymax in the component definition to default to zero if not explicitly specified.

**Comment by willend** [comment]
Hi @ajulik1997, thanks for the comment. 

It can indeed be seen as problematic, but is a side-effect of the way we define (redundant) parameters in McStas.

For the specific case, I have also been thinking about removing the xmin/.../ymax all together which then on the other hand means that an asymmetric slit must be implemented via the AT specifier. But your solution should also be OK - but should then probably be supplemented by a default, finite xwidth/yheight. 

(A mathematical slit that defaults to not transport anything is probably harmful to newcomers...)

Best,
Peter
