### ISSUE TITLE
m*gui suggestion from Kim Lefmann: Use "ray count"

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#524]
Email from Kim in Danish:

<pre>
Hej Peter,

Jeg kom lige til at se, at i mcgui står der "neutron count" for antallet af neutron rays. 
Er det ikke mere logisk at skrive "neutron ray count"? Det er altid så svært at forklare
folk forskellen på N og I, og så er det godt hvis vores ordvalg matcher...

mvh Kim
</pre>

Current situation across Neutrons and Photons, Perl and Python:

![xquartzscreensnapz001](https://user-images.githubusercontent.com/8593355/28061007-48517df2-6629-11e7-9f28-24ab52b68f74.png)

Looking at both mcxtrace and mcstas at once, I belive the right solution would be to write "Ray count" everywhere - perhaps with a mouse-over tooltip pointing to the manual(s)

**Comment by willend** [comment]
Started work in this direction on https://github.com/McStasMcXtrace/McCode/commit/429517d14a8a206cfc3f441727c2e833f616f22f

(Tooltip could be something like:

<pre>
The Ray count specifies your simulation statistical grannularity and is NOT equal to the number of actual particles simulated. For a thorough explanation, see the chapter "Monte Carlo Techniques and simulation strategy" in your user manual
</pre>

)

**Comment by climbcat** [comment]
This has been added. However,  the tooltip may be so "hidden" in the UI that users may have to stumble upon it to be able to read it. It only if one hovers the mouse over the text, or the whitespace right next to it.

![mcgui_tooltip](https://user-images.githubusercontent.com/11196009/29319143-387acb2a-81d3-11e7-9359-6300e5b6af02.png)

**Comment by willend** [comment]
DONE in both the default Python and the legacy Perl ui.
