### ISSUE TITLE
mcgui fails in TRACE mode (at least on windows) with dash in .instr name

### ISSUE THREAD

**Issue by RichardHeenan** [McStasMcXtrace/McCode#525]
After several hours of systematically removing stuff from loki-master-model.instr, until nothing was left except a source and a monitor, for Trace from windows mcgui to still fail with 

Syntax error in input!
LexToken(COMPONENT,'COMPONENT',2,12)

I then discover that the problem was caused by the hyphens [= minus sign = dash or whatevwer in your language] in the .instr file name.

**Comment by climbcat** [comment]
Hi, thanks for reporting this. Fixed by 4cdcf89ab922cc51e58f427481c5eabed2271ce9.
