### ISSUE TITLE
mcgui on windows deleting .exe files

### ISSUE THREAD

**Issue by RichardHeenan** [McStasMcXtrace/McCode#526]
mcgui (windows) issue?  I wanted to compile several .instr files to set up and check all OK before starting a long batch job, which was expecting several .exe to be there.

If I open a new instrument in the gui and compile it, the previously compiled .exe is deleted, which is rather annoying in this situation, (though of course is required if the same instrument is being re-compiled).

I suspect that there are some other related issues here, where the .exe is not kept up to date, so the logic may be suspect in further circumstances.

**Comment by climbcat** [comment]
Thanks for noticing and reporting this. The bug has been fixed by e6220eb396f028738f6f59c1af3b934eea673ab0. Test results from your side are welcome.
