### ISSUE TITLE
McStas and Mantid Wiki page outdated

### ISSUE THREAD

**Issue by jamesphysics** [McStasMcXtrace/McCode#528]
The current Wiki (https://github.com/McStasMcXtrace/McCode/wiki/McStas-and-Mantid) instructions no longer work correctly in Linux and need to be slightly modified for Windows users. I recommend updating/adding the following which is a slight correction to the Linux instructions as well as the addition of an explanation of how to run the same commands from a mcstas shell in windows:

Linux:
•	Compile McStas instrument code including support for NeXus output:
o	export MCSTAS_CFLAGS="-g -O2 -lm -DUSE_NEXUS -lNeXus"
o	mcrun.pl -c -n0 templateSANS_Mantid.instr
•	Generate IDF
o	Mcdisplay.pl templateSANS_Mantid.instr --format=Mantid -n0
•	Run simulation
o	Mcrun.pl templateSANS_Mantid.instr -n1e6 --format=Nexus

Windows:
Must have Nexus format libraries installed. At http://downloads.mcstas.org/ find folder named after most recent version of McStas and then run the file under /windows/extras/nexus-4.3-0-win32.exe. Default installation path is C:\Program Files (x86)\NeXus Data Format.
•	Compile McStas instrument code including support for NeXus output (using the default installation path):
o	SET MCSTAS_CFLAGS=-g -O2 -DUSE_NEXUS -llibNeXus-0 -I "C:\Program Files (x86)\NeXus Data Format\include\nexus" -L "C:\Program Files (x86)\NeXus Data Format\lib\nexus"
o	mcrun-pl -c -n0 templateSANS_Mantid.instr
•	Generate IDF
o	mcdisplay-pl templateSANS_Mantid.instr --format=Mantid -n0
•	Run simulation
o	mcrun-pl templateSANS_Mantid.instr -n1e6 --format=Nexus

**Comment by jamesphysics** [comment]
Anders-Markvardsen

**Comment by jamesphysics** [comment]
@Anders-Markvardsen

**Comment by trnielsen** [comment]
Hi James

Thanks for looking into this. I will up date the wiki.

McStas is changing from Perl based tools to Python based tools. Not all Perl tools are yet available as Python tools. I believe that is why we for a short time still need to use mcdisplay.pl to generate the IDF.

**Comment by trnielsen** [comment]
@willend 

We need to also to update the OSX part in the section "Tested Versions". 

Is the statement "Use either the Intel or gcc 4.8 compiler. Simulations using Nexus format and event data does not work using the Clang compiler." still applicable?

**Comment by climbcat** [comment]
@trnielsen  

Indeed the .pl tool is still needed to generated an idf, which is, as I recall, used by the mcstas instrument outputting mantid commands in the trace stream. However, the next step of converting the stream from a mcstas mantid instrument into a mantid xml does indeed exist in the python tools.

It is distributed as mcdisplay-mantid.

**Comment by jamesphysics** [comment]
@willend has helpfully pointed out that this can be done very easily in the GUI and is explained for both Mac and Windows on the final pages of a slide from the McStas and Mantid workshop. Here is my amended suggestion incorporating this knowledge.

----

# Installing NeXus
In order for McStas to produce Mantid readable output, NeXus needs to be installed.

## Windows
Get latest release from https://github.com/nexusformat/code/releases?after=4.3.1 and install it.

## macOS
Get homebrew via https://brew.sh 
lnstall it via the recipe given then, in a terminal issue

`DTUs-MacBook-Pro:Downloads dtuphysics$ brew search nexusformat`
`homebrew/science/nexusformat `✔
`DTUs-MacBook-Pro:Downloads dtuphysics$ brew install homebrew/science/nexusformat`

# Running simulations and generating IDFs
## Graphical User Interface
![setmantidenvironmentgui](https://user-images.githubusercontent.com/10106942/28919270-aaa5fd20-7844-11e7-8df4-121c7dfd8a28.png)

In the McStas GUI, go to File >> Configuration and then make sure the settings highlighted in red are selected and then, to make sure the correct NeXus libraries and headers can be located, enter into the C flags box:
### Windows
` -g -O2 -lm -DUSE_NEXUS -lNeXus-0  -L"C:\Program Files (x86)\NeXus Data Format\bin" -L"C:\Program Files (x86)\NeXus Data Format\lib\nexus" -I"C:\Program Files (x86)\NeXus Data Format\include"`

### macOS
`-DUSE_NEXUS -lNeXus -L/usr/local/lib -I/usr/local/include`

these CFLAGS will be used in any future compilation, be it commandline or gui.

**Comment by trnielsen** [comment]
@jamesphysics 

Based on your input I will update the wiki with how-to use info for Win, OSX and Ubuntu.

**Comment by Anders-Markvardsen** [comment]
@trnielsen let us know when the wiki has been updated and which platforms you would like us to test the these on

**Comment by trnielsen** [comment]
@Anders-Markvardsen  I'll let you know when to have a look a the new wiki. It will be based on our paper.

**Comment by trnielsen** [comment]
Wiki page is update. 
Closing Issue.
