### ISSUE TITLE
mcdisplay / mccode-r xml-IDF handling: Sometimes causes issues with \r on windows

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#530]
@trnielsen and I have found that on Windows, our NeXus file output can get corrupted when

* XML output is "big", i.e. from an instrument with many components
* Windows-style linefeeds (\r\n) are present in the IDF data

Envisioned solution is to strip IDF data from any \r within mccode-r

**Comment by jamesphysics** [comment]
Have downloaded the fix but still getting the same issue I'm afraid

**Comment by willend** [comment]
Please triple-check that you recompiled your instrument file again (and that a new .c file was generated), otherwise the binary instr could still behave the same.

**Comment by jamesphysics** [comment]
Can confirm my instrument file did recompile and a new .c file was generated. Have checked a couple of times with different instruments.

**Comment by willend** [comment]
OK. Can you send me both your instr, c and exe in a zip, preferably via email?

**Comment by willend** [comment]
Hi there, the exe I got seems to have been compiled without nexus:
<pre>
C:\Users\pwill\Desktop\Vanadium1\Vanadium1>.\Vanadium1.exe --help
Incoherent (Vanadium1.instr) instrument simulation, generated with McStas 2.4.1 - Jun. 26, 2017 (Jun. 26, 2017)
Usage: .\Vanadium1.exe [options] [parm=value ...]
Options are:
  -s SEED   --seed=SEED      Set random seed (must be != 0)
  -n COUNT  --ncount=COUNT   Set number of neutrons to simulate.
  -d DIR    --dir=DIR        Put all data files in directory DIR.
  -t        --trace          Enable trace of neutrons through instrument.
  -g        --gravitation    Enable gravitation for all trajectories.
  --no-output-files          Do not write any data files.
  -h        --help           Show this help message.
  -i        --info           Detailed instrument information.
  --format=FORMAT            Output data files using FORMAT=MCSTAS

Known signals are: BREAK (save) TERM (save and exit)
</pre>
(Otherwise it would have had a NEXUS in the FORMAT= list above).

Recompiling with NeXus and running again, I get an h5 file that loads fine into my Mantid here, but that doesn't include any event-workspaces. Will bounce that to you via email for checks on your side.

**Comment by jamesphysics** [comment]
I did a recompile and am now getting
```
C:\Users\ezz64382\Desktop\McStas\Vanadium>Vanadium.exe --help
Incoherent (Vanadium.instr) instrument simulation, generated with McStas 2.4.1 - Jun. 26, 2017 (Jun. 26, 2017)
Usage: Vanadium.exe [options] [parm=value ...]
Options are:
  -s SEED   --seed=SEED      Set random seed (must be != 0)
  -n COUNT  --ncount=COUNT   Set number of neutrons to simulate.
  -d DIR    --dir=DIR        Put all data files in directory DIR.
  -t        --trace          Enable trace of neutrons through instrument.
  -g        --gravitation    Enable gravitation for all trajectories.
  --no-output-files          Do not write any data files.
  -h        --help           Show this help message.
  -i        --info           Detailed instrument information.
  --format=FORMAT            Output data files using FORMAT=MCSTAS NEXUS
```
But still the same issue in Mantid. The file you sent loads fine into Mantid with workspaces but still no instrument loaded:
![mccode](https://user-images.githubusercontent.com/10106942/29613620-ced5b248-87fe-11e7-8e7b-08937140e1fa.png)

Have emailed you the recompiled files.

**Comment by willend** [comment]
This one was never reproduced here, closing
