### ISSUE TITLE
McCode creates C file that is unreadable to GCC when using absolute paths

### ISSUE THREAD

**Issue by ajulik1997** [McStasMcXtrace/McCode#532]
When compiling an instrument from the command line using:
`mcstas -t instrument_name.instr`
a .c file is generated that contains:
![image](https://user-images.githubusercontent.com/9460842/29322806-ca2ed248-81d6-11e7-9823-af6dfe4afb8b.png)
which compiles fine using gcc

When doing the same but using absolute baths, as in:
`mcstas -t C:\path\to\instrument_name.instr`
then the generated c. file looks as follows:
![image](https://user-images.githubusercontent.com/9460842/29322886-0c219d20-81d7-11e7-9e73-f8d5fe707e7a.png)

This file cannot then be compiled using GCC because \\ is used instead of \\\ and it interprets the path as being full of unknown escape characters:
![image](https://user-images.githubusercontent.com/9460842/29322936-4ae79974-81d7-11e7-94a6-7c35f875c092.png)

A quick fix would be to just default to \\\ for every path, or alternatively use / under Windows (does not seem to make a difference to windows paths).

**Comment by willend** [comment]
Hi there,

Thanks for pointing this out, you are absolutely right. Most of our tools (silently) assume that your instr is in . anyway, but it would indeed be good to escape or turn the single \'s

**Comment by willend** [comment]
It seems a reasonable workaround is that you call your mcstas using the suggested double backslashes:
<pre>
mcstas -t c:\\Users\\pwill\\BNL_H8.instr
</pre>
Yields
<pre>
char mcinstrument_source[] = "c:\\Users\\pwill\\BNL_H8.instr";
</pre>
in my generated source code.

As the (GUI) tools make their most to NOT let you work with absolute paths on Windoze, I think that workaround is an acceptable way of achieving what you want? :-) Hence I will close and mark as 'wontfix'
