### ISSUE TITLE
McXtrace-comps: Monitor_nD monitoring phase seems to be broken in list mode

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#535]
In list mode,  when asking for output of the photon ray phase, the result is either zero or some
value which does not appear to be correct.

**Comment by willend** [comment]
Hmm, missing token in the "table" of things to possibly monitor?

Does it work to put the phase in a user var and use that in the list mode?

**Comment by ebknudsen** [comment]
fixed by 2d1756886c7d7bed0a79efca004a4045848c4920
