### ISSUE TITLE
McStas: Polarization for supermirror reflectors leads to |P|>1

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#536]
When the polarization vector is _not_ parallel to the polarization direction of the supermirror this can lead to unphysical polarization vectors. Something is clearly wrong in the complex of Reflection functions in pol-lib.c

**Comment by willend** [comment]
@ebknudsen what is the status?

**Comment by willend** [comment]
@ebknudsen A status update please?

**Comment by ebknudsen** [comment]
Have found the offending piece of code - I think it's a day or two's job. It is in the functions SetPolMonoRefOut and SetPolMonoTransOut that theres' an implicit assumption that what you are dealing with is "classical polarization", understood as up or down being the only possibilities.

**Comment by ebknudsen** [comment]
cbf8df1e34caa13ee894bb8479 adds a note in the docs about the current limitation pending a real fix
