### ISSUE TITLE
McCode: user json conifg file is only created by GUI - command line way wanted

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#539]
The user mccode_config.json file is only generated automatically when the gui is installed. This is impractical when setting up an installation on e.g. a cluster where the GUI is not wanted.
A workaround is to load mccode_config.py in an interactive interpreter and call the save_config function.

Some kind of command line entry point to write a user config .json file would be nice.

**Comment by climbcat** [comment]
What kind of entry point is convenient?

**Comment by willend** [comment]
I would suggest something like

`mcrun --generate-userconfig`

**Comment by ebknudsen** [comment]
... or simply distribute a "*.sample" kind of file in the distro.
Arguably this could be done by having mkdist (or preferrably cmake) call
the appropriate function in mccodelib.py to generate one. The reason
would be to avoid extra complexity in mcrun. I realize this is in
opposition to my original suggestion :-). Either way is fine by me.
/e

**Comment by willend** [comment]
I think the best solution is to have an mcrun hook - which could for instance be used install-time to generate the kind of sample file you suggest.

 - Reasoning being that the json file in principle is auto-generated from whatever content we have defined in the mccode_config.py.in (which is already dulicated with a mccode_config.py in the repo, already giving one layer of confusion...)

**Comment by ebknudsen** [comment]
Ah - sorry I should have read my original post :-). I obviously meant the "call the appropriate function in mccode_config.py". But no matter. either way is fine by me - it's a simple enough hook to m[xc]run.

**Comment by ebknudsen** [comment]
Ah - sorry I should have read my original post :-). I obviously meant the "call the appropriate function in mccode_config.py". But no matter. either way is fine by me - it's a simple enough hook to m[xc]run.

**Comment by climbcat** [comment]
A command-line option now exists, as pr. b2bde03ef7bb70e6217acf2e38c1dd861bf1a7c8. It is an option "write-user-config" to mcrun.
