### ISSUE TITLE
McCode tools: mcgui/mxgui missing parameter input box for parameters without default value 

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#543]
If a parameter does not have a default value, the run window does not generate an input box for that parameter. This in turn prevents running the instrument since the runtime aborts with a message about missing input value.

[BNL_H8_mod.txt](https://github.com/McStasMcXtrace/McCode/files/1329248/BNL_H8_mod.txt)

**Comment by climbcat** [comment]
Hi, the root cause of this bug is actuallly in mccode. 

The output of e.g.

<code>./BNL_H8_mod.out --info</code>

changes depending on the definition is <code>lambda=0</code> or just <code>lambda</code>.

I can fix this if you like, but I need some pointers regarding where to look for it... :)

**Comment by ebknudsen** [comment]
Ok cool. 
I agree that this is due to a bug in mccode (in the function mcruninfo_out, lines: 931+), which could/should be fixed.

Bar that, the perl-gui handles the situation somehow - but I don't remember how unfortunately.

**Comment by climbcat** [comment]
lambda was stated in the info text, although not in the last lind...

**Comment by ebknudsen** [comment]
I've sort of got a fix - how should it be reported for mcgui (python) to pick it up?
as:
 'Param: lambda'
or 
 'Param: lambda='
