### ISSUE TITLE
McCode-tools: mcplot/mxplot-pyqtgraph. Scan plot legends only display [mcstas.dat]

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#544]
The legends on scan plots merely display [mcstas.dat] which is unhelpful/confusing (particularly for McXtrace). The datafile is named "mccode.dat".
Perhaps the legend could come from the yvars field n the datafile?

**Comment by climbcat** [comment]
This has been fixed by ca840644d8393574b08ca790416573b5adbf0059

**Comment by willend** [comment]
Correct, closing
