### ISSUE TITLE
McCode: man pages are out of date 

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#549]
The man pages shipped with the kernel and the perl tools are out of date. Also no man pages at all exist for the python tools.

Some updates are clearly needed - Do we want the man pages at all?
Suggest to keep the mcstas/mcxtrace ones (perhaps merge with mc-/mxformat) and the mcrun/mxrun pages, as these relate to GUI-less installations which are more likely to rely on the manpages (I think)

**Comment by willend** [comment]
How about using e.g. https://www.gnu.org/software/help2man/

**Comment by willend** [comment]
Here is output of help2man mcrun - not perfect, but a start:
[mcrun-py.1.txt](https://github.com/McStasMcXtrace/McCode/files/1579993/mcrun-py.1.txt)

<pre>
LOADING(1)                                             User Commands                                            LOADING(1)

NAME
       loading - manual page for loading user configuration from /Users/pkwi/.mcstas/2.4.1/mccode_config.json

SYNOPSIS
       mcrun.py [-cpnN] Instr [-sndftgahi] params={val|min,max|min,guess,max}...

DESCRIPTION
       loading user configuration from /Users/pkwi/.mcstas/2.4.1/mccode_config.json

OPTIONS
       --version
              show program's version number and exit

       -h, --help
              show this help message and exit

              mcrun options:

       -c, --force-compile
              force rebuilding of instrument

       -p FILE, --param=FILE
              read parameters from file FILE

       -N NP, --numpoints=NP
              set number of scan points

       -L, --list
              use a fixed list of points for linear scanning

       -M, --multi
              run a multi-dimensional scan

       --autoplot
              open plotter on generated dataset

       --embed
              store copy of instrument file in output directory

       --mpi=NB_CPU
              spread simulation over NB_CPU machines using MPI

       --machines=machines
              defines path of MPI machinefile to use in parallel mode


       --optimise-file=FILE
              store scan results in FILE (defaults to: "mccode.dat")

       --no-cflags
              disable optimising compiler flags for faster compilation

       --verbose
              enable verbose output

              Instrument options:

       -s SEED, --seed=SEED
              set random seed (must be: SEED != 0)

       -n COUNT, --ncount=COUNT
              set number of neutrons to simulate

       -t, --trace
              enable trace of neutron through instrument

       -g, --gravitation, --gravity
              enable gravitation for all trajectories

       -d DIR, --dir=DIR
              put all data files in directory DIR

       --format=FORMAT
              output data files using format FORMAT (format list obtained from <instr>.out -h)

       --no-output-files
              Do not write any data files

       -i, --info
              Detailed instrument information

       2.4.1

SEE ALSO
       The  full  documentation for loading is maintained as a Texinfo manual.  If the info and loading programs are prop-
       erly installed at your site, the command

              info loading

       should give you access to the complete manual.

loading user configuration from /Users/pkwi/.mcstas/2.4Decembere2017fig.json  
</pre>

**Comment by willend** [comment]
- build use of help2man into the build system(s) for most / all tools (mcstas/mcxtrace/mcrun variants/mcplot/variants/mcdisplay variants)

- Start with just one example, e.g. replace https://github.com/McStasMcXtrace/McCode/blob/master/mcstas/doc/man/mcstas.1.in

**Comment by climbcat** [comment]
When I run man for any of the tools for my current installation, which is a local build, I get  

jaga@HP-EliteBook-840-G4:~/source/McCode/mcstas/doc/man$ man mcrun
No manual entry for mcrun
See 'man 7 undocumented' for help when manual pages are not available.

Is this expected?

**Comment by willend** [comment]
True, something is not set up completely right. The manages are in e.g.
<pre>
/usr/share/mcstas/2.4.1/doc/man/man1
</pre>
What should work is to put MANPATH=/usr/share/mcstas/2.4.1/doc/man/man1, but that doesn't work for me here...

I can get output by 
<pre>
man /usr/share/mcstas/2.4.1/doc/man/man1/mcstas-2.4.1.1
</pre>

**Comment by climbcat** [comment]
My suggestion is to reduce complexity by removing all man- related files and references. If users know about "man", they are in my opinion likely to try "--help" next.

**Comment by willend** [comment]
Yup, seems to work. DONE

**Comment by willend** [comment]
Oops, closed wrong issue reopening for discussion

**Comment by ebknudsen** [comment]
outdated
