### ISSUE TITLE
McCode-tools: Python mcrun/mxrun does not honor  --no-output-files completely

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#550]
Python mcrun and mxrun create directories for data output even if the --no-output-files flag is set.
The instrument file is copied into the directory but otherwise no data is created (as expected).

**Comment by climbcat** [comment]
I have investigated this, and it turns out that it is the binary which whites the folder and copies the instrument file.

**Comment by willend** [comment]
Yup, it seems that a binary will create an empty dir even if --no-output-files is set:
<pre>
mcstas-2.4.1 env tmp $ ./BNL_H8.out --no-output-files -d test lambda=2.36
Instrument:     BNL_H8 on localhost.
Monochromator : DM = 3.3539
A1 = 20.60, A2 = 41.20 (deg)
Ki = 2.662 Angs-1 Energy = 14.69 meV
Velocity = 1676 m/s, lambda = 2.36 Angs
[BNL_H8] Initialize

Save [BNL_H8]
Detector: D0_Source_I=0.00315599 D0_Source_ERR=1.39197e-05 D0_Source_N=51406 "D0_Source.psd"
Detector: D1_SC1_Out_I=0.0204266 D1_SC1_Out_ERR=3.53999e-05 D1_SC1_Out_N=334834 "D1_SC1_Out.psd"
Detector: D2_A4_I=0.0137644 D2_A4_ERR=2.90622e-05 D2_A4_N=225933 "D2_A4.psd"
Detector: D4_SC2_In_I=0.00153732 D4_SC2_In_ERR=3.07115e-06 D4_SC2_In_N=254148 "D4_SC2_In.psd"
Detector: D5_SC2_Out_I=0.00120113 D5_SC2_Out_ERR=2.71445e-06 D5_SC2_Out_N=200260 "D5_SC2_Out.psd"
Detector: D7_SC3_In_I=1.19527e-07 D7_SC3_In_ERR=2.19939e-10 D7_SC3_In_N=325441 "D7_SC3_In.psd"
Detector: D8_SC3_Out_I=2.29663e-08 D8_SC3_Out_ERR=9.69604e-11 D8_SC3_Out_N=61801 "D8_SC3_Out.psd"
Detector: D10_SC4_In_I=1.18564e-09 D10_SC4_In_ERR=6.98378e-12 D10_SC4_In_N=31814 "D10_SC4_In.psd"
Detector: He3H_I=9.18886e-10 He3H_ERR=6.14074e-12 He3H_N=24764 "He3.psd"

Finally [BNL_H8: test]. Time: 2 [s] 
mcstas-2.4.1 env tmp $ ls | grep test
test    # <- Here is the empty folder!!!
<pre>
The Python code has a check for existence of the folder before copying in the instr file, so a fix will be to (silently) fully honour --no-output-files by NOT creating any dir!
