### ISSUE TITLE
Python tools: Qt4->Qt5 (only RPM solution remains)

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#552]
We are currently using the "awkward mix" of Python 3 and Qt4, it would be good and pave the way for the future to go Qt5. (An would likely resolve dependency issues in Anaconda)

**Comment by climbcat** [comment]
python3-pyqt5.qsci

**Comment by climbcat** [comment]
pip3 install pyqt5

**Comment by climbcat** [comment]
pyuic5 from pyqt5-dev-tools

**Comment by climbcat** [comment]
We are now at a stage that is ready for evaluation - although I have fixed quite a few bugs, there may be more. The code is present in the "qt5" branch.

The working combination of pyqt and qscintilla was pyqt5.9, not the default deb version pyqt5.5, which has a serious bug in it making keyboard shortcuts non-functional. 

pip3 install pyqt5
apt-get install python3-pyqt5.qsci

For managing the .ui files with qtcreator, we now use pyuic5 from the package pyqt5-dev-tools. This has been tested as well we are using the new auto-generated code.

**Comment by willend** [comment]
I think we should see if there is a pyqt5.9 available as a .deb package somewhere, I really would like us to avoid using pip...

I am about to push a couple of minor (packaging-related) things to the qt5 branch - and stumbled upon a PyQt4 reference in tools/Python/mcgui/ui-pywrap.py - should that be fixed also?

Otherwise things look good on the Mac, will look at Windows later.

**Comment by climbcat** [comment]
Ok, great to hear that it works on all platforms. I have deleted the mentioned file. PyQt5 requires the updated pyuic5 tool for compiling qtcomposer .ui files, and the file was an unused remnant related to the corresponding PyQt4 tool.

**Comment by willend** [comment]
Status:

- macOS: OK
- Windows: OK
- Debian: Looks OK, but check that dependencies are now OK
- RPM: Needs testing

**Comment by willend** [comment]
RPM is functional, closing
