### ISSUE TITLE
Issues with Single_crystal focusing

### ISSUE THREAD

**Issue by t-weber** [McStasMcXtrace/McCode#555]
There seem to be possible issues (or maybe misunderstandings on my part...) with the crystal curvature code in samples/Single_crystal.comp. The code of interest consists of these two parts:

Code part 1, starting at line 1146 of Single_crystal.comp:
```
      /* lattice curvature option: rotate neutron velocity */
      if (RX || RY || RZ) {
        if (RX) { rotate(b1x,b1y,b1z,vx,vy,vz,    atan2(x,RX),0,0,1); }
        else { b1x=vx; b1y=vy; b1z=vz; }
        if (RY) { rotate(b2x,b2y,b2z,b1x,b1y,b1z, atan2(y,RY),1,0,0); }
        else { b2x=b1x; b2y=b1y; b2z=b1z; }
        if (RZ) { rotate(b1x,b1y,b1z,b2x,b2y,b2z, atan2(z,RZ),0,1,0); }
        else { b1x=b2x; b1y=b2y; b1z=b2z; }
        kix = V2K*b1x;
        kiy = V2K*b1y;
        kiz = V2K*b1z;
      } else {
        kix = V2K*vx;
        kiy = V2K*vy;
        kiz = V2K*vz;
      }
```

Code part 2, starting at line 1308:
```
      /* lattice curvature option: rotate back neutron velocity */
      if (RZ || RY) {
        if (RX) { rotate(b1x,b1y,b1z,vx,vy,vz,    -atan2(x,RX),0,0,1); }
        else { b1x=vx; b1y=vy; b1z=vz; }
        if (RY) { rotate(b2x,b2y,b2z,b1x,b1y,b1z, -atan2(y,RY),1,0,0); }
        else { b2x=b1x; b2y=b1y; b2z=b1z; }
        if (RZ) { rotate(b1x,b1y,b1z,b2x,b2y,b2z, -atan2(z,RZ),0,1,0); }
        else { b1x=b2x; b1y=b2y; b1z=b2z; }
        vx=b1x; vy=b1y; vz=b1z;
            }
```

Part 1 rotates the neutron velocity in the opposite direction the crystal would be bent, part 2 rotates it back. Here are possible problems I've encountered in a simulation:

- As part 1 rotates the velocity in the order RX, RY, RZ, part 2 should rotate it back in the opposite order, namely RZ, RY, RX, to undo the effects.
- If you look at, for example, the RX code, it does not actually produce curvature: The line "rotate(b1x,b1y,b1z,vx,vy,vz,  atan2(x,RX),0,0,1)"  rotates the neutron velocity around the beam direction z based on the x position. This creates a twist, not a curvature. It should rather rotate around the "up" (y) direction.
- The code uses the rotate(...) macro defined in lib/share/mccode-r.h. This macro is based on the general Euler-Rodrigues formula for rotations around arbitrary vectors, and does not give the best efficiency for simple rotations around the principal axes [1,0,0], [0,1,0], and [0,0,1].

Here's an idea to have a curvature system that behaves similar to the RH and RV parameters in optics/Monochromator_curved.comp (with RX==RH and RY==RV here):

Replace part 1 with:
```
/* lattice curvature option: rotate neutron velocity */
/* TODO: check if the PG c-rotation affects the focus rotations... */
double curv_xangle = 0;
double curv_yangle = 0;

double _vx = vx;
double _vy = vy;
double _vz = vz;

if(RY)
{ /* rotate v around x axis based on y pos, for vertical focus */
    curv_yangle = atan2(y, RY);
    vec_rotate_2d(&vy,&vz, curv_yangle);
    vec_rotate_2d(&sy,&sz, curv_yangle);

    /*changing y,z actually curves the crystal, not only the planes*/
    /*comment out if only curvature of the lattice planes is needed*/
    vec_rotate_2d(&y,&z, curv_yangle);
}
if(RX)
{ /* rotate v around y axis based on x pos, for horizontal focus */
    curv_xangle = atan2(x, RX);
    vec_rotate_2d(&vx,&vz, curv_xangle);
    vec_rotate_2d(&sx,&sz, curv_xangle);

    /*changing x,z actually curves the crystal, not only the planes*/
    /*comment out if only curvature of the lattice planes is needed*/
    vec_rotate_2d(&x,&z, curv_xangle);
}

kix = V2K*vx;
kiy = V2K*vy;
kiz = V2K*vz;
vx = _vx;
vy = _vy;
vz = _vz;
```

Replace part 2 with:
```
/* lattice curvature option: rotate back neutron velocity */
if(RX)
{
    vec_rotate_2d(&vx,&vz, -curv_xangle);
    vec_rotate_2d(&sx,&sz, -curv_xangle);

    /*changing x,z actually curves the crystal, not only the planes*/
    /*comment out if only curvature of the lattice planes is needed*/
    vec_rotate_2d(&x,&z, -curv_xangle);
}
if(RY)
{
    vec_rotate_2d(&vy,&vz, -curv_yangle);
    vec_rotate_2d(&sy,&sz, -curv_yangle);

    /*changing y,z actually curves the crystal, not only the planes*/
    /*comment out if only curvature of the lattice planes is needed*/
    vec_rotate_2d(&y,&z, -curv_yangle);
}
```

Add the following much simpler rotation function to the SHARED section:
```
/* rotate vector ccw */
void vec_rotate_2d(double* x, double* y, double angle)
{
    double c = cos(angle);
    double s = sin(angle);

    double newx = *x*c - *y*s;
    double newy = *x*s + *y*c;

    *x = newx;
    *y = newy;
}
```

If needed, I could supply a small test instrument file comparing focusing in Single_crystal and Monochromator_curved.

Many thanks for clarification and best regards!

**Comment by willend** [comment]
Hi there,

Sorry for not having responded before! A patch for Single_crystal along with a test instrument would be much welcomed!

Best,

Peter

**Comment by t-weber** [comment]
Thank you! Just created the patch (pull request #592) and a test instrument (pull request #593).

The test instrument compares focusing of Monochromator_curved and Single_crystal. The reworked parameters RX and RY of the crystal are now analogous to RH and RV of the monochromator component, RZ has been removed. In the test instrument you can switch between the two components with mono_ideal=0 (which uses the single crystal) and mono_ideal=1 (which uses the curved mono). The test uses double-focusing by default.

**Comment by ebknudsen** [comment]
Hi there,
I've taken a look at this - this looks great. Many thanks for the patch and pull request Tobias.
I do have a concern, though.

Let me elaborate a bit. The original intent of this code was to target (up to) moderate curvature, where drift can be neglected. If it can't, the problem gets much more complex as we can't treat the crystal as being constant along the initial neutron trajectory.
In this approximation, I'd say it doesn't really matter if you rotate the neutron wrt. to the lattice planes or the other way around (which I agree would be the correct thing to do). It was in fact validated in some sense at ILL - how and by whom I don't recall at present. (@farhi might). If you do rotate the neutron, you have to rotate it back in the straight crystal frame afterwards. If you don't then that would be wrong, no? 
Thus, I have a question to the PR: Aren't lines 1361... introducing an error rotation? The curvature of the crystal is already taken account of once. Granted, there ought to be a correction, but are we not overshooting here? I may (likely perhaps) be misunderstanding something here. Could you comment @t-weber ?

**Comment by t-weber** [comment]
Hi and thanks for the comment!

If I understand correctly, your question is about the method used here in general and not about a possible error in this concrete implementation (which of course cannot be fully ruled out either...)? If so: The code starting in lines 1361 takes care of undoing the rotation on the neutron velocity done in lines 1182ff. Why this is necessary can be see like this:

The McStas component without the curvature code can be seen (in a linearised simplification) as performing a transformation A on -- e.g. -- the neutron velocity v, both of which are here given in the local component frame L:

v[L]' = A[L] v[L].

If we want to include curvature, the operator A representing the rest of the component without the curvature code would now be in a wrong, uncurved coordinate frame F. We have to transform it by rotating into the curved frame (based on the position of the neutron):

v[L]' = T[F->L] A[F] T[L->F] v[L].

The neutron velocity in the local frame v[L] is transformed by T[L->F] into the uncurved frame of the original component code, single crystal scattering is done by the original A[F]. Finally, v'[F] is transformed back into the original local frame where McStas expect it, T[F->L], giving the final velocity in the local frame, v[L]'.

Here,
T[L->F] = R(X)R(Y) corresponds to the trafo on lines 1182ff,
A[F] corresponds to the component code inbetween, and
T[F->L] = T[L->F]^(-1) = R(-Y)R(-X) corresponds to the trafo code on line 1361ff.

The approximation here is of course that such a base trafo is only valid for linear operators A and therefore first order scattering, small angles, etc. It should be regarded as a quick method for initial testing. The fully correct way to handle crystal focusing would be to place and group individual Single_crystals in the instrument file and rotate them individually, modelling a real focusing mono/ana. Which requires much more programming effort.

Hope this helps!

PS: It shouldn't matter (at least in the linear approximation) if we rotate the component or alternatively counter-rotate the neutron velocity:
Rotating the component is v[L]' = (T[F->L] A[F] T[L->F]) v[L],
whereas counter-rotating the velocity is v[L]' = T[F->L] A[F] (T[L->F] v[L]),
which are of course both the same.

**Comment by ebknudsen** [comment]
@t-weber: I agree - Point taken. I shall push through your PRs now. I have simply forgotten - sorry.
