### ISSUE TITLE
Continuing dependency problems with RHEL6 mcstas updates

### ISSUE THREAD

**Issue by JCCNIST** [McStasMcXtrace/McCode#556]
Running RHEL6 kernel version: 2.6.32-696.13.2.el6.x86_64
yum update problems:

Error: Package: mcstas-comps-2.4.1-1.0-1.x86_64 (mccode)
           Requires: libc.so.6(GLIBC_2.14)(64bit)
Error: Package: mcstas-2.4.1-1.0-1.x86_64 (mccode)
           Requires: libc.so.6(GLIBC_2.14)(64bit)
Error: Package: mcstas-comps-2.4.1-1.0-1.x86_64 (mccode)
           Requires: libgfortran.so.3(GFORTRAN_1.4)(64bit)

Currently installed versions:
glibc-2.12-1.209.el6_9.2.i686
libgfortran-4.4.7-18.el6.x86_64 and libgfortran-4.4.7-18.el6.i686

**Comment by willend** [comment]
Hi there,

Sorry for not commenting anything here before!

Could you try to see if the alternative set of RPM's provided here (http://download.mcstas.org/mcstas-2.4.1/linux/mcstas-2.4.1-rpm64-Scientific_Linux_6.1/) work any better for you? (Manual installation, I know...)

Alternatively, I suggest you try out building the packages for your own system using the top-level build_rpms_mcstas, e.g. from the mcstas-2.4.1-release branch. (Most dependencies for building should be listed in https://github.com/McStasMcXtrace/McCode/blob/master/BUILD_DEPS.TXT)

Best,
Peter

**Comment by willend** [comment]
Hi there,

With the help of what is in 
https://github.com/McStasMcXtrace/McCode/blob/master/getdeps_centos7 and 
https://github.com/McStasMcXtrace/McCode/blob/master/build_rpms_mcstas it should be completely possible to compile McStas distribution packages on RHEL 6. (This will even pull you a miniconda3 Python and create a portable python install with all bells and whistles.)

Wrt. the gui oriented dependencies for the older Perl set of tools, I would suggest to
1) Enable the EPEL repo
2) Experiment with the various versions of packages that I indicated above

Sorry for not being a greater support on RHEL, but people run all kinds of RPM based distros that are frankly not too compatible... (Fedora/Mandriva/SuSe/RHEL/CentOS/SL...)

For future releases I would love to assist in porting, but this probably will require that I have remote acces for resolving what exactly is going on
