### ISSUE TITLE
McCode mc/mxplot.pl fails on debian testing (and prob. newer)

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#558]
The perl plotting tools have a problem on debian testting and newer preventing also mc/mxgui from starting. On these systems a pgplot replacement based on giza is preferred as libpgplot-perl depends on libcpgplot0 and libpgplot0 (which are giza-based).

This manifests itself by mcplot.pl and mcgui.pl crashing with error messages similar to:
```
%giza - ERROR - giza_open_device: Unknown device, device not opened
Opening new window (pgopen) failed: -1
 at /usr/lib/x86_64-linux-gnu/perl5/5.26/PDL/Graphics/PGPLOT/Window.pm line 2412.
	PDL::Graphics::PGPLOT::Window::release_and_barf("Opening new window (pgopen) failed: -1\x{a}") called at /usr/lib/x86_64-linux-gnu/perl5/5.26/PDL/Graphics/PGPLOT/Window.pm line 2606
```
etc.

* m[cx]gui crashes since it attempts to open the pgxwin_server.  
* libpgplot-perl is configured to load the shared libraries ending with "so.0" and so by default loads the giza-libraries instead.

Workarounds exist:
1. Install the native pgplot5 packages from the non-free section.
2. change symlinks installed by libpgplot and libcpgplot to point to the pgplot5-versions of the library
> cd /usr/lib/x86_64-linux-gnu
> sudo ln -sf ../libpgplot.so libpgplot.so.0
> sudo ln -sf ../libcpgplot.so libcpgplot.so.0

Alternatively it is possible to directly use the giza-libraries by setting the environment variable PGPLOT_DEV
> export PGPLOT_DEV="/xwin"

This has drawbacks: 1. The 2D-plots are not nice. 2. The plot windows do not behave nicely.
This method is _not_ recommended.

**Comment by willend** [comment]
I think we could easily do the links in a postinstall script?

**Comment by willend** [comment]
@ebknudsen we should decide what to do here

**Comment by ebknudsen** [comment]
Have decided to change the default pgplot device is now "/xwin" on debian. That way it works out of the box, irrespective of the workaround above (which is reported to _not_ always work). Ref. commit 137ee31.

**Comment by willend** [comment]
Recommendation is still to
<pre>
cd /usr/lib/x86_64-linux-gnu
sudo ln -sf ../libpgplot.so libpgplot.so.0
sudo ln -sf ../libcpgplot.so libcpgplot.so.0
</pre>
Note that the resulting links may get overwritten on reinstall of the related packages.
