### ISSUE TITLE
Python mcplot parsing for scans in mccodelib

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#559]
In the event an instrument has a Monitor_nD where filename="" is not specified, the component will automatically generate such a filename.

Since the auto-generated filename depends on system clock and PID etc., the filename will change across a scan.

Hence, the mcplotloader should use the "enumeration" of output files in the individual mccode.sim files within the scan rather than a fixed filename for the monitor output, i.e.

scan/mccode.sim
scan/0/mccode.sim
scan/1/mccode.sim
...
will have the same set of monitors in the same order, but the filenames can change...

Issue migrated across from the McWeb stuff:
https://github.com/McStasMcXtrace/McWeb/issues/165

**Comment by climbcat** [comment]
This was fixed some time in the past. I have verified that the desired behavior is actual, by changing a filename and the "# filename: " property in mccode.sim simultaneously.

**Comment by willend** [comment]
Yup, tested to work. Closing
