### ISSUE TITLE
Does Python mcrun really support use of the --param=filename?

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#561]
The help indicates it does, but this may not work in reality:

<pre>
mcrun --help
loading user configuration from /Users/pkwi/.mcstas/2.4.1/mccode_config.json
Usage: mcrun.py [-cpnN] Instr [-sndftgahi] params={val|min,max|min,guess,max}...

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit

  mcrun options:
    -c, --force-compile
                        force rebuilding of instrument
    -p FILE, --param=FILE
                        read parameters from file FILE
    -N NP, --numpoints=NP
                        set number of scan points
    -L, --list          use a fixed list of points for linear scanning
    -M, --multi         run a multi-dimensional scan
    --autoplot          open plotter on generated dataset
    --embed             store copy of instrument file in output directory
    --mpi=NB_CPU        spread simulation over NB_CPU machines using MPI
    --machines=machines
                        defines path of MPI machinefile to use in parallel
                        mode
    --optimise-file=FILE
                        store scan results in FILE (defaults to: "mccode.dat")
    --no-cflags         disable optimising compiler flags for faster
                        compilation
    --verbose           enable verbose output

  Instrument options:
    -s SEED, --seed=SEED
                        set random seed (must be: SEED != 0)
    -n COUNT, --ncount=COUNT
                        set number of neutrons to simulate
    -t, --trace         enable trace of neutron through instrument
    -g, --gravitation, --gravity
                        enable gravitation for all trajectories
    -d DIR, --dir=DIR   put all data files in directory DIR
    --format=FORMAT     output data files using format FORMAT (format list
                        obtained from <instr>.out -h)
    --no-output-files   Do not write any data files
    -i, --info          Detailed instrument information
</pre>

We should either make sure this works or remove the -p / --param line in the help 

(Can anyway be done easily on a Unix via e.g. cat my_parameters.dat | xargs mcrun My_instrument -n1e7 -d A_folder)

**Comment by willend** [comment]
Tested to not work in the python implementation.

Format of the parameter file is simple:
`A=15
B=8
Lambda=4.7`

**Comment by climbcat** [comment]
this has been implemented by 75320bed1c56932e68066a9b0b224142f08f0db5

**Comment by willend** [comment]
Tested to work fine with e.g.

mcrun.py PSI_DMC.instr --param=John.par  

and John.par contents:
<pre>
lambda=2.36
BARNS=0
</pre>

(NOTE: Combinations of --param=filename and PAR=SOMETHING is not supported)
