### ISSUE TITLE
McStas Source_simple should allow to point to an off-axis target window (via target_index)

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#566]
Currently [0 0 dist] is calculated, we should use all components of the target_index instead.

**Comment by willend** [comment]
Have a look at the [0 0 dist] vs. target_index as implemented in ESS_butterfly.comp

**Comment by climbcat** [comment]
Hi! I don't see any [0 0 dist] anywhere in Source_simple.comp. Could you explain further what is needed? At first glance, the impl. of the two componens are identical for (target_index && !dist)...

**Comment by willend** [comment]
I see, didn't formulate so clearly I see. :-) 

The recipe would be to use e.g. tx,ty,tz instead of 0,0, dist in the call below
<pre>
 randvec_target_rect_real(&xf, &yf, &rf, &pdir,
			  0, 0, dist, focus_xw, focus_yh, ROT_A_CURRENT_COMP, x, y, z, 2);
</pre>
- and then if (dist) put tx=0, ty=0, tz=dist
