### ISSUE TITLE
MPI x86 in Windows 7 x64 issue

### ISSUE THREAD

**Issue by haodengfrm2** [McStasMcXtrace/McCode#568]
Multi-Core computing can be realized in win7 x64 systerm with "strawberry-perl-5.18.2.1-64bit"+"mpich2-1.4.1p1-win-x86-64"+"McStas-Metapackage-2.3-win32". Although there would be an issue that Parameter Scans cannot be done because of 64bit perl problem, simulation still can be done without Parameter Scans.
However, when I tried to turn to "strawberry-perl-5.18.2.1-32bit"+"mpich2-1.4.1p1-win-ia32"+"McStas-Metapackage-2.3-win32", there would be a fail as follows:
![mpi x86 in windows 7 issue](https://user-images.githubusercontent.com/22814682/33939791-c1087b80-e00c-11e7-8072-b83e4cfc7b93.png)

**Comment by haodengfrm2** [comment]
I did Multi-Core Parameter Scans in Linux in the past. It would take double time (half efficiency) for the same simulation in Linux than in Windows, probably because in Linux everything is 32bit and in Windows is 64bit. 
Nevertheless, I have to use lots of Windows programs, such as Jana2006, Origin, Office and so on and so on. Working in Linux, without such a bunch of programs, is rather painful... I really hope I could do simulation and other works in parallel in Windows, instead of bearing so many user unfriendly softwares.

**Comment by haodengfrm2** [comment]
win7 x64 systerm with "strawberry-perl-5.18.2.1-64bit"+"mpich2-1.4.1p1-win-x86-64"+"McStas-Metapackage-2.3-win32". Without parameter scan, running smoothly:
![mpix64 compiling](https://user-images.githubusercontent.com/22814682/33942433-30df83be-e016-11e7-88b0-1178993ad962.png)
![mpix64](https://user-images.githubusercontent.com/22814682/33942436-35ae6324-e016-11e7-89f7-cd37a72c277f.png)

**Comment by haodengfrm2** [comment]
double time (half efficiency) for the same simulation in Linux than in Windows:
![screenshot from 2017-12-13 15-17-43](https://user-images.githubusercontent.com/22814682/33943382-36a1f6ee-e019-11e7-8f92-1e6167e9c337.png)

**Comment by willend** [comment]
Hi there,

First a general comment: From 2.4.1 (current release) we have started recommending using Microsoft MPI over MPICH2. (And the installation is prepared for that) - The installation files are available here: http://download.mcstas.org/current/windows/ (MPI binaries in the extras/ subfolder).


You list several issues here:

1) Using "strawberry-perl-5.18.2.1-32bit"+"mpich2-1.4.1p1-win-ia32"+"McStas-Metapackage-2.3-win32":

- The error messages respectively indicate that mpiexec.exe and mpi.h are not found. Tweaking the various hardcoded paths in your c:\mcstas-2.3\bin\mpirun.bat and c:\mcstas-2.3\bin\mpicc.bat should fix that.

2) In terms of performance differences between Linux and Windows, my experience is that the choice of compiler more than anything decides the speed. So different versions of gcc may be the origin of what you see.


My general recommendation would be that you move to the newest McStas release, which will give you access to our both our Python and Perl tool sets by default. I am sure mpi + scanning would work under windows there also.

**Comment by haodengfrm2** [comment]
Hi Peter,

I fully agree Python would make the software more flexible. I also really appreciate your group contribute such a powerful software for Neutron Society.

I just tried as you said. I first tried Microsoft MPI, it's not working. Then I switched to "mpich2-1.4.1p1-win-ia32", and now it works.
![mpi32](https://user-images.githubusercontent.com/22814682/33991692-e8e194a2-e0cf-11e7-8575-a7ff4be922c9.png)
Interestingly, it would also take double time (half efficiency) for the same simulation than "strawberry-perl-5.18.2.1-64bit"+"mpich2-1.4.1p1-win-x86-64"+"McStas-Metapackage-2.3-win32". As you said, the 32bit version of gcc may act half the speed as 64bit one.

Best
Hao

**Comment by willend** [comment]
In principle you should have a set of Python tools on your 2.3 system - may require installation of Anaconda 2.2 - e.g. from http://download.mcstas.org/mcstas-2.3/windows/

Otherwise, please consider moving to 2.4.1 which is our supported release.

**Comment by haodengfrm2** [comment]
Hi peter,
the picture from the last reply is a result from 2.4.1+Microsoft MPI.

**Comment by willend** [comment]
OK, thanks - I didn't see that at first. 👍
