### ISSUE TITLE
mcdisplay.pl: Detector shapes in Mantid format has problems 

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#575]
There are issues with the Mantid xml output mode.
- Rectangular detectors seem to be set in the (slightly) wrong place. This is probably caused (in part at least) by a one-off error in the binning interpretation.
- Banana shaped detectors somehow get duplicated (at least in one instance).
- In both cases, the definition of pixel-corners appear unintuitive (will investigate further to determine if also wrong).

**Comment by willend** [comment]
Please also check how mcdisplay-mantid works in this respect

**Comment by ebknudsen** [comment]
analysis and status of the problems:
1. One off-errors in the bin definitions for both rectangular and banana-shaped detectors. This resulted in detectors panels being offset by half a pixel. Fixed by b2c99a8b
2. Banana shaped detectors get wrong when they have >1 y-pixel (row) and are angled. The rows are always stacked according to the global y-direction (and subseq. angled) no matter the orientation of the detector. Fix pending

**Comment by huegle** [comment]
I think I encountered the same bug. It gets pretty bad when you have a detector that has very few pixels in one direction (see attached). A detector that McStas simulates as being 1 meter high and having three bins get written into an xml that is 1.5 meters high.

Is this also the reason why it does not work to have only one pixel in one direction (e.g. x bins 16, y bins 1)? I was trying to simulate some packs of single ended tubes this way. 


[mcstasmantid_idfbug.txt](https://github.com/McStasMcXtrace/McCode/files/1793727/mcstasmantid_idfbug.txt)

**Comment by ebknudsen** [comment]
In the old version this (due to the 1-off error) would lead to a division by 0, which is the error message I'm getting. This works with the fixed version.
