### ISSUE TITLE
McXtrace Comps: mxrun.pl --test has failures

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#578]
A recent run of mxrun.pl --test (for 1.4) revealed a number of failing tests and missing test procedures. This should be fixed - some of them are likely fixed already but investigate.

INFO: ===
Test Abstract for selftest_QRfe
[notest] Test_BM (no test procedure)
[notest] Test_ML_elliptic (no test procedure)
[notest] MAXII_811 (no test procedure)
[notest] TestSAXS (no test procedure)
[notest] Test_Mirror_toroid (no test procedure)
[OK]     Test_PowderN_1 (accuracy, 2 %)
[OK]     Test_Sources_2 (accuracy, 0 %)
[OK]     Test_Sources_3 (accuracy, 0 %)
[OK]     Test_Sources_4 (accuracy, 0 %)
[OK]     Test_Sources_5 (accuracy, 0 %)
[OK]     Test_Sources_6 (accuracy, 0 %)
[OK]     Test_Sources_7 (accuracy, 0 %)
[OK]     Test_Sources_8 (accuracy, 0 %)
[OK]     Test_Sources_9 (accuracy, 0 %)
[notest] DBD_IBM_Si_analyzer (no test procedure)
[notest] MAXII_711 (no test procedure)
[notest] templateSasView (no test procedure)
[notest] ESRF_ID01 (no test procedure)
[notest] XFEL_SPB (no test procedure)
[OK]     template_2Slit_Diff_10 (accuracy not checked)
[notest] MAXIV_DanMAX (no test procedure)
[??????] Test_source_lab_11 (reference not found)
[??????] Test_source_lab_12 (reference not found)
[notest] Test_monitors (no test procedure)
[??????] NSLS2_CHX_13 (reference not found)
[notest] template_simple (no test procedure)
[notest] template_body_simple (no test procedure)
[OK]     JJ_SAXS_14 (accuracy, 1 %)
[notest] template_header_simple (no test procedure)
[notest] Test_CRL (no test procedure)
[OK]     Test_capillary_15 (accuracy, 3 %)
[FAILED] ESRF_ID11_16 (compilation/execution)
[FAILED] Test_MCPL_input_17 (compilation/execution)
[OK]     Test_Filter_18 (accuracy, 1 %)
[OK]     Test_Filter_19 (accuracy, 4 %)
[notest] Pump_probe_solvent (no test procedure)
[notest] Be_BM_beamline (no test procedure)
[notest] SAXS_saxlab (no test procedure)
[OK]     template_1Slit_Diff_20 (accuracy not checked)
[FAILED] Test_undulator_21 (accuracy off by 59 %)
[FAILED] Test_Mono_22 (accuracy off by 51 %)
[notest] MAXIV_FemtoMAX (no test procedure)
[FAILED] Test_MCPL_output_23 (compilation/execution)
[OK]     Test_Saxs_spheres_24 (accuracy, 1 %)
[OK]     Test_Mask_25 (accuracy, 1 %)
[OK]     Test_Mask_26 (accuracy, 1 %)
[notest] Pump_probe (no test procedure)

\# Execution check:    FAILED. 3 instrument(s) did not compile/execute.
\# >> Check instruments and mcxtrace installation.
\# End Date: Fri Jan  5 22:21:47 2018

**Comment by willend** [comment]
Remaining failures are present in detailed form in the new tickets #807 #808 #809 #810 #811 . Closing this one
