### ISSUE TITLE
Multiple scattering simulation fails with 1e7 particles on Windows

### ISSUE THREAD

**Issue by Anders-Markvardsen** [McStasMcXtrace/McCode#582]
Platform: Windows
McStas version 2.4.1 (Jun. 26, 2017)

When trying to run

[Vanadium.zip](https://github.com/McStasMcXtrace/McCode/files/1622263/Vanadium.zip)

to generate a Nexus output that can be read into Mantid this works when the particle count is 1e6 (or lower), in which case the terminal output is:

![capture](https://user-images.githubusercontent.com/1135476/34822526-395c97ba-f6bf-11e7-8399-c0b75c3268af.JPG)

If however I increase the particle count to 1e7 the terminal is:

![capture](https://user-images.githubusercontent.com/1135476/34822601-6aea4dea-f6bf-11e7-9ea4-11832a3345e7.JPG)

In both cases a nexus output is returned, but in the latter case only parts of the data are saved. This can be seen from this HDFview:

![capture](https://user-images.githubusercontent.com/1135476/34822849-3852de50-f6c0-11e7-8000-46284f8e900b.JPG)

**Comment by willend** [comment]
@Anders-Markvardsen,  I can confirm the behaviour. 

@farhi could you help have a short look at this? I never saw the error message before on other systems: The (re-)allocation of the event list buffer at https://github.com/McStasMcXtrace/McCode/blob/af917bf4a5df157893fdd0a3a07a3082212aef8a/mcstas-comps/share/monitor_nd-lib.c#L801 fails. Are there any options= keywords to avoid the realloc (Flag_List=3 mode ?) for a case of storing "all" events?

**Comment by ebknudsen** [comment]
@Anders-Markvardsen @willend : Do you get the same problem when not using NeXus?

**Comment by willend** [comment]
Hi @ebknudsen:
If the file is **compiled** with NeXus and **run without** NeXus, everything works OK here... So NeXus format during runtime is part of the equation.

**Comment by Anders-Markvardsen** [comment]
If I run templateSANS_Mantid in attached zip with 1e7 particles:

[templateSANS_Mantid.zip](https://github.com/McStasMcXtrace/McCode/files/1672953/templateSANS_Mantid.zip)

I get

![capture](https://user-images.githubusercontent.com/1135476/35503309-abcd5cf0-04d7-11e8-951d-25ff57ab0a7f.JPG)

**Comment by willend** [comment]
Hi @Anders-Markvardsen,

I've made a compile-time define that can be used as a workaround for the issue. To try this out, use this installer: [http://tmp.mcstas.org/McStas-Metapackage-2.5beta01-win32.exe](http://tmp.mcstas.org/McStas-Metapackage-2.5beta01-win32.exe)

and define
<pre>
-DMONND_BUFSIZ=100000
</pre>
in your mcgui CFLAGS area.

The image below shows the "usual" simulation of 1e7 with NeXus completing OK:
<img width="921" alt="vmware fusionscreensnapz004" src="https://user-images.githubusercontent.com/8593355/36413889-80397f9c-1620-11e8-9c6a-9fc881f581db.png">

**Comment by Anders-Markvardsen** [comment]
I am trying to install your new windows build above. When I install I see the following: 

![capture](https://user-images.githubusercontent.com/1135476/36442381-88ce18fa-166d-11e8-90df-57ae11bda90e.JPG)

I am not sure if I need to be concerned with this? After installing and within the bin folder I have mcgui.bat and mcgui-pl.bat. The latter starts up, but not if I should use it? The former complains it can find module 'PyQt5'. Do I need to install PyQt separately?

**Comment by willend** [comment]
@Anders-Markvardsen sorry about that, had forgotten this needed fixing after rolling the beta. Will build one ASAP.

**Comment by willend** [comment]
@Anders-Markvardsen could you try the newly uploaded [http://tmp.mcstas.org/McStas-Metapackage-2.5beta02-win32.exe](http://tmp.mcstas.org/McStas-Metapackage-2.5beta02-win32.exe) - may prompt you still for an OK/[y] to install the Python stuff, but at least everything will be downloaded / installed automatically

**Comment by Anders-Markvardsen** [comment]
The above installer installed well, however I find it produces the same results as before.

The results from the mcgui log window running on the instrument file attached in the zip above:

McStas version 2.5beta02 (Feb. 20, 2018)
Copyright (C) DTU Physics and Risoe National Laboratory, 1997-2018
Additions (C) Institut Laue Langevin, 2003-2018
All rights reserved

- Component library: McStas-2.5beta02, built Feb. 20, 2018

Instrument opened: Vanadium.instr
Setting environment:
MCSTAS_OVERRIDE=
 C:\mcstas-2.5beta02\lib\tools\Python\mcgui\..\mccodelib\..\..\..

MCSTAS_CFLAGS_OVERRIDE=
 -g -O2 -lm -DUSE_NEXUS -llibNeXus-0 -I "C:/Program Files (x86)/NeXus Data Format/include/nexus" -L "C:/Program Files (x86)/NeXus Data Format/lib/nexus" -DMONND_BUFSIZ=100000

MCSTAS_CC_OVERRIDE=
 gcc

MCSTAS_MPICC_OVERRIDE=
 mpicc.bat

mcrun --format=NeXus -c Vanadium.instr -n0 
      loading user configuration from C:\Users\ajm64\AppData\mcstas\2.5beta02\mccode_config.json
INFO: No output directory specified (--dir)
INFO: Using directory: "Vanadium_20180220_211517"
INFO: Recompiling: Vanadium.exe
INFO: Regenerating c-file: Vanadium.c
CFLAGS=
INFO: ===
compile thread done 

INFO: No output directory specified (--dir)
INFO: Using directory: "Vanadium_20180220_211530"
INFO: Using existing binary: Vanadium.exe
INFO: ===

start mcdisplay-pl --format=Mantid Vanadium.instr --no-output-files -n 1
INFO: No output directory specified (--dir)
INFO: Using directory: "Vanadium_20180220_211545"
INFO: Using existing binary: Vanadium.exe
INFO: ===

start mcrun --format=NeXus Vanadium.instr -d 1e7new -n 1e7

And the cmd windows show

![capture](https://user-images.githubusercontent.com/1135476/36467887-c4a58f64-16d8-11e8-824e-1602a4af5c39.JPG)

And my mccode_config.json is:

{"configuration": {"MCCODE_VERSION": "2.5beta02", "MCCODE_LIB_DIR": "C:\\mcstas-2.5beta02\\lib\\tools\\Python\\mcgui\\..\\mccodelib\\..\\..\\..", "MCCODE": "mcstas", "MCRUN": "mcrun --format=NeXus", "MCPLOT": "mcplot-pyqtgraph", "MCDISPLAY": "mcdisplay-pl --format=Mantid", "TOOL_NAME": "mcgui", "PARTICLE": "neutron", "BROWSER": "start"}, "compilation": {"CFLAGS": "-g -O2 -lm -DUSE_NEXUS -llibNeXus-0 -I \"C:/Program Files (x86)/NeXus Data Format/include/nexus\" -L \"C:/Program Files (x86)/NeXus Data Format/lib/nexus\" -DMONND_BUFSIZ=100000", "NEXUSFLAGS": "-DUSE_NEXUS -lNeXus", "MPIFLAGS": "-DUSE_MPI -lmpi", "CC": "gcc", "MPICC": "mpicc.bat", "MPIRUN": "mpiexec.exe", "MPINODES": "4"}, "platform": {"EXESUFFIX": "exe"}}

**Comment by willend** [comment]
Everything works OK here. Are you sure you recompiled before running the simulation? (Either through a trivial edit of the instr file or through Simulation->Compile.

**Comment by willend** [comment]
Generated NeXus file attached in this zip:
[mccode.h5.zip](https://github.com/McStasMcXtrace/McCode/files/1743378/mccode.h5.zip)

**Comment by willend** [comment]
And BTW I ran with <pre>-DMONND_BUFSIZ=1000000</pre> (1e6)

**Comment by Anders-Markvardsen** [comment]
Good news and well I beleive less good news. With -DMONND_BUFSIZ=1000000 it works when I am using 1e7 particles, but it fails when I am using 1e8 with the error:

![capture](https://user-images.githubusercontent.com/1135476/36481146-d257379c-1706-11e8-9f8b-7a060d4b7f9e.JPG)

**Comment by willend** [comment]
Yes, I knew this would more or less be the case, sorry. :-) - This is also why I labeled this a "workaround"... As long as your memory allows you may increase MONND_BUFSIZ - I guess a factor of 10 will do it here (total will still be less than GB's I think)

**Comment by Anders-Markvardsen** [comment]
When I increase by a factor of 10 I get:

![capture](https://user-images.githubusercontent.com/1135476/36499369-ec447d18-1738-11e8-96b7-e28e64556599.JPG)

Can you explain again how you suggest setting MONND_BUFSIZ for different particle numbers please and why?

**Comment by willend** [comment]
As said it is a workaround, not a proper patch or solution. 

It works by having a buffer which is "large enough" to hold all event data pr. monitor without writing these to disk/hdf file.

And I must admit I didn't look into the maths of ncount vs. MONND_BUFSIZ enough that I can explain the need for a 100x bigger buffer to hold a 10x larger ncount "yield".

Will go to a workshop / codecamp in Dresden in march with @farhi who is the most well-versed of us into the details of the Monitor_nD logic, hope to have a closer look at the issue there.

**Comment by willend** [comment]
It looks like this may be solved by a recent commit (https://github.com/McStasMcXtrace/McCode/issues/689). Currently running a test with the old 1e4 BUFSIZ to check

**Comment by willend** [comment]
Yup, current master build confirmed to work! 

Both the above-mentioned patch and our 64bit build are likely elements of this coming in place.

**Comment by Anders-Markvardsen** [comment]
Cheers
