### ISSUE TITLE
Another look at font and colormap sizes in mcplot-pyqtgraph overview plot

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#586]
mcplot-pyqtgraph on the attached dataset:
<img width="1288" alt="terminalscreensnapz012" src="https://user-images.githubusercontent.com/8593355/35384719-87f2e430-01c6-11e8-8cf8-80c2c52ef286.png">

mcplot.pl on the same dataset:
<img width="1128" alt="xquartzscreensnapz005" src="https://user-images.githubusercontent.com/8593355/35384757-a6c0d1ba-01c6-11e8-9d71-94e2c63d8a40.png">

dataset:
[Guide_January_short.zip](https://github.com/McStasMcXtrace/McCode/files/1663659/Guide_January_short.zip)

**Comment by climbcat** [comment]
this has arguably been iplemented by 5302c43494cc3e099b5dfdae5b39a01b20481c4f - testing requested

**Comment by willend** [comment]
Corrected, closing
