### ISSUE TITLE
Displaying many tuning variables in the python GUI

### ISSUE THREAD

**Issue by rasmustp** [McStasMcXtrace/McCode#598]
Dear McStas team, 

I have an instrument file with a crazy number of variables. When I run the newest version of McStas - using the python GUI - i get a window that is too large for my screen, and I am unable to resize it. The large number of parameters seem to lock the size of the window. 

Might it be possible to have a scroll mechanism or similar? I have attached the instrument file with support components. 

Cheers

RAsmus
[ProblemInstrument.zip](https://github.com/McStasMcXtrace/McCode/files/1762600/ProblemInstrument.zip)

**Comment by willend** [comment]
If you want to patch this to your local installation, one way would is to change every integer division % 6 to % 12 in the function createParamsWidgets of the file viewclasses.py, which exists in your c:\\mcstas-2.4.1\\tools\\Python\\mcgui folder

**Comment by willend** [comment]
Closing this one as I have defined #610 to implement the above solution (user configurable)
