### ISSUE TITLE
Some tasks for code simplification (short term) and porting (long term)

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McCode#602]
Objective: Reduce complexity of the mccode platform to free up brain-cpu power for the development of solutions. 

Goal: Focus on complexity reduction in terms of the generated .c code. Since GPU implementations are relatively low level, targeting this for comprehension and readability should allow for quicker dev/test cycles.

Short term:
- Get rid of all "mc" prefixes (cogen3 should make this "protection strategy" redundant?)
- Re-factor all global variables into local context/state variable(s) that can be passed into the component functions
- Reorganize the generated .c file in clear sections. For ex.: library functions, imports, component code section, engine/loop section.
- Documentation headers needs to be deleted and updated, add section headers, etc.
- Split up the generated .c into more files e.g. core-lib, engine, components, user-lib

Medium/Long term:
- Rewrite/port the instrument parser into a high-level language (Python of cause) to further rationalize development cycles
- Rewrite/port the cogen also

Long term, one approach: Targeting GPU in an organized manor
- Target a component subset for GPU porting
- Target a subset of the mcstas/mxtrace features
- Implement a batch-based approach to maximal GPU processing and memory utilization.
- Apply the newly gained platform experience and GPU/acc knowledge to draft some DSL- or component level architectural features for parallelization. This should aid users who wish to utilize the GPU in the future.

**Comment by ebknudsen** [comment]
outdated
