### ISSUE TITLE
possible sweep output mcstas.dat bug related to this change: 6639...

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McCode#603]
[PSI_DMC_1Peak.txt](https://github.com/McStasMcXtrace/McCode/files/1834325/PSI_DMC_1Peak.txt)

**Comment by climbcat** [comment]
51fda08c48117fd1e389a6f8913c15430441d479

**Comment by willend** [comment]
@climbcat any recollection about what the issue was and what the status is?
