### ISSUE TITLE
Garbage output with MCPL on Windows 10

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#617]
Looking at the output of mcpltool on windows, the particle data looks OK:

**Windows:**
<pre>
C:\mcstas-2.4.1\lib\libs\mcpl>mcpltool synts.mcpl
Opened MCPL file synts.mcpl:

  Basic info
    Format             : MCPL-2
    No. of particles   : 1000
    Header storage     : 105 bytes
    Data storage       : 32000 bytes

  Custom meta data
    Source             : "FakeMcStas-v2.2a"
    Number of comments : 2
          -> comment 0 : "Some comment."
          -> comment 1 : "Another comment."
    Number of blobs    : 0

  Particle data format
    User flags         : no
    Polarisation info  : no
    Fixed part. type   : yes (pdgcode 2112)
    Fixed part. weight : no
    FP precision       : single
    Endianness         : little
    Storage            : 32 bytes/particle

index     pdgcode   ekin[MeV]       x[cm]       y[cm]       z[cm]          ux          uy          uz    time[ms]      weight
    0        2112 1.0103e+011       16807 2.8248e+008 1.6227e+009     0.62291     0.72357     0.29738 1.4579e+009 1.4588e+009
    1        2112 1.1375e+012 2.0072e+009 8.2356e+008 1.1154e+009     0.99708    0.041483    0.064149 1.4413e+009 1.6532e+007
    2        2112 1.8171e+012 8.2338e+008 1.4354e+008 8.9654e+008     0.52919     0.45383     0.71694 1.1316e+009 1.9749e+008
    3        2112 1.0193e+011 1.4043e+009 8.9335e+008 1.5058e+009     0.74866     0.62684     0.21584 1.5807e+009 7.0488e+008
    4        2112 1.5519e+012 1.3586e+009 1.6244e+009 2.1282e+009     0.33922     0.22938     0.91231 1.6178e+009 1.3991e+009
    5        2112 1.0259e+012 1.5609e+008 1.3564e+009 1.8999e+009     0.29539      0.4727     0.83024 5.1062e+008 5.9036e+008
    6        2112 1.9427e+012 7.7152e+008 3.5757e+008 1.0448e+009     0.70178     0.71081    0.047349 1.0835e+009 1.1087e+009
    7        2112 1.5837e+011 6.8512e+008 2.1188e+009 1.0608e+009     0.26921     0.09178      0.9587 1.0753e+009 8.2494e+008
    8        2112 1.6353e+012 5.9503e+008 1.9624e+009 1.1376e+009      0.4421      0.8957    0.047674  1.654e+009 1.7777e+009
    9        2112 1.5578e+012 2.6922e+008 3.4076e+007 1.4784e+009     0.66745     0.48395     0.56596 2.1463e+009 1.9082e+009

C:\mcstas-2.4.1\lib\libs\mcpl>
</pre>

**Same on Unix:**
<pre>
pkwi-mbp2016:mcpl pkwi$ mcpltool synts.mcpl 
Opened MCPL file synts.mcpl:

  Basic info
    Format             : MCPL-2
    No. of particles   : 1000
    Header storage     : 105 bytes
    Data storage       : 32000 bytes

  Custom meta data
    Source             : "FakeMcStas-v2.2a"
    Number of comments : 2
          -> comment 0 : "Some comment."
          -> comment 1 : "Another comment."
    Number of blobs    : 0

  Particle data format
    User flags         : no
    Polarisation info  : no
    Fixed part. type   : yes (pdgcode 2112)
    Fixed part. weight : no
    FP precision       : single
    Endianness         : little
    Storage            : 32 bytes/particle

index     pdgcode   ekin[MeV]       x[cm]       y[cm]       z[cm]          ux          uy          uz    time[ms]      weight
    0        2112  1.0103e+11       16807  2.8248e+08  1.6227e+09     0.62291     0.72357     0.29738  1.4579e+09  1.4588e+09
    1        2112  1.1375e+12  2.0072e+09  8.2356e+08  1.1154e+09     0.99708    0.041483    0.064149  1.4413e+09  1.6532e+07
    2        2112  1.8171e+12  8.2338e+08  1.4354e+08  8.9654e+08     0.52919     0.45383     0.71694  1.1316e+09  1.9749e+08
    3        2112  1.0193e+11  1.4043e+09  8.9335e+08  1.5058e+09     0.74866     0.62684     0.21584  1.5807e+09  7.0488e+08
    4        2112  1.5519e+12  1.3586e+09  1.6244e+09  2.1282e+09     0.33922     0.22938     0.91231  1.6178e+09  1.3991e+09
    5        2112  1.0259e+12  1.5609e+08  1.3564e+09  1.8999e+09     0.29539      0.4727     0.83024  5.1062e+08  5.9036e+08
    6        2112  1.9427e+12  7.7152e+08  3.5757e+08  1.0448e+09     0.70178     0.71081    0.047349  1.0835e+09  1.1087e+09
    7        2112  1.5837e+11  6.8512e+08  2.1188e+09  1.0608e+09     0.26921     0.09178      0.9587  1.0753e+09  8.2494e+08
    8        2112  1.6353e+12  5.9503e+08  1.9624e+09  1.1376e+09      0.4421      0.8957    0.047674   1.654e+09  1.7777e+09
    9        2112  1.5578e+12  2.6922e+08  3.4076e+07  1.4784e+09     0.66745     0.48395     0.56596  2.1463e+09  1.9082e+09
</pre>

**But the test instrument produces garbage**?? (check particle data below...)
<pre>
:\Users\pwill\Desktop\MCPL>mcrun-pl -c Test_MCPL_input.instr -n0
*** No directory given - placing data in Test_MCPL_input_20180522_131607 ***
Translating instrument definition 'Test_MCPL_input.instr' into C ...
mcstas -t -o Test_MCPL_input.c Test_MCPL_input.instr
      CFLAGS= -DMCPLPATH=@MCCODE_LIB@/libs/mcpl/voutput.mcpl -I@MCCODE_LIB@/libs/mcpl -L@MCCODE_LIB@/libs/mcpl -lmcpl
Compiling C source 'Test_MCPL_input.c' ...
gcc -o Test_MCPL_input.exe Test_MCPL_input.c -lm -g -O2 -lm -DMCPLPATH=C:\\mcstas-2.4.1\\lib/libs/mcpl/voutput.mcpl -IC:\\mcstas-2.4.1\\lib/libs/mcpl -LC:\\mcstas-2.4.1\\lib/libs/mcpl -lmcpl
mccode-r.c: In function 'mcuse_dir':
mccode-r.c:2053:8: warning: implicit declaration of function 'mkdir' [-Wimplicit-function-declaration]
mccode-r.h:214:27: note: in definition of macro 'MPI_MASTER'
mccode-r.c: In function 'sighandler':
mccode-r.c:3611:64: warning: implicit declaration of function 'getpid' [-Wimplicit-function-declaration]
Running simulation 'Test_MCPL_input.exe' ...
Test_MCPL_input.exe --dir=Test_MCPL_input_20180522_131607 --format=PGPLOT --ncount=0

C:\Users\pwill\Desktop\MCPL>
C:\Users\pwill\Desktop\MCPL>
C:\Users\pwill\Desktop\MCPL>
C:\Users\pwill\Desktop\MCPL>Test_MCPL_input.exe
Instrument parameters for Test_MCPL_input (Test_MCPL_input.instr)
Set value of instrument parameter repeat (double) [default='1']:

Set value of instrument parameter E_smear (double) [default='0.1']:

Set value of instrument parameter pos_smear (double) [default='0.001']:

Set value of instrument parameter dir_smear (double) [default='0.01']:

Using the input file: C:\mcstas-2.4.1\lib/libs/mcpl/voutput.mcpl
[Test_MCPL_input] Initialize
Message(vin): MCPL file (C:\mcstas-2.4.1\lib/libs/mcpl/voutput.mcpl) produced with McStas 2.3rc12 Test_MCPL_output.
Message(vin): MCPL file (C:\mcstas-2.4.1\lib/libs/mcpl/voutput.mcpl) contains 1000 particles.

 Warning: You are using MCPL_input with a repeat_count of 1:
 - Minimum neutron count requested is 1000 x 0 <= 1 neutrons total

Initialize ncount is 1000
MCPL_input verbose mode - outputting data on the 10 first read neutrons in MCPL units:
id=1 pdg=2112   ekin=9.57271e-178 MeV   x=-8.2632e+121 cm       y=-1.22325e-296 cm      z=1.58946e-314 cm       ux=-8.03656e-082        uy=1.75277e+275 uz=7.03642e-042 t=9.94647e+086 ms       weight=-8.93957e-167       polx=5.4306e-315        poly=0  polz=0
id=2 pdg=2112   ekin=5.32221e+177 MeV   x=-2.46006e+260 cm      y=-4.23517e-022 cm      z=1.5899e-314 cm        ux=3.21989e-147 uy=-6.61017e-214        uz=-1.93891e+049        t=-1.88275e-183 ms      weight=6.65247e-120        polx=5.43979e-315       poly=0  polz=0
id=3 pdg=2112   ekin=4.6969e+199 MeV    x=-1.8348e+106 cm       y=7.41842e-068 cm       z=5.27718e-315 cm       ux=4.73007e+296 uy=-1.68418e-150        uz=-6.0715e-146 t=-2.14302e+301 ms      weight=5.69127e-306        polx=5.44207e-315       poly=0  polz=0
id=4 pdg=2112   ekin=-2.38466e+121 MeV  x=-4.19867e-140 cm      y=4.57671e-246 cm       z=5.2889e-315 cm        ux=-1.3084e+170 uy=2.21562e+255 uz=-3.30399e-266        t=9.36336e-097 ms       weight=4.91956e+277        polx=5.42439e-315       poly=0  polz=0
id=5 pdg=2112   ekin=2.83892e-111 MeV   x=4.38362e-193 cm       y=-1.88275e-183 cm      z=5.28068e-315 cm       ux=2.37693e+101 uy=4.08628e+170 uz=-1.04588e-150        t=2.00012 ms    weight=-1.36884e+084       polx=9.60223e-315       poly=0  polz=0
id=8 pdg=2112   ekin=-6.04246e-210 MeV  x=2.3371e-315 cm        y=-1.35346e-312 cm      z=4.06976e-312 cm       ux=-6.64378e-103        uy=3.95352e-193 uz=1.256e-314   t=1.32094e-312 ms       weight=2.01762e+196        polx=1.39169e-312       poly=0  polz=0
id=9 pdg=2112   ekin=1.47887e-189 MeV   x=2.85666e-315 cm       y=6.78376e-312 cm       z=4.07013e-312 cm       ux=0    uy=0    uz=0    t=-2.68172e+154 ms      weight=5.75923e+195     polx=1.39262e-312
poly=0  polz=0
id=11 pdg=2112  ekin=-1.08998e-103 MeV  x=9.38432e-316 cm       y=3.46837e-310 cm       z=1.04212e-309 cm       ux=0    uy=1.061e-314   uz=1.061e-314   t=3.37716e-310 ms       weight=-1.47143e+276    polx=3.57035e-310  poly=0  polz=0
id=12 pdg=2112  ekin=-2.31696e-034 MeV  x=1.39068e-309 cm       y=-1.#QNAN cm   z=3.46896e-310 cm   ux=0        uy=0    uz=0    t=3.36973e-310 ms       weight=4.07912e-238     polx=3.56752e-310       poly=0     polz=0
id=15 pdg=2112  ekin=1.35264e-193 MeV   x=4.6982e-315 cm        y=2.43279e-309 cm       z=1.04229e-309 cm       ux=5.30859e+185 uy=1.08488e-160 uz=5.30859e+185 t=3.37434e-310 ms       weight=3.99443e-082        polx=3.56471e-310       poly=0  polz=0
</pre>

**Comment by willend** [comment]
Supplemental (reduced) file output from Test_MCPL_input

OS X:
[OSX_output_short.txt](https://github.com/McStasMcXtrace/McCode/files/2034837/OSX_output_short.txt)

Win 10:
[WIN_output_short.txt](https://github.com/McStasMcXtrace/McCode/files/2034839/WIN_output_short.txt)

Notice how the particle index doesn't flow the same way!! (But the first 3-4 particles kind of look OK on Windows.

**Comment by tkittel** [comment]
I am not sure I 100% understand which parts of those two files you are referring to? The first line that looks like related to MCPL seems to contain garbage in the windows file.

And this is now the MCPL *input* component? Reading a supposedly buggy mcpl file created on the same platform, or reading another file which is supposed to OK?

**Comment by willend** [comment]
Easy now @tkittel :-) The stuff here is McStas-oriented output, and put here essentially for my own reference as I dig through/understand what is going on. Currently the assumption is that @ebknudsen or I messed something up on the McStas side of things...

The moment this turns out to be identified as a proper MCPL bug, it will of course go to the issue list for that project...

**Comment by tkittel** [comment]
Ok, fair enough. I'll ignore this then until you realise it is indeed my mess :-)

**Comment by willend** [comment]
👍 Deal :-)

**Comment by willend** [comment]
Test_MCPL_output does not immediately compile on Windows. A work-around is to add an <pre>#include <sys/stat.h></pre> in the component. (Separate issue defined ont that problem here: https://github.com/McStasMcXtrace/McCode/issues/618)

Particle status output looks broken from the COMP side, but resulting MCPL files are close to identical...

OS X:
https://www.dropbox.com/s/8qua2k3e644gfo7/OSX_voutput.mcpl.gz?dl=1

Win 10:
https://www.dropbox.com/s/s1uidpq3va1nkyd/WIN10_voutput.mcpl.gz?dl=1

**Comment by willend** [comment]
I turned out there were multiple issues - but all in the McStas layer:

1) Garbage example mcpl files distributed w. mcstas due to "todos" calls also on binary files. Fixed by future use of unix2dos instead (https://github.com/McStasMcXtrace/McCode/commit/3ff5cf80da8e75836f1577ef8e79d5a9aac6b5fb)

2) Error in presentation of data from mcpl files in the MCPL_input component due to use of %lu rather than the more portable PRIu64 (https://github.com/McStasMcXtrace/McCode/commit/58e7768455271c1c9ecd6a4df3c3d95701d05709)
