### ISSUE TITLE
example ESS_2015_test.instr uses unavailable ESS_moderator_corr component

### ISSUE THREAD

**Issue by farhi** [McStasMcXtrace/McCode#626]
The `ESS_2015_test` test instrument uses an instance of the `ESS_moderator_corr` component which is not part of the current component library (main branch).

**Comment by willend** [comment]
OK, thanks for reporting that. I will have a look, but likely we should just retire that instr

**Comment by farhi** [comment]
Fixed with commit d3240fbde8cbc816f106a20a0e86781e51cec2f8
Now using the `ESS_moderator` component (not `_corr` version)
