### ISSUE TITLE
ESS_butterfly: variable dt in TRACE used but not assigned

### ISSUE THREAD

**Issue by farhi** [McStasMcXtrace/McCode#627]
cogen3 reveals that the variable 'dt' is not assigned (except locally in a `{}` sub block), but is used when calling function `cold_bril` and `thermal_bril`. In fact this is not blocking, as 'dt' is not used in the called these functions. This parameter may then be removed.

**Comment by willend** [comment]
Thanks. Is used in the case of "time focusing" with the ESS source.

It should simply be declared (and initialised to 0) in the global scope, potentially reset to non-zero value like this:   

<pre>
if (tfocus_width>0) {
    dt = tfocus_dist/vz;
...
</pre>

- and then propagated into the _bril( functions that I believe indeed make use of the value...

Will correct later.

**Comment by farhi** [comment]
Fixed with commit 66e70959bd60e5c80e8f21a4b29cbdb441f528cc
Perhaps this fix should be checked for the 'time focusing'
