### ISSUE TITLE
mcgui: edit button should raise() the window (especially on windows)

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McCode#629]

**Comment by willend** [comment]
It would also be good with explicit raise() on the various plotters / mcdisplays

**Comment by climbcat** [comment]
There is indeed a raise_() call for every time one clicks the "Edit" button. Perhaps the latest version of PYQT has a more robust call.

**Comment by climbcat** [comment]
A bug has been fixed and this should work as intended, as by 5f41bd5a6975fe6cc5a40988a8485ab85d040ed2.

**Comment by willend** [comment]
Tested and works, closing
