### ISSUE TITLE
Cogen3 branch: Status of instrument porting

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#632]
From @farhi :

> branch: Dresden-2018-cogen3-openACC-topdown
> 
> Directory: mcstas-comps/examples-full
> Failed: 89
> Compiled: 87
> The number of compiled instruments dropped due to a change I made in cogen.c.in, but this is going in the right direction though. Current lists:
> 
> Failed:
> 
>   'ESS_2015_test.instr'
>   'ESS_butterfly_Guide_curved_test.instr'
>   'ESS_butterfly_MCPL_test.instr'
>   'ESS_butterfly_tfocus_NOFOCUS_test.instr'
>   'ESS_mcpl2hist.instr'
>   'FZJ_BenchmarkSfin2.instr'
>   'Granroth_SNS_decoupled_poisoned.instr'
>   'HZB_FLEX.instr'
>   'Histogrammer.instr'
>   'ILL_H10_IN8.instr'
>   'ILL_H13_IN20.instr'
>   'ILL_H142_IN12.instr'
>   'ILL_H143_LADI.instr'
>   'ILL_H15_IN6.instr'
>   'ILL_H16_IN5.instr'
>   'ILL_H16_IN5_Mantid.instr'
>   'ILL_H22_D1A.instr'
>   'ILL_H22_D1B.instr'
>   'ILL_H22_VIVALDI.instr'
>   'ILL_H25_IN22.instr'
>   'ILL_H5.instr'
>   'ILL_H53_D16.instr'
>   'ILL_H53_IN14.instr'
>   'ILL_H5_new.instr'
>   'ILL_H8_IN1.instr'
>   'ILL_IN13.instr'
>   'ILL_IN5.instr'
>   'ILL_IN5_Mantid.instr'
>   'ILL_IN6.instr'
>   'ISIS_CRISP.instr'
>   'ISIS_GEM.instr'
>   'ISIS_MERLIN.instr'
>   'ISIS_OSIRIS.instr'
>   'RITA-II.instr'
>   'Reflectometer.instr'
>   'SAFARI_MPISI.instr'
>   'SEMSANS_instrument.instr'
>   'SE_example.instr'
>   'SE_example2.instr'
>   'SNS_ARCS.instr'
>   'SNS_test.instr'
>   'TestSANS.instr'
>   'Test_Fermi.instr'
>   'Test_Guides.instr'
>   'Test_Guides_Curved.instr'
>   'Test_MCPL_input.instr'
>   'Test_Magnetic_Constant.instr'
>   'Test_Magnetic_Majorana.instr'
>   'Test_Magnetic_Rotation.instr'
>   'Test_Magnetic_Userdefined.instr'
>   'Test_Monochromators.instr'
>   'Test_Pol_Bender.instr'
>   'Test_Pol_Bender_Vs_Guide_Curved.instr'
>   'Test_Pol_Guide_Vmirror.instr'
>   'Test_Pol_Mirror.instr'
>   'Test_Pol_TripleAxis.instr'
>   'Test_PreMonitor_nD.instr'
>   'Test_SSR_SSW.instr'
>   'Test_SSR_SSW_Guide.instr'
>   'Test_Sample_nxs_diffraction.instr'
>   'Test_Sample_nxs_imaging.instr'
>   'Test_Scatter_log_losses.instr'
>   'Test_Scatter_log_mvalues.instr'
>   'Test_Scatter_log_ssw_mcnp.instr'
>   'Test_Sources.instr'
>   'Test_StatisticalChopper.instr'
>   'Test_pol_tabled.instr'
>   'Test_shellguides.instr'
>   'Union_demonstration.instr'
>   'Union_demonstration_absorption_image.instr'
>   'Union_external_component.instr'
>   'Union_external_component_test.instr'
>   'Union_incoherent_validation.instr'
>   'Union_laue_camera.instr'
>   'Union_manual_example.instr'
>   'Union_powder_validation.instr'
>   'Union_sample_picture_replica.instr'
>   'Union_single_crystal_validation.instr'
>   'Union_tagging_demo.instr'
>   'Union_test_absorption.instr'
>   'Union_test_absorption_image.instr'
>   'Union_test_box.instr'
>   'Union_test_mask.instr'
>   'Union_test_powder.instr'
>   'Union_time_of_flight.instr'
>   'Vin_test.instr'
>   'Vout_test.instr'
>   'templateSasView.instr'
>   'templateSasView_Mantid.instr'

**Comment by farhi** [comment]
Now have :
- Failed: 75
- Compiled: 101

There is grammar issue with `%include` instruments. Will fix.
Detailed list of faulty instruments (most probably components) :

```
    'FZJ_BenchmarkSfin2.instr'
    'Granroth_SNS_decoupled_poisoned.instr'
    'Histogrammer.instr'
    'ILL_H10_IN8.instr'
    'ILL_H13_IN20.instr'
    'ILL_H142_IN12.instr'
    'ILL_H143_LADI.instr'
    'ILL_H15_IN6.instr'
    'ILL_H16_IN5.instr'
    'ILL_H16_IN5_Mantid.instr'
    'ILL_H22_D1A.instr'
    'ILL_H22_D1B.instr'
    'ILL_H22_VIVALDI.instr'
    'ILL_H25_IN22.instr'
    'ILL_H5.instr'
    'ILL_H53_D16.instr'
    'ILL_H53_IN14.instr'
    'ILL_H5_new.instr'
    'ILL_H8_IN1.instr'
    'ISIS_MERLIN.instr'
    'ISIS_OSIRIS.instr'
    'RITA-II.instr'
    'Reflectometer.instr'
    'SEMSANS_instrument.instr'
    'SE_example.instr'
    'SE_example2.instr'
    'SNS_ARCS.instr'
    'SNS_test.instr'
    'TestSANS.instr'
    'Test_Fermi.instr'
    'Test_Guides.instr'
    'Test_Guides_Curved.instr'
    'Test_MCPL_input.instr'
    'Test_Magnetic_Constant.instr'
    'Test_Magnetic_Majorana.instr'
    'Test_Magnetic_Rotation.instr'
    'Test_Magnetic_Userdefined.instr'
    'Test_Monochromators.instr'
    'Test_Pol_Bender.instr'
    'Test_Pol_Bender_Vs_Guide_Curved.instr'
    'Test_Pol_Guide_Vmirror.instr'
    'Test_Pol_Mirror.instr'
    'Test_Pol_TripleAxis.instr'
    'Test_PreMonitor_nD.instr'
    'Test_SSR_SSW.instr'
    'Test_SSR_SSW_Guide.instr'
    'Test_Sample_nxs_diffraction.instr'
    'Test_Sample_nxs_imaging.instr'
    'Test_Scatter_log_losses.instr'
    'Test_Scatter_log_mvalues.instr'
    'Test_Scatter_log_ssw_mcnp.instr'
    'Test_Sources.instr'
    'Test_StatisticalChopper.instr'
    'Test_pol_tabled.instr'
    'Test_shellguides.instr'
    'Union_demonstration.instr'
    'Union_demonstration_absorption_image.instr'
    'Union_external_component.instr'
    'Union_external_component_test.instr'
    'Union_incoherent_validation.instr'
    'Union_laue_camera.instr'
    'Union_manual_example.instr'
    'Union_powder_validation.instr'
    'Union_sample_picture_replica.instr'
    'Union_single_crystal_validation.instr'
    'Union_tagging_demo.instr'
    'Union_test_absorption.instr'
    'Union_test_absorption_image.instr'
    'Union_test_box.instr'
    'Union_test_mask.instr'
    'Union_test_powder.instr'
    'Union_time_of_flight.instr'
    'Vin_test.instr'
    'templateSasView.instr'
    'templateSasView_Mantid.instr'
```

**Comment by farhi** [comment]
cogen3 Commit b35860f95ba04474608ab00f8c2d54f77c976b90 now provides:

- Directory: Dresden-2018-cogen3-openACC-topdown/mcstas-comps/examples-full
- Failed:   62
- Compiled: 114

The list of failed instrument examples is now:

```
    'ILL_BRISP.instr'
    'ILL_H10_IN8.instr'
    'ILL_H13_IN20.instr'
    'ILL_H142_IN12.instr'
    'ILL_H143_LADI.instr'
    'ILL_H15_IN6.instr'
    'ILL_H16_IN5.instr'
    'ILL_H16_IN5_Mantid.instr'
    'ILL_H22_D1A.instr'
    'ILL_H22_D1B.instr'
    'ILL_H22_VIVALDI.instr'
    'ILL_H25_IN22.instr'
    'ILL_H5.instr'
    'ILL_H53_D16.instr'
    'ILL_H53_IN14.instr'
    'ILL_H5_new.instr'
    'ILL_H8_IN1.instr'
    'ILL_IN4.instr'
    'ILL_IN6.instr'
    'ISIS_HET.instr'
    'ISIS_MERLIN.instr'
    'PSI_Focus.instr'
    'Reflectometer.instr'
    'SE_example2.instr'
    'TestSANS.instr'
    'Test_Fermi.instr'
    'Test_Guides.instr'
    'Test_Guides_Curved.instr'
    'Test_MCPL_input.instr'
    'Test_Pol_Bender.instr'
    'Test_Pol_Bender_Vs_Guide_Curved.instr'
    'Test_Pol_Guide_Vmirror.instr'
    'Test_PreMonitor_nD.instr'
    'Test_SSR_SSW.instr'
    'Test_SSR_SSW_Guide.instr'
    'Test_Sample_nxs_diffraction.instr'
    'Test_Sample_nxs_imaging.instr'
    'Test_Scatter_log_losses.instr'
    'Test_Scatter_log_mvalues.instr'
    'Test_Scatter_log_ssw_mcnp.instr'
    'Test_Sources.instr'
    'Test_StatisticalChopper.instr'
    'Test_shellguides.instr'
    'Union_demonstration.instr'
    'Union_demonstration_absorption_image.instr'
    'Union_external_component.instr'
    'Union_external_component_test.instr'
    'Union_incoherent_validation.instr'
    'Union_laue_camera.instr'
    'Union_manual_example.instr'
    'Union_powder_validation.instr'
    'Union_sample_picture_replica.instr'
    'Union_single_crystal_validation.instr'
    'Union_tagging_demo.instr'
    'Union_test_absorption.instr'
    'Union_test_absorption_image.instr'
    'Union_test_box.instr'
    'Union_test_mask.instr'
    'Union_test_powder.instr'
    'Union_time_of_flight.instr'
    'templateSasView.instr'
    'templateSasView_Mantid.instr'
```

**Comment by farhi** [comment]
Commit 2779386e275bda8de932a27a757929a897fb3d3b (silly missing ';' )
Directory: Dresden-2018-cogen3-openACC-topdown/mcstas-comps/examples-full
Failed:   56
Compiled: 120

**Comment by farhi** [comment]
Commit ad434d9f602b9d526a06b0cc5c3e1a4b51377967
Directory: Dresden-2018-cogen3-openACC-topdown/mcstas-comps/examples-full
Failed:   45
Compiled: 131

**Union** and **%include** instruments currently fail.
Failed compilation for:
```
    'ILL_H10_IN8.instr'
    'ILL_H13_IN20.instr'
    'ILL_H142_IN12.instr'
    'ILL_H143_LADI.instr'
    'ILL_H15_IN6.instr'
    'ILL_H16_IN5.instr'
    'ILL_H16_IN5_Mantid.instr'
    'ILL_H22_D1A.instr'
    'ILL_H22_D1B.instr'
    'ILL_H22_VIVALDI.instr'
    'ILL_H25_IN22.instr'
    'ILL_H53_D16.instr'
    'ILL_H53_IN14.instr'
    'ILL_H5_new.instr'
    'ILL_H8_IN1.instr'
    'Reflectometer.instr' ********** Issue #628: will not fix ?
    'SE_example2.instr'
    'Test_Fermi.instr'
    'Test_SSR_SSW.instr'
    'Test_SSR_SSW_Guide.instr'
    'Test_Sample_nxs_diffraction.instr'
    'Test_Sample_nxs_imaging.instr'
    'Test_Scatter_log_losses.instr'
    'Test_Scatter_log_mvalues.instr'
    'Test_Scatter_log_ssw_mcnp.instr'
    'Test_shellguides.instr'
    'Union_demonstration.instr'
    'Union_demonstration_absorption_image.instr'
    'Union_external_component.instr'
    'Union_external_component_test.instr'
    'Union_incoherent_validation.instr'
    'Union_laue_camera.instr'
    'Union_manual_example.instr'
    'Union_powder_validation.instr'
    'Union_sample_picture_replica.instr'
    'Union_single_crystal_validation.instr'
    'Union_tagging_demo.instr'
    'Union_test_absorption.instr'
    'Union_test_absorption_image.instr'
    'Union_test_box.instr'
    'Union_test_mask.instr'
    'Union_test_powder.instr'
    'Union_time_of_flight.instr'
    'templateSasView.instr'
    'templateSasView_Mantid.instr'
```

**Comment by farhi** [comment]
Commit d5810326838a0f14812a694dc04d9c7905ffd68b
Directory: Dresden-2018-cogen3-openACC-topdown/mcstas-comps/examples-full
Failed:   42
Compiled: 134

**Comment by farhi** [comment]
Commit 931466a4b287d5f70f9273f5beacfc547c571d88
Directory: Dresden-2018-cogen3-openACC-topdown/mcstas-comps/examples-full
Failed:   29
Compiled: 147

**Comment by climbcat** [comment]
Current status of instrument port: High compile rate, and the tests that exist, pretty much all run! (Tested with mctest-py.)

- SEMSANS instrument compile error is related to a #define based selection of a function, this is one of the few "missing features" of cogen3.
- recentt "GPU" instruments don't compile, but this is semi-expected, these instruments are highly experimental at this point. 

<pre>
BNL_H8                              :   2.92
BNL_H8_simple                       :   2.79
Demo_shape_primitives               :   1.90
ESS_2001_bispectral                 :   3.00
ESS_2015_test                       :   2.23
ESS_Brilliance_2001                 :   3.57
ESS_Brilliance_2013                 :   3.57
ESS_Brilliance_2014                 :   3.60
ESS_Brilliance_2015                 :   3.70
ESS_Brilliance_TDR                  :   3.59
ESS_IN5_reprate                     :   4.09
ESS_butterfly_Guide_curved_test     :   4.86
ESS_butterfly_MCPL_test             :   4.95
ESS_butterfly_test                  :   3.98
ESS_butterfly_tfocus_NOFOCUS_test   :   4.03
ESS_butterfly_tfocus_test           :   4.04
ESS_mcpl2hist                       :   2.82
FZJ_BenchmarkSfin2                  :   0.13
FZJ_KWS2_Lens                       :   2.29
FZJ_SANS_KWS2_AnySample             :   2.44
Gallmeier_SNS_decoupled_poisoned    :   1.59
Granroth_SNS_decoupled_poisoned     :   1.57
HZB_FLEX                            :   4.01
HZB_NEAT                            :   6.10
Histogrammer                        :   3.61
ILL_D2B                             :   5.09
ILL_D4                              :   4.59
ILL_H10_IN8                         :   5.03
ILL_H113                            :   7.62
ILL_H13_IN20                        :   5.04
ILL_H142                            :   8.27
ILL_H142_IN12                       :  10.40
ILL_H143_LADI                       :   7.42
ILL_H15                             :   6.31
ILL_H15_IN6                         :   9.19
ILL_H16                             :   4.52
ILL_H16_IN5                         :   7.59
ILL_H16_IN5_Mantid                  :   7.60
ILL_H16_Mantid                      :   4.49
ILL_H22                             :   7.58
ILL_H22_D1A                         :   8.96
ILL_H22_D1B                         :   9.21
ILL_H22_VIVALDI                     :   9.11
ILL_H24                             :   6.57
ILL_H25                             :   7.02
ILL_H25_IN22                        :   9.08
ILL_H5                              :  23.37
ILL_H512_D22                        :   7.47
ILL_H53                             :   6.33
ILL_H53_D16                         :   8.30
ILL_H8_IN1                          :   4.97
ILL_IN13                            :   4.36
ILL_IN4                             :   7.14
ILL_IN5                             :   5.99
ILL_IN5_Mantid                      :   7.30
ILL_IN6                             :   6.59
ILL_Lagrange                        :   7.15
ISIS_CRISP                          :   3.66
ISIS_GEM                            :   4.12
ISIS_HET                            :   4.61
ISIS_MERLIN                         :   4.00
ISIS_OSIRIS                         :   6.75
ISIS_Prisma2                        :   4.41
ISIS_SANS2d                         :   3.11
ISIS_SANS2d_Mantid                  :   5.78
ISIS_TS1_Brilliance                 :   2.09
ISIS_TS2_Brilliance                 :   2.13
ISIS_test                           :   3.74
LLB_6T2                             :   4.51
MCPL2hist                           :   3.63
Mezei_SNS_decoupled_poisoned        :   1.64
PSI_DMC                             :   5.48
PSI_Focus                           :   7.03
RITA-II                             :  11.16
RTP_DIF                             :   3.99
RTP_Laue                            :   3.69
RTP_NeutronRadiography              :   3.51
RTP_SANS                            :   4.27
Reflectometer                       :   0.11
SAFARI_MPISI                        :   5.00
SAFARI_PITSI                        :   4.43
template_simple                     : COMPILE ERROR using:
mcrun --info /tmp/mctest/20191021_2016_40/3.0-dev/SEMSANS_instrument/SEMSANS_instrument.instr
SNS_ARCS                            :   3.90
SNS_BASIS                           :   9.20
SNS_analytic_test                   :   2.84
SNS_test                            :   2.68
Samples_Incoherent                  :   5.45
Samples_Incoherent_off              :   2.91
Samples_Isotropic_Sqw               :   3.78
Samples_Phonon                      :   1.41
Samples_vanadium                    :   1.48
TestSANS                            :   1.70
Test_Collimator_Radial              :   3.51
Test_FocalisationMirrors            :   2.07
Test_Jump_Iterate                   :   3.24
Test_Lens                           :   4.41
Test_MCPL_input                     :   2.68
Test_MCPL_output                    :   2.71
Test_Monochromators                 :   3.35
Test_PSD_Detector                   :   2.76
Test_Pol_Guide_Vmirror              :   2.83
Test_Pol_MSF                        :   1.87
Test_Pol_Mirror                     :   2.34
Test_Pol_SF_ideal                   :   1.42
Test_Pol_Set                        :   1.68
Test_PowderN_Res                    :   3.38
Test_PreMonitor_nD                  :   3.46
Test_SSR_SSW                        :   1.34
Test_SSR_SSW_Guide                  :   1.72
Test_Sample_nxs_diffraction         :   2.40
Test_Sample_nxs_imaging             :   2.27
Test_Selectors                      :   2.83
Test_Sources                        :   3.30
Tomography                          :   2.76
Vin_test                            :   1.65
Vout_test                           :   2.09
h8_test_legacy                      :   2.71
linup-1                             :   2.13
linup-2                             :   2.42
linup-3                             :   2.28
linup-4                             :   2.49
linup-5                             :   2.47
linup-6                             :   2.53
linup-7                             :   2.40
micro                               :   1.22
mini                                :   1.29
nano                                :   1.15
template                            :   1.11
templateDIFF                        :   3.82
templateLaue                        :   2.36
template_simple                     : COMPILE ERROR using:
mcrun --info /tmp/mctest/20191021_2016_40/3.0-dev/templateLaueGPU/templateLaueGPU.instr
template_simple                     : COMPILE ERROR using:
mcrun --info /tmp/mctest/20191021_2016_40/3.0-dev/templateLaueGPU_SXonly/templateLaueGPU_SXonly.instr
template_simple                     : COMPILE ERROR using:
mcrun --info /tmp/mctest/20191021_2016_40/3.0-dev/templateLaueGPU_rngonly/templateLaueGPU_rngonly.instr
templateNMX                         :   2.39
templateNMX_TOF                     :   2.72
templateSANS                        :   1.71
templateSANS_Mantid                 :   3.08
templateSasView                     :   1.75
templateSasView_Mantid              :   3.17
templateTAS                         :   4.57
templateVanadiumMultipleScat_Mantid :   2.76
template_simple                     :   1.12

Running tests...
BNL_H8                               :   1.60
BNL_H8_simple                        :   0.50
ESS_IN5_reprate                      :   2.37
FZJ_KWS2_Lens                        :   0.84
FZJ_SANS_KWS2_AnySample              :   0.47
HZB_NEAT                             :   6.17
ILL_D2B                              :   1.21
ILL_D4                               :  10.82
ILL_H10_IN8                          :   1.75
ILL_H113                             :   8.03
ILL_H13_IN20                         :   1.81
ILL_H142                             :   6.74
ILL_H142_IN12                        :   1.60
ILL_H15                              :   5.56
ILL_H16                              :   2.12
ILL_H16_IN5                          :   1.04
ILL_H16_IN5_Mantid                   :   1.18
ILL_H22                              :   1.66
ILL_H22_D1A                          :   8.36
ILL_H22_D1B                          :   4.19
ILL_H22_VIVALDI                      :   5.08
ILL_H24                              :   1.43
ILL_H25                              :   5.40
ILL_H25_IN22                         :   1.87
ILL_H512_D22                         :   2.34
ILL_H53                              :   3.37
ILL_H8_IN1                           :   5.26
ILL_IN13                             :  46.84
ILL_IN4                              :  10.81
ILL_IN5                              :   0.62
ILL_IN5_Mantid                       :   0.81
ILL_Lagrange                         :  21.98
ISIS_GEM                             :   5.00
ISIS_HET                             :   2.20
ISIS_Prisma2                         :   1.22
ISIS_test                            :   0.72
PSI_DMC                              :   1.14
PSI_Focus                            :   4.45
Samples_Incoherent                   :   1.41
Samples_Incoherent_off               :  20.02
Samples_Isotropic_Sqw                :   6.30
Samples_Phonon                       :   2.58
Samples_vanadium                     :   0.85
Test_Collimator_Radial               :   0.89
Test_FocalisationMirrors             :   0.74
Test_Jump_Iterate                    :   1.61
Test_MCPL_input                      :   0.11
Test_MCPL_output                     :   0.12
Test_Monochromators                  :   0.76
Test_PSD_Detector                    :   0.58
Test_Pol_Guide_Vmirror               :   0.71
Test_Pol_MSF                         :   0.55
Test_Pol_Mirror                      :   0.61
Test_Selectors                       :   0.45
Test_Sources                         :   1.22
Tomography                           :  24.09
linup-1                              :   0.78
linup-2                              :   0.79
linup-3                              :   0.78
linup-4                              :   0.83
linup-5                              :   0.82
linup-6                              :   0.85
linup-7                              :   0.82
templateDIFF                         :   2.16
templateLaue                         :   0.83
templateSANS                         :   0.54
templateSANS_Mantid                  :   0.56
templateTAS                          :   4.62
</pre>
