### ISSUE TITLE
mcstas: components: Pol_FieldBox and SE_example2 do not compile

### ISSUE THREAD

**Issue by farhi** [McStasMcXtrace/McCode#633]
Using the optics/Pol_FieldBox component, e.g. McStas example SE_example2.instr leads to compilation error. Indeed, the field_parameters assigned as void can not be further set its vector values, e.g.:

```
field_parameters = (void *) const_field_parameters;
...
field_parameters[0]=Bx;
field_parameters[1]=By;
field_parameters[2]=Bz;
```

and worse, the case with an interpolator pointer is not handled in the TRACE section. So seems broken.

**Comment by farhi** [comment]
This also blocks `SE_example2.instr`

**Comment by willend** [comment]
@ebknudsen and I will have a look after vacation(s)

**Comment by willend** [comment]
@ebknudsen was this not fixed for 2.5? @farhi was this cogen3-oriented or general?

**Comment by farhi** [comment]
I confirm that this issue affects legacy McStas, including 2.5... It will most probably be the same with COGEN3.
Currently, as stated above, `Pol_FieldBox` component and `SE_example2` instrument do not compile.

**Comment by ebknudsen** [comment]
1d7e15 should have fixed this issue. Now testing

**Comment by willend** [comment]
@ebknudsen did the test turn out OK?

**Comment by ebknudsen** [comment]
Tests compile fine - but SE_example2 now has runtime failures due to #536

**Comment by willend** [comment]
@ebknudsen thanks for the update. What are the chances we can do someting about #536 within ~1-2 weeks?

**Comment by ebknudsen** [comment]
Not sure yet - analysing the issue right now. Estimate pending

**Comment by ebknudsen** [comment]
Have found the offending piece of code - I think it's a day or two's job. It is in the functions SetPolMonoRefOut and SetPolMonoTransOut that theres' an implicit assumption that what you are dealing with is "classical polarization", understood as up or down being the only possibilities.
