### ISSUE TITLE
cogen3: Vitess_ChopperFermi and Test_Fermi fail to compile

### ISSUE THREAD

**Issue by farhi** [McStasMcXtrace/McCode#636]
The `Vitess_ChopperFermi` component doers not compile with cogen3, as it uses many hidden global variables. A full re-implementation is probably required. This also blocks the Test_Fermi instrument.

**Comment by willend** [comment]
I think it would be reasonable to retire `Vitess_ChopperFermi` for McStas 3.0, including an edit of `Test_Fermi`
