### ISSUE TITLE
cogen3: Scatter_logger mechanism need adaption to new cogen

### ISSUE THREAD

**Issue by farhi** [McStasMcXtrace/McCode#637]
The `Scatter_logger` and `Scatter_logger_stop` components need to be adapted to the new cogen3 methodology. In a way, this is easier as particles are stored as structures (`mcneutron`), which have an `_index` member for the current component. This value can be changed with the macro:

- `JUMPTOCOMP(comp)`

which sets the `_index` to that of the component '`comp`'. The current trajectory of particles is also available in the `mcinstrument->_trajectory`
So, one can

- redefine `ABSORB` to only change the _index of the neutron to that of the `Scatter_logger_stop` one
- get the status of the particle at the `ABSORB` location (`Scatter_logger` index)
- to reset ABSORB to its initial behaviour, one can simpley use: `#define ABSORB ABSORB0`

**Comment by farhi** [comment]
These components use 'goto' labels

**Comment by willend** [comment]
`These components use 'goto' labels`

Which is of course always a great idea ;-) 
![goto](https://user-images.githubusercontent.com/8593355/42497454-b57dc51a-8429-11e8-9cad-10ec080e4cf3.png)

@ebknudsen @EsbenKlinkby we should get this in place. (And btw also include an example instrument using the logging mechanism together with MCPL output)

**Comment by climbcat** [comment]
I've come across this as well. If you can find someone who knows what this component combo is supposed to do or how it works, I can fix it or implement something similar.

**Comment by willend** [comment]
@ebknudsen is currently looking at this for an MCPL application on the master branch, which may / could provide an example
