### ISSUE TITLE
cogen3: Guide_four_side* components porting is heavy

### ISSUE THREAD

**Issue by farhi** [McStasMcXtrace/McCode#638]
The components in 'contrib':

- `Guide_four_side.comp`
- `Guide_four_side_2_shells.comp`
- `Guide_four_side_10_shells.comp`

mix shared and local component variables/functions in a messy way. In the current form, they are not compatible with the cogen3 methodology. This also blocks the `Test_shellguides` instrument example.

Work is not too complex, but question arise: are these components used except in this example ? **Could we just get rid of them ?** 

In principle, Guide_anyshape could probably do a similar job, if given a shell-guide geometry as PLY/OFF.

**Comment by willend** [comment]
There are indeed multiple good reasons to consider obsoleting these components. Alternatively let me try asking at PSI if the original author would do the work.

**Comment by climbcat** [comment]
@willend any news on this? Should I obsolete those components?

**Comment by willend** [comment]
Yes, I think we can obsolete these on the cogen3 branch for now.
