### ISSUE TITLE
mcplot on Windows 10 (64bit): "sweep plotting" currently not functional

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#649]
Turning debug on in the click handler shows that all if click, ctrl+click and meta+click return 0. Could be this is a virtualisation issue (I am running through VMware on the Mac)

**Comment by willend** [comment]
I can make ALT return something on-zero, namely 134217728

**Comment by willend** [comment]
The attached python code works - with ALT as modifier - on my Windows machine. We need to try on proper hardware if the issue is around or not...

[pqtgfrontend.py.txt](https://github.com/McStasMcXtrace/McCode/files/2324146/pqtgfrontend.py.txt)

**Comment by willend** [comment]
BTW the matplotlib plotter exhibits the same problem

**Comment by climbcat** [comment]
Ok, very strange. We should probably set modifiers ctrl AND alt for all platforms, we have no need to restrict modifiers, and that way we can get rid of the OS switch

**Comment by climbcat** [comment]
The fix has been applied and a test is needed.

**Comment by willend** [comment]
Tested and confirmed to work with
* Ctrl on Linux
* Meta on macOS
* Alt on windows
