### ISSUE TITLE
mcplot-matplotlib, mouse-based click-features not available

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#654]
On mac and Ubuntu it seems neither selection of subplots, sweep plots etc. are non-functional.

**Comment by climbcat** [comment]
We should debug this on a mac, since the click features work fine on my system...

**Comment by willend** [comment]
Hmm, my Ubuntu 18.04 behaves the same as my mac?!

**Comment by willend** [comment]
Fixed after DMSC debugging session, last commit to master works OK with the side effects that

1) "sweep-plotting" uses x+click rather than ctrl+click on mac (enabled everywhere). Problem relates to Anaconda not being a "framework build" and therefore not picking up all signals properly, see https://github.com/matplotlib/matplotlib/issues/2120

2) We are now using the slightly brutal pylab.close() instead of pylab.clf since the latter does not work properly on Ubuntu 18.04 and current macOS. Side effect is that the new window may/will reappear in another position
