### ISSUE TITLE
mcdisplay-pyqtgraph, possibly also others may hide fatal errors from underlying mcrun

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#655]
With the attached instrument (and c-snippets etc.), the simulation in the underlying mcrun never starts, since the file S3.mcpl.gz is not in place.

In the case of using mcdisplay, the error message (which probably originates from the MCPL library "below" McStas) 
<pre>
MCPL ERROR: Unable to open file!
</pre>

is never propagated to the terminal where mcdisplay is run, so nothing really happens after that.

(To actually run the instrument without the error 
<pre>
cp S3short.mcpl.gz S3.mcpl.gz
</pre>

With mcdisplay.pl the information arrives on the terminal and mcdisplay terminates.

[Package.zip](https://github.com/McStasMcXtrace/McCode/files/2401556/Package.zip)

**Comment by willend** [comment]
Oops you need the attached set of files in the same folder
[Stuff.zip](https://github.com/McStasMcXtrace/McCode/files/2401611/Stuff.zip)
 also...

**Comment by climbcat** [comment]
This is partially fixed by b268cfda587793d0d22f0d7d1b5093c589ac53ad. However, I could not fix a better solution, fixing the behavior of mcrun to communicate show the underlying stderr message. My environment seems to be using the "old" version 2.4.1 version, rather than the newly installed "test01" version - see screen-shot. 

![mcstas_versions](https://user-images.githubusercontent.com/11196009/46952567-7febee00-d08b-11e8-97aa-6c081c7ddfcf.png)

The file 'equivs-build' for debs meta package seems to be missing (https://github.com/McStasMcXtrace/McCode/blob/e69eab1d4c7463dfd959f32fe447cab585ad00d5/meta-pkgs/deb/build_deb_metas), maybe this is related to the problem somehow, since I install locally build packages with "dpkg -i dist/*"?

**Comment by willend** [comment]
I think you should be able to get equivs-build by apt-get install?

**Comment by climbcat** [comment]
Ok yes I got it, thx for the tip!

**Comment by climbcat** [comment]
Further testing reveals some oddities in the way mcrun works.

If line 66 in mccode.py is changed to pipe = PIPE, then mcrun hangs! But this is the change we want, for the error message from mcstas to be sent to the pipe, and not written directly to the console (my current theory). If one runs the instrument in mcrun directly, the error message is printed, but if one runs it in mcdisplay, only the exit code is available, and the underlying error message never appears.

**Comment by willend** [comment]
I had a look at this one with a build from yesterday afternoon - better in some way, but what was witten in the stderr from the simulation still seems to get lost in translation:

<pre>

INFO: Using directory: "DREAM_mcnp_13_06_2018_20181129_104208"
INFO: Regenerating c-file: DREAM_mcnp_13_06_2018.c
Warning: Using DEFINITION parameter of component Brilliance_monitor() (potential syntax error) at line DREAM_mcnp_13_06_2018.instr:372
srcarea=( 100 * 0.06 * 100 * 2 * 0.03 / 2.5 )
Warning: Using DEFINITION parameter of component Brilliance_monitor() (potential syntax error) at line DREAM_mcnp_13_06_2018.instr:381
srcarea=( 100 * 0.06 * 100 * 2 * 0.03 / 2.5 )
Info:    'Elliptic_guide_gravity' is a contributed component.
Warning: Component G1=Guide_anyshape_pl(string reflect) definition parameter
may be changed into a setting parameter to avoid
warnings at compile time.
Warning: Component G1=Guide_anyshape_pl(string geometry) definition parameter
may be changed into a setting parameter to avoid
warnings at compile time.
CFLAGS= -I@MCCODE_LIB@/libs/mcpl -L@MCCODE_LIB@/libs/mcpl -lmcpl
INFO: Recompiling: ./DREAM_mcnp_13_06_2018.out
INFO: ===
process exited with code: 1
Traceback (most recent call last):
  File "/Applications/McStas-2.5rc24.app/Contents/Resources/mcstas/2.5rc24/bin/../tools/Python/mcdisplay/pyqtgraph/mcdisplay.py", line 579, in <module>
    raise e
  File "/Applications/McStas-2.5rc24.app/Contents/Resources/mcstas/2.5rc24/bin/../tools/Python/mcdisplay/pyqtgraph/mcdisplay.py", line 574, in <module>
    main(args)
  File "/Applications/McStas-2.5rc24.app/Contents/Resources/mcstas/2.5rc24/bin/../tools/Python/mcdisplay/pyqtgraph/mcdisplay.py", line 536, in main
    instrument = reader.read_instrument()
  File "/Applications/McStas-2.5rc24.app/Contents/Resources/mcstas/2.5rc24/bin/../tools/Python/mcdisplay/pyqtgraph/../../mccodelib/mcdisplayutils.py", line 61, in read_instrument
    self.pipeman.join()
  File "/Applications/McStas-2.5rc24.app/Contents/Resources/mcstas/2.5rc24/bin/../tools/Python/mcdisplay/pyqtgraph/../../mccodelib/pipetools.py", line 342, in join
    raise self.reader.exc_obj
  File "/Applications/McStas-2.5rc24.app/Contents/Resources/mcstas/2.5rc24/bin/../tools/Python/mcdisplay/pyqtgraph/../../mccodelib/pipetools.py", line 282, in run
    raise Exception("process exited with code: %s" % str(poll))
Exception: process exited with code: 1
</pre>

I would actually prefer that mcdisplay terminated without exception status, but instead printed to screen whatever came to stderr

P

**Comment by willend** [comment]
@ebknudsen what do you think?

**Comment by willend** [comment]
Works beautifully now, closing!
