### ISSUE TITLE
mc/xgui feature request: Run mc/xdoc for loaded instrument

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#657]
@ebknudsen has come up with the idea that a hook to run the mcdoc util on the currently loaded instrument would be quite useful.

I am thinking that placement e.g. under File-> is OK, so no new buttons necessary.

**Comment by climbcat** [comment]
Should be implemented by ea9b18f1694c6a7ac40aa6c64ef690965ad5c25a

**Comment by willend** [comment]
Placed in the Help menu, works as expected
