### ISSUE TITLE
Issues with Sqw in 2.4.1

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#658]
* Issues using MPI may occur - look at potentially reverting list-mode changes
* Issues with reuse of tables from updated read_table-lib

Needs fixing or reverting for 2.5

**Comment by ebknudsen** [comment]
OK I'll take a look

**Comment by farhi** [comment]
Good, on my side I will solve the issue with the calculation (detailed balance) #196 and #300. Then the 'legacy' should be taken out.

**Comment by willend** [comment]
Hi @farhi,
Is there a test result / something that shows this is in fact fully done? :-)

**Comment by farhi** [comment]
Here are results of a few tests. Shows that at least the SEGV with MPI seems solved.

**ILL_IN4 / McStas 2.3 / Ubuntu 16.04: mcrun --no-output-files ILL_IN4 lambda=2 (single core)** 
```
Detector: Detector_I=3.32224e+06 Detector_ERR=30001.4 Detector_N=102918 "Detector_1543399555.th_y"
Detector: Detector_qe_I=15736.7 Detector_qe_ERR=102.653 Detector_qe_N=31590 "Detector_qe_1543399555.A_E"
```

**ILL_IN4 / McStas 2.3 / Ubuntu 16.04: mcrun --no-output-files --mpi=24 ILL_IN4 lambda=2 (MPI)** 
```
Detector: Detector_I=3.18571e+06 Detector_ERR=29205.4 Detector_N=100102 "Detector_1543399633.th_y"
Detector: Detector_qe_I=15018.8 Detector_qe_ERR=101.084 Detector_qe_N=29912 "Detector_qe_1543399633.A_E"
```
**Current Sqw / ILL_IN4 / McStas 2.4.1 / Ubuntu 16.04: mcrun --no-output-files ILL_IN4 lambda=2 (single core)** 
```
Detector: Detector_I=3.12135e+06 Detector_ERR=28657.3 Detector_N=96549 "Detector_1543400937.th_y"
Detector: Detector_qe_I=14472 Detector_qe_ERR=99.0292 Detector_qe_N=28654 "Detector_qe_1543400938.A_E"
```
**Current Sqw / ILL_IN4 / McStas 2.4.1 / Ubuntu 16.04: mcrun --no-output-files ILL_IN4 lambda=2 --mpi=4 (MPI)** 
`SEGV in Sqw_readfile (INIT) after 'Computing scattering unit density'`

**Updated Sqw / ILL_IN4 / McStas 2.4.1 / Ubuntu 16.04: mcrun --no-output-files ILL_IN4 lambda=2 (single core)** 
```
Detector: Detector_I=3.0792e+06 Detector_ERR=29970.8 Detector_N=97137 "Detector_1543400673.th_y"
Detector: Detector_qe_I=15616.1 Detector_qe_ERR=102.576 Detector_qe_N=31110 "Detector_qe_1543400673.A_E"
```

**Updated Sqw / ILL_IN4 / McStas 2.4.1 / Ubuntu 16.04: mcrun --no-output-files ILL_IN4 lambda=2 --mpi=4 (MPI)** 
```
Detector: Detector_I=3.07201e+06 Detector_ERR=28282 Detector_N=95199 "Detector_1543400053.th_y"
Detector: Detector_qe_I=14213.8 Detector_qe_ERR=98.2699 Detector_qe_N=28359 "Detector_qe_1543400053.A_E"
```

**Comment by willend** [comment]
Great, thanks for sharing / documenting this :-) 👍

**Comment by farhi** [comment]
@willend will you move the Sqw_legacy in 'obsolete' and restore the Sqw tests in the `mcrun --test` list ? 

I think it makes the landscape fuzzy ("which one to choose ?") and brings a feeling that this is not reliable enough. 
I'm also very satisfied with the new 'quantum correction' which avoids divergences in S(q,w) for any temperature. All this was getting dust on the shelf for years, good work done.

**Comment by willend** [comment]
Absolutely, will do. Reopening this ticket to ensure I don't forget!

**Comment by willend** [comment]
Hi @farhi, 

Just had a look - to me it looks like these instruments include Isotropic_Sqw:
<pre>
grep Isotropic_Sqw *.instr | cut -f1 -d: | sort | uniq
HZB_NEAT.instr
ILL_BRISP.instr
ILL_D4.instr
ILL_H5.instr
ILL_H512_D22.instr
ILL_H5_new.instr
ILL_IN4.instr
ILL_IN5.instr
ILL_IN5_Mantid.instr
ILL_IN6.instr
ILL_Lagrange.instr
SNS_BASIS.instr
Samples_Incoherent.instr
Samples_Isotropic_Sqw.instr
Test_Monitor_Sqw.instr
Test_StatisticalChopper.instr
templateTAS.instr
templateTOF.instr
</pre>
- and out of these, most actually already feature a test that is enabled?
<pre>
grep Isotropic_Sqw *.instr | cut -f1 -d: | sort | uniq | xargs -n1 grep -H Example
HZB_NEAT.instr:* %Example: lambda=6                       Detector: Detector_I=2900
HZB_NEAT.instr:* %Example: lambda=6 coh=Y2O3.laz inc=NULL Detector: Detector_I=1080
ILL_BRISP.instr:* %Example: coh="V.laz" Detector: Detector_I=31.55
ILL_D4.instr:* %Example: lambda=0.7 Detector: BananaTheta_I=1.44351e+06
ILL_H512_D22.instr:* %Example: lambda=4.5 Detector: D22_Detector_I=1.76653e+07
ILL_IN4.instr:* %Example: lambda=1.2 DM=1.677 Detector: sample_flux_I=4.43306e+06
ILL_IN5.instr:* %Example: lambda=4.5 Detector: Det_PSD_I=1.3e6
ILL_IN5_Mantid.instr:* %Example: lambda=4.5 Detector: Det_PSD_I=1.3e6
ILL_IN6.instr:* Example: lambda=4.14 Detector: M_theta_t_all_I=118160
ILL_Lagrange.instr:* %Example: lambda=0.897 Detector: Detector_I=21.7527
SNS_BASIS.instr:* Example: mcrun BASIS_guide.instr Lam=6.4
Samples_Incoherent.instr:* Examples:
Samples_Incoherent.instr:* %Example: SAMPLE=1 STOP=1 V_multiples=0 Detector: PSD_Sphere_4pi_I=1.2321e+06
Samples_Incoherent.instr:* %Example: SAMPLE=2 STOP=1 V_multiples=0 Detector: PSD_Sphere_4pi_I=1.2324e+06
Samples_Incoherent.instr:* %Example: SAMPLE=3 STOP=1 V_multiples=0 Detector: PSD_Sphere_4pi_I=1.3196e+06
Samples_Incoherent.instr:* %Example: SAMPLE=4 STOP=1 V_multiples=0 Detector: PSD_Sphere_4pi_I=1.3246e+06
Samples_Incoherent.instr:* %Example: SAMPLE=5 STOP=1 V_multiples=0 Detector: PSD_Sphere_4pi_I=1.3252e+06
Samples_Incoherent.instr:* %Example: SAMPLE=6 STOP=1 V_multiples=0 -n 1e5 Detector: PSD_Sphere_4pi_I=1.2324e+06
Samples_Incoherent.instr:* %Example: SAMPLE=7 STOP=1 V_multiples=0 -n 1e5 Detector: PSD_Sphere_4pi_I=1.3225e+06
Samples_Incoherent.instr:* %Example: SAMPLE=8 STOP=1 V_multiples=0 -n 1e5 Detector: PSD_Sphere_4pi_I=1.3233e+06
Samples_Incoherent.instr:* %Example: SAMPLE=9 STOP=1 V_multiples=0 -n 1e5 Detector: PSD_Sphere_4pi_I=1.3239e+06
Samples_Incoherent.instr:* %Example: SAMPLE=10 STOP=1 V_multiples=0 -n 1e5 Detector: PSD_Sphere_4pi_I=1.28905e+06
Samples_Isotropic_Sqw.instr:* %Example: lambda=3.4 Detector: M_theta_t_I=1.57351e-07
Test_Monitor_Sqw.instr:* %Example: beam_wavelength_Angs=4.1 Detector: M_single_coh_I=8.7974e-11
Test_Monitor_Sqw.instr:* %Example: beam_wavelength_Angs=1.6 beam_resolution_meV=1.07 Detector: M_single_coh_I=3.50732e-09
Test_StatisticalChopper.instr:* %Example: lambda=1 Detector: time_mon2_I=6.03103e-13
templateTAS.instr:* %Example: QM=1 Sqw_coh=V.laz Detector: D7_SC3_1D_I=2.55907e+08
templateTAS.instr:* %Example: QM=1 Sqw_coh=V.laz Detector: He3H_I=256
templateTOF.instr:* %Example: E0=4.94 Detector:  M_single_coh_I=3.5e-11
templateTOF.instr:* %Example: E0=33 dE=1.07 dt=9.6e-6 Detector: M_single_coh_I=5.93372e-10
</pre>

Now obsoleting the Legacy comp and will start a test

**Comment by willend** [comment]
Closing this one - test issue will then resolve whatever potentially remains
