### ISSUE TITLE
m(c,x)gui: Make list of m(c,x)display-backends available on run dialogue

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#661]
When selecting TRACE mode, it would be useful to have direct access to which of the many mcdisplay backends available.

I.e. 

1) Make the list also on configuration dialogue appear once TRACE is selected (like the Inspect pulldown)

2) Take the choice of mcdisplay backend from that list

**Comment by climbcat** [comment]
This has been implemented today by a series of commits.

**Comment by willend** [comment]
DONE, review confirms this works as expected
