### ISSUE TITLE
m(c,x)gui parsing of inspect list for trace mode is too restrictive

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#663]
Using the attached instrumentfile, a number of components do not show up in the Inspect: list in mcgui. The file includes several examples of components that become invisible in the Inspect list, including:

* (whitespace) COMPONENT ...
* SPLIT 100 COMPONENT
* COMPONENT Mine=yours (i.e. no spaces around the = sign)

Note that the old mcgui.pl exhibits at least also the latter of these issues also. (Should be looked at separately)

Also note that components that are inside c-style comments are on the other hand shown. :-) (Don't put effort to fix that - too much complicated parsing IMHO)

<pre>
/*
COMPONENT Blah = ...
*/
</pre>

[TOSCA_Mantid_2.instr.txt](https://github.com/McStasMcXtrace/McCode/files/2455870/TOSCA_Mantid_2.instr.txt)

**Comment by climbcat** [comment]
Should have been fixed by 3a417e1e721012915abbf25925f199bf7065e7e8

**Comment by willend** [comment]
Looks great and works mostly well - mcdisplay-webgl chosen this way crashes here with
<pre>
mcgui TOSCA_Mantid_2.instr
Running: mcrun TOSCA_Mantid_2.instr -d /Users/pkwi/OKtoRemove/TOSCA_Mantid_2_20181010_215459 -n 1000000  inc=Rb_liq_coh.sqw  zdepth=0.002  dx=0  dy=0  dz=0  Emin=0.01  Emax=500  index=-16  eventmode=0
Running: mcdisplay-pyqtgraph TOSCA_Mantid_2.instr --no-output-files -n 100  inc=Rb_liq_coh.sqw  zdepth=0.002  dx=0  dy=0  dz=0  Emin=0.01  Emax=500  index=-16  eventmode=0
Running: mcrun TOSCA_Mantid_2.instr -d /Users/pkwi/OKtoRemove/TOSCA_Mantid_2_20181010_215741 -n 100  inc=Rb_liq_coh.sqw  zdepth=0.002  dx=0  dy=0  dz=0  Emin=0.01  Emax=500  index=-16  eventmode=0
Traceback (most recent call last):
  File "/Applications/McStas-2.5bb.app/Contents/Resources/mcstas/2.5bb/bin/../tools/Python/mcgui/mcgui.py", line 593, in handleRunOrInterruptSim
    self.state.run(fixed_params, new_instr_params, inspect)
  File "/Applications/McStas-2.5bb.app/Contents/Resources/mcstas/2.5bb/bin/../tools/Python/mcgui/mcgui.py", line 337, in run
    runstr = mccode_config.configuration["MCDISPLAY"] + ' ' + os.path.basename(self.__instrFile) + ' --no-output-files'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
/Applications/McStas-2.5bb.app/Contents/Resources/mcstas/2.5bb/bin/mcgui: line 35:  7151 Abort trap: 6           python3 ${LIB}/mcgui.py $*
</pre>

**Comment by climbcat** [comment]
This side effect should be fixed by 51789c4144297ecbbb20d3d842d6df2a55d5db54

**Comment by willend** [comment]
Yup, seems to work. DONE
