### ISSUE TITLE
mcgui-request from DMSC workshop: Make editor honour main file-handling options from main gui

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#669]
- That is:

Add things like Open, Close and Save As from mcgui main:
<img width="853" alt="screenshot 2018-11-03 at 11 25 25" src="https://user-images.githubusercontent.com/8593355/47951020-56700500-df5b-11e8-8cea-970f071e5ad6.png">

... also to the editor window:

<img width="358" alt="screenshot 2018-11-03 at 11 26 18" src="https://user-images.githubusercontent.com/8593355/47951023-5f60d680-df5b-11e8-8983-55a30595b7ea.png">

**Comment by climbcat** [comment]
A "Save As..." button has been added to mcgui e94ea85113560e20da83f6289a102170787e96c5.

**Comment by willend** [comment]
Tested to work, closing
