### ISSUE TITLE
Current (master) mcgui crashes attempting compile of any instr 

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#671]
Looks like related to recent changes of stdout/stderr mechanism? 

Here is what it looks like on my macOS, will try with a Linux also:
<pre>
mcgui
</pre>
File->New from template and press Run
<pre>                    
objc[47385]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8af621d0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x10c90bdc8). One of the two will be used. Which one is undefined.
Traceback (most recent call last):
  File "/Applications/McStas-2.5rc01.app/Contents/Resources/mcstas/2.5rc01/bin/../tools/Python/mcgui/mcgui.py", line 84, in run
    for stderrdata in process.stderr:
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/McStas-2.5rc01.app/Contents/Resources/mcstas/2.5rc01/bin/../tools/Python/mcgui/mcgui.py", line 90, in run
    self.thread_exception.emit(value.message)
AttributeError: 'TypeError' object has no attribute 'message'
/Applications/McStas-2.5rc01.app/Contents/Resources/mcstas/2.5rc01/bin/mcgui: line 35: 47385 Abort trap: 6           python3 ${LIB}/mcgui.py $*
</pre>

**Comment by willend** [comment]
Having compiled on the commandline before makes the same issue once run is pressed:
<pre>
Traceback (most recent call last):
  File "/Applications/McStas-2.5rc01.app/Contents/Resources/mcstas/2.5rc01/bin/../tools/Python/mcgui/mcgui.py", line 84, in run
    for stderrdata in process.stderr:
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/McStas-2.5rc01.app/Contents/Resources/mcstas/2.5rc01/bin/../tools/Python/mcgui/mcgui.py", line 90, in run
    self.thread_exception.emit(value.message)
AttributeError: 'TypeError' object has no attribute 'message'
/Applications/McStas-2.5rc01.app/Contents/Resources/mcstas/2.5rc01/bin/mcgui: line 35: 47457 Abort trap: 6           python3 ${LIB}/mcgui.py $*
</pre>

**Comment by willend** [comment]
Hmm, in part this seems platform / Python version specific... On my Ubuntu 18.04 the gui proceeds running, i.e. no fatal crash, but I still have this stuff in the terminal:
<img width="903" alt="screenshot 2018-11-08 at 12 58 21" src="https://user-images.githubusercontent.com/8593355/48197429-ffe93900-e355-11e8-9b64-a768f1c94bc1.png">

**Comment by climbcat** [comment]
should have been fixed by f5cd219f243175d642efd050cf5cedcd1f475896

**Comment by willend** [comment]
Yup, thanks, seems to work. I attach an alternative that also worked OK here - in case we have an interest in maintaining the original structure of the run() function?

[mcgui.py.txt](https://github.com/McStasMcXtrace/McCode/files/2571965/mcgui.py.txt)
