### ISSUE TITLE
macOS High Sierra and Mojave "math.h not found"

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#676]
On High Sierra and Mojave you may experience issues with missing math.h in case of:

* installation of McStas 2.5
* If, after an upgrade to Mojave you get compilation issues with the error message

<pre>
mccode-r.h:39:18: fatal error: math.h: No such file or
directory
</pre>

Then the solution is to follow the below steps 

On High Sierra:
please run the following command in a terminal:
1. 
<pre>xcode-select --install</pre> - to initiate installation of updated Xcode commandline tools
2.
If the problem persists, then manually install Xcode command line tools via 
http://developer.apple.com/downloads/
(You will need an apple developer account)

On Mojave:
please run the following commands in a terminal:
1. 
<pre>xcode-select --install</pre> - to initiate installation of updated Xcode commandline tools
2.
<pre>sudo open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg</pre>- to install the development headerfiles in the usual /usr/include location

**Comment by willend** [comment]
I believe that 26495ee (which should configure for clang on macOS) is enough for now - and to be able to release @ebknudsen what do you think?

**Comment by ebknudsen** [comment]
@willend I believe you're right - I am ok with this.

**Comment by willend** [comment]
Roger @ebknudsen then I will simply close

**Comment by willend** [comment]
Also btw. https://github.com/McStasMcXtrace/McCode/issues/799 is the new location of the general solution / hint - which we should keep open
