### ISSUE TITLE
mcgui:  "autoplot" from run dialogue via list of plotters

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#678]
Ala what was done to choose mcdisplay

Today:

![screenshot 2018-11-21 at 10 16 38](https://user-images.githubusercontent.com/8593355/48831174-95cd8c80-ed76-11e8-890e-81ec87375482.png)

New solution something like this - with a None possibility at the top:
![screenshot 2018-11-21 at 10 16 38](https://user-images.githubusercontent.com/8593355/48831295-d0cfc000-ed76-11e8-8ccc-0a782621f62f.png)

**Comment by climbcat** [comment]
Have a look at this, could do the job: 9cdd24e90f4d7d8f659bd887ff977863b9559018

**Comment by willend** [comment]
Hmm, good point wrt. the silent saving - hadn't thought of that.

Could be we should do something like
<pre>
--autoplot=plotter
</pre>
instead - such that the plotter argument is optional and we use whatever is in the file otherwise...

**Comment by willend** [comment]
@ebknudsen maybe you have an opinion?

**Comment by climbcat** [comment]
Had to add a option --autoplotter in addition to the already existing --autoplot. You can't have a bool and a string put into one option, it seems, so we had to flag for autoplot, and optionally select the plotter as a string afterwards.

Feel any better now? 46d0893a3bbc8aec60560748fe67e28e1d376ec0

**Comment by willend** [comment]
Looks good, closing
