### ISSUE TITLE
NeXus and McStas 2.5 on macOS clarification

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#679]
@trnielsen you mentioned that NeXus is not too difficult to build locally on macOS?

Suggested way forward either
* Develop short build script
* Look if the below is enough - document?
<pre>
brew tap brewsci/bio
brew tap brewsci/science
brew install hdf4
brew install nexusformat
</pre>

**Comment by trnielsen** [comment]
Yes
I am thinking that we should also set-up build and test VM for for upcoming code camp. We can do for OSX, Win10, and Centos7, Ubuntu18.

**Comment by willend** [comment]
Good idea.

The home-brew stuff from above installs, but consistently seems to lead to <pre>Abort trap: 6</pre>...

**Comment by willend** [comment]
A workable solutions looks to be

1) Use this semi-ancient HDF5 build (looks to be the last one that the HDF Group supplies)
https://support.hdfgroup.org/ftp/HDF5/prev-releases/hdf5-1.8/hdf5-1.8.7/bin/mac-intel-x86_64/hdf5-1.8.7-mac-intel-x86_64-static.tar.gz - and use the h5redeploy util inside to put e.g. deep in the McStas app bundle

2) Build NeXus against that from the GitHub NeXus sources

**Comment by willend** [comment]
(Of course one **_can_** in principle also build HDF from source, but I believe that this would be insane - build takes much longer than the whole McStas build process it seems :-D)

**Comment by willend** [comment]
I propose we take steps 1+2 and do these within the macOS bundle - through the build_macos_mcstas script

**Comment by willend** [comment]
Looked like a great idea, and seems to run but produces junk... :-(

**Comment by willend** [comment]
Seems we should still keep clang / cc / /usr/bin/gcc out of the equation. But with an embedded conda-gcc things work

**Comment by willend** [comment]
This works:
<pre>
#install homebrew:
    1  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
#ensure to fully update
    2  brew update &&  brew update
#install hdf5
    4  brew install hdf5
#pick the legacy recipe for building nexusformat and build against local hdf5 version
    5  brew install brewsci/science/nexusformat --build-from-source
 </pre>

Not too nice, but at least a way forward. Closing

**Comment by willend** [comment]
Oh and BTW this only works with McStas if (our conda) gcc is used for compilation
