### ISSUE TITLE
Current master build mcgui -> python mcdisplay error with -n1e6

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#680]
Pasted from mcgui:
<pre>mcdisplay-webgl BNL_H8.instr --no-output-files -n 10000  lambda=2.36 &
Instrument:     BNL_H8 on localhost.
Monochromator : DM = 3.3539
A1 = 20.60, A2 = 41.20 (deg)
Ki = 2.662 Angs-1 Energy = 14.69 meV
Velocity = 1676 m/s, lambda = 2.36 Angs

max particle count exceeded, blocking all further trace particle trace lines...
INFO: Using directory: "BNL_H8_20181125_093332"
INFO: Using existing c-file: ./BNL_H8.c
INFO: Using existing binary: ./BNL_H8.out
INFO: ===
Warning: Number of events 2480 reaching SPLIT position Component[12] PG1Xtal=Monochromator_flat()
is probably too low. Increase Ncount.
Warning: Number of events 2220 reaching SPLIT position Component[19] Sample=V_sample()
is probably too low. Increase Ncount.
Warning: Number of events 630 reaching SPLIT position Component[24] PG2Xtal=Monochromator_flat()
is probably too low. Increase Ncount.
process exited with code: -15
</pre>
All is OK with -n1e3 and below. Filtering mechanism or advice  already in mcgui?

Same situation with pyqtgraph

**Comment by willend** [comment]
Updated: Seems to behave the same on my Linux...

It seems the "hard limit" is around 1002 events?! :-) - at least in PSI_DMC

**Comment by willend** [comment]
On Windows the behaviour is worse: 
mcgui hangs until one gives input in underlying terminal window!

**Comment by willend** [comment]
Likely this has to do with signal handling: Once we have more than ~1e3 rays in mcdisplay-webgl the underlying process is killed, which then triggers an exception since the process is being monitored... 

We'll need a workaround for sure

**Comment by climbcat** [comment]
In <code>pipetools.McrunPipeMan</code> we have <code>self.reader.join(1000)</code>, a 1000 second timeout. However, in <code>TraceReader<code>, we have <code>max_particles=1000<code>.

**Comment by climbcat** [comment]
What would the optimal behavior be?

**Comment by willend** [comment]
Tested to work well after https://github.com/McStasMcXtrace/McCode/commit/b6275823906ea24b2743a0c412642f0d2fc53e1d, closing
