### ISSUE TITLE
Wiki - Update McStas-Mantid section

### ISSUE THREAD

**Issue by trnielsen** [McStasMcXtrace/McCode#685]
Use input from AM

**Comment by willend** [comment]
I have updated the page with instructions how to build nexusformat on macOS via homebrew

**Comment by trnielsen** [comment]
From e-mail by AM:
Hej,

Bare for at sige at jeg har bedt Keith Butler om at prøve vores wiki før møde onsdag som Mac bruger. Tilsyneladende kunne Göran Nielsen ikke finde ud af det som Mac bruger. Han gav op og prøvede istedet Windows som han delvist fik til at virke, men havde nogle små problemer med Mantid syntaks i McStas instrument filen som Peter hjalp med at forstå.

Nogle ting vi kan forbedre med wikien er nok

1. Gør det nemmere at forstå hvad der skal installeres
2. Måske ha en command line test example som brugeren kan køre for at teste det virker
3. Gør det nemmere at forstå hvordan man bruger Mantid syntaks i McStas instrument filen

Snakkes
Anders

**Comment by trnielsen** [comment]
Anders Markvardsen has asked for a reorganisation of the Mantid-McStas wiki pages on Github. 
The current wiki is one very long page which needs to be reorganised such that user may navigate easy through the "McStas-Mantid workflow".
AM has already provided some user feedback related to the current layout with suggestion for changes to be made.

**Comment by willend** [comment]
@trnielsen is this one done - or do you need feedback/review? (Or should we simply leave as is until after the actual release)

**Comment by willend** [comment]
Roger, removing from the board but keeping the ticket
