### ISSUE TITLE
Test if existing Vagrant environments still work

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#686]
in /Vagrant

**Comment by trnielsen** [comment]
Have test with new Vagrant file for OSX 13 and getdep_macos. 
Works Ok. Just need to update docs on wiki

**Comment by willend** [comment]
Centos Vagrant box fully functional

**Comment by willend** [comment]
Ubuntu 18.04 box fully functional

**Comment by willend** [comment]
macOS box fully functional

**Comment by willend** [comment]
Windows build via ubuntu now fully functional

**Comment by willend** [comment]
Fedora29 also seems to work
