### ISSUE TITLE
NeXus issues on Windows with 64 bit toolchain

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#689]
@ebknudsen here is the issue I promised to send you earlier. Time for hunting bugs close to the metal... ;-)

With e.g. this build of McStas for Windows: 
http://tmp.mcstas.org/McStas-Metapackage-2.5rc17-win64.exe

That needs this Perl in place before:
http://strawberryperl.com/download/5.26.2.1/strawberry-perl-5.26.2.1-64bit.msi

For NeXus, please use
https://github.com/nexusformat/code/releases/download/4.3.0/nexus-4.3-0-win64.exe

- it turns out that event lists end up empty in NeXus runs on Windows 10 with our new 64bit setup...

To illustrate what is going on, please use the attached mccode-r.c that gives some extra debugging messages e.g. with templateSANS_Mantid.instr 

To compile and run on my Mac:
<pre>
export MCSTAS_CFLAGS="-g -lm -O2 -DUSE_NEXUS -lNeXus -I/usr/local/include/nexus -L/usr/local/lib"
mcrun.pl -c templateSANS_Mantid.instr -n0
mcdisplay.pl --format=Mantid templateSANS_Mantid.instr -n0
mcrun.pl templateSANS:_Mantid.instr --format=NeXus -dWhatever
</pre>
On Mac I get the following output for the last detector:
<pre>
...
mcdetector_import filename=bank01_events_dat_list.p.x.y.n.id.t, format=NeXus list
 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 RETURN mcdetector_import filename=bank01_events_dat_list.p.x.y.n.id.t, format=NeXus list
 RETURN detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEX detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEX1 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo2 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo3 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo4 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo5 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo6 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo7 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo8 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo9 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo10 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo11 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo12 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list component nD_Mantid_1 sizes 1310,6,1
 NEX2 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
In out_data_nexus, detector filename is bank01_events_dat_list.p.x.y.n.id.t, detector component is nD_Mantid_1
In out_data_nexus, detector pointer value is 0x7ffee59eb7f0
detector.format is NeXus list for bank01_events_dat_list.p.x.y.n.id.t 
Events:   "bank01_events_dat_list.p.x.y.n.id.t"
 NEX3 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list

Finally [templateSANS_Mantid: Whatever]. Time: 1 [s] 
Warning: 235955 events were removed in Component[8] detector=PSD_monitor()
         (negative time, miss next components, rounding errors, Nan, Inf).
<pre>

And on windows I instead get
<pre>
mcdetector_import filename=bank01_events_dat_list.p.x.y.n.id.t, format=NeXus list
 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 RETURN mcdetector_import filename=bank01_events_dat_list.p.x.y.n.id.t, format=NeXus list
 RETURN detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEX detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEX1 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo2 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo3 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo4 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo5 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo6 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo7 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo8 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo9 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo10 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo11 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list
 NEXinfo12 detector.filename=bank01_events_dat_list.p.x.y.n.id.t, detector.format=NeXus list component nD_Mantid_1 sizes 10,140703128616966,1
 NEX2 detector.filename=
, detector.format=
In out_data_nexus, detector filename is
, detector component is
In out_data_nexus, detector pointer value is 00000000006E3A00
ERROR: group entry7/data does not exist
 NEX3 detector.filename=
, detector.format=

Finally [templateSANS_Mantid: .]. Time: 0 [s]
Warning: Number of events 5230 reaching SPLIT position Component[7] sampleMantid=Sans_spheres()
         is probably too low. Increase Ncount.
Warning: 2609 events were removed in Component[8] detector=PSD_monitor()
         (negative time, miss next components, rounding errors, Nan, Inf).
</pre>

Attached, mccode-r.c as a .txt file
[mccode-r.c.txt](https://github.com/McStasMcXtrace/McCode/files/2621869/mccode-r.c.txt)

**Comment by ebknudsen** [comment]
Have found a fix for this - but have as of yet not understood why it works...stay tuned

**Comment by willend** [comment]
Don't be a complete tease man, let us know! ;-)  :-D

**Comment by ebknudsen** [comment]
potentially fixed by: a150bbb8b4808a6f9e593381e5cb11bc70852b3
This bypasses the issue on my test machine for reasons unknown.

**Comment by willend** [comment]
Hmm, seems to still fail on my machine

**Comment by ebknudsen** [comment]
A side-remark:  the special windows printf-thing still gives garbage values for m,n,p - whereas it is ok to use a straight %d for these things. But anyway - we'll have to investigate further.

**Comment by willend** [comment]
OK. Could you try to send me the generated NeXus from your machine file for inspection?

**Comment by willend** [comment]
Did a fresh build this morning and tested templateSANS.instr - this now indeed works!
