### ISSUE TITLE
Updated Union comps etc.

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#693]
@mads-bertelsen has a patchers set of comps and Union code, we should try to get this into 2.5

**Comment by climbcat** [comment]
Ok, sounds great! Do we have a good all-round way to test the union components?

**Comment by willend** [comment]
One good way to get this would be to have %Example in the Union instruments?

<pre>
pkwi-mbp2018:examples pkwi$ grep Example * | grep -i union
Union_demonstration.instr:* Example: Detector: m4pi_two_or_more_samples_I=0.0945567
Union_demonstration_absorption_image.instr:* Example: Detector: screen_I=0.0107579
Union_external_component.instr:* Example showing the use of the "number_of_activations" parameter to include
Union_external_component.instr:* Example: Detector: Banana_monitor_I=5.26267
Union_external_component_test.instr:* Example: Detector: Banana_monitor_I=4.49056
Union_incoherent_validation.instr:* Example: Detector: Banana_monitor_I=18.4632
Union_laue_camera.instr:* %Example: mosaic=5 Detector: Banana_monitor_I=1.74328e+06
Union_manual_example.instr:* Example on using Union components from the Union project manual
Union_manual_example.instr:* Example: Detector: Banana_monitor_I=3.823e-05
Union_powder_validation.instr:* Example: Banana_monitor_I=20.1897
Union_sample_picture_replica.instr:* Example: Detector: detector_I=1982.98
Union_single_crystal_validation.instr:* %Example: comp_select=1 Detector: Banana_monitor_I=964146
Union_tagging_demo.instr:* Example: Detector: Banana_monitor_I=9.84391e-09
Union_test_absorption.instr:* Example: Detector: screen_I=5.91451e-06
Union_test_absorption_image.instr:* Example: Detector: screen_I=0.00925
Union_test_box.instr:* Example: Detector: m4pi_both_I=4.8716e-10
Union_test_mask.instr:* Example: Detector: m4pi_I=2.27579e-07
Union_test_powder.instr:* Example: Detector: m4pi_I=4.23557e-06
Union_time_of_flight.instr:* Example: stick_displacement=0 Detector: banana_detector_tof_I=566.295
pkwi-mbp2018:examples pkwi$ 
</pre>

**Comment by willend** [comment]
Hmm, not as easy as I thought, these instruments present lots of output (see attached) that seems to clash with the mcrun.pl test procedure. 

[output.txt](https://github.com/McStasMcXtrace/McCode/files/2649291/output.txt)


This of course does not prevent running the instruments pr. hand

**Comment by willend** [comment]
@mads-bertelsen, can you provide a fresh set of Union comps and infrastructure for McStas 2.6?

**Comment by mads-bertelsen** [comment]
@willend The version on the repo is the newest version. It does include the mesh component with the issue that it doesn't work with the basic geometries, which is stated clearly in the header.

**Comment by willend** [comment]
Excellent, thanks!

Is the new code from Victor Laliena also included?

**Comment by mads-bertelsen** [comment]
@willend No, I have not heard from Victor in a long time. From the SINE2020 documents it does however look like he has something that works.
