### ISSUE TITLE
mcdoc-py windows usage

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McCode#696]
Relating to this (faulty) code state: 0a6fc708cf277ab7ef09d9c335270b1c434efe19 :

During installation:

![image](https://user-images.githubusercontent.com/11196009/49596138-ea2d5a80-f979-11e8-9230-25af0317e370.png)

And after the installation has completed, in a mcstas console:

![image](https://user-images.githubusercontent.com/11196009/49596253-34164080-f97a-11e8-8120-358bfcb726aa.png)

**Comment by willend** [comment]
For the first part of the issue let’s try to
1) look if there is a mcdoc.bat in place at all?
2) Add the bat suffix in the nullsoft package definition 

For the second one, check that the mcdoc py correctly installed in the wanted folder and that the above path indeed resolves to the wanted place with all the ..\\..

**Comment by willend** [comment]
Works now - from the terminal, but we need to fix such that mcdoc (python) is called from mcgui

**Comment by willend** [comment]
With https://github.com/McStasMcXtrace/McCode/commit/fabd9ae327ccedd2b9699b04ca3d4b5e34b67c25 the python mcdoc is also what is run on windows from the gui.

One remaining issue it seems @climbcat - one gets an error if trying to do mcdoc current instrument on windows:
![screenshot 2018-12-07 at 09 32 32](https://user-images.githubusercontent.com/8593355/49636704-a54e0600-fa03-11e8-8911-ce654db6eed2.png)

**Comment by willend** [comment]
Same problem, different flavour on macOS - all I get is an empty html page:
![screenshot 2018-12-07 at 09 43 13](https://user-images.githubusercontent.com/8593355/49637020-8a2fc600-fa04-11e8-87ef-54e7b0b5f85b.png)

Perhaps what is missing is a check if the first argument is a single component or instrument - simply generate the mcdoc page if not there - and open directly?

**Comment by willend** [comment]
Looks good. closing
