### ISSUE TITLE
mcgui / mcdisplay halts with EOF when reading line when using ESS_BEER_MCPL

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#701]
From within mcgui using the default parameters I get:

![screenshot 2018-12-07 at 10 53 17](https://user-images.githubusercontent.com/8593355/49640627-5c4f7f00-fa0e-11e8-919c-58cc55a0927d.png)

To reproduce, please copy the BEER*mcpl files from your $MCSTAS/data folder to the current working folder

Strangely, mcdisplay-webgl works OK from the terminal with the copy-pasted mcdisplay command:
<pre>
mcdisplay-webgl ESS_BEER_MCPL.instr --no-output-files -n 1000000  input=BEER_MR.mcpl  repetition=50  pwdfile=duplex.laz  lc=6.65  lam0=2  dlam=1.8  omega=45  chi=90  colw=1  modul=0  mod_frq=2240  mod_twidth=0.0029  mod_shift=0  only_event=-1  pinc=0.1  ptra=0  strain=0  ustrain=0
</pre>

**Comment by climbcat** [comment]
For me, the mcdisplay hangs, also when run in the console. I have no problems running the instrument with mcrun.

**Comment by climbcat** [comment]
the problem is a side effect of the "looking for prompt" regex used by the mcdisplay backend. BEER surprisingly outputs a false positive.

**Comment by climbcat** [comment]
Should have been fixed by 1f232cafb0cbbacc2a7cca9aac531a645f63f825

**Comment by willend** [comment]
Tested, works. DONE
