### ISSUE TITLE
mcgui comboboxes for autoplot and mcdisplay not fully rendered (on old macOS versions only)

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#708]
In the released 2.5, the full content of the combobox selectors on the run dialogue (autoplot / mcdisplay) is not always completely visible.

Dragging the width of the run dialogue helps immediately, I guess we should just add 5-10% in starting width 

![screen shot 2018-12-14 at 09 31 51](https://user-images.githubusercontent.com/8593355/49992190-a511b580-ff83-11e8-9d41-1e06dd983dc8.png)
![screen shot 2018-12-14 at 09 32 31](https://user-images.githubusercontent.com/8593355/49992191-a511b580-ff83-11e8-8308-f6c98c65fc0b.png)

**Comment by willend** [comment]
Consider if this is worth any effort as this looks OK on e.g. Mojave and was so far only observed on El Capitan

**Comment by willend** [comment]
Indeed, but as it seems only relevant on old macOS's so we can also just park it as a "wont fix" - because if people drag the window once all is good...

**Comment by climbcat** [comment]
widened slightly by 14831d94ab1ba419498efe46d6f04efcfd578e57

**Comment by willend** [comment]
after 14831d9 looks OK, closing
