### ISSUE TITLE
mcstas-3.0 branch: Isotropic_Sqw crashes in two instruments

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#746]
@climbcat reports that both ILL_BRISP and templateTOF fail with segfaults ala below on Linux and modern gcc's only 

<pre>
 Last I/O Error: No such file or directory
Quit (core dumped)
[FAILED] ILL_BRISP: (33536): 
Test Abstract for selftest_yGIE
[FAILED] ILL_BRISP_1 (compilation/execution)

# Execution check:    FAILED. 1 instrument(s) did not compile/execute.
# >> Check instruments and mcstas installation.
# End Date: Thu Jan 24 15:42:48 2019
</pre>

- Local version of the component? Or maybe changes to read_table-lib that needs porting? @ebknudsen @farhi ?

**Comment by farhi** [comment]
Yes, this is the version before I fixed the crash. The issue arises from MPI parts in the initalisation of the component. An easy fix is to get the version from the master branch:

- https://github.com/McStasMcXtrace/McCode/commit/58093521166081c29f6eb7cd5d50335fd7af1951#diff-7c95d646cb27a29eb9a4d9d688f619c3

**Comment by willend** [comment]
@climbcat I guess we can close this one?

**Comment by ebknudsen** [comment]
supercerded
