### ISSUE TITLE
Single_crystal: Make docs more clear on benefits of p_transmit in [0,1]

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#751]
Make it easier to understand that it can be highly beneficial to use e.g. p_transmit=0.001

**Comment by willend** [comment]
@ebknudsen how relevant is this one wrt. McXtrace 1.5? 

As far as I can see p_transmit defaults to -1 there whereas it has had a 10% value in McStas. 

(I am about to commit a change on the McStas side that reduces to one permille and enhances the doc string)

**Comment by ebknudsen** [comment]
A good edit on docs I think.

**Comment by ebknudsen** [comment]
Wrt the default value - What I hear is that users get confused by p_transmit and largely want to keep it at the physical values.

**Comment by willend** [comment]
@ebknudsen I understand the point of view, but I believe it is reasonable to have a "better" default than 10% which we had before. A simple adjustment of this input parameter is what allowed the NMX team to proceed - were otherwise stuck

**Comment by ebknudsen** [comment]
@willend Sure - I can see that. I buy the 1pm vs 10% thing. We just need to be very clear that it is possible to use the physical values by setting p_transmit=-1. And perhaps as a stretch goal unify the description across Single_crystal and PowderN.
In summary OK - I'm persuaded :-)

**Comment by willend** [comment]
I've further edited the comments along the direction of explaining what it does: I believe this is better_

* Monte Carlo probability for neutrons to be transmitted without any scattering. Used to improve statistics of the scattering pattern wrt. the attenuated, direct beam. It is typically beneficial to leave this parameter at a value << 1. Use the value -1 to deactivate any stratified sampling and partition probabilities fully in accordance with the material cross-sections.

Commit coming in a few minutes which close the issue
