### ISSUE TITLE
cogen3: reimplement defpars into setpars

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McCode#755]
In order to upgrade cogen3 to a class-based approach, components using definition parameters need to be reimplemented.

**Comment by climbcat** [comment]
Defpars using components after applying dynamic 1d/2d/3d arrays: 20

**Comment by climbcat** [comment]
Defpars using components classified as "MCGET_PAR" using a component name as a defpar: 9

**Comment by climbcat** [comment]
Defpars using components classified as "function name": 5

**Comment by climbcat** [comment]
Defpars using component (unclassified/other): 5

<pre>
mcstas-comps/samples/Isotropic_Sqw.comp
mcstas-comps/samples/Isotropic_Sqw_legacy.comp
mcstas-comps/monitors/Monitor_Sqw.comp
mcstas-comps/monitors/Monitor_nD.comp
mcstas-comps/contrib/union/Powder_process.comp
</pre>

**Comment by climbcat** [comment]
How to get rid of compname / MC_GETPAR usage.

The MC_GETPAR macro is defined as
<pre>
#define MC_GETPAR2(comp, par) (_ ## comp->_parameters.par)
#define MC_GETPAR(comp, par) MC_GETPAR2(comp,par)
</pre>
and a typical usage is
<pre>
double angle = MC_GETPAR(rotator, angle);
</pre>
The "rotator" symbol is written as a component name definition parameter, and "angle" is the parameter variable name.

To liberate the 'rotator' symbol as a def par, it must be written as a setting parameter string.

**Comment by climbcat** [comment]
Suppose we generated a function during the cogen step:
<pre>
void* _getvar_parameters(char* compname)
{
...
  if (!strcmp(compname, "Mon_Source")) return _Mon_Source->_parameters;
... (one strcmp line pr. component instance)
}
</pre>
We could then rewrite the "component API" from the simple MC_GETPAR form, to something more complicated involving the component parameters type:
<pre>
//struct MonitornD_Variables *Vars = &(MC_GETPAR(monitor_comp, Vars));
struct MonitornD_Variables *Vars = &((class_MonitornD_parameters) _getvar_parameters(monitor_comp)).Vars;
</pre>
where <code>class_MonitornD_parameters</code> is the struct pointer type generated from the component type during the cogen process, and monitor_comp is a string containing the (user-defined) monitor component instance name.

*****

Note that a naive rewrite of MC_GETPAR into the following would NOT do the job, because the return value of the <code>_getvar</code> function is <code>void*</code> and can thus not be dereferenced. Thus an API change is necessary to eliminate this use of definition parameters.
<pre>
#define MC_GETPAR2(compname, par) (_getvar_parameters(compname).par)
</pre>

**Comment by climbcat** [comment]
Instruments that test MC_GETPAR using functions are listed below, located in "mcstas-comps/examples-full":

<pre>
Test_PreMonitor_nD.instr
Test_Scatter_log_losses.instr
Test_Scatter_log_mvalues.instr
Test_Scatter_log_ssw_mcnp.instr
Test_Sources.instr
Test_StatisticalChopper.instr
</pre>

**Comment by climbcat** [comment]
Possibly, the component "MC_GETPAR" code should be more along the lines of:

<pre>
struct MonitornD_Variables *Vars = &((class_Monitor_nD_parameters_struct*) _getvar_parameters(monitor_comp))->Vars;
</pre>

with 
<pre>
typedef struct class_Monitor_nD_parameters class_Monitor_nD_parameters_struct
</pre>

Note that <code>typedef</code> is required, because we can not cast to a struct.

**Comment by climbcat** [comment]
TEST REULTS:

The <code>PreMonitor_nD.comp</code> tested using <code>examples-full/Test_Premonitor_nD.instr</code> ran successfully with the following version of MC_GETPAR:

<pre>
struct MonitornD_Variables *Vars = &( ((class_Monitor_nD_parameters *) _getvar_parameters(monitor_comp))->Vars );
</pre>

Explaination:

Since the result of <code>_getvar_parameters</code> is <code>void *</code>, we need to cast this to the proper (cogened) comp parameters type pointer, then dereference to get the <code>Vars</code> using the "follow pointer to value" symbol, <code>-></code>, and finally assign the address of the parameter to the pointer Vars. This results in a verbose use of brackets.

**Comment by willend** [comment]
Sounds really good! Is the needed code to do this test already in the repo?

**Comment by willend** [comment]
Everything was indeed in the repo. Attached graphic shows that the output is essentially the same (was run with same seed, but our reordered code between master and 3.0 branch seems to influence the test result)

![screenshot 2019-02-28 at 15 40 40](https://user-images.githubusercontent.com/8593355/53574350-baa07f80-3b6f-11e9-9bc8-f6fe319ce28a.png)


Graphics produced using https://github.com/McStasMcXtrace/McCode/tree/master/tools/other/test Matlab code and output datasets produced using stock 2.5 and a build from the 3.0 branch.

**Comment by climbcat** [comment]
Current status of defpars removal process.

MC_GETPAR dependence has been removed and replaced by MC_GETPAR3, which takes the type as the first argument, a symbol, the component name as the second, a string, and then the parameter as a symbol.

However, the change could not be tested fully See c3e029557eb3f1e5f29ab8a2873aee3f8b029fae. We need to have a look at scatter logger with @ebknudsen at some point, because there are function pointer defpars in some of the scatter logger components, that need to be resolved simultaneously, for the tests to run.

- A few defpars remain, and these are all of the weird ones. Currently 12 components have defpars.

- For example, <code>Isotropic_Sqw.comp</code>, <code>Monitor_Sqw.comp</code> and <code>Monitor_nD.comp</code> use defpars. @farhi do you have any easy fixes for these, and/or do they cover special cases that can be ignored for now?

- As of now I am focusing on simplifying the cogen process and the generated code.

**Comment by climbcat** [comment]
Update: Currently only the following components contain definition parameters: 

<pre>
mcstas-comps/optics/Pol_mirror.comp
mcstas-comps/optics/Pol_FieldBox.comp
mcstas-comps/optics/Pol_Bfield.comp
mcstas-comps/obsolete/Pol_simpleBfield.comp
mcstas-comps/misc/Scatter_log_iterator.comp
</pre>
