### ISSUE TITLE
Single_crystal: consider new default for p_transmit

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#767]
Following discussions with Esko Oksanen et al. wrt. NMX that uses a 1mm^3 sample, most of the stats go into the beamstop... Putting p_transmit to a finite value (e.g. 1%) gave in the case of PPase sample a factor of 30000 stat improvement.

I.e.: Consider putting the default for p_interact to 0.1 or 0.5 and UPDATE THE DOCS

**Comment by ebknudsen** [comment]
... also update docs to reflect this _clearly_
