### ISSUE TITLE
Create presentation templates 

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#771]

**Comment by willend** [comment]
We recently got a new "corporate" DTU slide design which I have derived the attached examples from. I tend to like the green one best... 

![screenshot 2019-03-06 at 13 28 25](https://user-images.githubusercontent.com/8593355/53881453-0772d300-4014-11e9-8b51-7058e1a29a07.png)

![screenshot 2019-03-06 at 13 29 05](https://user-images.githubusercontent.com/8593355/53881463-0d68b400-4014-11e9-9d3b-80cf6be736d1.png)

![screenshot 2019-03-06 at 13 28 34](https://user-images.githubusercontent.com/8593355/53881466-10fc3b00-4014-11e9-9c66-92483dbedcab.png)

![screenshot 2019-03-06 at 13 28 39](https://user-images.githubusercontent.com/8593355/53881471-148fc200-4014-11e9-9818-f4bac07ec7db.png)

**Comment by mads-bertelsen** [comment]
Looks nice! The color scheme of my old presentation on Union is matched the the KU and NBI logos using their red and green colors. I will have to change color scheme anyways, so you do not need to consider how those slides look in the new template.

**Comment by willend** [comment]
Roger. I am opting for the red theme anyway, feels more "DTU" than the other ones... :-) Will put these in a Dropbox shortly

**Comment by willend** [comment]
The red version is now uploaded to the DropBox that can be found via http://csns2019.mcstas.org (links to both DropBox and GitHub based material available there)

**Comment by willend** [comment]
(Exists in Keynote, ppt and libreoffice formats, provided both as presentation files and actual template files)
