### ISSUE TITLE
Incremental optics exercises (Tuesday)

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#772]
* Collimators and slits
* Guide
* Rotating optics
  -> DiskChopper
  -> Velocity selector
  -> Fermi
* Monochromators

**Comment by mads-bertelsen** [comment]
Where should I place the instrument files / instructions?

**Comment by willend** [comment]
I will create a repo for that shortly

**Comment by willend** [comment]
I propose to put them in this repo
https://github.com/McStasMcXtrace/Schools/

- have made an empty CSNS folder inside which could have subfolders for days  and subsub folders for tasks ?

**Comment by willend** [comment]
Closing as duplicate of https://github.com/McStasMcXtrace/Schools/issues/5

**Comment by willend** [comment]
Closing as duplicate of https://github.com/McStasMcXtrace/Schools/issues/5
