### ISSUE TITLE
Create google calendar for the CSNS week

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#773]

**Comment by mads-bertelsen** [comment]
A first draft of the program have been made in google calendar with short descriptions of each session. It can be found here: [https://calendar.google.com/calendar?cid=MzJiOGhmZTBqZ25ucXRtaGpvNXBibXZoMmNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ](url)

Invitations for editing sent to Erik and Peter.

I feel there is a time for a bit more content, or maybe I have been to optimistic with the length of each session?
We should perhaps ask the host about appropriate work hours and lunch time.

**Comment by willend** [comment]
Hi there,

I have taken a look and made a slight modification: 
Interchange of DECLARE-INITIALIZE and Monochromators. 

The idea is then that we work with Bragg's law in DECLARE-INITIALIZE after introduction of the Monochromator, i.e. change from direct angular input to calculation of scattering angle.

I have further introduced a coffee break in the morning of Tuesday.

I generally like the fact that some undefined time is available in the programme as these things typically take longer than expected...

**Comment by willend** [comment]
Closing as as duplicate of https://github.com/McStasMcXtrace/Schools/issues/4
