### ISSUE TITLE
cogen3: update Monitor_nD to not use defpars

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McCode#778]
edit: Not relevant.

**Comment by willend** [comment]
The user1,..user3 are in fact always double valued and neutron-dependent.

They typically come from the instr def section:
<pre>
DECLARE %{
    double MyVal;
%}
</pre>

and then calculate / extract something from a component e.g.

<pre>
COMPONENT Whatever = PowderN( ... )
EXTEND %{
  MyVar=SCATTERED;
%}
</pre>

Proposal for a solution:

A. Define either 
1. A new macro that glues MyVar to the neutron struct (i.e. neutronvar('MyVar'))
2. A special section ala DECLAR e.g. called VARS that using normal catenation adds that block to the neutron struct

B. Make a table of 'lookup strings' ala what was done for mc_getpar for these new vars

C. 
1. Make the user vars in Monitor_nD normal setting parameter strings with default "UNDEF" 
2. In the top of Monitor_nD TRACE, use something like
<pre>
   if (strcmp(user1,"UNDEF")) Vars.UserVariable1 = getNeutronVar(user1);
</pre>
to let Mon_nD look up the value

**Comment by willend** [comment]
@farhi @ebknudsen 

Your inputs would be appreciated here

**Comment by climbcat** [comment]
Having discussed this issue with Erik, the problem seemed slightly more complicated than first anticipated, which lead us to suggest an alternative. 

The alternative solution consists of two macros: <code>CG_ADD_PARTICLE_VAR(var)</code> and <code>GET_PARTICLE_VAR_DPTR(char *varname)</code>. The first is a CG/cogen macro, which on a precompiler level simply produces a comment. Primarily, the cogen step uses this macro to add the variable to the particle struct. This step extracts the variable using re.c, a ~500 lines public domain impl. that we added yesterday, but it does not edit that code.

The solution you suggested above turned out to require even more code parsing, in that the extraction of C-style variable declarations from a VARS block is nontrivial, and, unfortunately, the code base did not possess an equivalent implementation from the past. DECLARE blocks are simply copy-pasted.

The second rationale for this macro-based approach, is that the EXTEND block above would not work without further non-trivial code editing. The <code>MyVar=0.1</code> needs to be substituted with <code>particle->MyVar=0.1</code>, and this substitution is non-trivial, because of situations where users have named their variables something like <code>MyVar, MyVar2.</code>. This is a headache we may want to avoid.

**Comment by farhi** [comment]
Looking all this from some distance, it looks quite complicated getting rid of DEFPARS. Perhaps a safer route would be first to have a an "easy cogen-3 " which still supports the old syntax, and stabilize it. Then, once all is functional, go onto the full OO approach. A new code generation is already by itself quite challenging, and it does impose changes on the grammar. But better keep these changes as limited as possible from one release to the other, keeping simple implementation solutions. This is just my 2c.

**Comment by willend** [comment]
Hi guys,

Erik and I have had yet another another look.

The "best" way to add user variables to the neutron struct would indeed be to have a VARS (or equivalent) section in the INSTRUMENT scope, working exactly as DECLARE does in the components. This works the way that one can only have things like

VARS %{
    double a_number; // With a comment.
%}

The current implementation that puts DECLARE content in comps into the comp struct can be re-used, that is more or less copied. Comments are supported in the sense that these are stripped off as far as I can see (Erik and I even tried adding a

double complex CC;

which works fine as long as there is a #include <complex.h> somewhere.)

Best
Peter

**Comment by climbcat** [comment]
Hi Peter. 

Unfortunately, we can't reuse that code. (I thought so as well until I looked into it.) The code that "parses" the declare section uses the component parameters as keys to look for. What we have are wildcards and that requires a new implementation.

Even then, there's still the EXTEND section issue...

**Comment by willend** [comment]
First a comment to my own input above:

... and in fact after some thoughts, code-digging and rambling we now have the impression that with the VARS construction made like the above we are looking at a non-isssue. (The DTU-part of the team will have an in-depth discussion the next time we are all in the same room - and update @farhi  afterwards!)

Our thoughts are along the lines of the below which we can discuss the next time we are together

( 
1) Assuming VARS means that myvar is now member of the neutron struct, i.e. #define myvar neutron->myvar just like it works for 'x'. This has to be known BEFORE any initialisation / comp struct building

2) A Monitor_nD instance has user1=myvar (which is now NOT a defpar but a normal setting par), which will result in the copy-in of user1=myvar; (just like what is done for radius in the BNL_H8 Source_simple resulting in   _Source->_parameters.radius = 0.10; in the generated code near _Source_setpos

3) Around the component trace we have #define user1 comp->user1 and in the Source simple case from above something like   #define radius (comp->_parameters.radius)

4) In the actual Monitor_nD component code we have things like the below line
if (user1 != FLT_MAX) Vars.UserVariable1 = user1;

that will automatically then translate to 

if(comp->user1 !=FLT_MAX) Vars.UserVariable1 = comp->user1
)

**Comment by willend** [comment]
And a comment to your statement  @climbcat that this can not be used, I really don't think this is true. if we limit the possibilities of what can be in the VARS section to

VARS %{
     double myvar;
%}

the code-generation can glue this into the neutron struct.

**Comment by climbcat** [comment]
1)

Right, I forgot about that def/undef trick we talked about on thursday. That part is not difficult to do.

2)

The only DECLARE "parsing" code I could find is in the function <code>cogen_comp_declare</code> in the code generator.

The extraction code here has an outer loop which iterates over the combined defpars and separs of the component, looking for matches in the DECLARE text. It deals with comments at the same time which makes the code complicated.

Our issue is that we need to work with wildcards (unknown variable names), and in pure C this is no fun at all. However, with regex it is much more doable.

**Comment by farhi** [comment]
Hi @climbcat . I confirm that identifying the variable names in the DECLARE block to search for C declarations, taking into account the comments, was not easy to write into some code. 

The solution I actually came to is not ideal, and works. But it _certainly_ will handle situations were that code will not work. So a regexp approach makes sense at this level, I agree.

**Comment by willend** [comment]
Guys, one _could_ also do one of these within the VARS block

a) Add a new cogen grammar item like ADD_NEUTRONVAR(varname,type) 
b) Let the cogen parse the VARS lines for the last label before any ; e.g. double complex alpha; would lead to alpha.

There are surely ways!

**Comment by willend** [comment]
... I guess a) is more or less what you propose above with CG_ADD_PARTICLE_VAR(var) @climbcat

**Comment by climbcat** [comment]
Yes it is. That has actually been implemented as a start. We can implement the VARS in which users can put their own variables using regex. (259d54873e9d36b060c7a89b70a620af7e03dbb0)

**Comment by climbcat** [comment]
Changes b7e8df4ffc8e314306b2cef28fc7ffb08ac5a046 (and 3c6ec9a19c7958f1669dc28aa022870f1b363346) now result in only 10 instruments not compiling. All instruments in /examples/ that previously failed because they contained Monitor_nD, now compile.

**Comment by farhi** [comment]
Good work @climbcat ! Many thanks.

**Comment by willend** [comment]
Let me 👍 that also

**Comment by climbcat** [comment]
Thanks guys! Now let's test it some more btw.:-)

**Comment by climbcat** [comment]
This has now been achieved, see #782.
