### ISSUE TITLE
McStas-Components,McXtrace-Components: zero weight coherent  scattering chains in Single_crystal

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#78]
**Reported by erkn on 25 Nov 2009 13:03 UTC**
If incoherent scattering is set to 0, Single crystal may end up in nonending scattering chains with neutron weight set to 0. The particular cause is the probability for tunneling may be <1. 

Thus the neutron may end up in the scattering branch, but if no coherent peaks are in the vicinity the weight is simply set to zero (unchecked for). There's a mixing of monte carlo/real scattering models here

**Comment by willend** [comment]
**Modified by erkn on 25 Nov 2009 13:03 UTC**

**Comment by willend** [comment]
Likely related to https://github.com/McStasMcXtrace/McCode/issues/143

**Comment by farhi** [comment]
It seems this is now fixed. Just ran Test_SX.instr and specify sigma_inc=0
```
COMPONENT sample = Single_crystal(reflections="Mo.lau", material="Mo.txt", 
  radius = .5e-4, yheight = 1e-3, p_transmit = 0, mosaic=1, sigma_inc=0)
```

produces a "normal" result. weights are non-0. A few

**Comment by ebknudsen** [comment]
Iirc the problem also "required" that absorption was turned off.
