### ISSUE TITLE
cogen3: Bring back all instruments from examples-full

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McCode#784]

**Comment by climbcat** [comment]
A lot of instruments have been brought back. Many of the remaining ones depend on components with "fct pointer" type defpars.

**Comment by climbcat** [comment]
Many instruments were brought back and three directories are used: examples, examples-fail and examples-parked. The first should contain all functioning instruments, the second contain instruments that are easily fixable or have not been evaluated. The last directory contains instruments that take a dedicated effort or specialized knowledge to fix.

**Comment by climbcat** [comment]
There are currently FIVE compilation/execution errors in examples-fail, and SIXTEEN instruments in examples-parked. This is disregarding Union components, which should be fixable by the aid of MB.

**Comment by climbcat** [comment]
<pre>
# Last I/O Error: No such file or directory
[FAILED] Test_Monitor_Sqw: (131): 

# Last I/O Error: No such file or directory
[FAILED] templateTOF: (131): 

# Last I/O Error: No such file or directory
Quit (core dumped)
[FAILED] ILL_BRISP: (33536): 

[FAILED] Test_Pol_TripleAxis: (256): 
</pre>

Note that the last instrument didn't mention why it failed to compile/execute.

**Comment by climbcat** [comment]
What is this about? Instrument file Test_StatisticalChopper fails in this way:

<pre>
INSTRUMENT Test_StatisticalChopper:
  An example using a statistical/correlation chopper and its de-correlation monitor

Executing: mcrun.pl Test_StatisticalChopper lambda=1 -n 1000000 --format=PGPLOT -d Test_StatisticalChopper_1
Info:    'StatisticalChopper' is a contributed component.
Info:    'StatisticalChopper_Monitor' is a contributed component.
CFLAGS=
Test_StatisticalChopper.c: In function ‘sighandler’:
Test_StatisticalChopper.c:4865:5: warning: implicit declaration of function ‘kill’; did you mean ‘ceill’? [-Wimplicit-function-declaration]
     kill(0, SIGKILL); /* kill myself if error occurs within sighandler: loops */
     ^~~~
     ceill
Test_StatisticalChopper.c: In function ‘Table_Read_Handle’:
Test_StatisticalChopper.c:8067:18: warning: implicit declaration of function ‘strncasecmp’; did you mean ‘strcasecmp’? [-Wimplicit-function-declaration]
             if (!strncasecmp(lexeme,"NaN",3))
                  ^~~~~~~~~~~
                  strcasecmp
Test_StatisticalChopper.c: In function ‘class_StatisticalChopper_Monitor_init’:
Test_StatisticalChopper.c:13434:21: error: request for member ‘_parameters’ in something not a structure or union
   #define Vars (comp->_parameters.Vars)
                     ^
Test_StatisticalChopper.c:13438:10: note: in expansion of macro ‘Vars’
   strcpy(Vars.compcurname, NAME_CURRENT_COMP);
          ^~~~
Test_StatisticalChopper.c:370:32: error: request for member ‘_name’ in something not a structure or union
 #define NAME_CURRENT_COMP (comp->_name)
                                ^
Test_StatisticalChopper.c:13438:28: note: in expansion of macro ‘NAME_CURRENT_COMP’
   strcpy(Vars.compcurname, NAME_CURRENT_COMP);
                            ^~~~~~~~~~~~~~~~~
Test_StatisticalChopper.c:13424:24: error: request for member ‘_parameters’ in something not a structure or union
   #define options (comp->_parameters.options)
                        ^
Test_StatisticalChopper.c:13439:7: note: in expansion of macro ‘options’
   if (options != NULL)
       ^~~~~~~
Test_StatisticalChopper.c:13434:21: error: request for member ‘_parameters’ in something not a structure or union
   #define Vars (comp->_parameters.Vars)
                     ^
Test_StatisticalChopper.c:13440:13: note: in expansion of macro ‘Vars’
     strncpy(Vars.option, options, CHAR_BUF_LENGTH);
             ^~~~
Test_StatisticalChopper.c:13424:24: error: request for member ‘_parameters’ in something not a structure or union
   #define options (comp->_parameters.options)
                        ^
Test_StatisticalChopper.c:13440:26: note: in expansion of macro ‘options’
     strncpy(Vars.option, options, CHAR_BUF_LENGTH);
</pre>

**Comment by farhi** [comment]
The `StatisticalChopper_Monitor` component is defined as an extended **COPY** of Monitor_nD. This way, it uses the same logic (here INIT) and adds some more code afterwards.

StatisticalChopper_Monitor, line 50:
```
INITIALIZE COPY Monitor_nD EXTEND
...
if (!strstr(Vars.option, "time")) {
...

```

The INIT EXTEND section makes explicit use to the Vars structure, which is defined in Monitor_nD. Perhaps the cogen3 does not properly make this structure available in the copied/extended component ?

To my knowledge, there are quite few components which use this COPY/EXTEND syntax, and this component is one of these.

**Comment by climbcat** [comment]
Thanks for the hint. It turns out that StatChopMon has a parameter named "comp", which is also the name of the component local variable in all class functions. I will simply follow my own suggestion and rename all such "engine" components to start with an _underscore.

**Comment by climbcat** [comment]
Currently, 140 instrument examples compile. Of those who have a test, 11 fail with inaccuracy. 

<pre>
# Execution check:    OK.     Computing time: 696 [sec] for 99 tests.
# Accuracy check:     FAILED. 11 test(s) with inaccurate results.
# End Date: Tue Apr  9 14:46:06 2019
</pre>

In addition, there are 8 instruments in examples-fail, and 34 in examples-parked, of which half are Union.

**Comment by climbcat** [comment]
This task can be closed.
