### ISSUE TITLE
McCode: a WHEN clause cannot have ' single quotes in it

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#785]
Apparently the instrument file analyser gets confused if there is one (or more) single quotes inside the expression inside a WHEN-clause.
Example (activating a monitor depending on the type of scattering in Single_crystal)

 /*Does not work*/
 DECLARE
 %{
   char myvar;
 %}
 ...
 COMPONENT sx = Single_crystal( ... ) 
 AT(0,0,0) RELATIVE PREVIOUS 
 EXTEND
 %{
   myvar=hkl_info.type;
 %}

 COMPONENT psd = PSD_monitor( ... )
 WHEN (myvar=='c') AT (0,0,1) RELATIVE PREVIOUS

**Comment by farhi** [comment]
Double quotes work OK:

`ILL_H53_D16.instr:WHEN (Powder && strlen(Powder) && strcmp(Powder,"NULL"))  `

the error may come from the grammar scope in the bison part (instrument.y)

**Comment by ebknudsen** [comment]
related to #978

**Comment by farhi** [comment]
close with last commit
