### ISSUE TITLE
MCSTAS 2.5

### ISSUE THREAD

**Issue by eddymaoui** [McStasMcXtrace/McCode#789]
after instalation of
strawberry-perl-5.26.3.1-64bit
nexus-4.3-0-win64
McStas-metapackage-2.5-win64
I got files on my desktop mcgui-2.5 and mcstas-shell-2.5 when I click on the first the cmd will open and close at the same time when the second click on the cmd will open and leave a message "" McStas shell environment:
McStas version 2.5 (Dec. 12, 2018)
Copyright (C) DTU Physics and Riske National Laboratory, 1997-2018
Additions (C) Laue Langevin Institute, 2003-2018
All rights reserved
Microsoft Windows [Version 10.0.17134.648]
(c) 2018 Microsoft Corporation. All rights reserved.

C: \ Users \ EDDY AHMED> "" "
please help me
thank you

**Comment by willend** [comment]
Hello @eddymaoui,

OK, this seems to indicate an issue with our (anaconda) Python based GUI. My guess is that there is a related error message in the terminal window that appears when you run via the mcgui-2.5 link.

Could you try issuing the command "mcgui" via the mcstas-shell-2.5 window? Then I can have a better idea what is going on?

Best
Peter

**Comment by eddymaoui** [comment]
hello Peter Willendrup
thank you for your constructive response
I issue the command "mcgui" via the window mcstas-shell-2.5
after I got this message "" Traceback (most recent call last):
   File "C: \\ mcstas-2.5 \\ lib \\ tools \\ Python \\ mcgui \\ mcgui.py",
line 14, in <module>
     from PyQt5 import QtCore, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'

C: \ Users \ EDDY AHMED> "" "
thank you

Le lun. 1 avr. 2019 à 13:59, Peter Willendrup <notifications@github.com> a
écrit :

**Comment by willend** [comment]
Hello again,

OK, as I assumed it is an issue with the python modules... What is the output of the following command if you give it in the same terminal?

<pre>
python --version
</pre>

Is there a chance you tried installing McStas behind a proxy server - or without access to the internet? If you were behind a proxy, try setting the variables
<pre>
set HTTP_PROXY=http://your_proxy_ip:port
set HTTPS_PROXY=http://your_proxy_ip:port
</pre>
Anyway try installing the python modules again using
<pre>
conda config --add channels conda-forge
conda install mingw -y
conda install -c msys2 m2w64-gsl -y
pip install pyqt5 qscintilla mpld3 pyqtgraph pyaml ply matplotlib numpy tornado scipy pillow
</pre>
(These commands are taken from https://github.com/McStasMcXtrace/McCode/blob/master/meta-pkgs/windows/python-install.bat.in)

**Comment by willend** [comment]
Judging from the later issues, I assume you succeeded in getting McStas running? :-) Therefore I am closing this issue. :-)
