### ISSUE TITLE
Exit code 255

### ISSUE THREAD

**Issue by hyatt03** [McStasMcXtrace/McCode#798]
Hello

I'm getting the following error message when running display 2d using mcstas 2.5.0:
TraceReader- mcrun process exited with code: 255

I've tried searching around and looking in the documentation, but I cannot figure out what it means, can you please help?

**Comment by willend** [comment]
Hi there,

To allow us to figure out what is going on, please provide 

1) A zip file with instrument file and all needed bits and pieces

2) Information on your OS and it’s version

3) A screenshot or text output indicating the exact error message with all the surrounding output

Cheers
Peter

**Comment by ebknudsen** [comment]
no response - closing
