### ISSUE TITLE
macOS 10.14.5 "Mojave" and McStas-distributed gcc:  mccode-r.h:39:18: fatal error: math.h: No such file or directory

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#799]
With the latest update to Xcode command line tools, there is no longer an option to install the system header files to the legacy location of /usr/include .

This means that the miniconda-based gcc that we distribute with McStas and McXtrace is no longer able to locate the math.h header file and compilations fail with

```
mccode-r.h:39:18: fatal error: math.h: No such file or directory
```

For now, the easiest workaround is to instead use the Xcode-distributed clang compiler, i.e. in mcgui enter File->Preferences and adjust the CC and MPICC settings to those shown below and press save.

![Screenshot 2019-06-07 at 14 17 18](https://user-images.githubusercontent.com/8593355/59103912-6eb06400-8930-11e9-8b91-effc3ca8f4d9.png)

- Similarly for mcgui.pl:
![Screenshot 2019-06-07 at 14 35 38](https://user-images.githubusercontent.com/8593355/59104319-93f1a200-8931-11e9-9acf-6f987965281e.png)

We will will address the issue more directly in the coming versions of the packages.

**Comment by ebknudsen** [comment]
Solution is to use /usr/bin/clang - closing
