### ISSUE TITLE
Compilation issues with multiple McXtrace instr on master

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#801]
A fresh build of McXtrace (from the master branch) on Centos7 fails to compile most instruments - here is the mxrun.pl test abstract:

(I am attaching the full output, zip file and text file below)

<pre>
Test Abstract for selftest_4EB2
[notest] MAXIV_FemtoMAX (no test procedure)
[notest] Pump_probe_solvent (no test procedure)
[notest] DBD_IBM_Si_analyzer_BC (no test procedure)
[notest] PBD_BT (no test procedure)
[notest] template_simple (no test procedure)
[OK]     Test_Filter_1 (accuracy, 1 %)
[OK]     Test_Filter_2 (accuracy, 1 %)
[??????] Test_Filter_3 (reference not found)
[notest] TestSAXS (no test procedure)
[FAILED] Test_Mono_4 (compilation/execution)
[FAILED] ESRF_ID11_5 (compilation/execution)
[notest] Pump_probe (no test procedure)
[??????] Test_source_lab_6 (reference not found)
[??????] Test_source_lab_7 (reference not found)
[notest] MAXII_711 (no test procedure)
[FAILED] Test_undulator_8 (compilation/execution)
[FAILED] Test_Sources_9 (compilation/execution)
[FAILED] Test_Saxs_spheres_10 (compilation/execution)
[notest] template_body_simple (no test procedure)
[FAILED] Test_capillary_11 (compilation/execution)
[notest] Be_BM_beamline (no test procedure)
[FAILED] JJ_SAXS_12 (compilation/execution)
[notest] Test_ML_elliptic (no test procedure)
[FAILED] Test_PowderN_13 (compilation/execution)
[FAILED] Template_Johann_spec_14 (compilation/execution)
[notest] Test_BM (no test procedure)
[FAILED] Test_MCPL_input_15 (compilation/execution)
[OK]     template_1Slit_Diff_16 (accuracy not checked)
[notest] Test_monitors (no test procedure)
[notest] ESRF_ID01 (no test procedure)
[notest] DBD_IBM_Si_analyzer (no test procedure)
[FAILED] Test_Mask_17 (compilation/execution)
[FAILED] NSLS2_CHX_18 (compilation/execution)
[notest] SAXS_saxlab (no test procedure)
[notest] template_header_simple (no test procedure)
[notest] MAXII_811 (no test procedure)
[notest] Test_Mirror_toroid (no test procedure)
[notest] XFEL_SPB (no test procedure)
[OK]     template_2Slit_Diff_19 (accuracy not checked)
[notest] Test_CRL (no test procedure)
[FAILED] Test_MCPL_output_20 (compilation/execution)
[notest] templateSasView (no test procedure)

# Execution check:    FAILED. 13 instrument(s) did not compile/execute.
# >> Check instruments and mcxtrace installation.
# End Date: Thu Jun 13 06:50:35 2019
</pre>

[selftest_4EB2.zip](https://github.com/McStasMcXtrace/McCode/files/3284943/selftest_4EB2.zip)
[testlog.txt](https://github.com/McStasMcXtrace/McCode/files/3284944/testlog.txt)

**Comment by willend** [comment]
Looks like most of the issues is down to PSD_monitor

**Comment by willend** [comment]
With earlier PSD_monitor.comp things look a lot better:

<pre>
Test Abstract for selftest_hp9W
[notest] MAXIV_FemtoMAX (no test procedure)
[notest] Pump_probe_solvent (no test procedure)
[notest] DBD_IBM_Si_analyzer_BC (no test procedure)
[notest] PBD_BT (no test procedure)
[notest] template_simple (no test procedure)
[OK]     Test_Filter_1 (accuracy, 1 %)
[OK]     Test_Filter_2 (accuracy, 2 %)
[??????] Test_Filter_3 (reference not found)
[notest] TestSAXS (no test procedure)
[FAILED] Test_Mono_4 (compilation/execution)
[FAILED] ESRF_ID11_5 (accuracy off by 59 %)
[notest] Pump_probe (no test procedure)
[??????] Test_source_lab_6 (reference not found)
[??????] Test_source_lab_7 (reference not found)
[notest] MAXII_711 (no test procedure)
[FAILED] Test_undulator_8 (compilation/execution)
[OK]     Test_Sources_9 (accuracy, 0 %)
[OK]     Test_Sources_10 (accuracy, 0 %)
[OK]     Test_Sources_11 (accuracy, 0 %)
[OK]     Test_Sources_12 (accuracy, 0 %)
[OK]     Test_Sources_13 (accuracy, 0 %)
[OK]     Test_Sources_14 (accuracy, 0 %)
[OK]     Test_Sources_15 (accuracy, 0 %)
[OK]     Test_Sources_16 (accuracy, 0 %)
[OK]     Test_Saxs_spheres_17 (accuracy, 2 %)
[notest] template_body_simple (no test procedure)
[OK]     Test_capillary_18 (accuracy, 3 %)
[notest] Be_BM_beamline (no test procedure)
[OK]     JJ_SAXS_19 (accuracy, 0 %)
[notest] Test_ML_elliptic (no test procedure)
[OK]     Test_PowderN_20 (accuracy, 3 %)
[FAILED] Template_Johann_spec_21 (compilation/execution)
[notest] Test_BM (no test procedure)
[FAILED] Test_MCPL_input_22 (compilation/execution)
[OK]     template_1Slit_Diff_23 (accuracy not checked)
[notest] Test_monitors (no test procedure)
[notest] ESRF_ID01 (no test procedure)
[notest] DBD_IBM_Si_analyzer (no test procedure)
[OK]     Test_Mask_24 (accuracy, 1 %)
[OK]     Test_Mask_25 (accuracy, 1 %)
[??????] NSLS2_CHX_26 (reference not found)
[notest] SAXS_saxlab (no test procedure)
[notest] template_header_simple (no test procedure)
[notest] MAXII_811 (no test procedure)
[notest] Test_Mirror_toroid (no test procedure)
[notest] XFEL_SPB (no test procedure)
[OK]     template_2Slit_Diff_27 (accuracy not checked)
[notest] Test_CRL (no test procedure)
[FAILED] Test_MCPL_output_28 (compilation/execution)
[notest] templateSasView (no test procedure)


# Execution check:    FAILED. 5 instrument(s) did not compile/execute.
# >> Check instruments and mcxtrace installation.
# End Date: Thu Jun 13 07:19:29 2019
</pre>

[selftest_hp9W.zip](https://github.com/McStasMcXtrace/McCode/files/3285075/selftest_hp9W.zip)
[testlog2.txt](https://github.com/McStasMcXtrace/McCode/files/3285077/testlog2.txt)

**Comment by ebknudsen** [comment]
PSD issue is fixed by  fe915fb - others remain

**Comment by willend** [comment]
Sound good @ebknudsen, I am currently building to run an updated test. Was thinking that a detailed issue pr. failing instr would maybe be good?

**Comment by willend** [comment]
Status can be seen below. Test_Filter_3 seemed to hang for some reason, was cancelled by a kill from another terminal.

Will create individual tickets tomorrow

<pre>
Test Abstract for selftest_r3he
[notest] MAXIV_FemtoMAX (no test procedure)
[notest] Pump_probe_solvent (no test procedure)
[notest] DBD_IBM_Si_analyzer_BC (no test procedure)
[notest] PBD_BT (no test procedure)
[notest] template_simple (no test procedure)
[OK]     Test_Filter_1 (accuracy, 2 %)
[OK]     Test_Filter_2 (accuracy, 1 %)
[FAILED] Test_Filter_3 (compilation/execution)
[notest] TestSAXS (no test procedure)
[FAILED] Test_Mono_4 (compilation/execution)
[FAILED] ESRF_ID11_5 (accuracy off by 59 %)
[notest] Pump_probe (no test procedure)
[??????] Test_source_lab_6 (reference not found)
[??????] Test_source_lab_7 (reference not found)
[notest] MAXII_711 (no test procedure)
[FAILED] Test_undulator_8 (compilation/execution)
[OK]     Test_Sources_9 (accuracy, 0 %)
[OK]     Test_Sources_10 (accuracy, 0 %)
[OK]     Test_Sources_11 (accuracy, 0 %)
[OK]     Test_Sources_12 (accuracy, 0 %)
[OK]     Test_Sources_13 (accuracy, 0 %)
[OK]     Test_Sources_14 (accuracy, 0 %)
[OK]     Test_Sources_15 (accuracy, 0 %)
[OK]     Test_Sources_16 (accuracy, 1 %)
[OK]     Test_Saxs_spheres_17 (accuracy, 1 %)
[notest] template_body_simple (no test procedure)
[OK]     Test_capillary_18 (accuracy, 4 %)
[notest] Be_BM_beamline (no test procedure)
[OK]     JJ_SAXS_19 (accuracy, 1 %)
[notest] Test_ML_elliptic (no test procedure)
[OK]     Test_PowderN_20 (accuracy, 5 %)
[FAILED] Template_Johann_spec_21 (compilation/execution)
[notest] Test_BM (no test procedure)
[FAILED] Test_MCPL_input_22 (compilation/execution)
[OK]     template_1Slit_Diff_23 (accuracy not checked)
[notest] Test_monitors (no test procedure)
[notest] ESRF_ID01 (no test procedure)
[notest] DBD_IBM_Si_analyzer (no test procedure)
[OK]     Test_Mask_24 (accuracy, 2 %)
[OK]     Test_Mask_25 (accuracy, 1 %)
[??????] NSLS2_CHX_26 (reference not found)
[notest] SAXS_saxlab (no test procedure)
[notest] template_header_simple (no test procedure)
[notest] MAXII_811 (no test procedure)
[OK]     Test_Mirror_toroid_27 (accuracy, 1 %)
[notest] XFEL_SPB (no test procedure)
[OK]     template_2Slit_Diff_28 (accuracy not checked)
[notest] Test_CRL (no test procedure)
[FAILED] Test_MCPL_output_29 (compilation/execution)
[notest] templateSasView (no test procedure)


# Execution check:    FAILED. 6 instrument(s) did not compile/execute.
# >> Check instruments and mcxtrace installation.
# End Date: Thu Jun 13 13:10:47 2019
</pre>

**Comment by ebknudsen** [comment]
Cool. Good idea to create issues for each thing

**Comment by willend** [comment]
Have rebuilt from master and rerun the test - things now fall in a few cathegories - will give each of them a separate issue:

Abstract:
<pre>
Test Abstract for selftest_xo2K
[notest] MAXIV_FemtoMAX (no test procedure)
[notest] Pump_probe_solvent (no test procedure)
[notest] DBD_IBM_Si_analyzer_BC (no test procedure)
[notest] PBD_BT (no test procedure)
[notest] template_simple (no test procedure)
[OK]     Test_Filter_1 (accuracy, 1 %)
[OK]     Test_Filter_2 (accuracy, 1 %)
[??????] Test_Filter_3 (reference not found)
[notest] TestSAXS (no test procedure)
[FAILED] Test_Mono_4 (compilation/execution)
[FAILED] ESRF_ID11_5 (accuracy off by 59 %)
[notest] Pump_probe (no test procedure)
[OK]     Test_source_lab_6 (accuracy, 1 %)
[OK]     Test_source_lab_7 (accuracy, 1 %)
[notest] MAXII_711 (no test procedure)
[FAILED] Test_undulator_8 (compilation/execution)
[OK]     Test_Sources_9 (accuracy, 0 %)
[OK]     Test_Sources_10 (accuracy, 0 %)
[OK]     Test_Sources_11 (accuracy, 0 %)
[OK]     Test_Sources_12 (accuracy, 0 %)
[OK]     Test_Sources_13 (accuracy, 0 %)
[OK]     Test_Sources_14 (accuracy, 0 %)
[OK]     Test_Sources_15 (accuracy, 0 %)
[OK]     Test_Sources_16 (accuracy, 0 %)
[OK]     Test_Saxs_spheres_17 (accuracy, 4 %)
[OK]     Test_capillary_18 (accuracy, 3 %)
[notest] Be_BM_beamline (no test procedure)
[OK]     JJ_SAXS_19 (accuracy, 0 %)
[notest] Test_ML_elliptic (no test procedure)
[OK]     Test_PowderN_20 (accuracy, 5 %)
[FAILED] Template_Johann_spec_21 (compilation/execution)
[notest] Test_BM (no test procedure)
[FAILED] Test_MCPL_input_22 (compilation/execution)
[OK]     template_1Slit_Diff_23 (accuracy not checked)
[notest] Test_monitors (no test procedure)
[notest] ESRF_ID01 (no test procedure)
[notest] DBD_IBM_Si_analyzer (no test procedure)
[OK]     Test_Mask_24 (accuracy, 1 %)
[OK]     Test_Mask_25 (accuracy, 1 %)
[OK]     NSLS2_CHX_26 (accuracy, 1 %)
[notest] SAXS_saxlab (no test procedure)
[notest] MAXII_811 (no test procedure)
[OK]     Test_Mirror_toroid_27 (accuracy, 1 %)
[notest] XFEL_SPB (no test procedure)
[OK]     template_2Slit_Diff_28 (accuracy not checked)
[notest] Test_CRL (no test procedure)
[FAILED] Test_MCPL_output_29 (compilation/execution)
[notest] templateSasView (no test procedure)


# Execution check:    FAILED. 5 instrument(s) did not compile/execute.
# >> Check instruments and mcxtrace installation.
# End Date: Thu Jun 13 14:29:47 2019
</pre>


Problems requring C99 mode:
<pre>
1) Instrument without test: MAXIV_FemtoMAX
Executing: mxrun.pl -c -n0 --no-cflags MAXIV_FemtoMAX
/usr/local/mcxtrace/1.5beta3/optics/Bragg_crystal.comp: In function 'Mx_DarwinReflectivityBC':
/usr/local/mcxtrace/1.5beta3/optics/Bragg_crystal.comp:240:5: error: 'for' loop initial declarations are only allowed in C99 mode
                 p*=R;
     ^
/usr/local/mcxtrace/1.5beta3/optics/Bragg_crystal.comp:240:5: note: use option -std=c99 or -std=gnu99 to compile your code
/usr/local/mcxtrace/1.5beta3/optics/Bragg_crystal.comp: In function 'Mx_LaueReflectivityBC':
/usr/local/mcxtrace/1.5beta3/optics/Bragg_crystal.comp:451:5: error: 'for' loop initial declarations are only allowed in C99 mode
** Error exit **
Instrument without test: DBD_IBM_Si_analyzer_BC
Executing: mxrun.pl -c -n0 --no-cflags DBD_IBM_Si_analyzer_BC
/usr/local/mcxtrace/1.5beta3/contrib/Bragg_crystal_bent_BC.comp: In function 'Mx_DarwinReflectivityBC':
/usr/local/mcxtrace/1.5beta3/contrib/Bragg_crystal_bent_BC.comp:245:5: error: 'for' loop initial declarations are only allowed in C99 mode
                          crystal_type,structure_factor_scale_r,structure_factor_scale_i);
     ^
/usr/local/mcxtrace/1.5beta3/contrib/Bragg_crystal_bent_BC.comp:245:5: note: use option -std=c99 or -std=gnu99 to compile your code
/usr/local/mcxtrace/1.5beta3/contrib/Bragg_crystal_bent_BC.comp: In function 'Mx_LaueReflectivityBC':
/usr/local/mcxtrace/1.5beta3/contrib/Bragg_crystal_bent_BC.comp:456:5: error: 'for' loop initial declarations are only allowed in C99 mode
** Error exit **

2) INSTRUMENT Test_Mono:
  Compares intensities of Monochromator components.

Executing: mxrun.pl Test_Mono -n 1e6 Mono=1 --format=PGPLOT -d Test_Mono_4
/usr/local/mcxtrace/1.5beta3/optics/Bragg_crystal.comp: In function 'Mx_DarwinReflectivityBC':
/usr/local/mcxtrace/1.5beta3/optics/Bragg_crystal.comp:240:5: error: 'for' loop initial declarations are only allowed in C99 mode
                 p*=R;
     ^
/usr/local/mcxtrace/1.5beta3/optics/Bragg_crystal.comp:240:5: note: use option -std=c99 or -std=gnu99 to compile your code
/usr/local/mcxtrace/1.5beta3/optics/Bragg_crystal.comp: In function 'Mx_LaueReflectivityBC':
/usr/local/mcxtrace/1.5beta3/optics/Bragg_crystal.comp:451:5: error: 'for' loop initial declarations are only allowed in C99 mode
** Error exit **
[FAILED] Test_Mono: (256): 

3) INSTRUMENT Template_Johann_spec:
  Template instrument  for a curved crystal Johann-spectrometer

Executing: mxrun.pl Template_Johann_spec L=2 dtheta_s=0 -n 1000000 --format=PGPLOT -d Template_Johann_spec_21
/usr/local/mcxtrace/1.5beta3/contrib/Bragg_crystal_bent_BC.comp: In function 'Mx_DarwinReflectivityBC':
/usr/local/mcxtrace/1.5beta3/contrib/Bragg_crystal_bent_BC.comp:245:5: error: 'for' loop initial declarations are only allowed in C99 mode
                          crystal_type,structure_factor_scale_r,structure_factor_scale_i);
     ^
/usr/local/mcxtrace/1.5beta3/contrib/Bragg_crystal_bent_BC.comp:245:5: note: use option -std=c99 or -std=gnu99 to compile your code
/usr/local/mcxtrace/1.5beta3/contrib/Bragg_crystal_bent_BC.comp: In function 'Mx_LaueReflectivityBC':
/usr/local/mcxtrace/1.5beta3/contrib/Bragg_crystal_bent_BC.comp:456:5: error: 'for' loop initial declarations are only allowed in C99 mode
** Error exit **
[FAILED] Template_Johann_spec: (256): 


4) Instrument without test: DBD_IBM_Si_analyzer
Executing: mxrun.pl -c -n0 --no-cflags DBD_IBM_Si_analyzer
Info:    'Bragg_crystal_bent_BC' is a contributed component.
Warning: Component Origin=Progress_bar(string profile) definition parameter
         may be changed into a setting parameter to avoid
         warnings at compile time.
Warning: Component DBD_tube=Source_lab(string material_datafile) definition parameter
         may be changed into a setting parameter to avoid
         warnings at compile time.
Warning: Component DBD_tube_tails=Source_lab(string material_datafile) definition parameter
         may be changed into a setting parameter to avoid
         warnings at compile time.
Warning: Component flat_source=Source_flat(string spectrum_file) definition parameter
         may be changed into a setting parameter to avoid
         warnings at compile time.
Warning: Component spectrum_mon=E_monitor(string filename) definition parameter
         may be changed into a setting parameter to avoid
         warnings at compile time.
CFLAGS=
/usr/local/mcxtrace/1.5beta3/contrib/Bragg_crystal_bent_BC.comp: In function 'Mx_DarwinReflectivityBC':
/usr/local/mcxtrace/1.5beta3/contrib/Bragg_crystal_bent_BC.comp:245:5: error: 'for' loop initial declarations are only allowed in C99 mode
                          crystal_type,structure_factor_scale_r,structure_factor_scale_i);
     ^
/usr/local/mcxtrace/1.5beta3/contrib/Bragg_crystal_bent_BC.comp:245:5: note: use option -std=c99 or -std=gnu99 to compile your code
/usr/local/mcxtrace/1.5beta3/contrib/Bragg_crystal_bent_BC.comp: In function 'Mx_LaueReflectivityBC':
/usr/local/mcxtrace/1.5beta3/contrib/Bragg_crystal_bent_BC.comp:456:5: error: 'for' loop initial declarations are only allowed in C99 mode
** Error exit **
</pre>



Missing components or other pieces:
<pre>
1) Instrument without test: PBD_BT
Executing: mxrun.pl -c -n0 --no-cflags PBD_BT
Cannot find file containing definition of component 'Source_lab_lorentzian'.
Check the McXtrace library installation or your MCXTRACE environment variable
or copy the component definition file locally.
Info:    'Bragg_crystal_BC' is a contributed component.
McXtrace: 1 Errors encountered during parse of PBD_BT.instr.
** Error exit **

2) Instrument without test: TestSAXS
Executing: mxrun.pl -c -n0 --no-cflags TestSAXS
Cannot find file containing definition of component 'SAXSNanodiscsWithTagsFast'.
Check the McXtrace library installation or your MCXTRACE environment variable
or copy the component definition file locally.
Cannot find file containing definition of component 'SAXSQMonitor'.
Check the McXtrace library installation or your MCXTRACE environment variable
or copy the component definition file locally.
McXtrace: 2 Errors encountered during parse of TestSAXS.instr.
** Error exit **

3) Instrument without test: templateSasView
Executing: mxrun.pl -c -n0 --no-cflags templateSasView


Fatal error: Cannot open include file 'sasview_proxy.c' on line 2191 of file '/usr/local/mcxtrace/1.5beta3/samples/SasView_model.comp'.


Program aborted.
** Error exit **

4) INSTRUMENT Test_undulator:
   Unit test instrument for the Undulator component

Executing: mxrun.pl Test_undulator.instr minh=1 maxh=2 FAST=1 -n 1000000 --format=PGPLOT -d Test_undulator_8
Warning: Component Origin=Progress_bar(string profile) definition parameter
         may be changed into a setting parameter to avoid
         warnings at compile time.
Warning: Component e_monitor=E_monitor(string filename) definition parameter
         may be changed into a setting parameter to avoid
         warnings at compile time.
Warning: Component e_monitor1=E_monitor(string filename) definition parameter
         may be changed into a setting parameter to avoid
         warnings at compile time.
CFLAGS= -lgsl -lgslcblas
/usr/local/mcxtrace/1.5beta3/sources/Undulator.comp:68:31: fatal error: gsl/gsl_sf_bessel.h: No such file or directory
 #include <gsl/gsl_sf_bessel.h>
                               ^
compilation terminated.
** Error exit **
[FAILED] Test_undulator: (256):


5) INSTRUMENT Test_MCPL_input:
  A test instrument for MCPL_input

Executing: mxrun.pl Test_MCPL_input -n1e3 dummy=0 --format=PGPLOT -d Test_MCPL_input_22
Warning: Component Origin=Progress_bar(string profile) definition parameter
         may be changed into a setting parameter to avoid
         warnings at compile time.
CFLAGS= -DMCPLPATH=@MCCODE_LIB@/MCPL/voutput.mcpl -I@MCCODE_LIB@/libs/mcpl -L@MCCODE_LIB@/libs/mcpl -lmcpl
/usr/local/mcxtrace/1.5beta3/misc/MCPL_input.comp:48:18: fatal error: mcpl.h: No such file or directory
 #include <mcpl.h>
                  ^
compilation terminated.
** Error exit **
[FAILED] Test_MCPL_input: (256): 

5b) INSTRUMENT Test_MCPL_output:
  A test instrument for MCPL_output

Executing: mxrun.pl Test_MCPL_output -n1e3 dummy=0 --format=PGPLOT -d Test_MCPL_output_29
Warning: Component Origin=Progress_bar(string profile) definition parameter
         may be changed into a setting parameter to avoid
         warnings at compile time.
Warning: Component sa=Source_flat(string spectrum_file) definition parameter
         may be changed into a setting parameter to avoid
         warnings at compile time.
CFLAGS= -I@MCCODE_LIB@/libs/mcpl -L@MCCODE_LIB@/libs/mcpl -lmcpl
/usr/local/mcxtrace/1.5beta3/misc/MCPL_output.comp:65:18: fatal error: mcpl.h: No such file or directory
 #include <mcpl.h>
                  ^
compilation terminated.
** Error exit **
[FAILED] Test_MCPL_output: (256): 

</pre>

Missing references:
<pre>
1) INSTRUMENT Test_Filter:
  Test instrument for checking the Filter.comp component 

Executing: mxrun.pl Test_Filter DL=4.9 L0=5 filter_mat=Si -n 1000000 --format=PGPLOT -d Test_Filter_1
[OK] Test_Filter: l_mon1_I = 1.31146e-07 +/- 3.31671e-10, equals 1.31502e-07
 within 1 %
Executing: mxrun.pl Test_Filter DL=4.9 L0=5 filter_mat=Rh -n 1000000 --format=PGPLOT -d Test_Filter_2
[OK] Test_Filter: l_mon1_I = 4.04814e-29 +/- 3.51414e-31, equals 4.04921e-29
 within 1 %
Executing: mxrun.pl Test_Filter -n5e6 DL=4.9 L0=5 filter_mat=Ti F2=1 --format=PGPLOT -d Test_Filter_3
[???] Test_Filter: lmon1 = 0 (may have failed, reference not found)
</pre>


Numerical inconsistency:
<pre>
1) INSTRUMENT ESRF_ID11:
  
Executing: mxrun.pl ESRF_ID11.instr ANGLE=0 -n 1000000 --format=PGPLOT -d ESRF_ID11_5
[FAILED] ESRF_ID11: psd_eh3_sample_I = 0.118636 +/- 0.000344436, should be 0.285899 
</pre>


Wrong input parameters:
<pre>
1) Instrument without test: ESRF_ID01
Executing: mxrun.pl -c -n0 --no-cflags ESRF_ID01

Unmatched actual parameter cut for component ZonePlate() at line ESRF_ID01.instr:249. Please change its name to a valid one:
  Definition parameters: 
  Setting parameters: radius xwidth yheight L lambda0 focus_x0 focus_y0 focus_xw focus_yh dist 
McXtrace: 1 Errors encountered during parse of ESRF_ID01.instr.
** Error exit **


2) Instrument without test: Test_CRL
Executing: mxrun.pl -c -n0 --no-cflags Test_CRL

Unmatched actual parameter T for component Lens_parab() at line Test_CRL.instr:75. Please change its name to a valid one:
  Definition parameters: material_datafile 
  Setting parameters: r r_ap yheight d N rough_z rough_xy 
Info:    'T' parameter name used in instrument matches
         component Lens_parab parameter 'material_datafile' from library but
         may be misspelled. Check component instance.
McXtrace: 1 Errors encountered during parse of Test_CRL.instr.
** Error exit **
</pre>

**Comment by willend** [comment]
Remaining failures are present in detailed form in the new tickets #807 #808 #809 #810 #811 . Closing this one

**Comment by willend** [comment]
Seems I never closed this one?
