### ISSUE TITLE
McXtrace MxGUI/Help/Manuals point to 'McStas' items

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#802]

**Comment by willend** [comment]
Works with 910f94b7, closing

**Comment by ebknudsen** [comment]
oops wrong number - above commit was closing 805

**Comment by willend** [comment]
but I guess we can close it anyway since a patch was introduced with 910f94b?

**Comment by ebknudsen** [comment]
sorry - me bad

**Comment by farhi** [comment]
Time to get  a coffee, Erik ?
