### ISSUE TITLE
McXtrace compilation issues 2: Missing comps or other code

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#808]
<pre>
1) Instrument without test: PBD_BT
Executing: mxrun.pl -c -n0 --no-cflags PBD_BT
Cannot find file containing definition of component 'Source_lab_lorentzian'.
Check the McXtrace library installation or your MCXTRACE environment variable
or copy the component definition file locally.
Info:    'Bragg_crystal_BC' is a contributed component.
McXtrace: 1 Errors encountered during parse of PBD_BT.instr.
** Error exit **

2) Instrument without test: TestSAXS
Executing: mxrun.pl -c -n0 --no-cflags TestSAXS
Cannot find file containing definition of component 'SAXSNanodiscsWithTagsFast'.
Check the McXtrace library installation or your MCXTRACE environment variable
or copy the component definition file locally.
Cannot find file containing definition of component 'SAXSQMonitor'.
Check the McXtrace library installation or your MCXTRACE environment variable
or copy the component definition file locally.
McXtrace: 2 Errors encountered during parse of TestSAXS.instr.
** Error exit **

3) Instrument without test: templateSasView
Executing: mxrun.pl -c -n0 --no-cflags templateSasView

Fatal error: Cannot open include file 'sasview_proxy.c' on line 2191 of file '/usr/local/mcxtrace/1.5beta3/samples/SasView_model.comp'.

Program aborted.
** Error exit **

4) INSTRUMENT Test_undulator:
   Unit test instrument for the Undulator component

Executing: mxrun.pl Test_undulator.instr minh=1 maxh=2 FAST=1 -n 1000000 --format=PGPLOT -d Test_undulator_8
Warning: Component Origin=Progress_bar(string profile) definition parameter
         may be changed into a setting parameter to avoid
         warnings at compile time.
Warning: Component e_monitor=E_monitor(string filename) definition parameter
         may be changed into a setting parameter to avoid
         warnings at compile time.
Warning: Component e_monitor1=E_monitor(string filename) definition parameter
         may be changed into a setting parameter to avoid
         warnings at compile time.
CFLAGS= -lgsl -lgslcblas
/usr/local/mcxtrace/1.5beta3/sources/Undulator.comp:68:31: fatal error: gsl/gsl_sf_bessel.h: No such file or directory
 #include 
                               ^
compilation terminated.
** Error exit **
[FAILED] Test_undulator: (256):

5) INSTRUMENT Test_MCPL_input:
  A test instrument for MCPL_input

Executing: mxrun.pl Test_MCPL_input -n1e3 dummy=0 --format=PGPLOT -d Test_MCPL_input_22
Warning: Component Origin=Progress_bar(string profile) definition parameter
         may be changed into a setting parameter to avoid
         warnings at compile time.
CFLAGS= -DMCPLPATH=@MCCODE_LIB@/MCPL/voutput.mcpl -I@MCCODE_LIB@/libs/mcpl -L@MCCODE_LIB@/libs/mcpl -lmcpl
/usr/local/mcxtrace/1.5beta3/misc/MCPL_input.comp:48:18: fatal error: mcpl.h: No such file or directory
 #include 
                  ^
compilation terminated.
** Error exit **
[FAILED] Test_MCPL_input: (256): 

5b) INSTRUMENT Test_MCPL_output:
  A test instrument for MCPL_output

Executing: mxrun.pl Test_MCPL_output -n1e3 dummy=0 --format=PGPLOT -d Test_MCPL_output_29
Warning: Component Origin=Progress_bar(string profile) definition parameter
         may be changed into a setting parameter to avoid
         warnings at compile time.
Warning: Component sa=Source_flat(string spectrum_file) definition parameter
         may be changed into a setting parameter to avoid
         warnings at compile time.
CFLAGS= -I@MCCODE_LIB@/libs/mcpl -L@MCCODE_LIB@/libs/mcpl -lmcpl
/usr/local/mcxtrace/1.5beta3/misc/MCPL_output.comp:65:18: fatal error: mcpl.h: No such file or directory
 #include 
                  ^
compilation terminated.
** Error exit **
[FAILED] Test_MCPL_output: (256): 

</pre>

**Comment by willend** [comment]
MCPL instr issue has to do with not packaging MCPL, 753b010d should fix these

**Comment by willend** [comment]
At a49ba321 the Test_MCPL_output compiles, but fails due to mismatch between example string and instr params. Test_MCPL_input fails  with 

<pre>
Test_MCPL_input.c:10818:22: error: 'mccvin_used_photons' undeclared (first use in this function)
 #define read_photons mccvin_read_photons
</pre>

**Comment by willend** [comment]
7c20790 fixes the MCPL oriented instruments

**Comment by willend** [comment]
Remaining:
<pre>
1) Instrument without test: PBD_BT
Executing: mxrun.pl -c -n0 --no-cflags PBD_BT
Cannot find file containing definition of component 'Source_lab_lorentzian'.
Check the McXtrace library installation or your MCXTRACE environment variable
or copy the component definition file locally.
Info:    'Bragg_crystal_BC' is a contributed component.
McXtrace: 1 Errors encountered during parse of PBD_BT.instr.
** Error exit **

2) Instrument without test: TestSAXS
Executing: mxrun.pl -c -n0 --no-cflags TestSAXS
Cannot find file containing definition of component 'SAXSNanodiscsWithTagsFast'.
Check the McXtrace library installation or your MCXTRACE environment variable
or copy the component definition file locally.
Cannot find file containing definition of component 'SAXSQMonitor'.
Check the McXtrace library installation or your MCXTRACE environment variable
or copy the component definition file locally.
McXtrace: 2 Errors encountered during parse of TestSAXS.instr.
** Error exit **

3) Instrument without test: templateSasView
Executing: mxrun.pl -c -n0 --no-cflags templateSasView


Fatal error: Cannot open include file 'sasview_proxy.c' on line 2191 of file '/usr/local/mcxtrace/1.5beta3/samples/SasView_model.comp'.


Program aborted.
** Error exit **

4) INSTRUMENT Test_undulator:
   Unit test instrument for the Undulator component

Executing: mxrun.pl Test_undulator.instr minh=1 maxh=2 FAST=1 -n 1000000 --format=PGPLOT -d Test_undulator_8
Warning: Component Origin=Progress_bar(string profile) definition parameter
         may be changed into a setting parameter to avoid
         warnings at compile time.
Warning: Component e_monitor=E_monitor(string filename) definition parameter
         may be changed into a setting parameter to avoid
         warnings at compile time.
Warning: Component e_monitor1=E_monitor(string filename) definition parameter
         may be changed into a setting parameter to avoid
         warnings at compile time.
CFLAGS= -lgsl -lgslcblas
/usr/local/mcxtrace/1.5beta3/sources/Undulator.comp:68:31: fatal error: gsl/gsl_sf_bessel.h: No such file or directory
 #include 
                               ^
compilation terminated.
** Error exit **
[FAILED] Test_undulator: (256):

</pre>

**Comment by willend** [comment]
templateSasView compiles with 176946b

**Comment by willend** [comment]
Test_undulator compiles with 7b8a284, but the numerical value is off - @ebknudsen your call I think

**Comment by willend** [comment]
Otherwise, what remains is:
<pre>
1) Instrument without test: PBD_BT
Executing: mxrun.pl -c -n0 --no-cflags PBD_BT
Cannot find file containing definition of component 'Source_lab_lorentzian'.
Check the McXtrace library installation or your MCXTRACE environment variable
or copy the component definition file locally.
Info:    'Bragg_crystal_BC' is a contributed component.
McXtrace: 1 Errors encountered during parse of PBD_BT.instr.
** Error exit **

2) Instrument without test: TestSAXS
Executing: mxrun.pl -c -n0 --no-cflags TestSAXS
Cannot find file containing definition of component 'SAXSNanodiscsWithTagsFast'.
Check the McXtrace library installation or your MCXTRACE environment variable
or copy the component definition file locally.
Cannot find file containing definition of component 'SAXSQMonitor'.
Check the McXtrace library installation or your MCXTRACE environment variable
or copy the component definition file locally.
McXtrace: 2 Errors encountered during parse of TestSAXS.instr.
** Error exit **
</pre>

**Comment by ebknudsen** [comment]
acknowledged - I'll take a look

**Comment by ebknudsen** [comment]
1st issue should be fixed by dc4bfbb9ff2fb285a31d5e0836db9fdf4bc9280e

**Comment by ebknudsen** [comment]
2nd issue is now fixed
