### ISSUE TITLE
McXtrace compilation issues 3: missing reference

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#809]
<pre>
1) INSTRUMENT Test_Filter:
  Test instrument for checking the Filter.comp component 

Executing: mxrun.pl Test_Filter DL=4.9 L0=5 filter_mat=Si -n 1000000 --format=PGPLOT -d Test_Filter_1
[OK] Test_Filter: l_mon1_I = 1.31146e-07 +/- 3.31671e-10, equals 1.31502e-07
 within 1 %
Executing: mxrun.pl Test_Filter DL=4.9 L0=5 filter_mat=Rh -n 1000000 --format=PGPLOT -d Test_Filter_2
[OK] Test_Filter: l_mon1_I = 4.04814e-29 +/- 3.51414e-31, equals 4.04921e-29
 within 1 %
Executing: mxrun.pl Test_Filter -n5e6 DL=4.9 L0=5 filter_mat=Ti F2=1 --format=PGPLOT -d Test_Filter_3
[???] Test_Filter: lmon1 = 0 (may have failed, reference not found)
</pre>

**Comment by ebknudsen** [comment]
fixed by 18023e8bcc04cc89c78b4f6cf5e6dfaa938a2a5
