### ISSUE TITLE
McXtrace compilation issues 4: Numerical inconsistency

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#810]
<pre>
1) INSTRUMENT ESRF_ID11:
  
Executing: mxrun.pl ESRF_ID11.instr ANGLE=0 -n 1000000 --format=PGPLOT -d ESRF_ID11_5
[FAILED] ESRF_ID11: psd_eh3_sample_I = 0.118636 +/- 0.000344436, should be 0.285899 
</pre>

**Comment by ebknudsen** [comment]
fixed by f54530f9fd0a9c20f6cd0409c4d03d36a02de0f0
