### ISSUE TITLE
McXtrace compilation issues 5: Parameter naming

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#811]
<pre>
1) Instrument without test: ESRF_ID01
Executing: mxrun.pl -c -n0 --no-cflags ESRF_ID01

Unmatched actual parameter cut for component ZonePlate() at line ESRF_ID01.instr:249. Please change its name to a valid one:
  Definition parameters: 
  Setting parameters: radius xwidth yheight L lambda0 focus_x0 focus_y0 focus_xw focus_yh dist 
McXtrace: 1 Errors encountered during parse of ESRF_ID01.instr.
** Error exit **

2) Instrument without test: Test_CRL
Executing: mxrun.pl -c -n0 --no-cflags Test_CRL

Unmatched actual parameter T for component Lens_parab() at line Test_CRL.instr:75. Please change its name to a valid one:
  Definition parameters: material_datafile 
  Setting parameters: r r_ap yheight d N rough_z rough_xy 
Info:    'T' parameter name used in instrument matches
         component Lens_parab parameter 'material_datafile' from library but
         may be misspelled. Check component instance.
McXtrace: 1 Errors encountered during parse of Test_CRL.instr.
** Error exit **
</pre>

**Comment by ebknudsen** [comment]
this has now been fixed. outstanding issue with accuracy of LENS=2 test on Test_CRL
