### ISSUE TITLE
Polarised components under polarised/ category?

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#828]
@ebknudsen the pol comps seem to be "all over", should we reorganise?

**Comment by ebknudsen** [comment]
I.e. a pol-category like optics, sources, polarization, etc.?

**Comment by willend** [comment]
Yup that was the idea

**Comment by willend** [comment]
I think the ones that caught my eye were the ones in misc, the rest look more or less OK I think
<pre>
./misc/PolAnalyser_ideal.comp
./misc/Set_pol.comp
./monitors/MeanPolLambda_monitor.comp
./monitors/PolLambda_monitor.comp
./monitors/Pol_monitor.comp
./obsolete/Pol_simpleBfield_stop.comp
./obsolete/Pol_simpleBfield.comp
./obsolete/Virtual_tripoli4_input.comp
./obsolete/Virtual_tripoli4_output.comp
./contrib/Pol_bender_tapering.comp
./contrib/Pol_triafield.comp
./contrib/Transmission_polarisatorABSnT.comp
./contrib/Pol_pi_2_rotator.comp
./optics/Pol_FieldBox.comp
./optics/Pol_Bfield.comp
./optics/Monochromator_pol.comp
./optics/Pol_guide_mirror.comp
./optics/Pol_constBfield.comp
./optics/Pol_SF_ideal.comp
./optics/Pol_Bfield_stop.comp
./optics/Pol_guide_vmirror.comp
./optics/Pol_bender.comp
./optics/Pol_mirror.comp
</pre>

**Comment by ebknudsen** [comment]
I suppose those should really go in the optics section  - they do have "real" counterparts  although they are idealized models.

**Comment by willend** [comment]
OK, done with https://github.com/McStasMcXtrace/McCode/commit/2140a04f111ddde4b46463a7b0ae8ece4d8ad6b8
