### ISSUE TITLE
MCPL_output SIGSEGV error if the instrument source file is not found

### ISSUE THREAD

**Issue by saroun** [McStasMcXtrace/McCode#836]
If an instrument simulation is executed without having the source file (*.instr) in the current directory, the simulation stops with an error during initialization of the MCPL_output component.
**Example**: Running an instrument executable BEER_MCPL_PWD like
`../../mcstas/BEER_MCPL_PWD`
ends with an error:
`# McStas 2.5 - Dec. 12, 2018: [pid 5090] Signal 11 detected SIGSEGV (Mem Error)`
`# Simulation: BEER_MCPL_PWD (BEER_MCPL_PWD.instr) `
`# Breakpoint: vout (Init) 0.00 % (       0.0/   10000.0)`
`# Date:      Wed Aug  7 17:40:51 2019`
`# Started:   Wed Aug  7 17:40:48 2019`
`# Last I/O Error: No such file or directory`
`# McStas 2.5 - Dec. 12, 2018: Simulation stop (abort).`
There is no error if BEER_MCPL_PWD.instr is present in the current directory.

The reason is obviously in the attempt of the component to add the instrument source in the MCPL file as a blob field. The error is raised because of the call to
`fclose(NULL)`
on line 117 of MCPL_output.comp. 
A simple repair seems to be moving of `fclose()` two lines up so that it is not executed if the *.instr file is not found. 

The error is not always reproduced. In my case, it does not show on Windows, but it does so if I compile on Linux with gcc  7.4.0.

**Comment by willend** [comment]
Thanks for repoting this @saroun, will have a look. 

In most "standard" McStas settings the snippets will be around, but we clearly shouldn't raise a segfault. Moving the fclose() up makes sense, maybe a comment string should also be added to the MCPL along the lines of "Original instrument file was not found and hence not embedded"

**Comment by willend** [comment]
This was implemented in https://github.com/McStasMcXtrace/McCode/commit/11fb077f08a660b93d98a600d78db3196b093831 in the meantime, if the instr is not found, the component will warn that
```
Warning (vout): Source instrument file (Test_MCPL_output.instr) not found, hence not embedded.
```
