### ISSUE TITLE
 the file extension of "The Virtual_mcnp_ss_input Component"

### ISSUE THREAD

**Issue by eddymaoui** [McStasMcXtrace/McCode#837]
hi
what is the file extension to put in The Virtual_mcnp_ss_input Component
thanks

**Comment by willend** [comment]
No explicit file extension is needed, use the file parameter of the component to specify whatever filename your source surface file uses? i.e.:

<pre>
file="/full/path/to/where/your/file.is"
</pre>

These days we actually rather suggest to use the ssw2mcpl tool distributed with McStas and the MCPL_input component instead. This has better support for different versions of MCNP and MCNPX.

**Comment by farhi** [comment]
Closed for inactivity, and mitigation solution (ssw2mcpl).
