### ISSUE TITLE
mc(x)run (Python) always writes Numpoints=2 in scan datafile header irrespective of scan length

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#842]
From Marc Seifert, MLZ:

> I am helping a colleague of mine with some McStas simulations and wanted to use a self-written evaluation tool from a time when I did McStas simulations. (I think I used McStas 2.0.)
> My program evaluates certain monitors for a whole scan. For this it used to open the mccode.dat in the parent directory, where all the sub-simulation folders with the single scan steps are stored. The idea is to quickly get the number of scan steps of the whole simulation by reading the value from the "Numpoints" parameter. However, we performed a 16-step simulation but in line 4 of mccode.dat it says:
> 
> \# Numpoints: 2
> 
> Is this expected behavior or did I misinterpret this parameter?
> 
>I attached the mccode.dat to this e-mail. The (simplified) command to start the simulation was as follows:
> 
> mcrun --mpi=36 ODIN-v35.instr -d </some/path> -n 1e10 -N 16 fo1_cut=0.7,1

I have tested and reproduce the finding, I get <pre> \# Numpoints: 2 </pre> irrespective of the number of scan points.

The legacy mc(x)run.pl implementation uses the scan length

**Comment by willend** [comment]
This is now fixed on main, but keeping it on as a known McStas 2.5 / McXtrace 1.4 issue

**Comment by farhi** [comment]
Supposed to be now fixed.
