### ISSUE TITLE
McStas on Fedora 30 - broken dependencies

### ISSUE THREAD

**Issue by amivaleo** [McStasMcXtrace/McCode#843]
Hi!

I suceeded in installing mcstas in my computer, in which I run Fedora 30.
After a few days I noticed that, when I give any update/upgrade command like

`sudo dnf upgrade`

or

`sudo dnf update`

I get this error:

```
package mcstas-suite-python-2.5-1.x86_64 requires mcstas-comps-2.5, but none of the providers can be installed
  - cannot install the best update candidate for package mcstas-suite-python-2.3-1.x86_64
  - nothing provides libgfortran.so.3()(64bit) needed by mcstas-comps-2.5-1.0-1.x86_64
  - nothing provides libgfortran.so.3(GFORTRAN_1.0)(64bit) needed by mcstas-comps-2.5-1.0-1.x86_64
  - nothing provides libgfortran.so.3(GFORTRAN_1.4)(64bit) needed by mcstas-comps-2.5-1.0-1.x86_64
```

I don't find such package `libgfortran.so.3`, so I don't see how to fix this.

Can you help me please?

**Comment by willend** [comment]
Hi there,

How did you install in the first place - did you add our RPM repo directly or proceed as described in https://github.com/McStasMcXtrace/McCode/blob/master/INSTALL-McStas/Linux/fedora/README.md ?

(The thing is: The RPM's in our main repo are CentOS-7 oriented, so installing these would lead to all kinds of dependency pain.)

Is there a gfortran on your system already - otherwise try installing that to see if this gives any mileage.

Best
Peter

**Comment by amivaleo** [comment]
Hi!

Actually I followed this: http://mcstas.org/download/install_linux/

To be more specific, this:
```
cd /etc/apt/sources.list.d
sudo wget http://packages.mccode.org/debian/mccode.list
sudo apt-get update
```

About gfortran:
```
$ sudo dnf install gfortran
...
Package gcc-gfortran-9.1.1-1.fc30.x86_64 is already installed
```
So yes, it's definitely installed.

**Comment by willend** [comment]
OK, thanks - not too visible I guess, but at the top of that page it says that the page is obsolete.

![Screenshot 2019-08-21 at 09 22 11](https://user-images.githubusercontent.com/8593355/63411147-37ad0300-c3f5-11e9-9cf1-c66e5e34f058.png)

(This is of course a problem, and I will make sure this is corrected as soon as possible)

So in fact what you should do instead is

1) Uninstall all of your mcstas- packages
2) Remove the mccode.list repo definition from /etc/apt/sources.list.d
3) dnf update / dnf upgrade

- And then proceed with the manual installation method outlined in https://github.com/McStasMcXtrace/McCode/blob/master/INSTALL-McStas/Linux/fedora/README.md

(I have myself downloaded a Fedora 30 iso to try how things work here)

**Comment by amivaleo** [comment]
> not too visible I guess, but at the top of that page it says that the page is obsolete

Oh, gosh... Yeah, definitely not really visible. 😅

Anyway, my apologies, I copied the wrong commands.

I did this:
```
cd /etc/yum.repos.d
sudo wget http://packages.mccode.org/rpm/mccode.repo
sudo yum update
```
following the instructions in the same page. The previous instructions are for debian-like system, which is not my case.


> And then proceed with the manual installation method outlined in [...]

There's a tiny typo here: 

`sudo yum install pgplot perl-PGPLOT perl-Tk Perl-PDL perl python2`

The package `Perl-PDL` should have a lower case letter as first letter: `perl-PDL`.

And: the link "all-rpms" can't be found, so I can't download anything from there.

**Comment by willend** [comment]
Ouch, another typo it seems, both corrected on https://github.com/McStasMcXtrace/McCode/blob/master/INSTALL-McStas/Linux/fedora/README.md - please have another go downloading?

(Sorry that things are as unpolished, but Fedora was a last-minute "let's see if it works" sort of thing along our "standard" platforms of Windows, Debian and CentOS... :-) Upside is that you filled a ticket and the product gets better as a result... )

**Comment by amivaleo** [comment]
No worries! I like to help... Well, my colleagues say I like whining and complaining. 😂

They're the two sides of the same coin.

There are other tiny things that do not allow to quickly copy&paste the shell instructions in the readme. But well... Too much complaining for now. :smile: 

I can install the first set of rpms, but not the second half:

```
rpm -i mcstas-clusterscripts-2.5-rpm64.rpm \
mcstas-comps-2.5-rpm64.rpm \
mcstas-manuals-2.5-rpm64.rpm \
mcstas-suite-perl-2.5-1.x86_64.rpm \
mcstas-tools-perl-2.5-rpm64.rpm \
mcstas-tools-perl-cmdline-2.5-rpm64.rpm
```
I get an error about a missing `libtk-codetext-perl` dependency that I don't know how to install.

I assume that the second half of rpms are some kind of "extras".

I got a launcher in my menu, but it fails to open anything.

If I use the terminal:

```
$ mcgui
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

```
(I use the wayland session of gnome.)

**Comment by willend** [comment]
Agreed, two sides of the same coin, and if everybody just "hacks around" the problems, the software will not get any better. :-)

libtk-codetext-perl is also included in your downloaded all-rpms.tgz it seems?
<pre>
tar tzf all-rpms.tgz 
NCrystal_example_mcstas.instr
README.TXT
libtk-codetext-perl-0.3.4-2.noarch.rpm     <-------
mcstas-2.5-rpm64.rpm
mcstas-clusterscripts-2.5-rpm64.rpm
mcstas-comps-2.5-rpm64.rpm
mcstas-manuals-2.5-rpm64.rpm
mcstas-miniconda3-2.5-rpm64.rpm
mcstas-ncrystal-2.5-rpm64.rpm
mcstas-suite-perl-2.5-1.x86_64.rpm
mcstas-suite-python-2.5-1.x86_64.rpm
mcstas-tools-matlab-mcplot-2.5-rpm64.rpm
mcstas-tools-perl-2.5-rpm64.rpm
mcstas-tools-perl-cmdline-2.5-rpm64.rpm
mcstas-tools-python-mccodelib-2.5-rpm64.rpm
mcstas-tools-python-mcdisplay-mantid-2.5-rpm64.rpm
mcstas-tools-python-mcdisplay-pyqtgraph-2.5-rpm64.rpm
mcstas-tools-python-mcdisplay-webgl-2.5-rpm64.rpm
mcstas-tools-python-mcdoc-2.5-rpm64.rpm
mcstas-tools-python-mcgui-2.5-rpm64.rpm
mcstas-tools-python-mcplot-matplotlib-2.5-rpm64.rpm
mcstas-tools-python-mcplot-pyqtgraph-2.5-rpm64.rpm
mcstas-tools-python-mcplot-svg-2.5-rpm64.rpm
mcstas-tools-python-mcrun-2.5-rpm64.rpm
</pre>

Have no experience with wayland thus far, will give my VM a spin... Does it help to do 
<pre>
export QT_QPA_PLATFORM=wayland
</pre>
in the terminal before running mcgui?

(The whole Python dependency setup is btw not gotten via the normal Fedora dependencies, but instead via the miniconda package you also downloaded - can easily be that it prefers a "normal" oldschool X11 over wayland...)

**Comment by amivaleo** [comment]
> libtk-codetext-perl is also included in your downloaded all-rpms.tgz it seems

Apologies, I'm dumb. Maybe it wasn't in the list of rpms that get installed by copy&paste from the readme? Dunno.

Anyway, I installed that now.

I followed the new readme: https://github.com/McStasMcXtrace/McCode/blob/master/INSTALL-McStas/Linux/fedora/README.md

Everything gets installed.

Now I have two mcstas launchers... One of the two does nothing, while the other opens mcstas.

I should restart my machine in order to better investigate what's happening, but I can't now. I'll come back to this thread later today or in the following days to give some update info.

Thank you a lot for you time, willend!

**Comment by willend** [comment]
Hi again @amivaleo,

Sounds good! As you can see in the list of changes on https://github.com/McStasMcXtrace/McCode/blob/master/INSTALL-McStas/Linux/fedora/README.md I have taken out a number of typos and mishaps.

To check what happens wrt. the launchers, could you try these two commands in a terminal and paste output here if any?
- The python based gui:
<pre>
mcgui
</pre>
- The perl based gui:
<pre>
mcgui.pl
</pre>

(I an guessing the latter one is the one that fails - have them both running here on my VM though...)

**Comment by willend** [comment]
FYI I myself get 
![Screenshot 2019-08-21 at 14 04 07](https://user-images.githubusercontent.com/8593355/63430333-a3569680-c41c-11e9-9bb5-4d4868919377.png)
and 
![Screenshot 2019-08-21 at 14 03 53](https://user-images.githubusercontent.com/8593355/63430354-af425880-c41c-11e9-92ee-a34956f8ed75.png)
respectively.

(One thing that could hinder the execution of the .pl version is if not both free and non-free from rpm fusion are enabled?)

**Comment by willend** [comment]
Hmm, the plot thickens... If I actually try doing anything with the .pl gui it coredumps it seems:

<pre>
Floating point exception (core dumped)
</pre>
Could *very* easily be a Wayland  vs. Xorg issue

**Comment by willend** [comment]
Yup, Wayland indeed. If I enable sshd on the Fedora 30 VM and log in with remote display from my Mac mcgui.pl runs just fine on my Fedora 30

![Screenshot 2019-08-21 at 14 12 16](https://user-images.githubusercontent.com/8593355/63430804-c7ff3e00-c41d-11e9-9dd0-0e622e44d4f5.png)

**Comment by amivaleo** [comment]
> check what happens wrt. the launchers python based gui

$ mcgui
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

/usr/local/bin/mcgui: riga 35: 15737 Annullato               (core dump creato) python3 ${LIB}/mcgui.py $*

$ mcgui.pl
-> it opens three windows named "Mcgui", "PGPLOT Server", "PGPLOT Window 1". The content of the last two is completely black. More or less what you get here: https://user-images.githubusercontent.com/8593355/63430354-af425880-c41c-11e9-92ee-a34956f8ed75.png

The Mcgui window actually looks like this: https://user-images.githubusercontent.com/8593355/63430804-c7ff3e00-c41d-11e9-9dd0-0e622e44d4f5.png

**Comment by ebknudsen** [comment]
outdated, closing, but please file another issue if problem persists with McStas 2.7
