### ISSUE TITLE
Crashing of mcgui.pl on Fedora 30 (Wayland)

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#846]
After installation on Fedora 30 using the updated guidelines at https://github.com/McStasMcXtrace/McCode/blob/master/INSTALL-McStas/Linux/fedora/README.md,  mcgui.pl launches successfully, but crashes on most menu interactions with

<pre>
Floating point exception (core dumped)
</pre>

Remote ssh -X login seems to remove the issue, so likely this is Wayland specific

(See also https://github.com/McStasMcXtrace/McCode/issues/843)

**Comment by ebknudsen** [comment]
outdated
