### ISSUE TITLE
Monitor_nD list mode, funny truncation at v > 10000 m/s

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#847]
@ebknudsen found (and I have reproduced) a bug with Monitor_nD list mode. Once neutrons are of high enough velocity or energy, they seem to not be recorded in list mode.

The attached instrument demonstrates this most dramatically with case 1: Lmin=0.001, Lmax=0.3 where no neutrons are recorded on the list mode monitor:

![case1](https://user-images.githubusercontent.com/8593355/63776298-66d5df80-c8e1-11e9-913a-460036cbccef.png)

[case1.zip](https://github.com/McStasMcXtrace/McCode/files/3546379/case1.zip)
[case1.pdf](https://github.com/McStasMcXtrace/McCode/files/3546381/case1.pdf)

In case2: Lmin=1, Lmax=5 all neutrons are recorded again:
![case2](https://user-images.githubusercontent.com/8593355/63776326-781eec00-c8e1-11e9-8929-6d1bbf78bdff.png)

[case2.zip](https://github.com/McStasMcXtrace/McCode/files/3546382/case2.zip)
[case2.pdf](https://github.com/McStasMcXtrace/McCode/files/3546384/case2.pdf)

[HighEnergy.instr.txt](https://github.com/McStasMcXtrace/McCode/files/3546355/HighEnergy.instr.txt)

Of course 0.001Å neutrons are really epithermal, but there should be no reason not to store them? :-) And 0.3Å are used at some instruments?

**Comment by willend** [comment]
Hmm, a grep for 10000 yields
<pre>
monitor_nd-lib.c:          { Set_Vars_Coord_Type = DEFS->COORD_V; strcpy(Set_Vars_Coord_Label,"Velocity [m/s]"); strcpy(Set_Vars_Coord_Var,"v"); lmin = 0; lmax = 10000; }
monitor_nd-lib.c:          { Set_Vars_Coord_Type = DEFS->COORD_VZ; strcpy(Set_Vars_Coord_Label,"vz [m/s]"); strcpy(Set_Vars_Coord_Var,"vz"); lmin = -10000; lmax = 10000; }
</pre>

**Comment by willend** [comment]
The effect is removed by editing of the above to e.g. 1000000 or explicitly setting a limit on the Monitor_nD in question:

<pre>
COMPONENT Mon_nD = Monitor_nD(options="previous list all neutrons v limits=[0 1000000]", filename="testnD",restore_neutron=1)
AT (0, 0, 0) RELATIVE PREVIOUS
</pre>

**Comment by willend** [comment]
I guess this needs documentation somehow?

**Comment by farhi** [comment]
This is in mcstas-comps/share/monitor_nd-lib.c at line 361:
```
if (!strcmp(token, "v"))
          { Set_Vars_Coord_Type = DEFS->COORD_V; strcpy(Set_Vars_Coord_Label,"Velocity [m/s]"); strcpy(Set_Vars_Coord_Var,"v"); lmin = 0; lmax = 10000; }
```
The value of 10k/s is probably to low...

**Comment by ebknudsen** [comment]
should we not also raise the limits on the vx, vy, and vz components?

**Comment by farhi** [comment]
Yes, you're probably right. There is a speed limit when you turn right or left, but not straight forward.

**Comment by farhi** [comment]
Well, in fact these limits where there to produce sensible plots in most cases. Increasing the limits will produce plots with all events stacked in a few bins, and empty elsewhere. This stands for most variables in fact. So, perhaps the 10km/s was not too bad in fact !

**Comment by ebknudsen** [comment]
Ah yes - but in non-list cases monitor_nd defaults to using auto limits does it not? In the list case (obviously) there are no bins anyway.

**Comment by farhi** [comment]
OK, but suppose you want to restrict the list to events in a given range ? Then limits make sense. Storing everything may be too much. The best is probably to indeed, as suggested by Peter, to simply add a comment in the doc.

**Comment by ebknudsen** [comment]
Good point. Don't get me wrong - I don't have strong feelings either way :-). I mostly trying to figure out what the code really does. 
As far as I can tell - you can circumvent the default limits if you explicitly set them, isn't that right?
as in ` options="list all vx vy vz limits -100 100"` where the limits apply to vz only.
So conclusion: I agree - we should simply document this default behaviour. That the least invasive change I think

**Comment by willend** [comment]
Agreed guys. (Slightly) updated limits would be OK, say the 0.1Å-100Å range - and then explicitly listing this in the main McDoc docs, with syntax to lift the limits.

@ebknudsen will you do this?

**Comment by ebknudsen** [comment]
Cool. I'll get on it presently.

**Comment by ebknudsen** [comment]
oh - btw. I was wrong: not specifying limits does not imply auto.

**Comment by ebknudsen** [comment]
481007e1abbfca9de99d3f621ebc8b522d2a677b should have fixed this - similar changes should be applied to the mcxtrace-docs

**Comment by ebknudsen** [comment]
a6ada63289896da67bd15f5a84331 does something about it for McXtrace as well

**Comment by ebknudsen** [comment]
I think this is now fixed - closing
