### ISSUE TITLE
cmake build manuals fails

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#849]
When trying to build the manuals for mcstas, I get an error with the following output:
<code>
CMAKE_SOURCE_DIR=        /home/erkn/Repositories/McCode/doc/manuals/mcstas
CMAKE_CURRENT_SOURCE_DIR=/home/erkn/Repositories/McCode/doc/manuals/mcstas
CMAKE_CURRENT_LIST_DIR=  /home/erkn/Repositories/McCode/doc/manuals/mcstas
PROJECT_SOURCE_DIR=      /home/erkn/Repositories/McCode/doc/manuals/mcstas
PROJECT_BINARY_DIR=      /home/erkn/Repositories/McCode/doc/manuals/mcstas
include MCUtil
include UseLATEX
setup MCCODE
-- Compiling for Linux
/usr/local
CPack configuration
LaTeX configuration
CMake Error at cmake/Modules/UseLATEX.cmake:734 (MESSAGE):
  You cannot set LATEX_OUTPUT_PATH to the same directory that contains LaTeX
  input files.
Call Stack (most recent call first):
  cmake/Modules/UseLATEX.cmake:1339 (LATEX_GET_OUTPUT_PATH)
  CMakeLists.txt:68 (add_latex_document)

CMake Error at cmake/Modules/UseLATEX.cmake:734 (MESSAGE):
  You cannot set LATEX_OUTPUT_PATH to the same directory that contains LaTeX
  input files.
Call Stack (most recent call first):
  cmake/Modules/UseLATEX.cmake:1339 (LATEX_GET_OUTPUT_PATH)
  CMakeLists.txt:76 (add_latex_document)

-- Configuring incomplete, errors occurred!
</code>
This is with cmake 3.13 on a debian buster system. It seems somehow that we must do out-of-source builds, but that we do not set that correctly

**Comment by ebknudsen** [comment]
after fiddling a bit with and resetting LATEX_OUTPUT_PATH to something else I get this:
<code>
Could not find input file /home/erkn/Repositories/McCode/doc/manuals/mcstas/FORCE_PDF
CMake Error at cmake/Modules/UseLATEX.cmake:1253 (ADD_CUSTOM_TARGET):
  ADD_CUSTOM_TARGET cannot create target "dvi" because another target with
  the same name already exists.  The existing target is a custom target
  created in source directory
  "/home/erkn/Repositories/McCode/doc/manuals/mcstas".  See documentation for
  policy CMP0002 for more details.
Call Stack (most recent call first):
  cmake/Modules/UseLATEX.cmake:1360 (ADD_LATEX_TARGETS_INTERNAL)
  CMakeLists.txt:74 (add_latex_document)


CMake Error at cmake/Modules/UseLATEX.cmake:1267 (ADD_CUSTOM_TARGET):
  ADD_CUSTOM_TARGET cannot create target "pdf" because another target with
  the same name already exists.  The existing target is a custom target
  created in source directory
  "/home/erkn/Repositories/McCode/doc/manuals/mcstas".  See documentation for
  policy CMP0002 for more details.
Call Stack (most recent call first):
  cmake/Modules/UseLATEX.cmake:1360 (ADD_LATEX_TARGETS_INTERNAL)
  CMakeLists.txt:74 (add_latex_document)


CMake Error at cmake/Modules/UseLATEX.cmake:1281 (ADD_CUSTOM_TARGET):
  ADD_CUSTOM_TARGET cannot create target "ps" because another target with the
  same name already exists.  The existing target is a custom target created
  in source directory "/home/erkn/Repositories/McCode/doc/manuals/mcstas".
  See documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  cmake/Modules/UseLATEX.cmake:1360 (ADD_LATEX_TARGETS_INTERNAL)
  CMakeLists.txt:74 (add_latex_document)


CMake Error at cmake/Modules/UseLATEX.cmake:1294 (ADD_CUSTOM_TARGET):
  ADD_CUSTOM_TARGET cannot create target "safepdf" because another target
  with the same name already exists.  The existing target is a custom target
  created in source directory
  "/home/erkn/Repositories/McCode/doc/manuals/mcstas".  See documentation for
  policy CMP0002 for more details.
Call Stack (most recent call first):
  cmake/Modules/UseLATEX.cmake:1360 (ADD_LATEX_TARGETS_INTERNAL)
  CMakeLists.txt:74 (add_latex_document)


CMake Error at cmake/Modules/UseLATEX.cmake:1315 (ADD_CUSTOM_TARGET):
  ADD_CUSTOM_TARGET cannot create target "html" because another target with
  the same name already exists.  The existing target is a custom target
  created in source directory
  "/home/erkn/Repositories/McCode/doc/manuals/mcstas".  See documentation for
  policy CMP0002 for more details.
Call Stack (most recent call first):
  cmake/Modules/UseLATEX.cmake:1360 (ADD_LATEX_TARGETS_INTERNAL)
  CMakeLists.txt:74 (add_latex_document)


CMake Error at cmake/Modules/UseLATEX.cmake:1325 (ADD_CUSTOM_TARGET):
  ADD_CUSTOM_TARGET cannot create target "auxclean" because another target
  with the same name already exists.  The existing target is a custom target
  created in source directory
  "/home/erkn/Repositories/McCode/doc/manuals/mcstas".  See documentation for
  policy CMP0002 for more details.
Call Stack (most recent call first):
  cmake/Modules/UseLATEX.cmake:1360 (ADD_LATEX_TARGETS_INTERNAL)
  CMakeLists.txt:74 (add_latex_document)


-- Configuring incomplete, errors occurred!
</code>

**Comment by ebknudsen** [comment]
I should mention that additionally there're a bunch of warnings about a policy change in re quoting variables.

**Comment by willend** [comment]
How does it look if you use the relevant mkdist entry from the build_whatever script? I believe the added syntax to do an out-of-source-dir build is found therein

**Comment by willend** [comment]
i.e. something like

./mkdist mcstas-manuals 2.6beta doc/manuals/mcstas/ "" noarch "o" -- NONE 

(the "o" means out-of-source-dir build, can't decipher at the moment exactly how this is forwarded to cmake)

**Comment by willend** [comment]
- Seems to relate to <pre>"${CP_SRC}" = "y"</pre> in prepare_cpack

**Comment by ebknudsen** [comment]
humm I did start out using the mkdist line which does not have the "-o" option set. I do remember that option some time ago.

**Comment by willend** [comment]
The "o" line is only in build_manuals_mcstas - all we do in the other scipts is package the resulting PDFs

**Comment by ebknudsen** [comment]
Ah yes- now I remember. Cool. Getting a bit further now
