### ISSUE TITLE
gsl-dependent instruments fail on macOS (e.g. MAXIV_Bloch.instr)

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#851]
Issue:

1) macOS has dropped header location in /usr/include
2) miniconda has hence dropped inclusion of gcc 
3) When using the system clang, the headers in $MCXTRACE/miniconda3/include are not picked up

Idea for solution: Add -I @MCCODE_LIB@/miniconda3/include in DEPENDENCY in either related comps or instruments

![Screenshot 2019-09-06 at 14 45 25](https://user-images.githubusercontent.com/8593355/64429680-d0f73d00-d0b6-11e9-9bd3-bed98b73112c.png)

**Comment by ebknudsen** [comment]
I've tested the suggested implementation and on debian it does not create any problems. Let's do it his way then.

**Comment by ebknudsen** [comment]
should be fixed by 487919a7a7ef1367402d6831f47ee3 and f5cf1e39f7a93ac0d349

**Comment by willend** [comment]
With https://github.com/McStasMcXtrace/McCode/commit/d2deabc5a647ad2468f5588d2ea89b262b4fb38e also, this now works.
