### ISSUE TITLE
m[xc]doc.pl search algorithm seems completely confused

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#855]
There appears to be  something rather seriously wrong with the search algorithm in mcdoc.pl and mxdoc.pl.
Using McStas 2.5 the call
```mcdoc -t E_monitor.comp```
gives the following result
<code>
/usr/share/mcstas/2.5/bin/mcdoc.pl: reading local mcstas configuration from /home/erkn/.mcstas/mccode_config.perl
Warning: Possible syntax error in specification of SETTING PARAMETER in component Brilliance_monitor: source_dist .
/usr/share/mcstas/2.5/bin/mcdoc.pl: /usr/share/mcstas/2.5/monitors/Brilliance_monitor.comp
######## Component: Brilliance_monitor #####################
[Author]:  Peter Willendrup, derived from TOF_lambda_monitor.comp
[Origin]:  DTU Physics
[Date]:    May 23, 2012
[Version]:(Unknown)

Special "Brilliance" monitor.
######## Input parameters: ##############################
<nlam=101>: [1] Number of bins in wavelength 

<nt=1001>: [1] Number of bins in TOF 

<srcarea=1>: [cm^2] Source area 
<lambda_0=0>: [AA] Minimum wavelength detected 

<lambda_1=20>: [AA] Maximum wavelength detected 

<restore_neutron=0>: [1] If set, the monitor does not influence the neutron state 

<Freq>: [Hz] Source frequency. Use freq=1 for reactor source 

<tofcuts=0>: [1] Flag to generate TOF-distributions as function of wavelength 

<toflambda=0>: [1] Flag to generate TOF-lambda distribution output 

<xwidth=0.01>: [m] width of monitor 

<yheight=0.01>: [m] height of monitor 

<source_dist=1>: [m] Distance from source. Beware when transporting through neutron optics! 

<t_0=0>: [us] Minimum time 

<t_1=20000>: [us] Maximum time 

<nowritefile=0>: [1] If set, monitor will skip writing to disk

######## Output parameters: #############################
<tt_0>: <Undocumented>
<tt_1>: <Undocumented>
<BRIL_N>: <Undocumented>
<BRIL_p>: <Undocumented>
<BRIL_p2>: <Undocumented>
<BRIL_mean>: <Undocumented>
<BRIL_meanN>: <Undocumented>
<BRIL_meanE>: <Undocumented>
<BRIL_peak>: <Undocumented>
<BRIL_peakN>: <Undocumented>
<BRIL_peakE>: <Undocumented>
<BRIL_shape>: <Undocumented>
<BRIL_shapeN>: <Undocumented>
<BRIL_shapeE>: <Undocumented>
<xmin>: <Undocumented>
<xmax>: <Undocumented>
<ymin>: <Undocumented>
<ymax>: <Undocumented>
<ster>: <Undocumented>
<prsec>: <Undocumented>
<dlam>: <Undocumented>
<dt>: <Undocumented>

######## Description: ###################################
If used in the right setting, will output "instantaneous" and "mean" brilliances in units of Neutrons/cm^2/ster/AA/s. Conditions for proper units:
<ul>
<li>Use a with a source of area 1x1cm
<li>The source must illuminate/focus to an area of 1x1cm a 1m distance
<li>Parametrise the Brilliance_monitor with the frequency of the source
<li>To not change the source TOF distribution, place the Brilliance monitor close to the source!
</ul>

with a source of area 1x1cm illuminating/focusing to an area of 1x1cm a 1m distance, this monitor will output "instantaneous" and "mean" brilliances in units of Neutrons/cm^2/ster/AA/s

Here is an example of the use of the component. Note how the mentioned Unit conditions are implemented in instrument code.

COMPONENT Source = ESS_moderator_long(
   l_low = lambdamin, l_high = lambdamax, dist = 1, xw = 0.01, yh = 0.01,
   freq = 14, T=50, tau=287e-6, tau1=0, tau2=20e-6,
   n=20, n2=5, d=0.00286, chi2=0.9, I0=6.9e11, I2=27.6e10,
   branch1=0, branch2=0.5, twopulses=0, size=0.01)
 AT (0, 0, 0) RELATIVE Origin

COMPONENT BRIL = Brilliance_monitor(nlam=196,nt=401,filename="bril.sim",
	t_0=0,t_1=4000,lambda_0=lambdamin,
	lambda_1=lambdamax, Freq=14)
AT (0,0,0.000001) RELATIVE Source

#########################################################
</code>
Which is the documentation for **Brilliance_monitor**

**Comment by ebknudsen** [comment]
correspondingly
```mxdoc.pl -t Monitor.comp```
yields the docs for **DivE_monitor.comp** _and_ **SAXSQ_Monitor.comp**.

In turn this issue propagates into the auto-generated docs which are included in the Component manual.

**Comment by willend** [comment]
The tree builds manuals OK now, as long as an updated mcdoc.pl/mxdoc.pl is in place on the system... :)

We ought to do something about this
