### ISSUE TITLE
MAXIV_DanMAX_pxrd2d gives weird output on Mac

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#857]
One of the McXtrace instruments has a numerical value completely off on Mac:
<pre>
Test Abstract for selftest_nnml
[FAILED] MAXIV_DanMAX_pxrd2d_12 (accuracy off by 467 %)

# Execution check:    OK.     Computing time: 199 [sec] for 37 tests.
# Accuracy check:     FAIR. 1 test(s) with inaccurate results.
# End Date: Wed Sep 11 15:43:27 2019
</pre>

I include a zip with the test output data:
[MAXIV_DanMAX_pxrd2d_12.zip](https://github.com/McStasMcXtrace/McCode/files/3601093/MAXIV_DanMAX_pxrd2d_12.zip)

**Comment by willend** [comment]
Corresponding zip from a Ubuntu
[MAXIV_DanMAX_pxrd2d.zip](https://github.com/McStasMcXtrace/McCode/files/3601113/MAXIV_DanMAX_pxrd2d.zip)

**Comment by willend** [comment]
Using clang on Ubuntu makes no difference, where as using
<pre>
export MCXTRACE_CC_OVERRIDE=/usr/bin/gcc
<pre>
on the Mac makes the test run trough... Reasonable workaraound? (/usr/bin/gcc is still clang but with some GNU-oriented switches/compatibility)

**Comment by willend** [comment]
Observations from to day: The idea that /usr/bin/gcc makes a difference was NOT right.

Replacing Beamstop by an if(!SCATTERED) ABSORB; on the powder makes the calculations go right?!?

Investigate intensities in the different algo branches?

Here is a modified instrument file that outputs MCPL data from 4 different classes of neutrons (from the line_info.type within PowderN) - incoherent, coherent, transmitted and nothing (? - those that didn't hit the sample maybe - ?)

[MAXIV_DanMAX_pxrd2d.instr.txt](https://github.com/McStasMcXtrace/McCode/files/3610237/MAXIV_DanMAX_pxrd2d.instr.txt)

And two datasets from Ubuntu 18.04 and Mojave respectively. Will dig myself during the weekend if time allows.

[Ubuntu.zip](https://github.com/McStasMcXtrace/McCode/files/3610242/Ubuntu.zip)
[Mojave.zip](https://github.com/McStasMcXtrace/McCode/files/3610244/Mojave.zip)

**Comment by ebknudsen** [comment]
I've inspected the datasets, and to 1st order the weights are identical in all 4 files.

**Comment by ebknudsen** [comment]
There was a problem in the beamstop - The sense of direction of travel was tested against uninitialized values
