### ISSUE TITLE
Implement dynamical array-declarations in TOF-relevant PSD's

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#859]
From an email-request from Matthias Gutmann, STFC, below. 

This can of course be done via malloc() as in Monitor_nD, perhaps we should make a small library with the needed infrastructure "monitor-lib"? - Would make it easier to do this for "all" monitors with user-level macros/functions to replace <pre>double Blah[nx];</pre> in every component one at a time...

> Dear Peter,
>  
> Greetings from ISIS! We are doing instrument simulations with McStas 2.5 and are trying
> to use the PSD_TOF_monitor component as follows:
>  
> COMPONENT PSD_TOFmon = PSD_TOF_monitor(
>     nt=nbins,
>     nx=10, ny=10,
>     filename="Peak.dat",
>     xwidth=0.03,
>     yheight=0.03,
>     tmin=tmin,
>     tmax=tmax)
>  
> tmin, tmax and nbins are calculated further up:
>  
> INITIALIZE
> %{
>   latticea = 2.5;
>   astar = 2. * PI/latticea;
>   lambda = 2. * latticea * sin(theta * PI/180.);
>   lambdamin = 0.95 * lambda;
>   lambdamax = 1.05 * lambda;
>   tmin = (lambdamin*8525)/3.95613;
>   tmax = (lambdamax*8525)/3.95613;
>   nbins = ceil(tmax-tmin);
>   emin = 81.799/lambdamax/lambdamax;
>   emax = 81.799/lambdamin/lambdamin;
>   //pixn = 150;
>   //monsize = 0.015;
> %}
>  
> However, this fails to compile. Can the component not take variables for its parameters? If not, can this please be enabled?
> Does it need to be done differently?

**Comment by willend** [comment]
I am thinking that perhaps we already made moves like this on the mcstas-3.0 branch @climbcat ?

**Comment by climbcat** [comment]
Hi Peter, if the parameters are definition parameters, the mcstas 2.5 PSD_TOF_monitor should just work. What is the exact error message?

Yes in mcstas 3 we do have 1D, 2D and 3D allocation functions - see https://github.com/McStasMcXtrace/McCode/blob/mcstas-3.0/common/lib/share/mccode-r.h (line 194) on the mcstas-3.0 branch.

**Comment by willend** [comment]
The thing with the dimensionality-parameters being definition parameters means that they can not be functions of input parameters, so indeed one would need calls like those from the 3.0 branch. (btw your pasted link gives a 404 - but I will manage, thanks :-) )

**Comment by climbcat** [comment]
Yes I see. We could send them the code from the branch for them to use? However the 3D arrays have not been tested yet.

**Comment by willend** [comment]
I will have a look and maybe put these calls in mccode-r.h/c on the master branch also, in prep for the next 2.x release

**Comment by climbcat** [comment]
I just need a working 2.x reference instrument to test the code and fix any bugs...

**Comment by willend** [comment]
Here is a couple of array-snippets that one could use e.g. via inclusion in a SHARE section of the monitor component(s):
[arrays.c.txt](https://github.com/McStasMcXtrace/McCode/files/3616317/arrays.c.txt)
[arrays.h.txt](https://github.com/McStasMcXtrace/McCode/files/3616318/arrays.h.txt)

@climbcat for a working "3D monitor" example, I think there may be an example in  ESS_Brilliance_2015.instr  and its use of Brilliance_monitor. (To really enable use of 3D, set tofcuts=1)

**Comment by climbcat** [comment]
Thanks! I think that instrument works (the plotter not so much).

![image](https://user-images.githubusercontent.com/11196009/65037595-4fbd6700-d94e-11e9-8bff-8c7825c6f53f.png)

**Comment by willend** [comment]
True :-) A slightly overwhelming number of plots indeed. (mcplot.pl sort of copes, but you still can't see a lot...)

Maybe a better test case is templateNMX_TOF.instr that uses PSD_monitor_TOF (which is also 3-dimensional, but ordered differently)

**Comment by climbcat** [comment]
Ok, yes "templateNMX_TOF.inst" seems to work fine as a test example. And no, the 3d monitor does not work, I get "Quit (core dumped)". Looking into this.

**Comment by climbcat** [comment]
A bug was fixed and the 3d monitor code from the mcstas-3.0 branch works.

An issue was uncovered: SPLIT does not work on cogen3 right now.

**Comment by willend** [comment]
Excellent! Let's put e.g. arrays.h and arrays.c in common/lib/share on main? And then we update the two 3D monitors on that branch to use that code?

**Comment by willend** [comment]
Solution now exists on master from 63e6ad49.

3 example comps: PSD_TOF_monitor.comp PSD_monitor_TOF.comp (both 3D) and PSD_monitor (2D)

Array code sits in common/lib/share
