### ISSUE TITLE
McXtrace Filter.comp: Aviod default: 1; in case statements

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#862]
Clang on macOS dislikes the default 1; in case statements like

<pre>
      switch (prms->shape){
        case CUBE:
....
          break;
        default:
          1;
</pre>

When testing this yields

<pre>
/Applications/McXtrace-1.5beta010.app/Contents/Resources/mcxtrace/1.5beta010/optics/Filter.comp:179:11: warning: expression result unused [-Wunused-value]
          1;
          ^
/Applications/McXtrace-1.5beta010.app/Contents/Resources/mcxtrace/1.5beta010/optics/Filter.comp:215:11: warning: expression result unused [-Wunused-value]
          1;
          ^
</pre>

**Comment by ebknudsen** [comment]
12a7e4bece068a2b282f372d0c46d856bd9bcca0 should have fixed this

**Comment by willend** [comment]
Looks like this one can be closed - and test btw looks nice on macOS now: (full log also included below)
<pre>
Test Abstract for selftest_upoh
[notest] MAXII_711 (no test procedure)
[notest] XFEL_SPB (no test procedure)
[notest] TestSAXS (no test procedure)
[OK]     Template_Johann_spec_1 (accuracy, 18 %)
[notest] PBD_BT (no test procedure)
[OK]     Test_CRL_2 (accuracy, 0 %)
[OK]     Test_CRL_3 (accuracy, 1 %)
[OK]     Test_CRL_4 (accuracy, 0 %)
[OK]     Test_Filter_5 (accuracy, 1 %)
[OK]     Test_Filter_6 (accuracy, 2 %)
[OK]     Test_Filter_7 (accuracy, 1 %)
[OK]     JJ_SAXS_8 (accuracy, 0 %)
[OK]     Test_ML_elliptic_9 (accuracy, 1 %)
[OK]     Test_ML_elliptic_10 (accuracy, 1 %)
[notest] templateSasView (no test procedure)
[OK]     Test_capillary_11 (accuracy, 4 %)
[OK]     MAXIV_DanMAX_pxrd2d_12 (accuracy, 2 %)
[notest] Pump_probe (no test procedure)
[OK]     Test_Saxs_spheres_13 (accuracy, 1 %)
[notest] DBD_IBM_Si_analyzer (no test procedure)
[OK]     ESRF_ID11_14 (accuracy, 1 %)
[OK]     Test_undulator_15 (accuracy, 21 %)
[OK]     Test_PowderN_16 (accuracy, fair 8 %)
[notest] MAXIV_FemtoMAX (no test procedure)
[OK]     template_2Slit_Diff_17 (accuracy not checked)
[notest] Test_BM (no test procedure)
[notest] template_simple (no test procedure)
[notest] Test_SX (no test procedure)
[notest] SAXS_saxlab (no test procedure)
[notest] Pump_probe_solvent (no test procedure)
[OK]     Test_Mono_18 (accuracy, 5 %)
[notest] Test_monitors (no test procedure)
[notest] MAXII_811 (no test procedure)
[OK]     Test_Sources_19 (accuracy, 0 %)
[OK]     Test_Sources_20 (accuracy, 0 %)
[OK]     Test_Sources_21 (accuracy, 0 %)
[OK]     Test_Sources_22 (accuracy, 0 %)
[OK]     Test_Sources_23 (accuracy, 0 %)
[OK]     Test_Sources_24 (accuracy, 0 %)
[OK]     Test_Sources_25 (accuracy, 0 %)
[OK]     Test_Sources_26 (accuracy, 0 %)
[OK]     Test_MCPL_output_27 (accuracy, 1 %)
[OK]     template_1Slit_Diff_28 (accuracy not checked)
[OK]     NSLS2_CHX_29 (accuracy, 1 %)
[OK]     Test_MCPL_input_30 (accuracy, 1 %)
[OK]     Test_Mask_31 (accuracy, 1 %)
[OK]     Test_Mask_32 (accuracy, 1 %)
[notest] MAXIV_Bloch (no test procedure)
[notest] DBD_IBM_Si_analyzer_BC (no test procedure)
[OK]     Test_source_lab_33 (accuracy, 1 %)
[OK]     Test_source_lab_34 (accuracy, 1 %)
[OK]     MAXIV_DanMAX_pxrd1d_35 (accuracy, 2 %)
[OK]     ESRF_ID01_36 (accuracy, 4 %)
[notest] Be_BM_beamline (no test procedure)
[OK]     Test_Mirror_toroid_37 (accuracy, 1 %)


# Execution check:    OK.     Computing time: 233 [sec] for 37 tests.
# Accuracy check:     OK.
# End Date: Mon Oct  7 15:46:54 2019
</pre>
[testlog_20191007.txt](https://github.com/McStasMcXtrace/McCode/files/3697696/testlog_20191007.txt)

**Comment by willend** [comment]
All that remains are some scattered
<pre>
-Wformat-extra-args
-Wimplicit-function-declaration
-Wint-conversion
-Wparentheses-equality
-Wpointer-bool-conversion
-Wreturn-type
</pre>
