### ISSUE TITLE
cogen3 instrument/component parameter name clashes

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McCode#869]
In cogen 2, the "mcip" prefix would ensure universality of the chosen names for component and instrument parameters, within the given scopes.

In cogen3, instrument parameters can be used directly in extend blocks. In component code, the macro INSTRUMENT_GETPAR should be used. However, this is not reflected properly in the defines around extend blocks and the init/trace/finally class functions, respectively.

Workaround for now: use different names for instrument/component parameters.

Fix 1: Enforce this restriction in the mcstas grammar. Enforce the use of the above macro.

Fix 2 (final): Reorganize defines appropriately, keeping the above restriction on parameter names enabled in the EXTEND block only. Keep enforcing the use of the INSTRUMENT_GETPAR macro in component code.

**Comment by farhi** [comment]
Hi @climbcat 
As far as I remember, I implemented a 2 stage approach for the variable resolution:

1. first resolve as a component variable.
2. if not found as a comp symbol, search as an instrument variable.

But perhaps I'm wrong, or this was changed to adapt to other constraints...

**Comment by climbcat** [comment]
Hi @farhi. When I changed the instance-specific trace functions to the current, class-specific ones, we had to re-implement EXTEND, which is now an if-else block switching on component name. Something may have happened in this process.

What happens now, as far as I can see, is that by the end of a component trace code, we undef all parameter shorthands. If there is a naming clash, the instrument shorthad will then also have been undeffed! E.g. 

<pre>
#define Lmin _instrument->_parameters->Lmin
...
#define Lmin _comp->_parameters->Lmin
(component trace code here)
#undef Lmin
</pre>

The last line deletes the instrument par def...

**Comment by climbcat** [comment]
This relates to #907 (now closing): 

"A typical example is "v", used both as a local component variable in the trace section, and as a uservar. The auto-generated macro #define v (_particle->v) will clash with any component trace local variable named v."

We should re-think all name clashes issues into one, and try and find a fix / new policy to handle many of these cases.

**Comment by willend** [comment]
Indeed. To me (and Erik who is sitting beside me) it looks like we have a "new variant" of what we used to have for the EXTEND blocks wrt. input parameters, i.e.

* in 2.5 one needs to use ```mcpippar`` for variable par
* in 3.0 one needs to use ```instrument->_parameters._par``` instead...

My suggestion would be that we simply make a define that makes par available in the EXTEND block and "live with the fact" that there could potentially be a variable name clash. The thing is: it _is_ already pretty stupid to use the same name everywhere... :-)

**Comment by willend** [comment]
Hmm then again no, if people have lambda as input par that clashes with a component lambda... 

Maybe my point is only that ```instrument->_parameters._dummy``` feels a little too long :-) 

Another more explicit shorthand would perhaps help? ```instrpars_dummy``` ?

**Comment by willend** [comment]
Input from @ebknudsen is "how about a macro ala getpar"... Lets park it here and discuss next week :-)

**Comment by willend** [comment]
DOH! cogen3 already has

```#define INSTRUMENT_GETPAR(par)```

:-) Problem solved - more or less ?

**Comment by willend** [comment]
For full logic MC_GETPAR should perhaps be known as COMPONENT_GETPAR??

**Comment by climbcat** [comment]
Ok, we have eliminated one name clash: the TRACE / EXTEND / USERVARs one. Indeed I shall create a new macro called COMPONENT_GETPAR!

**Comment by climbcat** [comment]
| what | where | C scope |
| --- | --- | --- |
| instrument parameter | instrument file DEFINE | insrument <code>init</code> and <code>finally</code> functions |
| instrument variable | instrument file DECLARE | global |
| ccc | ccc | ccc |
| ccc | ccc | ccc |
| ccc | ccc | ccc |
| ccc | ccc | ccc |
| ccc | ccc | ccc |
| ccc | ccc | ccc |

**Comment by climbcat** [comment]
The table above could extended with an "example" column, and perhaps extended. However, a minor developer cheat sheet would ideally be short. Other elements to add to such a short-form documentation is a list of macros.

It has been entered into a wiki page at https://github.com/McStasMcXtrace/McCode/wiki/Variables-and-Scopes
