### ISSUE TITLE
Current mcstas-3.0 EXTEND mechanism will not work on GPU

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#870]
The current mcstas-3.0 implementation of EXTEND will generate code like this:
<pre>
if (!strcmp(_comp->_name, "Source")) {
     //Then do something...
}
</pre>
- which will never run on GPU due to the use of strcmp... We will have to find another way :-)

**Comment by willend** [comment]
I guess a reasonable way would be to evaluate on the component index instead?

**Comment by climbcat** [comment]
Ok, why no strcmp on gpu?? Anyway yes we could just use the index, using the macro INDEX_CURRENT_COMP.
