### ISSUE TITLE
Daily mcstas-3.0 (GPU+CPU) test results on the web?

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#873]
e.g. Cron-driven test with 
* Graphical / html output for
  * All instruments (a subset only will work on GPU)
  * N different configurations of target arch, compiler & RNG 
    0. McStas-2.x, mt
    1. CPU: gcc, mt
    2. CPU: gcc, KISS
    3. CPU: pgcc, KISS -ta:multicore,...
    4. GPU: pgcc, KISS -ta:tesla,...
    5. MPI-CPU: gcc with KISS
    * + whatever we may come up with later...

This would go in a folder structure like this
<pre>
date/label/instr/run
</pre>

![IMG_9321 2](https://user-images.githubusercontent.com/8593355/67769151-38e15880-fa54-11e9-8019-80dcfaf5ad39.JPG)

**Comment by willend** [comment]
Another thing that comes to mind: 
* We should keep logs of how the static numbers of "value" and compile / runtime evolve over time pr. instrument/test number

(I have an old Gnuplot hack somewhere to generate plots from that kind of information...)

**Comment by climbcat** [comment]
Folder structure under testroot:

date/label/instr/run_idx

**Comment by climbcat** [comment]
mctest has been reworked to work with the above diagram, the task of writing the html remains...

Output of mctest --help (note that the --configs mode is exclusive to the positional version argument):

<pre>
mctest-dev --help
usage: mctest.py [-h] [--configs] [--mccoderoot [MCCODEROOT]]
                 [--testroot [TESTROOT]] [--limit LIMIT] [--versions]
                 [--verbose]
                 [testversion]

positional arguments:
  testversion           mccode version to test

optional arguments:
  -h, --help            show this help message and exit
  --configs             test config files under mccodelib/MCCODE
  --mccoderoot [MCCODEROOT]
                        manually select root search folder for mccode
                        installations
  --testroot [TESTROOT]
                        output test results under this root folder
  --limit LIMIT         test only the first [LIMIT] instrs in every version
  --versions            display local versions info
  --verbose             output a test/notest instrument status header before
                        each test
</pre>

**Comment by climbcat** [comment]
A few questions: 

- How do we robustly identify compile errors?
- Identify runtime errors?
- When presenting instruments/tests on the overview page, how do we handle instruments that were not present in the selected reference (first column)? E.g. a new instrument or %Example was added, etc.
- The --configs or label test script requires writing permissions in the dist directory, "mccoderoot". So I guess we should run the test using sudo priv., change permissions post-install, or use a local mccoderoot folder when installing.

**Comment by climbcat** [comment]
Answers:

- Extra table with "no reference"
- Look for binary file existence to detect compile errors
- Look for retcode plus "error" in stdout/stderr to detect runtime errors

**Comment by willend** [comment]
Main features now implemented in solution at http://new-nightly.mccode.org/ and DTU hcp resources. Will define new ticket for visualising the simulation outputs
