### ISSUE TITLE
mcstas-3.0 weirdness with PGCC above 2e9 events

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#875]
When running on GPU or multicore via pgcc, something happens to both runtime and statistics in the range of 3-4e9 rays, likely due to an unsigned long / unsigned long long issue.

Behaviour is that
1) Below the said range, simulated values and statistics look normal, in the sense that  a 10x run gives same intensity and 10x stats

2) with 3e9 or 4e9 as ncount, simulations have been seen to either finish instantly with 0 as result (mini.instr) or to apparently hang e.g. be in infinite loop

3) at 5e9 results come back again with broken intensity values and reduced(!) statistics wrt. data from runs with lower ncount

Will put output data as comments below.

**Comment by willend** [comment]
Unfortunately, hypatia crashed on me during the process of gathering data. Now debugging on a non-GPU machine with -ta:multicore

**Comment by willend** [comment]
From multicore runs:
<pre>
pkwi@elearn1:~/Issue_875$ pgcc -ta=multicore -Minfo=accel -DUSE_PGI -DNOSIGNALS -DRNG_ALG=2 mini.c 
PGC-W-0221-Redefinition of symbol MC_RAND_MAX (mini.c: 481)
raytrace_all:
   6398, Generating Multicore code
       6399, #pragma acc loop gang
PGC/x86-64 Linux 19.4-0: compilation completed with warnings
pkwi@elearn1:~/Issue_875$ ./a.out -n1e9
Instrument parameters for Minimal (mini.instr)
^C
pkwi@elearn1:~/Issue_875$ time ./a.out -n1e8
Instrument parameters for Minimal (mini.instr)
Detector: detector_I=343.821 detector_ERR=0.069285 detector_N=2.46254e+07 "PSD.dat"

real	0m14.117s
user	7m19.175s
sys	0m0.368s
pkwi@elearn1:~/Issue_875$ time ./a.out -n1e9
Instrument parameters for Minimal (mini.instr)
Detector: detector_I=343.856 detector_ERR=0.021911 detector_N=2.46279e+08 "PSD.dat"

real	2m13.309s
user	69m41.867s
sys	0m0.373s
pkwi@elearn1:~/Issue_875$ time ./a.out -n3e9
Instrument parameters for Minimal (mini.instr)
Detector: detector_I=0 detector_ERR=0 detector_N=0 "PSD.dat"

real	0m0.062s
user	0m0.268s
sys	0m0.031s
pkwi@elearn1:~/Issue_875$ time ./a.out -n4e9
Instrument parameters for Minimal (mini.instr)
Detector: detector_I=0 detector_ERR=0 detector_N=0 "PSD.dat"

real	0m0.093s
user	0m0.530s
sys	0m0.032s
pkwi@elearn1:~/Issue_875$ time ./a.out -n5e9
Instrument parameters for Minimal (mini.instr)
Detector: detector_I=48.4891 detector_ERR=0.00367967 detector_N=1.73646e+08 "PSD.dat"

real	1m37.547s
user	50m9.534s
sys	0m0.376s
</pre>

**Comment by ebknudsen** [comment]
solution found
