### ISSUE TITLE
Much output from Test_Pol_Mirror.instr on mcstas-3.0 branch

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McCode#881]
[Test_Pol_Mirror_stdouterr.txt](https://github.com/McStasMcXtrace/McCode/files/3836937/Test_Pol_Mirror_stdouterr.txt)

**Comment by climbcat** [comment]
Erik do you know anything about this?

**Comment by ebknudsen** [comment]
This is likely related to #822 and the switch to SETTING PARAMETERS vector  for the reflectivity parameters. The fact that that the polarization vector is nowhere near <1 and fluctuates wildly suggests to me that the reflectivity parameters are random.
Will investigate further
