### ISSUE TITLE
Avoid use of exit(0) in error-cases

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#884]
It seems the McWeb simrunner crashes in case of exit(0) e.g. in dLambda >=Lambda in Source_Maxwell_3

**Comment by willend** [comment]
Relevant McStas comps:
<pre>
./monitors/PSD_monitor_TOF.comp:      exit(0);
./monitors/PSD_monitor_TOF.comp:      exit(0);
./monitors/DivLambda_monitor.comp:      exit(0);
./monitors/L_monitor.comp:      exit(0);
./monitors/PSD_monitor_psf.comp:      exit(0);
./monitors/PSDlin_diff_monitor.comp:      exit(0);
./monitors/PSD_monitor.comp:    exit(0);
./monitors/Divergence_monitor.comp:      exit(0);
./monitors/Hdiv_monitor.comp:      exit(0);
./monitors/PSD_monitor_psf_eff.comp:      exit(0);
./monitors/E_monitor.comp:      exit(0);
./monitors/EPSD_monitor.comp:      exit(0);
./monitors/PSDlin_monitor.comp:      exit(0);
./monitors/TOF2E_monitor.comp:      exit(0);
./monitors/DivPos_monitor.comp:      exit(0);
./monitors/Monitor.comp:      exit(0);
./monitors/TOF_monitor.comp:      exit(0);
./monitors/TOFLambda_monitor.comp:      exit(0);
./monitors/PSD_TOF_monitor.comp:    exit(0);
./monitors/PSD_TOF_monitor.comp:    exit(0);
./monitors/TOFlog_monitor.comp:      exit(0);
./obsolete/Isotropic_Sqw_legacy.comp:            exit(0);
./obsolete/ESS_moderator_long.comp:      exit(0);
./contrib/SNS_source.comp:   exit(0);
./contrib/Radial_div.comp:      exit(0);
./contrib/Single_crystal_inelastic.comp:    exit(0);
./contrib/SANSCurve.comp:            exit(0);
./contrib/union/Single_crystal_process.comp:    exit(0);
./contrib/PSD_Detector.comp:    exit(0);
./contrib/PSD_Detector.comp:    exit(0);
./contrib/PSD_Detector.comp:    exit(0);
./contrib/PSD_Detector.comp:    exit(0);
./contrib/PSD_Detector.comp:    exit(0);
./contrib/PSD_Detector.comp:    exit(0);
./contrib/PSD_Detector.comp:    exit(0);
./contrib/PSD_Detector.comp:    exit(0);
./contrib/PSD_Detector.comp:    exit(0);
./contrib/PSD_Detector.comp:      exit(0); }
./contrib/PSD_Detector.comp:        exit(0); }
./contrib/PSD_Detector.comp:        exit(0); }
./contrib/PSD_Detector.comp:      exit(0);
./contrib/PSD_Detector.comp:            exit(0);
./samples/Single_crystal_hack.comp:    exit(0);
./samples/Single_crystal.comp:    exit(0);
./sources/Source_Maxwell_3.comp:      exit(0);
./sources/Source_simple.comp:    exit(0);
./sources/Source_simple.comp:    exit(0);
./sources/Source_simple.comp:    exit(0);
./sources/Source_simple.comp:      exit(0);
./sources/ESS_moderator.comp:      exit(0);
./sources/Moderator.comp:      exit(0);
./sources/Source_div.comp:      exit(0);
./sources/Source_div.comp:    exit(0);
./sources/Source_div.comp:      exit(0);
./sources/Source_adapt.comp:      exit(0);
./optics/Collimator_linear.comp:    exit(0);
</pre>
Relevant McXtrace comps:
<pre>
./misc/Focus.comp:    exit(0);
./monitors/L_monitor.comp:      exit(0);
./monitors/Phi_monitor.comp:      exit(0);
./monitors/PSD_monitor.comp:      exit(0);
./monitors/Divergence_monitor.comp:      exit(0);
./monitors/PSD_monitor_coh.comp:      exit(0);
./monitors/DivE_monitor.comp:      exit(0);
./monitors/E_monitor.comp:      exit(0);
./monitors/EPSD_monitor.comp:      exit(0);
./monitors/EPSD_monitor.comp:      exit(0);
./monitors/DivPos_monitor.comp:      exit(0);
./monitors/Monitor.comp:      exit(0);
./monitors/W_psd_monitor.comp:      exit(0);
./monitors/TOF_monitor.comp:      exit(0);
./contrib/Detector_pn.comp:    exit(0);
./contrib/Detector_pn.comp:      exit(0);
./contrib/SAXSCurve.comp:            exit(0);
./samples/Single_crystal.comp:    exit(0);
./samples/Absorption_sample.comp:    exit(0);
./sources/Source_flat.comp:    exit(0);
./sources/Source_flat.comp:    exit(0);
./sources/Source_flat.comp:    exit(0);  
./sources/Source_pt.comp:    exit(0);
./sources/Source_div.comp:    exit(0);  
</pre>

**Comment by ebknudsen** [comment]
42b2cb92845cb645462ad6 fixes the McXtrace part of this, although it is labelled as fixing #844. This was a mistake
