### ISSUE TITLE
test output status for 3.0-dev / CPU

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McCode#886]
Aside from a few (fixable) compile errors, the prevailing point of failure seems to be "targetval for monitor name XXXX could not be extracted". We should look into the causes for these. A few times, I have noticed that the component name and the monitor output filename are not the same, and fixed that somewhat, but there might be more along the same lines.

Nearly all instruments should compile. At one point, they all did, and I moved the non-compiling ones to "parked" after evaluating whether they were worth fixing ta the time. What remains thus consists of new errors that have arisen as side effects, or consist of non-functional instruments (e.g. *_gpu.instr). 

<pre>
jaga@HP-EliteBook-840-G4:/tmp$ mctest-dev 3.0-dev
ncount is: 1e6
Testing: 3.0-dev

Finding instruments in: /usr/share/mcstas/3.0-dev
Copying instruments to: /tmp/mctest/20191120_1239_36/3.0-dev

Compiling instruments [seconds]...
BNL_H8                              :   2.80
BNL_H8_simple                       :   2.74
Demo_shape_primitives               :   1.86
ESS_2001_bispectral                 :   2.87
ESS_2015_test                       :   2.16
ESS_Brilliance_2001                 :   3.55
ESS_Brilliance_2013                 :   3.56
ESS_Brilliance_2014                 :   3.65
ESS_Brilliance_2015                 :   3.65
ESS_Brilliance_TDR                  :   3.56
ESS_IN5_reprate                     :   3.91
ESS_butterfly_Guide_curved_test     :   4.78
ESS_butterfly_MCPL_test             :   4.76
ESS_butterfly_test                  :   3.86
ESS_butterfly_tfocus_NOFOCUS_test   :   4.03
ESS_butterfly_tfocus_test           :   3.95
ESS_mcpl2hist                       :   2.80
FZJ_BenchmarkSfin2                  :   4.76
FZJ_KWS2_Lens                       :   2.20
FZJ_SANS_KWS2_AnySample             :   2.41
Gallmeier_SNS_decoupled_poisoned    :   1.53
Granroth_SNS_decoupled_poisoned     :   1.49
HZB_FLEX                            :   3.97
HZB_NEAT                            :   5.94
Histogrammer                        :   3.64
ILL_D2B                             :   5.03
ILL_D4                              :   4.61
ILL_H10_IN8                         :   4.95
ILL_H113                            :   7.28
ILL_H13_IN20                        :   5.02
ILL_H142                            :   8.18
ILL_H142_IN12                       :  10.45
ILL_H143_LADI                       :   7.21
ILL_H15                             :   6.20
ILL_H15_IN6                         :   8.91
ILL_H16                             :   4.41
ILL_H16_IN5                         :   7.53
ILL_H16_IN5_Mantid                  :   7.56
ILL_H16_Mantid                      :   4.46
ILL_H22                             :   7.32
ILL_H22_D1A                         :   8.68
ILL_H22_D1B                         :   9.23
ILL_H22_VIVALDI                     :   8.75
ILL_H24                             :   6.32
ILL_H25                             :   6.71
ILL_H25_IN22                        :   8.95
ILL_H5                              :  23.06
ILL_H512_D22                        :   7.17
ILL_H53                             :   6.12
ILL_H53_D16                         :   8.05
ILL_H8_IN1                          :   4.97
ILL_IN13                            :   4.38
ILL_IN4                             :   7.09
ILL_IN5                             :   6.06
ILL_IN5_Mantid                      :   7.62
ILL_IN6                             :   6.98
ILL_Lagrange                        :   6.59
ISIS_CRISP                          :   3.40
ISIS_GEM                            :   4.16
ISIS_HET                            :   4.55
ISIS_MERLIN                         :   4.05
ISIS_OSIRIS                         :   6.73
ISIS_Prisma2                        :   4.69
ISIS_SANS2d                         :   3.64
ISIS_SANS2d_Mantid                  :   5.73
ISIS_TS1_Brilliance                 :   1.93
ISIS_TS2_Brilliance                 :   1.97
ISIS_test                           :   3.74
LLB_6T2                             :   4.24
MCPL2hist                           :   3.29
Mezei_SNS_decoupled_poisoned        :   1.67
PSI_DMC                             :   4.79
PSI_DMC_simple                      :   4.57
PSI_Focus                           :   5.67
PSI_source                          :   1.31
RITA-II                             : COMPILE ERROR using:
mcrun --info /tmp/mctest/20191120_1239_36/3.0-dev/RITA-II/RITA-II.instr
RTP_DIF                             :   4.38
RTP_Laue                            :   4.01
RTP_NeutronRadiography              :   3.86
RTP_SANS                            :   4.65
Reflectometer                       : COMPILE ERROR using:
mcrun --info /tmp/mctest/20191120_1239_36/3.0-dev/Reflectometer/Reflectometer.instr
SAFARI_MPISI                        : COMPILE ERROR using:
mcrun --info /tmp/mctest/20191120_1239_36/3.0-dev/SAFARI_MPISI/SAFARI_MPISI.instr
SAFARI_PITSI                        :   4.70
SEMSANS_instrument                  : COMPILE ERROR using:
mcrun --info /tmp/mctest/20191120_1239_36/3.0-dev/SEMSANS_instrument/SEMSANS_instrument.instr
SNS_ARCS                            :   4.15
SNS_BASIS                           :   9.88
SNS_analytic_test                   :   2.95
SNS_test                            :   2.88
Samples_Incoherent                  :   5.95
Samples_Incoherent_off              :   3.14
Samples_Isotropic_Sqw               :   4.19
Samples_Phonon                      :   1.53
Samples_vanadium                    :   1.57
TestSANS                            :   1.70
Test_Collimator_Radial              :   3.79
Test_FocalisationMirrors            :   2.17
Test_Jump_Iterate                   :   3.35
Test_Lens                           :   4.62
Test_MCPL_input                     :   2.91
Test_MCPL_output                    :   2.91
Test_Monochromators                 :   3.57
Test_PSD_Detector                   :   3.01
Test_Pol_Guide_Vmirror              :   2.92
Test_Pol_MSF                        :   1.84
Test_Pol_Mirror                     :   2.32
Test_Pol_SF_ideal                   :   1.53
Test_Pol_Set                        :   1.73
Test_PowderN_Res                    :   3.49
Test_PreMonitor_nD                  :   3.39
Test_SSR_SSW                        :   1.34
Test_SSR_SSW_Guide                  :   1.78
Test_Sample_nxs_diffraction         :   2.57
Test_Sample_nxs_imaging             :   2.30
Test_Selectors                      :   3.01
Test_Sources                        :   3.62
Tomography                          :   2.97
Vin_test                            :   1.71
Vout_test                           : COMPILE ERROR using:
mcrun --info /tmp/mctest/20191120_1239_36/3.0-dev/Vout_test/Vout_test.instr
h8_test_legacy                      :   2.76
linup-1                             :   2.24
linup-2                             :   2.20
linup-3                             :   2.38
linup-4                             :   2.63
linup-5                             :   2.56
linup-6                             :   2.60
linup-7                             :   2.46
micro                               :   1.26
mini                                :   1.36
nano                                :   1.19
template                            :   1.16
templateDIFF                        :   4.18
templateLaue                        :   2.58
templateLaueGPU                     : COMPILE ERROR using:
mcrun --info /tmp/mctest/20191120_1239_36/3.0-dev/templateLaueGPU/templateLaueGPU.instr
templateLaueGPU_SXonly              : COMPILE ERROR using:
mcrun --info /tmp/mctest/20191120_1239_36/3.0-dev/templateLaueGPU_SXonly/templateLaueGPU_SXonly.instr
templateLaueGPU_rngonly             : COMPILE ERROR using:
mcrun --info /tmp/mctest/20191120_1239_36/3.0-dev/templateLaueGPU_rngonly/templateLaueGPU_rngonly.instr
templateNMX                         :   2.52
templateNMX_TOF                     :   2.95
templateSANS                        :   1.80
templateSANS_Mantid                 :   3.24
templateSasView                     :   1.79
templateSasView_Mantid              :   3.30
templateTAS                         :   4.92
templateVanadiumMultipleScat_Mantid :   3.01
template_simple                     :   1.17

Running tests...
BNL_H8                               :   1.72
BNL_H8_simple                        :   0.55
Demo_shape_primitives                :   NO TEST
ESS_2001_bispectral                  :   NO TEST
ESS_2015_test                        :   NO TEST
ESS_Brilliance_2001                  :   NO TEST
ESS_Brilliance_2013                  :   NO TEST
ESS_Brilliance_2014                  :   NO TEST
ESS_Brilliance_2015                  :   NO TEST
ESS_Brilliance_TDR                   :   NO TEST
ESS_IN5_reprate                      :   2.56
ESS_butterfly_Guide_curved_test      :   NO TEST
ESS_butterfly_MCPL_test              :   NO TEST
ESS_butterfly_test                   :   NO TEST
ESS_butterfly_tfocus_NOFOCUS_test    :   NO TEST
ESS_butterfly_tfocus_test            :   NO TEST
ESS_mcpl2hist                        :   NO TEST
FZJ_BenchmarkSfin2                   :   NO TEST
FZJ_KWS2_Lens                        :   0.81
FZJ_SANS_KWS2_AnySample              :   0.54
FZJ_SANS_KWS2_AnySample_2            :   0.53
FZJ_SANS_KWS2_AnySample_3            :   0.51
FZJ_SANS_KWS2_AnySample_4            :   0.51
Gallmeier_SNS_decoupled_poisoned     :   NO TEST
Granroth_SNS_decoupled_poisoned      :   NO TEST
HZB_FLEX                             :   NO TEST
HZB_NEAT                             :   6.58
HZB_NEAT_2                           :   3.58
Histogrammer                         :   NO TEST
ILL_D2B                              :   1.23
ILL_D4                               :   9.27
ILL_H10_IN8                          :   1.73
ILL_H113                             :   8.55
ILL_H13_IN20                         :   1.81
ILL_H142                             :   7.56
ILL_H142_IN12                        :   1.71
ERROR: targetval for monitor name D7_SC3_1D could not be extracted from instr. ILL_H142_IN12
ILL_H143_LADI                        :   NO TEST
ILL_H15                              :   5.99
ILL_H15_IN6                          :   NO TEST
ILL_H16                              :   2.14
ILL_H16_IN5                          :   1.08
ILL_H16_IN5_2                        :   1.07
ILL_H16_IN5_Mantid                   :   1.17
ILL_H16_IN5_Mantid_2                 :   1.19
ILL_H16_Mantid                       :   NO TEST
ILL_H22                              :   1.82
ILL_H22_D1A                          :   3.95
ERROR: targetval for monitor name BananaPSD could not be extracted from instr. ILL_H22_D1A
ILL_H22_D1B                          :   4.11
ILL_H22_VIVALDI                      :   5.32
ERROR: targetval for monitor name PSD_Vivaldi could not be extracted from instr. ILL_H22_VIVALDI
ILL_H24                              :   1.29
ILL_H25                              :   5.24
ILL_H25_IN22                         :   1.89
ILL_H5                               :   NO TEST
ILL_H512_D22                         :   1.99
ERROR: targetval for monitor name D22_Detector could not be extracted from instr. ILL_H512_D22
ILL_H53                              :   3.50
ERROR: targetval for monitor name H53_P5_Out_Phic could not be extracted from instr. ILL_H53
ILL_H53_D16                          :   NO TEST
ILL_H8_IN1                           :   4.73
ILL_IN13                             :  25.28
ILL_IN4                              :   6.48
ERROR: targetval for monitor name sample_flux could not be extracted from instr. ILL_IN4
ILL_IN5                              :   0.67
ILL_IN5_Mantid                       :   0.87
ILL_IN6                              :   NO TEST
ILL_Lagrange                         :  13.62
ISIS_CRISP                           :   NO TEST
ISIS_GEM                             :   4.76
ISIS_HET                             :   2.25
ISIS_MERLIN                          :   NO TEST
ISIS_OSIRIS                          :   NO TEST
ISIS_Prisma2                         :   0.98
ERROR: targetval for monitor name mon9 could not be extracted from instr. ISIS_Prisma2
ISIS_SANS2d                          :   NO TEST
ISIS_SANS2d_Mantid                   :   NO TEST
ISIS_TS1_Brilliance                  :   NO TEST
ISIS_TS2_Brilliance                  :   NO TEST
ISIS_test                            :   0.73
LLB_6T2                              :   NO TEST
MCPL2hist                            :   NO TEST
Mezei_SNS_decoupled_poisoned         :   NO TEST
PSI_DMC                              :   1.24
PSI_DMC_simple                       :   0.77
PSI_Focus                            :   3.70
PSI_source                           :   0.38
RITA-II did not compile
RTP_DIF                              :   NO TEST
RTP_Laue                             :   NO TEST
RTP_NeutronRadiography               :   NO TEST
RTP_SANS                             :   NO TEST
Reflectometer did not compile
SAFARI_MPISI did not compile
SAFARI_PITSI                         :   NO TEST
SEMSANS_instrument did not compile
SNS_ARCS                             :   NO TEST
SNS_BASIS                            :   NO TEST
SNS_analytic_test                    :   NO TEST
SNS_test                             :   NO TEST
Samples_Incoherent                   :   1.48
Samples_Incoherent_2                 :   1.30
Samples_Incoherent_3                 :   1.19
Samples_Incoherent_4                 :   1.16
Samples_Incoherent_5                 :   1.69
Samples_Incoherent_6                 :   1.77
Samples_Incoherent_7                 :   2.12
Samples_Incoherent_8                 :   1.77
Samples_Incoherent_9                 :   2.77
Samples_Incoherent_10                :   1.32
Samples_Incoherent_off               :  26.02
Samples_Isotropic_Sqw                :   7.57
Samples_Phonon                       :  34.37
Samples_vanadium                     :   0.96
TestSANS                             :   NO TEST
Test_Collimator_Radial               :   1.02
Test_Collimator_Radial_2             :   1.00
Test_Collimator_Radial_3             :   0.95
Test_FocalisationMirrors             :   1.06
Test_Jump_Iterate                    :   1.71
ERROR: targetval for monitor name Mon_LambdaDX_Out could not be extracted from instr. Test_Jump_Iterate
Test_Lens                            :   NO TEST
Test_MCPL_input                      :   0.24
Test_MCPL_output                     :  10.13
Test_Monochromators                  :   1.04
Test_Monochromators_2                :   0.80
Test_Monochromators_3                :   0.83
Test_Monochromators_4                :   1.02
Test_Monochromators_5                :   1.56
Test_PSD_Detector                    :   0.83
Test_Pol_Guide_Vmirror               :   1.45
Test_Pol_MSF                         :   0.71
Test_Pol_Mirror                      :   0.95
Test_Pol_SF_ideal                    :   NO TEST
Test_Pol_Set                         :   0.93
ERROR: targetval for monitor name polMonitor3 could not be extracted from instr. Test_Pol_Set
Test_PowderN_Res                     :   NO TEST
Test_PreMonitor_nD                   :   NO TEST
Test_SSR_SSW                         :   NO TEST
Test_SSR_SSW_Guide                   :   NO TEST
Test_Sample_nxs_diffraction          :   NO TEST
Test_Sample_nxs_imaging              :   NO TEST
Test_Selectors                       :   0.57
Test_Selectors_2                     :   0.52
Test_Sources                         :   1.49
Test_Sources_2                       :   1.01
Test_Sources_3                       :   1.49
Test_Sources_4                       :   1.05
Test_Sources_5                       :   1.18
Test_Sources_6                       :   1.05
Test_Sources_7                       :   1.27
Test_Sources_8                       :   1.09
Tomography                           :  32.82
Vin_test                             :   NO TEST
Vout_test did not compile
h8_test_legacy                       :   NO TEST
linup-1                              :   1.06
ERROR: targetval for monitor name sng could not be extracted from instr. linup-1
linup-2                              :   1.02
ERROR: targetval for monitor name sng could not be extracted from instr. linup-2
linup-3                              :   1.06
ERROR: targetval for monitor name sng could not be extracted from instr. linup-3
linup-4                              :   1.18
ERROR: targetval for monitor name sng could not be extracted from instr. linup-4
linup-5                              :   1.04
ERROR: targetval for monitor name sng could not be extracted from instr. linup-5
linup-6                              :   1.08
ERROR: targetval for monitor name sng could not be extracted from instr. linup-6
linup-7                              :   1.07
ERROR: targetval for monitor name sng could not be extracted from instr. linup-7
micro                                :   NO TEST
mini                                 :   0.41
nano                                 :   NO TEST
template                             :   NO TEST
templateDIFF                         :   3.07
templateLaue                         :   1.01
templateLaue_2                       :   3.29
templateLaueGPU did not compile
templateLaueGPU_SXonly did not compile
templateLaueGPU_rngonly did not compile
templateNMX                          :   NO TEST
templateNMX_TOF                      :   NO TEST
templateSANS                         :   0.63
templateSANS_Mantid                  :   0.68
templateSasView                      :   NO TEST
templateSasView_Mantid               :   NO TEST
templateTAS                          :   5.21
templateTAS_2                        :   6.22
ERROR: targetval for monitor name He3H could not be extracted from instr. templateTAS
templateVanadiumMultipleScat_Mantid  :   NO TEST
template_simple                      :   NO TEST
</pre>

**Comment by climbcat** [comment]
@willend do you know why so many target values can not be extracted?

**Comment by climbcat** [comment]
Here's the latest version:

<pre>jaga@HP-EliteBook-840-G4:/tmp$ mctest-dev 3.0-dev
ncount is: 1e6
Testing: 3.0-dev

Finding instruments in: /usr/share/mcstas/3.0-dev
Copying instruments to: /tmp/mctest/20191120_1725_12/3.0-dev

Compiling instruments [seconds]...
BNL_H8                              :   2.80
BNL_H8_simple                       :   2.73
Demo_shape_primitives               :   1.96
ESS_2001_bispectral                 :   2.98
ESS_2015_test                       :   2.24
ESS_Brilliance_2001                 :   4.07
ESS_Brilliance_2013                 :   4.46
ESS_Brilliance_2014                 :   4.82
ESS_Brilliance_2015                 :   4.46
ESS_Brilliance_TDR                  :   4.60
ESS_IN5_reprate                     :   4.74
ESS_butterfly_Guide_curved_test     :   6.11
ESS_butterfly_MCPL_test             :   5.46
ESS_butterfly_test                  :   4.90
ESS_butterfly_tfocus_NOFOCUS_test   :   5.45
ESS_butterfly_tfocus_test           :   5.35
ESS_mcpl2hist                       :   4.09
FZJ_BenchmarkSfin2                  :   6.84
FZJ_KWS2_Lens                       :   2.37
FZJ_SANS_KWS2_AnySample             :   2.92
Gallmeier_SNS_decoupled_poisoned    :   1.97
Granroth_SNS_decoupled_poisoned     :   2.85
HZB_FLEX                            :   6.16
HZB_NEAT                            :   8.44
Histogrammer                        :   4.18
ILL_D2B                             :   6.48
ILL_D4                              :   5.80
ILL_H10_IN8                         :   6.22
ILL_H113                            :  10.56
ILL_H13_IN20                        :   6.85
ILL_H142                            :  11.15
ILL_H142_IN12                       :  14.45
ILL_H143_LADI                       :   9.05
ILL_H15                             :   7.45
ILL_H15_IN6                         :  10.92
ILL_H16                             :   6.37
ILL_H16_IN5                         :   9.42
ILL_H16_IN5_Mantid                  :   9.43
ILL_H16_Mantid                      :   5.58
ILL_H22                             :   9.94
ILL_H22_D1A                         :  12.51
ILL_H22_D1B                         :  13.34
ILL_H22_VIVALDI                     :  13.91
ILL_H24                             :   9.99
ILL_H25                             :   9.70
ILL_H25_IN22                        :  12.86
ILL_H5                              :  34.08
ILL_H512_D22                        :  11.68
ILL_H53                             :  11.09
ILL_H53_D16                         :  11.27
ILL_H8_IN1                          :   6.20
ILL_IN13                            :   5.56
ILL_IN4                             :  10.02
ILL_IN5                             :   8.08
ILL_IN5_Mantid                      :   8.60
ILL_IN6                             :   7.24
ILL_Lagrange                        :   7.59
ISIS_CRISP                          :   4.17
ISIS_GEM                            :   4.78
ISIS_HET                            :   5.57
ISIS_MERLIN                         :   4.30
ISIS_OSIRIS                         :   8.28
ISIS_Prisma2                        :   5.87
ISIS_SANS2d                         :   4.41
ISIS_SANS2d_Mantid                  :   6.74
ISIS_TS1_Brilliance                 :   2.24
ISIS_TS2_Brilliance                 :   2.28
ISIS_test                           :   4.35
LLB_6T2                             :   5.28
MCPL2hist                           :   3.88
Mezei_SNS_decoupled_poisoned        :   1.91
PSI_DMC                             :   6.79
PSI_DMC_simple                      :   6.58
PSI_Focus                           :   7.98
PSI_source                          :   1.91
RITA-II                             :  21.22
RTP_DIF                             :   6.34
RTP_Laue                            :   6.39
RTP_NeutronRadiography              :   5.82
RTP_SANS                            :   7.13
SAFARI_MPISI                        :   8.10
SAFARI_PITSI                        :   6.75
SNS_ARCS                            :   5.47
SNS_BASIS                           :  12.91
SNS_analytic_test                   :   3.51
SNS_test                            :   3.20
Samples_Incoherent                  :   6.51
Samples_Incoherent_off              :   3.46
Samples_Isotropic_Sqw               :   4.23
Samples_Phonon                      :   1.63
Samples_vanadium                    :   1.64
TestSANS                            :   1.72
Test_Collimator_Radial              :   3.99
Test_FocalisationMirrors            :   2.24
Test_Jump_Iterate                   :   3.35
Test_Lens                           :   4.67
Test_MCPL_input                     :   3.15
Test_MCPL_output                    :   2.99
Test_Monochromators                 :   3.85
Test_PSD_Detector                   :   3.09
Test_Pol_Guide_Vmirror              :   3.23
Test_Pol_MSF                        :   2.34
Test_Pol_Mirror                     :   2.51
Test_Pol_SF_ideal                   :   1.86
Test_Pol_Set                        :   2.01
Test_PowderN_Res                    :   3.86
Test_PreMonitor_nD                  :   3.61
Test_SSR_SSW                        :   1.43
Test_SSR_SSW_Guide                  :   1.93
Test_Sample_nxs_diffraction         :   2.69
Test_Sample_nxs_imaging             :   2.78
Test_Selectors                      :   3.51
Test_Sources                        :   4.64
Tomography                          :   3.59
Vin_test                            :   2.07
Vout_test                           :   2.55
h8_test_legacy                      :   3.34
linup-1                             :   2.65
linup-2                             :   2.66
linup-3                             :   2.87
linup-4                             :   3.24
linup-5                             :   3.12
linup-6                             :   3.72
linup-7                             :   3.38
micro                               :   1.72
mini                                :   2.19
nano                                :   1.72
template                            :   1.46
templateDIFF                        :   5.01
templateLaue                        :   3.24
templateLaueGPU                     : COMPILE ERROR using:
mcrun --info /tmp/mctest/20191120_1725_12/3.0-dev/templateLaueGPU/templateLaueGPU.instr
templateLaueGPU_SXonly              : COMPILE ERROR using:
mcrun --info /tmp/mctest/20191120_1725_12/3.0-dev/templateLaueGPU_SXonly/templateLaueGPU_SXonly.instr
templateLaueGPU_rngonly             : COMPILE ERROR using:
mcrun --info /tmp/mctest/20191120_1725_12/3.0-dev/templateLaueGPU_rngonly/templateLaueGPU_rngonly.instr
templateNMX                         :   3.85
templateNMX_TOF                     :   3.75
templateSANS                        :   2.19
templateSANS_Mantid                 :   3.91
templateSasView                     :   2.09
templateSasView_Mantid              :   3.91
templateTAS                         :   6.03
templateVanadiumMultipleScat_Mantid :   3.64
template_simple                     :   1.39

Running tests...
BNL_H8                               :   1.98
BNL_H8_simple                        :   0.76
Demo_shape_primitives                :   NO TEST
ESS_2001_bispectral                  :   NO TEST
ESS_2015_test                        :   NO TEST
ESS_Brilliance_2001                  :   NO TEST
ESS_Brilliance_2013                  :   NO TEST
ESS_Brilliance_2014                  :   NO TEST
ESS_Brilliance_2015                  :   NO TEST
ESS_Brilliance_TDR                   :   NO TEST
ESS_IN5_reprate                      :   3.23
ESS_butterfly_Guide_curved_test      :   NO TEST
ESS_butterfly_MCPL_test              :   NO TEST
ESS_butterfly_test                   :   NO TEST
ESS_butterfly_tfocus_NOFOCUS_test    :   NO TEST
ESS_butterfly_tfocus_test            :   NO TEST
ESS_mcpl2hist                        :   NO TEST
FZJ_BenchmarkSfin2                   :   NO TEST
FZJ_KWS2_Lens                        :   1.09
FZJ_SANS_KWS2_AnySample              :   1.51
FZJ_SANS_KWS2_AnySample_2            :   0.78
FZJ_SANS_KWS2_AnySample_3            :   0.69
FZJ_SANS_KWS2_AnySample_4            :   0.64
Gallmeier_SNS_decoupled_poisoned     :   NO TEST
Granroth_SNS_decoupled_poisoned      :   NO TEST
HZB_FLEX                             :   NO TEST
HZB_NEAT                             :   8.23
HZB_NEAT_2                           :   4.31
Histogrammer                         :   NO TEST
ILL_D2B                              :   1.43
ILL_D4                               :  12.31
ILL_H10_IN8                          :   2.48
ILL_H113                             :  11.19
ILL_H13_IN20                         :   2.28
ILL_H142                             :  10.54
ILL_H142_IN12                        :   2.46
ERROR: targetval for monitor name D7_SC3_1D could not be extracted from instr. ILL_H142_IN12
ILL_H143_LADI                        :   NO TEST
ILL_H15                              :   8.80
ILL_H15_IN6                          :   NO TEST
ILL_H16                              :   2.62
ILL_H16_IN5                          :   1.53
ILL_H16_IN5_2                        :   1.52
ILL_H16_IN5_Mantid                   :   1.60
ILL_H16_IN5_Mantid_2                 :   1.54
ILL_H16_Mantid                       :   NO TEST
ILL_H22                              :   2.11
ILL_H22_D1A                          :   6.25
ERROR: targetval for monitor name BananaPSD could not be extracted from instr. ILL_H22_D1A
ILL_H22_D1B                          :   5.17
ILL_H22_VIVALDI                      :   7.00
ERROR: targetval for monitor name PSD_Vivaldi could not be extracted from instr. ILL_H22_VIVALDI
ILL_H24                              :   1.79
ILL_H25                              :   6.27
ILL_H25_IN22                         :   2.22
ILL_H5                               :   NO TEST
ILL_H512_D22                         :   2.42
ERROR: targetval for monitor name D22_Detector could not be extracted from instr. ILL_H512_D22
ILL_H53                              :   4.21
ERROR: targetval for monitor name H53_P5_Out_Phic could not be extracted from instr. ILL_H53
ILL_H53_D16                          :   NO TEST
ILL_H8_IN1                           :   5.62
ILL_IN13                             :  30.41
ILL_IN4                              :   0.79
ERROR: targetval for monitor name sample_flux could not be extracted from instr. ILL_IN4
ILL_IN5                              :   1.56
ILL_IN5_Mantid                       :   1.02
ILL_IN6                              :   NO TEST
ILL_Lagrange                         :  16.73
ISIS_CRISP                           :   NO TEST
ISIS_GEM                             :   5.82
ISIS_HET                             :   3.13
ISIS_MERLIN                          :   NO TEST
ISIS_OSIRIS                          :   NO TEST
ISIS_Prisma2                         :   1.40
ERROR: targetval for monitor name mon9 could not be extracted from instr. ISIS_Prisma2
ISIS_SANS2d                          :   NO TEST
ISIS_SANS2d_Mantid                   :   NO TEST
ISIS_TS1_Brilliance                  :   NO TEST
ISIS_TS2_Brilliance                  :   NO TEST
ISIS_test                            :   0.88
LLB_6T2                              :   NO TEST
MCPL2hist                            :   NO TEST
Mezei_SNS_decoupled_poisoned         :   NO TEST
PSI_DMC                              :   1.71
PSI_DMC_simple                       :   0.92
PSI_Focus                            :   4.53
PSI_source                           :   0.45
RITA-II                              :   NO TEST
RTP_DIF                              :   NO TEST
RTP_Laue                             :   NO TEST
RTP_NeutronRadiography               :   NO TEST
RTP_SANS                             :   NO TEST
SAFARI_MPISI                         :   NO TEST
SAFARI_PITSI                         :   NO TEST
SNS_ARCS                             :   NO TEST
SNS_BASIS                            :   NO TEST
SNS_analytic_test                    :   NO TEST
SNS_test                             :   NO TEST
Samples_Incoherent                   :   1.70
Samples_Incoherent_2                 :   1.95
Samples_Incoherent_3                 :   1.41
Samples_Incoherent_4                 :   1.52
Samples_Incoherent_5                 :   1.91
Samples_Incoherent_6                 :   2.12
Samples_Incoherent_7                 :   2.53
Samples_Incoherent_8                 :   2.18
Samples_Incoherent_9                 :   3.10
Samples_Incoherent_10                :   2.08
Samples_Incoherent_off               :  26.43
Samples_Isotropic_Sqw                :   7.81
Samples_Phonon                       :  30.67
Samples_vanadium                     :   0.88
TestSANS                             :   NO TEST
Test_Collimator_Radial               :   2.10
Test_Collimator_Radial_2             :   0.94
Test_Collimator_Radial_3             :   0.96
Test_FocalisationMirrors             :   0.91
Test_Jump_Iterate                    :   1.74
ERROR: targetval for monitor name Mon_LambdaDX_Out could not be extracted from instr. Test_Jump_Iterate
Test_Lens                            :   NO TEST
Test_MCPL_input                      :   0.15
Test_MCPL_output                     :   9.86
Test_Monochromators                  :   0.97
Test_Monochromators_2                :   0.77
Test_Monochromators_3                :   0.79
Test_Monochromators_4                :   1.06
Test_Monochromators_5                :   1.36
Test_PSD_Detector                    :   0.74
Test_Pol_Guide_Vmirror               :   1.42
Test_Pol_MSF                         :   0.78
Test_Pol_Mirror                      :   0.73
Test_Pol_SF_ideal                    :   NO TEST
Test_Pol_Set                         :   0.90
ERROR: targetval for monitor name polMonitor3 could not be extracted from instr. Test_Pol_Set
Test_PowderN_Res                     :   NO TEST
Test_PreMonitor_nD                   :   NO TEST
Test_SSR_SSW                         :   NO TEST
Test_SSR_SSW_Guide                   :   NO TEST
Test_Sample_nxs_diffraction          :   NO TEST
Test_Sample_nxs_imaging              :   NO TEST
Test_Selectors                       :   0.55
Test_Selectors_2                     :   1.15
Test_Sources                         :   1.40
Test_Sources_2                       :   1.05
Test_Sources_3                       :   1.46
Test_Sources_4                       :   1.06
Test_Sources_5                       :   1.26
Test_Sources_6                       :   1.03
Test_Sources_7                       :   1.20
Test_Sources_8                       :   1.08
Tomography                           :  31.21
Vin_test                             :   NO TEST
Vout_test                            :   NO TEST
h8_test_legacy                       :   NO TEST
linup-1                              :   0.92
ERROR: targetval for monitor name sng could not be extracted from instr. linup-1
linup-2                              :   0.99
ERROR: targetval for monitor name sng could not be extracted from instr. linup-2
linup-3                              :   0.97
ERROR: targetval for monitor name sng could not be extracted from instr. linup-3
linup-4                              :   0.97
ERROR: targetval for monitor name sng could not be extracted from instr. linup-4
linup-5                              :   0.96
ERROR: targetval for monitor name sng could not be extracted from instr. linup-5
linup-6                              :   0.99
ERROR: targetval for monitor name sng could not be extracted from instr. linup-6
linup-7                              :   0.95
ERROR: targetval for monitor name sng could not be extracted from instr. linup-7
micro                                :   NO TEST
mini                                 :   0.36
nano                                 :   NO TEST
template                             :   NO TEST
templateDIFF                         :   2.30
templateLaue                         :   0.91
templateLaue_2                       :   2.73
templateLaueGPU did not compile
templateLaueGPU_SXonly did not compile
templateLaueGPU_rngonly did not compile
templateNMX                          :   NO TEST
templateNMX_TOF                      :   NO TEST
templateSANS                         :   0.58
templateSANS_Mantid                  :   0.58
templateSasView                      :   NO TEST
templateSasView_Mantid               :   NO TEST
templateTAS                          :   4.49
templateTAS_2                        :   4.47
ERROR: targetval for monitor name He3H could not be extracted from instr. templateTAS
templateVanadiumMultipleScat_Mantid  :   NO TEST
template_simple                      :   NO TEST
</pre>

**Comment by willend** [comment]
@climbcat I am sure the reason for the non-extractability has to do with the simulation crashing - likely access to global structures in a non-atomic way. The stdout/stderr will tell us in that case.

**Comment by climbcat** [comment]
Ok, I'll double-check a few examples. Then these actually need to turn red.

**Comment by willend** [comment]
Hmm, linup-1 gives the right output when the old perl-based, test is run, 
<pre>
mcrun.pl --test linup-1
PGPLOT unactivated: install perl-PGPLOT first
PGPLOT unactivated: install perl-PDL first
*** No directory given - placing data in linup-1_20191121_110618 ***
# mcstas self-test (mcrun.pl --test)
McStas version 3.0-dev (Nov. 20, 2019)

# Installing 'selftest_0vs0' directory in /zhome/89/0/38697/tmp
# Copying instruments from /zhome/89/0/38697/McStas/mcstas/3.0-dev/examples/
# Counts:        1000000
# Output format: PGPLOT
# Start Date:    Thu Nov 21 11:06:18 2019
INSTRUMENT linup-1:
  The conventional cold-source triple-axis spectrometer TAS1 at Risoe National
Laboratory used as a diffractometer for monochromator rocking curves

Executing: mcrun.pl linup-1.instr PHM=-37.077 -n 1000000 --format=PGPLOT -d linup-1/0
PGPLOT unactivated: install perl-PGPLOT first
PGPLOT unactivated: install perl-PDL first
CFLAGS=
linup-1.c: In function 'sighandler':
linup-1.c:4929:5: warning: implicit declaration of function 'kill' [-Wimplicit-function-declaration]
     kill(0, SIGKILL); /* kill myself if error occurs within sighandler: loops */
     ^~~~
[OK] linup-1: sng_I = 0.000427037 +/- 4.21218e-06, equals 0.000429426
 within 1 %
Test Abstract for selftest_0vs0
[OK]     linup-1_1 (accuracy, 1 %)


# Execution check:    OK.     Computing time: 5 [sec] for 1 tests.
# Accuracy check:     OK.
# End Date: Thu Nov 21 11:06:23 2019
</pre>
I will now try to see what is going on in the mctest-driven case

**Comment by ebknudsen** [comment]
outdated
