### ISSUE TITLE
McXtrace 1.5 and Debian "old stable"

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#889]
Looks like there are issues in the Debian dependencies on Debian 9.x
<pre>
pkwi@mcstas-01:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch
pkwi@mcstas-01:~$ sudo apt-get install mcxtrace-suite-python 
[sudo] password for pkwi: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mcxtrace-suite-python : Depends: mcxtrace-comps-1.5 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
pkwi@mcstas-01:~$ sudo apt-get install mcxtrace-comps-1.5    
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mcxtrace-comps-1.5 : Depends: libgsl23 but it is not installable
E: Unable to correct problems, you have held broken packages.
pkwi@mcstas-01:~$ 
</pre>

We have
<pre>
# Debian
set(CPACK_DEBIAN_PACKAGE_DEPENDS "${FLAVOR}-${MCCODE_VERSION},libgsl23,libgsl-dev")
</pre>
in CMakeLists, and Debian 9 seems to have libgsl2 (stupid there is not an alias called libgsl...)

**Comment by willend** [comment]
@ebknudsen will make a dedicated package for "oldstable" that can be hand-installed in place of the repo version. General solution not envisioned as "oldstable" is "oldstable". :)

**Comment by ebknudsen** [comment]
We have set up a workaround for this:
1. Download the custom built: http://download.mcxtrace.org/patches_etc/debian_stretch/mcxtrace-comps-1.5-deb64.deb component library
2. Install the mcxtrace kernel by: ```sudo apt-get install mcxtrace1.5```
3. Install the component lib by hand: ```sudo dpkg --install /path/to/mcxtrace-comps-1.5-deb64.deb```
4. Install the full python suite: ```sudo apt-get install mcxtrace-python-suite```
