### ISSUE TITLE
uservars can clash with internal component vars

### ISSUE THREAD

**Issue by climbcat** [McStasMcXtrace/McCode#907]
A typical example is "v", used both as a local component variable in the trace section, and as a uservar. The auto-generated macro #define v (_particle->v) will clash with any component trace local variable named v.

**Comment by climbcat** [comment]
Peter suggests using uservars.v, is this is the most robust. We do not feel that checking all variable names in arbitrary trace sections is worth the trouble...

**Comment by willend** [comment]
Indeed a simple and robust solution. 

We could on the other hand as suggested by @climbcat check uservars against component and instrument parameters, which would on the other hand not have caught the 'v' from above...

**Comment by climbcat** [comment]
Closing to mere with another, related, issue.
