### ISSUE TITLE
GPUhack: Investigate where the segfaults in Single_crystal arise:

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#916]
Bigger problem with normal Laue than NMX? (Beam XS with sample?)

Bigger problem with large structures than small.

Bigger problem with high statistics.

Does something write to the comp structure? Make atomic?

**Comment by ebknudsen** [comment]
linked to #941 . Trying to use nvidia-gdb to investigate this issue

**Comment by ebknudsen** [comment]
The problem appears to be that the elements in the component struct are modified within TRACE.
... running tests

Drawback of this is that the optimization that avoids re-searching the hkl_list as is, has to be disabled.

**Comment by ebknudsen** [comment]
Component now runs: timing for 10^8 neutrons
Save [templateNMX]
Detector: det_I=5364.19 det_ERR=11.4521 det_N=231477 "psd.dat"

Finally [templateNMX: .]. Time: 431773 [h] 

real	8m41.448s
user	5m26.120s
sys	3m12.766s

**Comment by ebknudsen** [comment]
checking whether the results match up with stock 2.6 McStas

**Comment by willend** [comment]
@ebknudsen is the code that ran above checked in?

**Comment by ebknudsen** [comment]
AFAIK it is
