### ISSUE TITLE
GPUhack: Funnel-like simulation flow

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#917]
Implement "alternative neutron flow" in cogen, i.e. finalise all calculations on 1st comp before proceeding to 2nd etc.

Implement SPLIT in this context.

**Comment by climbcat** [comment]
Status update: We have cogen'd some more funnel code adjustments, which are compatible with the functional sort_absorb_last parallel impl. The change introduces the use of two pointer arrays, one for iteration, and a buffer. This is not portable yet, and no attempts to port sort_absorb_last have been made yet.

Note on the viability of this solution: After discussions with GPU experts, it seems that what the "funnel" approach is trying to achieve, is already implemented by OpenACC when using high-end cards live our VOLTAs at DTU: To re-engage idling threads with dead/absorbed particles. On lower end GPUs, however, this feature should be less pronounced.

**Comment by willend** [comment]
done
