### ISSUE TITLE
GPUhack: Monitor_nD auto

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#921]
Monitor_nD "auto" not surprisingly has issues. :-) See e.g. HZB_NEAT/1 or ILL_H16_IN5/1. The rest of those instruments actually seems good!

**Comment by farhi** [comment]
Fixed with https://github.com/McStasMcXtrace/McCode/commit/03a8a56d90a9c1eae5aae0f35e3488118d6bd6c6
