### ISSUE TITLE
GPUhack: NULL filename outputs

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#922]
Some monitors end up with filenames including the label NULL, e.g. in HZB_NEAT/1
<pre>
HZB_NEAT.instr
NEAT.psd
NULL.A_t
NULL.L
NULL.hd_vd
NULL.t
NULL.x_y
NULL.y_x
browse.html
mccode.sim
</pre>

**Comment by farhi** [comment]
Fixed with commit 79266ba1343e2765c31f0903965c99bb1bcbc037 :
mcstas/monitors: restored proper test for "NULL" filename which was commented
  on commit 2452b9d (Nov 2019) when USE_PGI
  did not allow use of 'strlen'/'strcmp'. Now fixed with our own functions.
