### ISSUE TITLE
GPUhack: Polarisation, with priority

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#948]
From http://gpuhack.mccode.org/remaining_comps_20200127.txt
### High priority
* Analyser_ideal.comp / PolAnalyser_ideal.comp (identical?)
* He3_cell.comp
* MeanPolLambda_monitor.comp
* Pol_mirror.comp / Monochromator_pol.comp (identical?)
* PolLambda_monitor.comp
* Pol_FieldBox.comp
* Pol_constBfield.comp
* Pol_Bfield.comp
* Pol_Bfield_stop.comp
### Low priority
- Pol_bender_tapering.comp
- Pol_guide_vmirror.comp
- Pol_pi_2_rotator.comp
- Foil_flipper_magnet.comp
- Pol_triafield.comp
- Pol_simpleBfield.comp
- Pol_simpleBfield_stop.comp

**Comment by willend** [comment]
Belive @ebknudsen has started here

**Comment by ebknudsen** [comment]
Analyser_ideal and PolAnalyser_ideal work out of the box but don't have a Test instrument. Fixing that in 975df8755...

**Comment by ebknudsen** [comment]
PolLambda and MeanPolLambda now work also for GPU 4c91ae7ba06d5b6c0b6c930f508c17d663105d3b

**Comment by ebknudsen** [comment]
Pol_Bfield requires more work -see #1072

**Comment by ebknudsen** [comment]
Pol_Fieldbox now works using an analytical approach.

**Comment by ebknudsen** [comment]
next step are the mirror components.  These should not be difficult,then back to the precession fields.

**Comment by ebknudsen** [comment]
Pol_mirror now works,
Pol_bender as well

**Comment by willend** [comment]
high-priority is done, ready for release.
