### ISSUE TITLE
GPUhack: Misc, with priority

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#949]
From http://gpuhack.mccode.org/remaining_comps_20200127.txt
### High Priority
* Rotator.comp
* Derotator.comp
### Low Priority
- Source_Optimizer.comp
- Source_adapt.comp
- Adapt_check.comp
- Beam_spy.comp
- Scatter_log_iterator.comp
- Scatter_log_iterator_stop.comp
- Scatter_logger.comp
- Scatter_logger_stop.comp

**Comment by farhi** [comment]
Re-worked at commit 85bf1617179065d64d6914e48369394500d864e1
- Rotator.comp
- Derotator.comp
- Source_Optimizer.comp
- Source_adapt.comp

**Comment by willend** [comment]
excellent, then we close
