### ISSUE TITLE
GPUhack: Remove destinction between OUTPUT_PARAMETERS and DECLARE block??

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#951]
It seems that only OUTPUT_PARAMETERS and component input parameters are carried over to the _comp struct and hence available in INITIALIZE and TRACE.

 - i.e. it seems ```double A;``` in a DECLARE block and unreferenced elsewhere does not make it to the comp struct.

https://github.com/McStasMcXtrace/McCode/wiki/Variables-and-Scopes

**Comment by willend** [comment]
@climbcat, @mads-bertelsen, @ebknudsen, @farhi we need a chat about scopes etc.

**Comment by willend** [comment]
Example:
* Run ```PSI_source.instr``` with attached PSD_monitor.comp.txt (OUTPUT parameters removed)

[PSD_monitor.comp.txt](https://github.com/McStasMcXtrace/McCode/files/4118053/PSD_monitor.comp.txt)

Error message is:
<pre>
pgcc -ta=tesla,managed,deepcopy -Minfo=accel -DUSE_PGI -DNOSIGNALS -DRNG_ALG=2 PSI_source.c      
PGC-W-0221-Redefinition of symbol MC_RAND_MAX (PSI_source.c: 495)
PGC-S-0039-Use of undeclared variable PSD_N (PSI_source.c: 6147)
PGC-W-0095-Type cast required for this conversion (PSI_source.c: 6147)
PGC-S-0039-Use of undeclared variable PSD_p (PSI_source.c: 6148)
PGC-W-0095-Type cast required for this conversion (PSI_source.c: 6148)
PGC-S-0039-Use of undeclared variable PSD_p2 (PSI_source.c: 6149)
PGC-W-0095-Type cast required for this conversion (PSI_source.c: 6149)
PGC-S-0054-Subscript operator ([]) applied to non-array (PSI_source.c: 6154)
PGC-S-0054-Subscript operator ([]) applied to non-array (PSI_source.c: 6154)
PGC-S-0054-Subscript operator ([]) applied to non-array (PSI_source.c: 6155)
PGC-S-0054-Subscript operator ([]) applied to non-array (PSI_source.c: 6155)
PGC-S-0054-Subscript operator ([]) applied to non-array (PSI_source.c: 6156)
PGC-S-0054-Subscript operator ([]) applied to non-array (PSI_source.c: 6156)
PGC-S-0054-Subscript operator ([]) applied to non-array (PSI_source.c: 6382)
PGC-S-0054-Subscript operator ([]) applied to non-array (PSI_source.c: 6382)
PGC-S-0054-Subscript operator ([]) applied to non-array (PSI_source.c: 6382)
PGC-S-0054-Subscript operator ([]) applied to non-array (PSI_source.c: 6382)
PGC-S-0054-Subscript operator ([]) applied to non-array (PSI_source.c: 6386)
PGC-S-0054-Subscript operator ([]) applied to non-array (PSI_source.c: 6386)
PGC-S-0054-Subscript operator ([]) applied to non-array (PSI_source.c: 6386)
PGC-S-0054-Subscript operator ([]) applied to non-array (PSI_source.c: 6386)
PGC-S-0054-Subscript operator ([]) applied to non-array (PSI_source.c: 6390)
PGC-S-0054-Subscript operator ([]) applied to non-array (PSI_source.c: 6390)
PGC-S-0054-Subscript operator ([]) applied to non-array (PSI_source.c: 6390)
PGC-S-0054-Subscript operator ([]) applied to non-array (PSI_source.c: 6390)
PGC-S-0054-Subscript operator ([]) applied to non-array (PSI_source.c: 6694)
PGC-S-0054-Subscript operator ([]) applied to non-array (PSI_source.c: 6694)
PGC-S-0054-Subscript operator ([]) applied to non-array (PSI_source.c: 6694)
PGC-S-0054-Subscript operator ([]) applied to non-array (PSI_source.c: 6694)
PGC-F-0008-Error limit exceeded (PSI_source.c: 6694)
PGC/x86-64 Linux 19.4-0: compilation aborted
</pre>

**Comment by willend** [comment]
First sketch of recipe:
* Clean up "OUTPUT PARAMETERS" part of cogen_comp_scope
* Handle comp declare block like USERVARS in the instrument

**Comment by climbcat** [comment]
Oops, there is not cogen_comp_scope in the mcstas-3.0 tree, but only in master. This means that our assumptions about DECLARE and so need a second look.

**Comment by climbcat** [comment]
This test can show how various parameters/variables are treated:

[ArmSpecial.comp.txt](https://github.com/McStasMcXtrace/McCode/files/4133662/ArmSpecial.comp.txt)
[SpecialVarsTest.instr.txt](https://github.com/McStasMcXtrace/McCode/files/4133664/SpecialVarsTest.instr.txt)

**Comment by climbcat** [comment]
Update: Some progress, variable extraction has been generalized and put into functions. We now 1) extract all variable statements using regex, and 2) comment-filter out false positives. (This is in a branch at the time of writing.)
