### ISSUE TITLE
rpm packages not available for Fedora

### ISSUE THREAD

**Issue by amivaleo** [McStasMcXtrace/McCode#969]
Hi!

I'm trying to follow the instructions here: https://github.com/McStasMcXtrace/McCode/tree/mcstas-2.6-release/INSTALL-McStas/Linux/fedora

(by the way, there's a typo in the title: "Fedor**d**a")

I get stuck on the "all-rpms" link which is invalid, it opens a blank page (404 not found).
If I try to right-click on that link and then save the file, the download doesn't even start because of some error.

Can you please fix that link?

Thank you!

**Comment by willend** [comment]
Hi @amivaleo,

Thanks for reporting this - broken link as the all-rpms.tgz had not been pust in place, sorry. :-)

Now corrected, please let us know if the rest works as intended or if you come across any further hick-ups. 

Best,
Peter

**Comment by willend** [comment]
Oh and BTW if Fedora29 turns out "too old for today's fedora" in terms of dependencies etc., please let me know.  - Then I can point you to information on building from the source code + locating dependencies.

**Comment by amivaleo** [comment]
There are two typos left in the list of packages in the command line:
`mcstas-comps-2.5-rpm64` has to be replaced by `mcstas-comps-2.6-rpm64`
`mcstas-miniconda3-2.5-rpm64.rpm` -> `mcstas-miniconda3-2.6-rpm64.rpm`

That's the only thing that needs to be adjusted. I've just successfully installed mcstas2.6 in Fedora 31 with the given instructions/dependencies.

Thank you!

**Comment by amivaleo** [comment]
Dear Peter,

after several months, I had to reinstall the OS on my laptop.
I still use Fedora (now, version 33).

The "all-rpm" link in this page 
<https://github.com/McStasMcXtrace/McCode/blob/master/INSTALL-McStas-3.0/Linux/fedora/README.md> 
is broken again.

Can you please fix it?

Thank you!


Jimmy

Il giorno lun 3 feb 2020 alle 00:32, Peter Willendrup 
<notifications@github.com> ha scritto:

**Comment by willend** [comment]
Hello again @amivaleo,

Link is fixed again, sorry for the inconvenience!

**Comment by amivaleo** [comment]
> Hello again @amivaleo,
> 
> Link is fixed again, sorry for the inconvenience!

Thank you a lot!

But there's an extra issue this time, related to this command:

```sudo yum install pgplot perl-PGPLOT perl-Tk perl-PDL perl python2```

both `pgplot` and `perl-PGPLOT` can't be found.

**Comment by willend** [comment]
Just to make sure you know, those are dependencies for the "legacy" gui and plotting, i.e. mcplot.pl mcgui.pl etc. 
Almost all functionality is available by selecting the python tools only - i.e. you can do without pgplot and friends.

If you really do need these, you will have to enable an extra repository for those, I believe https://rpmfusion.org is a solution.

**Comment by amivaleo** [comment]
> Just to make sure you know, those are dependencies for the "legacy" gui and plotting, i.e. mcplot.pl mcgui.pl etc.
> Almost all functionality is available by selecting the python tools only - i.e. you can do without pgplot and friends.
> 
> If you really do need these, you will have to enable an extra repository for those, I believe https://rpmfusion.org is a solution.

Oh. Alright. Well it says "dependencies", so... 🤷‍♂️️

Let's see if it will work. Still downloading the rpms... My connection is extremely slow today.

Thank you!
