### ISSUE TITLE
Corrupted link for adding info in the list of members

### ISSUE THREAD

**Issue by amivaleo** [McStasMcXtrace/McCode#970]
Hi!

I wanted to ask for some help using the email address given in the last sentence "Please report any trouble with the repository to mcstas-users" here: https://github.com/McStasMcXtrace/McCode/blob/master/INSTALL-McStas/Linux/fedora/README.md

I received this reply:
![Schermata da 2020-02-03 08-50-13](https://user-images.githubusercontent.com/24316547/73634782-4107f000-4662-11ea-8c35-18ce938a8c67.png)
That link http://mailman2.mcstas.org/cgi-bin/mailman/listinfo/mcstas-users loads a blank/error page.

Can you please fix it?

Thank you!

**Comment by willend** [comment]
Oops, another typo it seems but a more serious one. https://mailman2.mcstas.org/mailman/listinfo/mcstas-users is the URL, I will fix that in the auto reply immediately

**Comment by amivaleo** [comment]
Close the issue if you fixed this. I can't easily replicate the process since I subscribed to the member list using the link you wrote here, so I can't get the second email in my screenshot in the first post.

Thank you!

**Comment by willend** [comment]
Indeed, I will try from a random non-registered address myself

**Comment by willend** [comment]
Tested and now works as expected:

![Screenshot 2020-02-03 at 12 53 17](https://user-images.githubusercontent.com/8593355/73651296-702f5900-4684-11ea-8e27-fea4b2ed1b69.png)

**Comment by amivaleo** [comment]
Well done. Thank you! :)
