### ISSUE TITLE
McStas/McXtrace: Single_crystal and PowderN use chars to distinguish between scattering processes

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#978]
This creates slight problems - among which that a subsequent WHEN clause cannot contain quotes - which means that the ascii codes for 'c' etc. has to be used. This is not very legible.

Minimal solve:
change to an int or similar.

Long term solution - we could define an enum a'la errno with a set of codes for such things. (Possibly this could contain shape-codes as well to avoid cluttering namespace.) We could use this in a standard manner across components to target also the difference btw. interacttion/scattering/reflections etc.

**Comment by willend** [comment]
@ebknudsen I believe we don't need to fix this one for update releases like 1.5.1 and 2.6.1?

**Comment by ebknudsen** [comment]
Agreed, it is an annoyance but nothing more.
/e
________________________________

**Comment by farhi** [comment]
As #785 is now closed, we can keep this questionable choice ;-)
