### ISSUE TITLE
HELP!! :-) 91 comps need DECLARE-block fixing on f_decl_output_vars

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#981]
@climbcat has worked on f_decl_output_vars so that every DECLARE parameter becomes what we used to call an OUTPUT_PARAMETER, i.e. part of the _comp struct.

A side-effect is that every of these parameters MUST be defined singly on each line including type, that is:

```
DECLARE %{
  int A;
  double B;
%}
```
- NO commas etc.

We have checked in a file called shortlist.txt (see 3151fc896) listing the components that need fixes in this respect - please help us do some of this tedious work... :-) Please :-) @trnielsen @t-weber @ebknudsen @farhi @mads-bertelsen.

With each commit where components are fixed, PLEASE remove these from the shortlist.

(We can check later using 
```./find_commas_declare.sh  |grep \\.comp\ |cut -f3- -d\ |cut -f1 -d\  | sort > shortlist_newv.txt```

**Comment by willend** [comment]
(And once this has been done on the said branch, and run a succesful test it should be good to merge into mcstas-3.0)

**Comment by willend** [comment]
How to test locally (even a cpu-machine is OK, no GPU's needed here):
1) git checkout f_decl_output_vars
2) do some work
3) ./build_loc_3.0_tree as usual
4) /tools/Python/mctest/mctest.py --ncount=1e6 --configs --mccoderoot $HOME/McStas/mcstas --verbose --testdir wherever --config=McStas_CPU_GCC_KISS

( On a Linux - and if you don't mind overwriting your system mcstas,  3 and 4 can instead be done much easier:
./build_loc.sh
mctest 3.0-dev
)

**Comment by climbcat** [comment]
A little HELP tool / script has been added to this branch: <code>edit_manyfiles.py</code>.

From the root of McCode, use <code>python3 edit_manyfiles.py shortlist .</code> to edit much faster.

**Comment by willend** [comment]
I have edited a bunch of components and merged the branch into mcstas-3.0. as only 5 instruments "less than usual" didn't compile. 

- So edits can now be done directly on mcstas-3.0

shortlist is a lot shorter:
```
mcstas-comps/contrib/union/AF_HB_1D_process.comp
mcstas-comps/contrib/union/IncoherentPhonon_process.comp
mcstas-comps/contrib/union/Incoherent_process.comp
mcstas-comps/contrib/union/PhononSimple_process.comp
mcstas-comps/contrib/union/Powder_process.comp
mcstas-comps/contrib/union/Single_crystal_process.comp
mcstas-comps/contrib/union/Template_process.comp
mcstas-comps/contrib/union/Texture_process.comp
mcstas-comps/contrib/union/Union_box.comp
mcstas-comps/contrib/union/Union_conditional_PSD.comp
mcstas-comps/contrib/union/Union_conditional_standard.comp
mcstas-comps/contrib/union/Union_cone.comp
mcstas-comps/contrib/union/Union_cylinder.comp
mcstas-comps/contrib/union/Union_logger_2D_kf_time.comp
mcstas-comps/contrib/union/Union_logger_2D_space_time.comp
mcstas-comps/contrib/union/Union_logger_3D_space.comp
mcstas-comps/contrib/union/Union_make_material.comp
mcstas-comps/contrib/union/Union_master.comp
mcstas-comps/contrib/union/Union_mesh.comp
mcstas-comps/contrib/union/Union_sphere.comp
mcstas-comps/misc/MCPL_output.comp
mcstas-comps/misc/Scatter_log_iterator.comp
mcstas-comps/sources/ESS_butterfly.comp
mcstas-comps/sources/ESS_moderator.comp
mcstas-comps/sources/Source_adapt.comp
mcstas-comps/sources/Virtual_input.comp
```

**Comment by climbcat** [comment]
This all seems done now :-)

**Comment by willend** [comment]
Indeed. :)

**Comment by ebknudsen** [comment]
Has been outdated
