### ISSUE TITLE
Monitor_nD: spherical shape with only radius parameter not working

### ISSUE THREAD

**Issue by markusappel** [McStasMcXtrace/McCode#996]
This does not define a working spherical monitor, as one might expect:
`COMPONENT sphere = Monitor_nD(options="sphere t", radius=0.100)`

I think this is because `yheight` is left unset (=0) and the entire sphere is cut off by the top/bottom cap feature (`Vars.Cylinder_Height` is 0 in this instance):
https://github.com/McStasMcXtrace/McCode/blob/05b95cc8a4c95faab3d58b9291ef4e4b258d44b5/mcstas-comps/monitors/Monitor_nD.comp#L407-L413

It works as expected with
`COMPONENT sphere = Monitor_nD(options="sphere t", radius=0.100, yheight=1)`

**Comment by farhi** [comment]
Closed with last commit
