### ISSUE TITLE
McXtrace: Lacking  test cases for many "real" instruments. 

### ISSUE THREAD

**Issue by ebknudsen** [McStasMcXtrace/McCode#999]
There are a number of the examples of real instruments that do not have an actual test case:
* MAXII_711
* MAXII_811
* XFEL_SPB
* MAXIV_Bloch
* MAXIV_FemtoMAX
* DBD_IBM_Si_analyzer_BC
* PBD_BT
* SAXS_saxlab

**Comment by ebknudsen** [comment]
status is now:
- ~~MAXII_711~~
- MAXII_811
- XFEL_SPB
- MAXIV_Bloch
- MAXIV_FemtoMAX
- DBD_IBM_Si_analyzer_BC
- PBD_BT
- SAXS_saxlab

**Comment by ebknudsen** [comment]
~~MAXII_811~~

**Comment by ebknudsen** [comment]
~~XFEL_SPB~~

**Comment by farhi** [comment]
Still have missing tests:
- Be_BM_beamline
- DBD_IBM_Si_analyzer
- MAXIV_Bloch
- MAXIV_FemtoMAX
- PBD_BT
- SAXS_saxlab
- SOLEIL_ANATOMIX
- SOLEIL_DISCO
- SOLEIL_MARS
- SOLEIL_PX2a
- SOLEIL_ROCK
- TestSAXS
- Test_SX
- Test_Sqw
- Test_grating_reflect
- Test_mirror_elliptic
- Test_mirror_parabolic
- Union_geom_demo
- Union_incoherent
- czerny_turner
- templateSasView
- template_1Slit_Diff
- template_2Slit_Diff
- template_simple

**Comment by farhi** [comment]
Done with commit 256416eca0ced84ec80ff055ba8be5fa4061204c
It seems there are still issues with a few SAXS samples (giving 0 intensity).
